### ISSUE TITLE
Use npm to manage dep to Popper.js

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#1]
I think it would make sense to rely on npm to automatically get new versions and reduce the library size during installation (avoid dupe downloads of Popper)

**Comment by atomiks** [comment]
Good idea... I've never put anything on npm before. Is there a guide?

**Comment by FezVrasta** [comment]
I'm on pane ✈️ right now so it's not easy to Google it, but I'm sure there are a ton.

You should get rid of the copy of Popper.js from the src directory and:

```
npm i --save popper.js
```

Then you can publish your library following `npm publish --help`

**Comment by atomiks** [comment]
Updated. It's now a dependency and imports from node modules.
