### ISSUE TITLE
Multiple active tooltips

### ISSUE THREAD

**Issue by Andrew-Talley** [atomiks/tippyjs#10]
When you have multiple tooltips that are activated by clicking on them, clicking on one them will not cause the other one to close.

**Comment by atomiks** [comment]
With click triggers, this seems to be expected behaviour since you might want to have multiple tooltips open at the same time. How about an option in the settings object for you to change that behavior?

**Comment by Andrew-Talley** [comment]
I see where that would be helpful, though my thinking was that clicking outside a tooltip should cause it to close, so yes, I think an option would be very helpful.

**Comment by atomiks** [comment]
`multiple` is now an option in v0.1.11, and by default it's `false`.

Touch is still a bit whacky when it comes to showing multiple tooltips, but between clicks it works on mobile as well.
