### ISSUE TITLE
Warning for missing all the plugins.

### ISSUE THREAD

**Issue by amanagr** [atomiks/tippyjs#1005]
## Bug description

I am receiving warnings in [Zulip](github.com/zulip/zulip) development environment for missing plugins just by using [`import tippy, {delegate} from "tippy.js"`](https://github.com/zulip/zulip/blob/main/static/js/tippyjs.js).  It doesn't show up immediately but just after triggering a tooltip on hovering an element.

<img width="612" alt="Screenshot 2021-11-10 at 9 00 16 AM" src="https://user-images.githubusercontent.com/25124304/141045030-f2df75e7-88fa-469d-ac99-6f174c152b7f.png">

We are not using any of the plugins. Tippy v6.3.5 (tested)

## Reproduction

Cannot reproduce on codepen but easily on our development environment.

CodePen link: https://codepen.io/amanagr/pen/XWaYyre

**Comment by atomiks** [comment]
This means `tippy()` is somehow getting passed those props. If you can edit `node_modules` you can place some log calls to see what's happening
