### ISSUE TITLE
Laggy in macOS when quickly hovering several elements

### ISSUE THREAD

**Issue by Sumolari** [atomiks/tippyjs#101]
I noticed that when you hover quickly some simple items (no HTML content) with Tippy tooltips attached in Chrome in macOS the browser freezes and sometimes it completely crashes.

I can't upload a test case as I found this issue in a large project but I can provide a temporal fix: just use a different duration for hide animation.

When using the default duration of `350ms` (without setting duration parameter in Tippy constructor) the I could reproduce the issue in a MacBook Air. Using an explicit duration of `350ms` for both show and hide animation I could reproduce the issue too but it was more difficult to trigger it.

Finally using a show duration of `350ms` and a hide duration of `200ms` I couldn't reproduce the issue.

I hope this might be helpful it anybody faces this problem.

**Comment by atomiks** [comment]
Strange... never had any issue on my MBP in Chrome. Nice that there seems to be a solution though.

**Comment by atomiks** [comment]
Can you see if 1.2.2 fixes this?
