### ISSUE TITLE
Nesting demo in plain JavaScript

### ISSUE THREAD

**Issue by michaelborromeo** [atomiks/tippyjs#1010]
How would you create the nesting demo but in plain JavaScript, not React?

Thanks!

**Comment by atomiks** [comment]
A sub-button is inside the root button tippy's `content`. You call `tippy()` on the sub-button too, ad infinitum for further nesting

```js
tippy(rootButton, {
  content: elementContainingSubButton,
});

tippy(subButton, {
  content: 'nested'
});
```
