### ISSUE TITLE
same content html div cannot be used across different tooltips

### ISSUE THREAD

**Issue by anoosurf** [atomiks/tippyjs#1013]
## Bug description
same content html div cannot be used across different tooltips

 when we assign a dom DIV element directly as content ( not innerHTML but direct object reference in content:)
then if we call the sane element on another tooltip it does not show.. 
actually want to share a common popup div across multiple tooltip hover links

**Comment by atomiks** [comment]
This isn't a bug, you need to clone the node/up to you to handle
