### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by DavidSvi** [atomiks/tippyjs#1019]
I just followed the basic installation of tippyjs, I am using the latest version 6.xx

<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<link
  rel="stylesheet"
  href="https://unpkg.com/tippy.js@6/animations/shift-away.css"
/>

I set the placement as placement: 'right-end' the issue with small screen size the tooltip overflow

![image](https://user-images.githubusercontent.com/81103867/146225727-99a33d9d-ea55-4cd3-89ea-19c6641c04cf.png)

My settings

![image](https://user-images.githubusercontent.com/81103867/146225872-43c706b1-24e6-4845-9528-e39719aa5c39.png)

How I can fix that ?

**Comment by atomiks** [comment]
Flipping only works on the opposite side, but on mobile you'll want to fallback to either `top` or `bottom` like so:

```js
popperOptions: {
  modifiers: [
    {
      name: 'flip',
      options: {
        fallbackPlacements: ['left-end', 'top-end', 'bottom-end']
      }
    }
  ]
}
```
