### ISSUE TITLE
Tippy invokes `removeEventListener` and `addEventListener` with an undefined listener

### ISSUE THREAD

**Issue by LazyCompiler** [atomiks/tippyjs#1027]
## Bug description

The events `removeEventListener` and `addEventListener` of `transitionend` and `webkitTransitionEnd` are invoked with an undefined listener.

[dom-utils.ts / line 117](https://github.com/atomiks/tippyjs/blob/21a9c842ad00cacd32c84a91080208e8c9a2eb28/src/dom-utils.ts#L117)

    ['transitionend', 'webkitTransitionEnd'].forEach((event) => {
     box[method](event, listener as EventListener);
    });

This function does not verify that "listener" is defined after being triggered from ([createTippy.ts Line 411](https://github.com/atomiks/tippyjs/blob/cac8a1260cab174d8442efa1bc1d973e298d3373/src/createTippy.ts#L411)), that also didn't although it's an global variable that being defined only after its first run:

    updateTransitionEndListener(box, 'remove', currentTransitionEndListener);
    updateTransitionEndListener(box, 'add', listener);

    currentTransitionEndListener = listener;

currentTransitionEndListener is a global var that is undefined at first load, so first call is always undefined.

## Reproduction

CodePen link: https://codepen.io/lazycompiler/pen/rNYxBjQ

**Comment by atomiks** [comment]
An undefined event listener just gets ignored so I'm not sure what the bug is?

**Comment by LazyCompiler** [comment]
Because this data is required and not optional (removeEventListener: [Source 1](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener#parameters), [Source 2](https://www.w3schools.com/jsref/met_element_removeeventlistener.asp), addEventListener ([Source 1](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#parameters), [Source 2](https://www.w3schools.com/jsref/met_element_addeventlistener.asp)).

Here is some background: I'm working on a Chrome Extension, and I decided to use Tippy.js. I found out this website I'm targeting, override `window.EventTarget.prototype.removeEventListener`, and they access `eventHandler.listener` without verifying it exists. I immediately assumed it was their mistake (to assume it has value), but after reading about it, I found out this information is mandatory.

**Comment by atomiks** [comment]
<img width="442" alt="Screen Shot 2022-02-01 at 9 25 07 pm" src="https://user-images.githubusercontent.com/22450188/151951871-f876ba3e-a222-43aa-8650-9dd7ca62df1e.png">

It's required, but the value can be `undefined`. I'd say it's a problem of the website overriding a built-in function without adhering to the spec (never good practice), but I'm open to changing it to help compatibility in practice.

**Comment by LazyCompiler** [comment]
I see; indeed, it's not very good practice.

Perhaps to minimize the footprint of Tippy.js, at least we can avoid the first empty call in [line 411](https://github.com/atomiks/tippyjs/blob/cac8a1260cab174d8442efa1bc1d973e298d3373/src/createTippy.ts#L411) before `currentTransitionEndListener` is defined in [line 414](https://github.com/atomiks/tippyjs/blob/cac8a1260cab174d8442efa1bc1d973e298d3373/src/createTippy.ts#L414).
