### ISSUE TITLE
instance.destroy(); is not working

### ISSUE THREAD

**Issue by rwaidaAlmehanni** [atomiks/tippyjs#1033]
## Bug description

tooltip display text when hover on icon working fine but when switch language without refreshing page and hover again the tooltip display 2 tooltips for each language and when use destroy it is not working

## Reproduction

CodePen link: https://codepen.io/atomiks/pen/yvwQyZ

**Comment by ysilvela** [comment]
The same happens to me. I use it within a calendar and when I change the month, the previous month's tooltips are still seen. The destroy method does not work as it should.

**Comment by atomiks** [comment]
The destroy method is well-tested so I doubt it doesn't work. You're probably recreating the tooltip accidentally after destroying it without realizing. Add some logs to see the code flow.
