### ISSUE TITLE
Tippy js used with html content using Angular Material Icon

### ISSUE THREAD

**Issue by ParthMDave** [atomiks/tippyjs#1038]
## I have work with angular application with angular material component. For Tooltip functionality i have used Tippyjs. using Tippyjs i have display html content dynamically. but when i am trying to bind ### **<mat-icon> keyboard_double_arrow_right</mat-icon>** with tippyjs & Material Icon it just show me output as below:
![Capture](https://user-images.githubusercontent.com/58936725/158345902-0f77c6b3-7fc2-4946-aee5-0fc460ce93f8.PNG)

A clear and concise description of what the problem is.

## Solution

I want to display that material icon which i have given. outside the tooltip i am able to access mat-icon so their are no any issue regarding import of material icons.
Instead of below highlighted yellow text i want to display material icon

**Comment by atomiks** [comment]
You need to render HTML w/ `allowHTML: true`
