### ISSUE TITLE
Error in shift-away.scss

### ISSUE THREAD

**Issue by NateRobinsonAA** [atomiks/tippyjs#1054]
## Bug description

The SCSS for this animation seems to compile to CSS that doesn't show the correct animation.
The compiled CSS can be found here: https://unpkg.com/tippy.js@6.3.7/animations/shift-away.css
The first selector to make `opacity: 0` is correct, but the rest of the selectors should instead include `[data-state=visible]`.

## Reproduction

Here you'll see that the animation is completely absent:
CodePen link: https://codepen.io/progidy/pen/MWQpmVL

Here you'll see that the animation is reintroduced when the CSS is fixed:
https://codepen.io/progidy/pen/poaePKQ

**Comment by atomiks** [comment]
It doesn't need `data-state=visible` because `transform: translate(0)` is the default and implicit once the hidden state gets removed. Your CodePen is just missing the CSS file, it works fine: https://codepen.io/atomiks/pen/rNJymEB
