### ISSUE TITLE
Tippy Multiple Instances Issue

### ISSUE THREAD

**Issue by halid96** [atomiks/tippyjs#1084]
When I am trying to update Tippy, it creates a new Tippy tooltip for the same element... I tried several ways but didn't manage it to work.

I am using:
'https://unpkg.com/@popperjs/core@2',
'https://unpkg.com/tippy.js@6'

I tried:
https://atomiks.github.io/tippyjs/v6/tippy-instance/
https://atomiks.github.io/tippyjs/v6/methods/  ... The `.unmount()`, `.destroy()`, and `.setProps()` methods

Here is my code:

```                              
window.update_rating_info_tippy = function(){
      tippy(document.querySelectorAll('#vid-rate'), {
      theme: 'tippy-black',
      placement: 'top',
      arrow: false,
      animation: 'scale',
      content(reference) {
      const template = document.getElementById('vid-rate-tippy');
          return template.innerHTML;
      },
      allowHTML: true,
      interactive: true,
      duration: [100, 100]
      });
};
```
                                
Whenever I am trying to update it i am calling `update_rating_info_tippy()` ... It is working but creates a new tooltip, but not deletes the old ones.

                
![dsaewqeqw](https://user-images.githubusercontent.com/24207890/192125275-0b585519-31b7-48e5-a451-007a18281a5c.PNG)

**Comment by HarshaVardhanPVK** [comment]
I am also facing same issue.
![tippy](https://user-images.githubusercontent.com/13849530/201080837-d3a97b5a-1caa-4e5f-9f21-cd2eded04532.png)

**Comment by atomiks** [comment]
It's documented in the [v6 migration guide](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-multiple-or-relying-on-its-behavior)
