### ISSUE TITLE
Optional extra imports not working

### ISSUE THREAD

**Issue by bogdaniculae** [atomiks/tippyjs#1090]
[Bug replicated](https://codepen.io/bogdan-niculae/pen/PoerZQB)

I've imported the 'shift-away' separately but still not working. 
e.g:  `import 'tippy.js/animations/shift-away.css';`

**Comment by bogdaniculae** [comment]
Hmm seems to work.

**Comment by meeram1995** [comment]
How was this resolved? I've been stuck on a similar issue for a while now.

**Comment by xoex** [comment]
me too, themes and default styles have the same problem.
is there any config needed to this would work?

**Comment by bogdaniculae** [comment]
Without code I can't see what it doesn't works for you. As you can see on my codepen - this works now.
