### ISSUE TITLE
[Q] tool tip content with multiple lines

### ISSUE THREAD

**Issue by garan82** [atomiks/tippyjs#111]
Hello,

Is it possible to create a tool tip with multiple lines? I wasnt able to find this in documentation, and I tried to use "\n" but didn't work.

Thanks,
G

**Comment by garan82** [comment]
I found it, using <br> instead of \n works.

**Comment by simsinght** [comment]
Using what? Having the same issue.

**Comment by bennyty** [comment]
In case Google brought you here: See #292
