### ISSUE TITLE
Add example on how to update tooltip with html template

### ISSUE THREAD

**Issue by JamesJGoodwin** [atomiks/tippyjs#115]
Hello. Could you please add an example to the docs on how to update a tooltip with html-content? This could be usefull. Thanks.

**Comment by atomiks** [comment]
The docs say you can by using the direct element option. Do you mean you want an example like this?

Example of how to update a HTML template by incrementing a counter every time the tooltip is shown.

```html
<div id="template">
  1
</div>
```

```javascript
let counter = 1
const template = document.querySelector('#template')

tippy('selector', {
  html: template,
  onShow() {
    template.innerHTML = ++counter
  }
})
```

**Comment by JamesJGoodwin** [comment]
@atomiks no. I'm passing the function in the `html` option:

```html
<div data-id="12345abc">
  <div class="moar-proposals-holder">
  <span>Show me more</span>
    <div class="additional-proposals">
      <span></span>
      <span></span>
      <span></span>
      ...
    </div>
  </div>
</div>
```

```javascript
tippy('.moar-proposals-holder', {
    html: el => el.querySelector('.additional-proposals')
});
```

What I need to do is to find a block where `data-id="12345abc"` and then `.find('.additional-proposals')` and append a new element there. But I can't directly change this exact block because it was removed from the page.

**Comment by atomiks** [comment]
I'm not sure I understand your problem. Could you make a CodePen or something to help?

**Comment by JamesJGoodwin** [comment]
@atomiks sure. Take a look [here](https://jsfiddle.net/86jgzcvy/). If you see the source code of the page you cannot find `<div class="additional-proposals">` because it was removed from the page:

<img src="https://i.imgur.com/QkrDRx1.png">

Am I able to somehow access `<div class="additional-proposals">` and append some childs?

**Comment by atomiks** [comment]
>Am I able to somehow access <div class="additional-proposals"> and append some childs?

Yes, if you save it to a variable reference for later, before you invoke `tippy`.

So you can do 

```javascript
const el = document.querySelector('[data-id="12345abc"] .additional-proposals')

tippy('.moar-proposals-holder', {
  html: el => el.querySelector('.additional-proposals')
})

// You can now append children to `el` since it's saved...

el.appendChild(someElement)
```

**Comment by JamesJGoodwin** [comment]
Issue resolved. Thanks for the help!
