### ISSUE TITLE
Dynamically activate and deactivate tooltips

### ISSUE THREAD

**Issue by dschenk** [atomiks/tippyjs#117]
I tried to programmatically remove tooltips. via the `destroy()` and `destroyAll()` methods. But they do not work as I expected. I assume it's because of the following behaviour of the library (from the documentation):

> In order to optimize performance, the popperInstance property is not created until the tooltip is shown for the first time, so the data object will not contain it until you've shown a tooltip at least once.

If a tooltip has never been shown, there is no popper instance `const popper = tip.getPopperElement(el)` will return undefined and` tip.destroy(popper)` will not remove the tooltip.

I have the following use case: I want to dynamically activate and deactivate tooltips, based on the state of an application. There are cases where tooltips have to be deactivated even though they have never been shown.

Is there another way to achieve this?

**Comment by atomiks** [comment]
What you're describing doesn't happen 🤔 

See CodePen: https://codepen.io/anon/pen/OxqNgR?editors=1010

The `popper` element property will be there upon creation, it just needs to be shown once for the `popperInstance` property to be created.

So you can destroy it whenever.

**Comment by dschenk** [comment]
Thanks for the quick reply @atomiks and sorry: Should have made a codepen from the start.

Here is my use case:
https://codepen.io/anon/pen/YrgqoW

I initialize all tooltips at once. Then, on certain events, I want to destroy some of them.

**Comment by atomiks** [comment]
Right. In the above CodePen, the problem is that the `title` attribute gets removed when the Tippy tooltip is applied (otherwise it would interfere). So when you try to call `tippy()` once again on an individual button, it won't work, because the title attribute is missing. 

Destroying a tooltip will actually restore the title attribute, but it has to be done before the new instance is created.

**Comment by dschenk** [comment]
I see, thanks for the Info. How do I destroy a tooltip then? Is there a way to access the tippy instance without doing `tippy(button)`? Or is there a way to get all tippy instances from tippy? In the second case I could go through those and destroy the ones I want to. The only other alternative I see is to store all tippy instances myself, then I can destroy them whenever I want.

**Comment by atomiks** [comment]
>The only other alternative I see is to store all tippy instances myself, then I can destroy them whenever I want.

Yeah, you can store each instance in an array.

As an example:

```javascript
const tips = []

els.forEach(el => {
  tips.push(
    tippy(el)
  )
})
```
In this case, every tippy instance is only one single element / tooltip.

So to destroy the tooltip for the very first instance, just do:

```javascript
const first = tips[0]
first.destroy(first.store[0].popper)
```

**Comment by dschenk** [comment]
Yeah, I wrote a tooltip manager class which does exactly that. 

What would be nice is to get the tipsy instance from a DOM element directly if there is any. Maybe something for https://github.com/atomiks/tippyjs/issues/97 :)

Thanks for your time and the work you put into the library, much appreciated!
