### ISSUE TITLE
Adding tooltip to SVG line or image causes element to become selectable, with border

### ISSUE THREAD

**Issue by eponymous301** [atomiks/tippyjs#121]
Replication case [here](https://codepen.io/eponymous/pen/OxBJye).

Strange, adding a tooltip causes new behavior of SVG object - you can click on the red line in the case above, and cause it to have a border around it. Clicking anywhere else causes border to disappear.

<img width="512" alt="screen shot 2017-10-31 at 10 33 33 am" src="https://user-images.githubusercontent.com/29875759/32239201-19759990-be27-11e7-8e93-49427cdaf57d.png">
If you don't add a tooltip, line does not exhibit this behavior. Inspecting elements in browser console, I don't see how this border is getting added.

Happens on OS X in Safari and Chrome but not Firefox.

**Comment by eponymous301** [comment]
OS X: 10.12.6
Safari: 11.0 (12604.1.38.1.7)
Chrome: 61.0.3163.100 (Official Build) (64-bit)
Firefox: 56.0.2 (64-bit)

**Comment by atomiks** [comment]
^ That's right. By default, the trigger is `'mouseenter focus'` (focus accommodates keyboard users), so when they keyboard tab over to the tooltipped element it will show it, not just when hovering their cursor over. You can remove the styling, but I recommend using the `focus-ring.js` polyfill which removes the outline for mouse users but keeps it for keyboard users. I use it on the docs actually, very useful.
