### ISSUE TITLE
Custom selector (ref object) cannot get popper

### ISSUE THREAD

**Issue by lflserg** [atomiks/tippyjs#123]
When using a custom selector / reference object new selector is created basing on it, so there is no way to getPopperElement to work legally (previous reference becomes invalid). I bypassed this by modifying the object instead of creating a new one in my version of library.

**Comment by atomiks** [comment]
I'm not sure what you mean. Can you explain a bit more?

**Comment by lflserg** [comment]
Btw, @atomiks if you wont mind, could you give any tip of using such custom objects? I noticed that if I create one it is positioned as relative in the viewport, so moving with my scrolls.  And if i use real DOM node it gets binded to it. Is it expected or there is some hidden options to pass to make position "absolute" and not relative?

**Comment by atomiks** [comment]
I actually don't know how to use it properly, sorry. 😆  It was added via a pull req which was requested. I haven't had a need to use it yet which is why.

Btw, you can actually use `getPopperElement` if you use `instance.selector`, such as 

```javascript
const tip = tippy(refObj)
tip.getPopperElement(tip.selector)
```

since that refers to the selector object

**Comment by lflserg** [comment]
@atomiks  thanks for the tip, will use it.

And regarding the positioning, custom selector is the only choice - we cannot adjust position manually, right? So for example I could bind to a node and adjust position instead of using custom selector. 
(my goal is to display html popup right on user-selected text)

**Comment by atomiks** [comment]
You could make the reference node invisible (`visibility: hidden; opacity: 0` or such) and position it next to the selected text, couldn't you?

**Comment by lflserg** [comment]
Will do so, it just looks like a workaround and is not obvious. This may be the issue of Popper.js though.

**Comment by lflserg** [comment]
@atomiks I consulted on Popper.js page and it seems that keeping first object as valid and adding properties to it is better idea then accessing via instance.selector. Because that object may contain useful binding which will be dropped.

**Comment by atomiks** [comment]
Well Popper.js is using the `instance.selector` object ref, not the one you passed in as the argument anyway.

**Comment by atomiks** [comment]
In v2 the ref object is mutated directly and that method no longer exists anyway. Should fix the issues.
