### ISSUE TITLE
Please add onClick callback

### ISSUE THREAD

**Issue by yaizudamashii** [atomiks/tippyjs#125]
Often times, tippy created on dynamic DOM element immediately dismisses.  To show a tippy, i need to set the option {hideOnClick: 'persistent'} but then a click does not dismiss the tippy.  Please add onClick callback so I can dismiss the tippy.

**Comment by yaizudamashii** [comment]
I think the core problem is that document's event listener for click is called prior to a tippy being shown, when that tippy is triggered to appear on click somewhere.  Hence if we set tippy to hideOnClick: true, the tippy is hidden before it is shown!

**Comment by atomiks** [comment]
Can you please create a Codepen demonstrating this issue?

**Comment by atomiks** [comment]
Closing because there is no response...
