### ISSUE TITLE
Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by berstend** [atomiks/tippyjs#126]
Hi there,
thanks for this amazing library!

I ran into the same issue a couple of times when using tippy programmatically and was wondering if I might not use it correctly:

```es6

document.body.innerHTML = `
  <span id="tooltipTrigger" title="Hover title">Click me</span>
`.trim()

import tippy from "tippy.js"

$trigger = document.querySelector("#tooltipTrigger")

const hoverTip = tippy($trigger)

const modalTip = tippy($trigger, {
  html: document.createElement("div"),
  trigger: 'click',
  onShow: function (event) {
    console.info("modalTip onShow", event)
    hoverTip.hide()
  }
})
```

You could paste the above code into https://esnextb.in/ to quickly test it and see this error showing up in the console, when clicking on the element: `Uncaught TypeError: Cannot read property 'querySelector' of undefined`

I encountered the same problem when using `.hide()` programmatically.

Any ideas?

Thanks!

**Comment by berstend** [comment]
The problem seems to be related to `getInnerElements` and the `popper` element being undefined.

**Comment by berstend** [comment]
Whoops, my bad - I overlooked that one needs to pass the `popper` reference to `hide()`.

Replacing `hoverTip.hide()` in the above example with `hoverTip.hide(hoverTip.getPopperElement($trigger))` does the trick.

Cheers!

**Comment by atomiks** [comment]
@berstend - V2 removes the need to pass anything in, it simplified the manual workflow a lot more. You should check it out 🎈

**Comment by berstend** [comment]
Ah great, thanks for making me aware @atomiks
