### ISSUE TITLE
Add option to reuse the same DOM node

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#13]
To improve performances on the most common use case (a single tooltip displayed on the page)

**Comment by atomiks** [comment]
I'm working on rewriting it so a popper instance and node is only made when it needs to be (on show and destroyed on hide -- otherwise lots of poppers/event listeners can bog down the page)

**Comment by atomiks** [comment]
I've mostly rewritten it so that it now appends to the DOM on show, and removes on hide. Popper instances are created when the Tippy instance is created.

The only issue left now is that clicking Popover HTML causes the page to scroll to the top on Chrome and Safari, not Firefox though. Is there a way to disable scrolling behavior entirely in Popper.js?

**Comment by FezVrasta** [comment]
That's not a Popper.js issue, is that you are appending to the DOM a `position: absolute` focusable element (supposedly) and the browser automatically scrolls to it when attached to DOM.

This because a `position: absolute` element with `top: 0` will be at the top of the document.

You should append it with `top` equal to window scrollTop.

I hope it helps.

**Comment by atomiks** [comment]
Ah, you're right. I used focus for keyboard navigation. Is there a more suitable way to allow keyboard navigation without needing to do that?

**Comment by FezVrasta** [comment]
Not really, because anyone could add an `input` inside its tooltip and reproduce the same problem. You should append the DOM node as I explained.

**Comment by atomiks** [comment]
What about the `translate3d` setting? If the `top` is changed, it will offset it incorrectly?

**Comment by FezVrasta** [comment]
It should get overridden once Popper computes its styles

**Comment by atomiks** [comment]
So now on first click it doesn't scroll, but subsequent clicks to show do...

        popper.style.top = (window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop) + 'px'
        document.body.appendChild(popper)

        const instance = Tippy.bus.refs[Tippy.bus.popperMap.indexOf(popper)].instance
        instance.scheduleUpdate()

**Comment by FezVrasta** [comment]
I guess you have to perform the same every time the element is appended, not only the first time.

**Comment by atomiks** [comment]
It should do so every time, since that's in the `show` method

**Comment by FezVrasta** [comment]
¯\_(ツ)_/¯

**Comment by atomiks** [comment]
Without `update()`, it doesn't scroll weirdly and the popper is placed at the top of the viewport as expected, but with it, it scrolls down (and differently still on Firefox)

**Comment by atomiks** [comment]
Think I found a solution... only use `focus()` once the transition is complete

**Comment by atomiks** [comment]
Released as v0.2 - https://github.com/atomiks/tippyjs/releases/tag/v0.2

**Comment by FezVrasta** [comment]
Were you able to measure any performance improvement?

**Comment by atomiks** [comment]
Make a loop that appends 500 tooltipped elements to the DOM. Before, all poppers had listeners, making it very very slow. Now, they only have listeners on show, so it's basically infinitely more performant.

Also check v0.2.1, fixed a quick bug.
