### ISSUE TITLE
V2 init require title not empty

### ISSUE THREAD

**Issue by BigmacFR** [atomiks/tippyjs#130]
Hi,

I just try the new version.
In V1, I initialize all tippy with
`tippy('[data-toggle="tooltip"]', tippyConfig);`

All selected item was create even if there had `title=""`

Now with V2 `title=""` elements are ignored

I use this behavior to initialize all tippy and change title later to 'create' a real tippy.
I want to know which behavior is expected V1(empty title accept) or V2 (change title and tippy() after)

Regards,

**Comment by atomiks** [comment]
In V1 as of 1.4.2 (and well before that), empty title attributes were also ignored (falsy value). V2 didn't change anything in that regard.

https://codepen.io/anon/pen/POeMdP

If you add a space in the title attribute, it gets created. So I'm not sure how you had that behavior?

**Comment by BigmacFR** [comment]
Sorry for the time lost.
Seems that tippy() was call again after the title change.
I try to reproduce in simpler code but cannot find the same problem. (why second call didn't create in V2)
Maybe I didn't change tippy.css at first so it's look not init as wanted.

I change to : `set title then tippy()` and _`tippy.destroy() + set title=''` and now all is fine!
Thanks for the new version and continue your good work :)
