### ISSUE TITLE
Update CDN link in v1 documentation

### ISSUE THREAD

**Issue by crtlf** [atomiks/tippyjs#132]
In your v1 documentation, your default CDN ([//unpkg.com/tippy.js/dist](https://unpkg.com/tippy.js/dist/)) redirects to tippyjs v2.

➡️  https://atomiks.github.io/tippyjs/v1/index.html#getting-started

**Comment by atomiks** [comment]
Thanks, I'll fix it ip.

I accidentally published the v2 beta on npm as @latest without a tag, is there a way to reset @latest back to 1.4.2 until v2 is out of beta?

**Comment by crtlf** [comment]
It doesn't bother me that @latest is linked to v2.

In my project, I manually added `//unpkg.com/tippy.js/dist/tippy.css`, so I just change it to `//unpkg.com/tippy.js@1.4.2/dist/tippy.css`.
