### ISSUE TITLE
Tippy layer background's height  is not full displayed with html template.

### ISSUE THREAD

**Issue by hfxu** [atomiks/tippyjs#134]
Hi
I used tippy to show a HTML template, and update the template's content, but the tippy layer background's height and color  is not full displayed.
Here is a jsfiddle demo (when the template's content is more than 5 lines, the problem will appear) :
https://jsfiddle.net/ed8bsu6o/

How could I do to deal with it?
Thanks

**Comment by atomiks** [comment]
Set `animateFill: false`

The backdrop is really only for regular tooltips that are < 4 lines long.

**Comment by hfxu** [comment]
Hi atomiks
It works, thank you!
