### ISSUE TITLE
Tip with followCursor option appears wrong on svg lines

### ISSUE THREAD

**Issue by TGotwig** [atomiks/tippyjs#135]
Sometimes it appears wrong (with followCursor option) on svg lines:
<img src="https://user-images.githubusercontent.com/30773779/33612710-c1e8c6c6-d9d2-11e7-8832-12a4d395269e.png" width="30%" height="30%" />

**Comment by atomiks** [comment]
Can you make a CodePen?

**Comment by TGotwig** [comment]
Sometimes it appears below:
[https://codepen.io/tgotwig/pen/wPZJBa](url)

**Comment by TGotwig** [comment]
Sometimes it appears below:
https://codepen.io/tgotwig/pen/wPZJBa

**Comment by atomiks** [comment]
Set `flip: false` in the tippy options.

**Comment by TGotwig** [comment]
If I set flip to false,
then it appears sometimes on top instead of below,
but not exactly on cursor position.

**Comment by atomiks** [comment]
There is overflow prevention when the tooltip hits the edges of the viewport, is that what you mean?

**Comment by TGotwig** [comment]
The tooltip should be always on curser position, but isn't:
<img src="https://user-images.githubusercontent.com/30773779/33617549-4bbcf784-d9e0-11e7-9c74-d5440167e595.png" width="30%" height="30%" />

**Comment by TGotwig** [comment]
Here you can see it (on firefox 58.0b8 (64-Bit)):
https://www.dropbox.com/s/aiym3m9ynsdrew7/Ashampoo_Snap_2017.12.05_17h41m09s_001_.wmv?dl=0

**Comment by TGotwig** [comment]
I think this is an implementation failure,
because I used bootstrap tooltips in the past and there it works without this issue.

**Comment by atomiks** [comment]
That's quite strange..

Can you check if this problem exists in `beta-2`? There is a particular line that I think _might_ be causing it.

**Comment by TGotwig** [comment]
It also fails on beta-2.

**Comment by atomiks** [comment]
How about the last of v1,  v1.4.2? All those options except `flip: false` will work.

If not, go to the dist file of tippy.js and add `console.log(e)` to the function inside `createFollowCursorListener()`, and check the pageX, pageY coordinates when it happens. Perhaps the mouse event is not firing off the correct coordinates or something...

**Comment by TGotwig** [comment]
Maybe someone other can,
I just wanted to alert about this issue 😅

**Comment by atomiks** [comment]
Hmm.. looking at your gif again, it seems that the `show()` is triggered, but not any mousemove, so the tooltip ends up being shown at its default position. Perhaps depending on the browser/OS/device, this can become an issue.

I believe a solution would be to also update the position on show, even without a mousemove event needing to fire off.

**Comment by TGotwig** [comment]
Don't know how to inspect tooltips with the browser tools 🤔

**Comment by atomiks** [comment]
Use a `click` trigger, and scroll down to the bottom of the Elements tab (end of <body>) and you'll find the node there.

**Comment by TGotwig** [comment]
What is the selector name of an tooltip? 🤔
print the whole document is too large for codepen

**Comment by atomiks** [comment]
`.tippy-popper`

On Codepen it's within the iframe

**Comment by TGotwig** [comment]
<img src="https://user-images.githubusercontent.com/30773779/33623615-e18d5b76-d9f1-11e7-9dfb-5249b8ddbaf6.png" width="33%" height="33%" />

**Comment by atomiks** [comment]
`v2.0.3` fixes OP

@TGotwig can you make a new issue about the arrow problem? Thank you!
