### ISSUE TITLE
Gap between the arrow and tooltip

### ISSUE THREAD

**Issue by TGotwig** [atomiks/tippyjs#139]
https://codepen.io/tgotwig/pen/bLRVYo

82 is the wrong value for x position, it should be 100 (mid of 200):
<img src="https://user-images.githubusercontent.com/30773779/33623615-e18d5b76-d9f1-11e7-9dfb-5249b8ddbaf6.png" width="33%" height="33%" />

**Comment by atomiks** [comment]
Isn't this issue supposed to be the small 1px gap between the arrow and the tooltip?  😕 

(btw, 82px takes into account the popper's width, that's unrelated and already correct)

**Comment by TGotwig** [comment]
Oh you are right,
sorry my mistake.

**Comment by atomiks** [comment]
Just wondering, are you on a HiDPI display or a regular @1x display?

**Comment by TGotwig** [comment]
Don't know,
I use "Dell U2913WM 73,6 cm (29 Zoll) LCD-Monitor"

**Comment by Arkellys** [comment]
@atomiks Hello, I was wondering if you found a fix for the small gap ? I have it on one computer but not on the other. I am using the last FF version for both and don't have the issue on Chrome. Your library is still awesome anyway. :)

**Comment by atomiks** [comment]
The only fix I can think of is to set `transform: translateY(-1px)` or similar on the arrow element.

**Comment by Arkellys** [comment]
Okay, thank you !

**Comment by atomiks** [comment]
The above is a good solution if you aren't using transparency (tranlucent theme). Transparency will cause the opacity of the arrow + tooltip to overlap which causes darkening. But I feel like no 1px gaps between the arrow and tooltip is more worth it than handling translucent theme (which isn't the default theme anyway).

**Comment by atomiks** [comment]
Fixed in 3.0.0. The round arrow was not changed, because -1px ruins the shape a bit.
