### ISSUE TITLE
Add repository/url to package.json (all versions)

### ISSUE THREAD

**Issue by sherzinger** [atomiks/tippyjs#142]
Hello,

some tools make use of the the optional meta data fields in package.json such as `repository`.
https://docs.npmjs.com/files/package.json#repository

One such example is https://www.webjars.org/, which fails with

```
Failed!
The metadata was missing a required field: /repository/url
```

because of the missing entry.

Do you mind adding this?

**Comment by atomiks** [comment]
Added the field. Next version will release soon
