### ISSUE TITLE
.destroy() won't destroy old/update new tooltip on all elements

### ISSUE THREAD

**Issue by ljosberinn** [atomiks/tippyjs#145]
Lets say I have

`<td title="foo">bar</td>`

which changes to

`<td title="foo2">bar2</td>`

tippy won't update the title to foo2 at all.

Neither

```
if(el._tippy) {
el._tippy.destroy();
}

tippy(el, {
theme: "light"
});
```

nor including

`dynamicTitle: true`

will work.

What works though is

`<td><span title="foo">bar</span></td>`

and updating it with `dynamicTitle: true`, but I have a title on a svg, where I cannot insert another element on, so this won't work on all types of elements.

Edit: working on version 2.0.8

**Comment by atomiks** [comment]
>Edit: working on version 2.0.8

So it's all good? Which version were you having troubles on

**Comment by ljosberinn** [comment]
No, sorry for the confusion. I am working with version 2.0.8 and the issue is persisting.

**Comment by atomiks** [comment]
Oh okay.. can you make a CodePen demonstrating it?

I've made a starter template here for you: https://codepen.io/anon/pen/dJXygZ

**Comment by ljosberinn** [comment]
Very weird. I can't reproduce it on the pen (https://codepen.io/anon/pen/xpOxNr) so I tried it on my page again.

It was _definitely_ not a caching issue as I just went from 1.4.x to 2.0.8 plus have cache disabled when debugging, but it's working now....

Thanks for your time regardless.

**Comment by ljosberinn** [comment]
Nevermind, was able to reproduce it.

https://codepen.io/anon/pen/ypJyGX

Alternatively, without reinitializing tippy every time: 

https://codepen.io/anon/pen/wpWBbG

this won't show tippy at all.

**Comment by atomiks** [comment]
In the first CodePen, the tooltip is updating whenever I input something. What's wrong?

In the second one, the title must not be empty (`""`)

**Comment by ljosberinn** [comment]
![bildschirmfoto 2017-12-20 um 11 55 14](https://user-images.githubusercontent.com/29307652/34203807-ab41c84a-e57c-11e7-9992-9b76b91c5755.png)

updating the tooltip doesn't work for me in Chrome 63.0.3239.84 on macOS, neither on the svg nor the log-row

**Comment by atomiks** [comment]
Wait I was looking at the wrong CodePen lol, lemme see..

**Comment by atomiks** [comment]
Alright I see the issue.

The issue is that your `forEach` loop is running before the `MutationObserver` callback inside tippy which changes the title. Yet, you destroy it before it can change, and Tippy uses the `data-original-title` attribute to restore the `title` attribute on the element when it gets destroyed. Which is what was initially set.

So basically, you shouldn't be destroying it if you're using `dynamicTitle`, or manually set `data-original-title` to the new calculation before destroying it

**Comment by ljosberinn** [comment]
Ok, but if I don't destroy it, it will add an _additional_ tooltip, which will, at some point (I'm talking about potentially several hundred tooltip updates before a user refresh will happen) affect performance.

![bildschirmfoto 2017-12-20 um 12 42 16](https://user-images.githubusercontent.com/29307652/34205595-49941ab0-e583-11e7-8f9f-87b6b7fb47a3.png)

Second tooltip visible on bottom.

This is https://codepen.io/anon/pen/ypJyGX just without destroying it.

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/LeZGRd

Just check if the element doesn't have a tippy instance and create it if so, otherwise don't do anything.

**Comment by ljosberinn** [comment]
Whilst this works in the pen, it weirdly enough doesn't on my page.... it adds a second instance of again, but with former contents.

![bildschirmfoto 2017-12-20 um 13 12 03](https://user-images.githubusercontent.com/29307652/34206602-7f554634-e587-11e7-9277-ec9cb1a99661.png)

tippy-23 contains the correct values


```
el.title = title;

  if (!el._tippy) {
    tippy(el, {
      theme: "light",
      dynamicTitle: true
    });
  }
```

`el._tippy.show()` will only show the new instance (tippy-73), which will be in front of the correct one.

**Comment by atomiks** [comment]
If it works in the isolated pen environment, then you have some extra code somewhere causing the issue. I can't help without seeing it

**Comment by ljosberinn** [comment]
Entire function non-minified

```
function calcCompanyWorth() {

  var HQWorth = calcHQWorth(),
    FactoryWorth = calcGlobalFactoryWorth(),
    WarehouseWorth = calcTotalWarehouseWorth(),
    SpecialBuildingWorth = calcTotalSpecialBuildingWorth(),
    target = document.getElementById("total-company-worth"),
    infoTarget = document.getElementById("total-company-worth-info");

  var total = crunchNumber(HQWorth + FactoryWorth + WarehouseWorth + SpecialBuildingWorth);

  switch (loc) {
    <array definition>
  }

  var title = localizedArray[0] + "...<br />";
  title += localizedArray[1] + ": " + crunchNumber(FactoryWorth).toLocaleString("en-US") + unit + "<br />";
  title += localizedArray[2] + ": " + crunchNumber(WarehouseWorth).toLocaleString("en-US") + unit + "<br />";
  title += localizedArray[3] + ": " + crunchNumber(HQWorth).toLocaleString("en-US") + unit + "<br />";
  title += localizedArray[4] + ": " + crunchNumber(SpecialBuildingWorth).toLocaleString("en-US") + unit;

  target.innerText = total.toLocaleString("en-US") + unit;
  infoTarget.title = title;

  if (!infoTarget._tippy) {
    tippy(infoTarget, {
      theme: "light",
      dynamicTitle: true
    });
  }
}
```

The function is called whenever someone changes an input value (over 100 different).

Alternatively, when loading the page and something is stored in localStorage from a previous visit.
