### ISSUE TITLE
iOS/MacOS: setting html and interactive to true will scroll into that element

### ISSUE THREAD

**Issue by faelsoto** [atomiks/tippyjs#146]
Hey, first of all, great work with tippy!

I'm having some issues regarding how the `interactive` flag works (and a bit on platform-specific gotchas), because this snippet:

```
if (options.interactive) {
  popper.focus();
}
```

On iOS/MacOS, regardless the browser, it will scroll the window to where that element is. However in other platforms (Firefox/Chromium Linux, Firefox/Chrome Android), it will not. Is this intended behaviour? I suspect not.

The issue on iOS is not suprising at all, because it's the same engine after all, but the thing's that really weird is that it will scroll down on Safari, Firefox and Chrome on MacOS.

The easy fix would be to add a new option to focus the popper if it's interactive, or maybe delete those lines?

Here's a demo: https://codepen.io/anon/pen/ZvOrqq

Update: It seems that the demo has the scroll behaviour regardless of browser, but it's still working without it on the site I'm working on.

**Comment by atomiks** [comment]
The idea here was to make interactive tooltips accessible (i.e. with a keyboard), so it needs to become focused when it's shown.

**Comment by faelsoto** [comment]
Ok, that makes sense. But it seems it's causing unintended behavior, maybe before the `focus()`, it could check if it's within the user's actual viewport?

Anyways, I've removed those lines on my end. I just wanted to contribute.

**Comment by atomiks** [comment]
Actually yeah, I have a function in the library for that when they HIDE the tooltip, but not when shown. Because the former one is what I personally encountered. So yes, that's a good idea. 😄
