### ISSUE TITLE
interactive tooltips and SVG on IE11

### ISSUE THREAD

**Issue by JulienJo** [atomiks/tippyjs#148]
Hi and happy new year.
I'm trying to use tippy with interactive tooltip on svg circle. It works well on Chrome, Edge, Firefox... but not on IE11  :'-(
You can see it live on that [codepen](https://codepen.io/Julien-Jolly/pen/pprydG).

Thanks for your help.
Cheers!

**Comment by atomiks** [comment]
Try increasing `interactiveBorder` from `2` to about `10` or more?

**Comment by JulienJo** [comment]
It don't work. 
Note that I have some warning messages in the console (sorry for the french):
![tippy](https://user-images.githubusercontent.com/8792500/34525078-09bf2292-f09e-11e7-9976-9fb716ec3f6d.PNG)

**Comment by JulienJo** [comment]
![tippy2](https://user-images.githubusercontent.com/8792500/34525192-62fc2a58-f09e-11e7-9403-7d481353b8ab.PNG)

**Comment by atomiks** [comment]
Can you translate that for me?

**Comment by JulienJo** [comment]
- The object does not handle the property or method "contains"
- Can not get property "add" of a null or undefined reference

You should see that on the [codepen](https://codepen.io/Julien-Jolly/pen/pprydG).

**Comment by atomiks** [comment]
Unfortunately I can't test on IE11 easily (on a Mac)

can you use the unminified version and check which lines of code cause the errors?

**Comment by JulienJo** [comment]
ok, sure:
- The object does not handle the property or method "contains": **649,3**
- Can not get property "add" of a null or undefined reference: **3275, 11**

**Comment by atomiks** [comment]
>The object does not handle the property or method "contains": 649,3
This appears to be within Popper.js. Might need to make an issue there, make note of it in `findCommonOffsetParent`. Make sure to follow the repo guidelines for the issue.

The second one is in mine, but maybe the first one is causing it.

**Comment by JulienJo** [comment]
ok, if you want to complete or fix my issue: 
[https://github.com/FezVrasta/popper.js/issues/515](https://github.com/FezVrasta/popper.js/issues/515)

**Comment by atomiks** [comment]
The problem is that IE requires a polyfill for classList for SVG. Both Popper and Tippy use `classList`, so you'll need to add a polyfill for it if you're using an SVG element as the reference.
