### ISSUE TITLE
Tooltip out of screen on mobile

### ISSUE THREAD

**Issue by dvhx** [atomiks/tippyjs#149]
Try following code:

```
<html>
  <head>
    <link rel="stylesheet" href="tippy.css">
  </head>
  <body>
    <style>td { border: 1px solid black; }</style>
    <table width="2000px">.
      <tr>
        <td>First column</td>
        <td>Second column</td>
        <td>Third column</td>
        <td><button class="btn" title="I'm a tooltip!">Text</button></td>
        <td>Fifth column</td>
      </tr>
    </table>
    <script src="tippy.js"></script>
    <script>  
    tippy('.btn');
    </script>
  </body>     
</html>
```
On mobile phone (chrome on android or webview) you have to scroll right to see the button, place it so that the button is near the edge. When you click on the button tooltip is cut of by the edge of the screen like this:

![photo](https://user-images.githubusercontent.com/6670178/34525471-59b35fb0-f09f-11e7-9d5d-eeeabe53a0af.jpg)

**Comment by JulienJo** [comment]
Maybe you can try <table width="100%">
or put your tooltip on the left?

**Comment by dvhx** [comment]
Try what? I don't see the second line.

> or put your tooltip on the left?
The problem is to know when to put it on left, I spent whole day and I think it cannot be done. I have somewhat working solution but it is too crazy. Btw. I tested 3 other tooltip libraries and all have this issue.

**Comment by JulienJo** [comment]
Maybe you can try `<table width="100%">`

**Comment by dvhx** [comment]
That was only to make page go behind corner. I'm using tooltip on third party website (extension) so I cannot change what is on the page or their meta

**Comment by atomiks** [comment]
A CodePen of this issue would really help me. Thank you 😄

**Comment by dvhx** [comment]
https://codepen.io/anon/pen/ypooeb

**Comment by atomiks** [comment]
That appears to be v1.

Can you try on `v2.0.8.`?

**Comment by dvhx** [comment]
same result

**Comment by dvhx** [comment]
It also doing the same thing on normal desktop chrome: https://delphi-update.com/tippy/index.html

**Comment by atomiks** [comment]
Well I guess Popper.js realizes the document width exceeds the button reference and so it can overflow. The whole document on mobile is scrollable right?

You might want to look into the `offset` option and change that based on where the button is located and what the screen width is.

**Comment by dvhx** [comment]
I'm not sure if it can be done, on mobile even when I scroll both window and document says 0.

**Comment by atomiks** [comment]
>when I scroll both window and document says 0.

Not sure what this means?

**Comment by dvhx** [comment]
On mobile without that meta, even when I scroll right 100px, no window or documentElement attribute is 100px (the usual suspects like scrollX etc are all zero)

**Comment by atomiks** [comment]
You mean the responsive `meta` tag? I guess mobile browsers with their zooming-out behavior cause the issue. Honestly not sure what the problem really is here. Just make it so the page doesn't overflow

**Comment by dvhx** [comment]
Well this bug makes tippy completely useless in chrome extensions.

**Comment by atomiks** [comment]
If other tooltip libraries also have the issue, then I assume their positioning engines all make similar assumptions about the document dimensions so they know how to position the tooltip. This might mean you need to alter your page setup to accommodate this fundamental behavior?

Have you tried modifying the page setup to overcome this?

**Comment by dvhx** [comment]
I'm basically trying to use tooltip in chrome extension on other pages. When user click some extra info is shown in tooltip. I cannot change design of every page.

**Comment by atomiks** [comment]
Ah, right, I see... that makes it more difficult.

Maybe try fiddling with the `popperOptions` option. Specifically, [`preventOverflow`](https://popper.js.org/popper-documentation.html#modifiers..preventOverflow)
