### ISSUE TITLE
flipBehavior doesn't seem to be working

### ISSUE THREAD

**Issue by kyletinsley** [atomiks/tippyjs#150]
I just switched to version 2.08 and am having trouble with flipping when migrating the following:

tippy("#id", {
	position: "right-start",
	arrow: true,
	performance: true,
	inertia: true,
	interactiveBorder: 5,
	popperOptions: {
		modifiers: {
			flip: {
				behavior: ["right", "bottom"]
			}
		}
	}
});

to this:

tippy("#id", {
	placement: "right",
	arrow: true,
	performance: true,
	inertia: true,
	interactiveBorder: 5,
	flipBehavior: "clockwise"
});

The tooltip no longer flips from the right to the bottom.  However, this does work:

tippy("#id", {
	placement: "right",
	arrow: true,
	performance: true,
	inertia: true,
	interactiveBorder: 5,
	flipBehavior: ["right", "bottom"]
});

Is there an issue with flipBehavior?

Thanks!!

**Comment by atomiks** [comment]
It might be a problem with Popper.js... try and recreate it here

https://codepen.io/FezVrasta/pen/wGqJEz

**Comment by kyletinsley** [comment]
Okay, I added a comment here:
https://github.com/FezVrasta/popper.js/issues/167

Thanks for Tippy!!

**Comment by atomiks** [comment]
Closing Popper.js-related bugs, previously left them open for visibility.

If you experience problems with positioning please create an issue over at the Popper.js repo: https://github.com/FezVrasta/popper.js/issues

**Comment by cjsio** [comment]
So does anyone know of a working solution for `flipBehavior`?
