### ISSUE TITLE
Does not attach tip when no "title" present, but dynamicTitle is true

### ISSUE THREAD

**Issue by beether** [atomiks/tippyjs#151]
The expected behavior for "dynamicTitle" is that it will show a tip once a title is set. However, if the title is not _initially_ set, Tippy won't ever show a tip.

**Comment by atomiks** [comment]
Yeah the behavior has been like that since the option was introduced, but I guess it should still create the instance in that case.

**Comment by beether** [comment]
It's not a big deal, just caught me by surprise :)
