### ISSUE TITLE
Feature: Allow HTML in the title string

### ISSUE THREAD

**Issue by beether** [atomiks/tippyjs#154]
It would be _extremely_ convenient if one could allow HTML in the title string. It's a bit of a hassle to create a new DOM element, point to it, etc, just to add a "\<br\>" for example. Just an idea. Love the library either way :)

**Comment by atomiks** [comment]
It already is allowed

**Comment by beether** [comment]
Wow I'm an idiot. I swore last time I tried it literally showed `<br>`. Sorry about that
