### ISSUE TITLE
aria-describedby is set when no element is in DOM

### ISSUE THREAD

**Issue by omRm** [atomiks/tippyjs#156]
The *aria-describedby* Attribute is set even when the tooltip is not in the DOM.

from the MDN docs:
*since it is an ID, it must reference an element in the same DOM document.*

can we remove this attribute when the tippy is not shown ?

**Comment by atomiks** [comment]
Is there a reason it should be removed?

**Comment by omRm** [comment]
While the tooltip is not in the DOM,
the aria-describedby Points to nothing. Afaik screenreaders will have trouble with this. 

So dir accessibility reasons

**Comment by atomiks** [comment]
But when the reference element receives focus, the tooltip gets appended to the page and so it should not be an issue right?

**Comment by omRm** [comment]
depends. imagine a tooltip will only show on mouse-hover, a visually impaired user might only use the keyboard to tab. they won't be able to get the described information, even worse, screenreaders might trough some gibberish.

i know its best practise to only have a aria-describedby tag if there is an element.

**Comment by atomiks** [comment]
I just checked Bootstrap 4 and it looks like they also remove the attribute when it's hidden, so it's probably the best way to do it. Back in the alpha stages it kept it there so I assumed that was fine.

**Comment by omRm** [comment]
I think tooltip.js also removes it?

Only noticed this today as a coworker mentioned it.

**Comment by atomiks** [comment]
Should it be removed/added at the end of each transition? (aka `onShown` and `onHidden`)? Bootstrap appears to do that rather than add it immediately on show/hide

**Comment by omRm** [comment]
Im not sure. I guess adding It immediatly would ne better

**Comment by atomiks** [comment]
I've decided to do it after the transition ends because I think the delay is better for screenreaders so it can focus on the element first then the tooltip. Also I'm sure Bootstrap knows best 😆

**Comment by omRm** [comment]
Hehe, this is totally fine by me. I'm sure bootstrap knows it. If anything i can ask my accessibility expert tomorrow.
