### ISSUE TITLE
[Feature request] Add a 'skewed' arrow type

### ISSUE THREAD

**Issue by AlexandreBonneau** [atomiks/tippyjs#157]
First, Tippy is a great library! 👍

Second, would it be possible to add a new type of arrows, that would slightly change its appearance based on where the tooltip appears relative to its parent element?

An image is worth thousand words so, this is what I'm thinking about: 

![2018-01-15_tooltips_for_tippy](https://user-images.githubusercontent.com/7248877/34963670-d6a50eea-f9ed-11e7-8459-47b6d69a5cf5.png)

Bonus: the arrow could be moved a bit toward the parent element instead of being always in the tooltip axis (that would be even more meaningful on bigger elements like the one on the bottom of that picture).

**Comment by atomiks** [comment]
Nice idea! This should be possible.

**Comment by atomiks** [comment]
This has been possible since the beginning, and while I could add an `arrows/` directory for custom arrows styling, too much burden is placed on the lib. You can modify the arrow CSS or use a custom SVG arrow shape to achieve this.
