### ISSUE TITLE
Light theme is missing from CSS

### ISSUE THREAD

**Issue by andrewckor** [atomiks/tippyjs#158]
I recently updated from 1.x to 2.0.9 and seems like that the `light-theme` is missing, I can't find it anywhere in the css files. Has it been removed?

**Comment by hacknug** [comment]
I believe they were removed with 2.0. You can read about it in the beta changelog: https://github.com/atomiks/tippyjs/releases/tag/v2.0.0-beta

**Comment by andrewckor** [comment]
Yes you are right @hacknug, but they still exist in [/src](https://github.com/atomiks/tippyjs/tree/master/src/scss/themes) folder but they are not exported. @atomiks Can you include it in the final `/dist` export?

**Comment by atomiks** [comment]
@andrewckor sure thing

**Comment by atomiks** [comment]
`2.1.0` under the `themes` folder
