### ISSUE TITLE
pointer-events issue

### ISSUE THREAD

**Issue by andrewckor** [atomiks/tippyjs#159]
With the following settings, my interactive tooltip, doesnt seem to catch the mouse events.

```
defaultOptions: {
            duration: [300, 200],
            delay: [0, 50],
            distance: 5,
            size: 'small',
            arrowType: 'round',
            arrowTransform: 'scale(0.7, 0.6)  translateY(-3px)',
            flip: false,
            animation: 'shift-away',
            inertia: true,
            interactive: true,
            dynamicTitle: true,
            interactiveBorder: 20,
            arrow: true
}

tippy(options.popup, {
            distance: 20,
            duration: [350, 150],
            delay: [0, 150],
            interactiveBorder: 10,
            placement: 'bottom',
            size: 'small',
            theme: 'light popup'
});
```
Here is a gif of the bug:
![error](https://user-images.githubusercontent.com/929765/35105851-59820ee2-fc75-11e7-95b7-06af8f80dbf9.gif)

By adding 
```
.tippy-popper {
      pointer-events: true;
}
```
It is working correctly:
![success](https://user-images.githubusercontent.com/929765/35105912-8050664a-fc75-11e7-81f4-6f9b1397baab.gif)

**Comment by atomiks** [comment]
With `interactive` to true the pointer-events are enabled again. Did you solve this? (Noticed you closed the issue).

**Comment by andrewckor** [comment]
Yes, it is working, I forgot to extend default settings.
