### ISSUE TITLE
How to have different tooltips on the same page?

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#161]
Hi, I've got a problem I can't solve. I have several groups of icons with their tooltips. Fine. Problem: each group should show tooltips of different colors, based on the group's container class.
But tooltips are instantiated in document.body, and if I change the parent with the appendTo option, such as 

``` js
appendTo: function(){
   // so tootips should be instantiated inside each icons group's container
   return document.getElementsByClassName('lr-tgi-optional')
}
```

I get an error (TypeError: this.options.appendTo.contains is not a function).
So how to? Is there a way? Thank you

**Comment by atomiks** [comment]
You need to return an Element, currently it's a NodeList.

```js
appendTo: function () {
   return document.querySelector('.lr-tgi-optional')
}
```

**Comment by stratboy** [comment]
Mmmm I thought. But that doesn't work for my needs. Anyway, I ended up instantiating several tippy, one for each color, so I can use different themes. Tippy is plain awesome. Thank you.
