### ISSUE TITLE
Reinitialise tippy after AJAX load?

### ISSUE THREAD

**Issue by stevehosesolutions** [atomiks/tippyjs#162]
Hello,

Tippy is perfect! Except for I can't get it working on new data shown after an AJAX call.

Is there an easy way to reinitialise tippy so that it works on these new DOM elements?

Thanks!

**Comment by atomiks** [comment]
After they've been appended to the DOM, just call `tippy` again?

**Comment by stevehosesolutions** [comment]
I've tried putting the call in the ajax success callback function.

`	$.ajax({
	  	type: "POST",
	  	url: "/results.php",
	  	dataType: 'json',
	  	cache: false,
	  	data: {filterOptsSingle: optsSingle, filterOptsSelect: optsSelect, filterOptsMultiple: optsMultiple, filterOptsArea: optsArea, filterSort: optsSort},
	  	success: function(data){
            renderResults(data);
            tippy('.icon-tooltip, .extra-features li a' , {
			  	placement: 'right',
			  	arrow: true
			})
	  	}
	});`

Also, in a global ajaxComplete function:

`	$(document).ajaxComplete(function(){
	    tippy('.icon-tooltip, .extra-features li a' , {
		  	placement: 'right',
		  	arrow: true
		})
    });`

If I put the HTML on the page without AJAX, the tooltips work, it's just when AJAX appends the JSON data it doesn't work? 

Sorry, I know this is such a beginner issue, but I would really appreciate the help!

**Comment by atomiks** [comment]
I'm assuming `data` is just a bunch of HTML, and you basically append it to some element?

Make sure the elements have `title` attributes, and that they have the correct class names for the selectors there, and that they are actually on the DOM before `tippy()` gets invoked. For the last thing, wrap the tippy call in `setTimeout(() => tippy( ... ))`

**Comment by stevehosesolutions** [comment]
Perfect, it seems there was a 500ms delay on the data getting shown - so tippy was invoked before the data. setTimeout worked perfectly.

Thanks for helping out, you've made my day!
