### ISSUE TITLE
Tooltips are blurry on chrome

### ISSUE THREAD

**Issue by IbrahimAlKhalil** [atomiks/tippyjs#163]
Chrome makes tooltip blurry. 
FF, IE, Edge are okay, I changed theme, animation and inertia but not worked.

!!! Chrome !!!
![capture](https://user-images.githubusercontent.com/30016253/35324400-d3cffb92-011a-11e8-9445-bb126c092f33.PNG)

!!! Firefox !!!
![6a9b03e9-e7dc-4147-930c-e466fa6f71dc](https://user-images.githubusercontent.com/30016253/35324894-5c435c52-011c-11e8-8c4b-1b356314604a.png)

Please help!

**Comment by atomiks** [comment]
I think it's to do with `translate3d` that Popper uses... and sometimes Windows' system scaling thing from what I've read.

Is `translate` without `translate3d` (removing the 3rd arg too) fine? Maybe the `perspective` CSS rule on `.tippy-popper` as well?

Try: 

```js
tippy(el, {
  popperOptions: {
    modifiers: {
      computeStyle: {
        gpuAcceleration: false
      }
    }
  }
})
```

BUT this has a large performance impact.

**Comment by IbrahimAlKhalil** [comment]
It works! Thanks :)

**Comment by changbowen** [comment]
setting `gpuAcceleration: false` also worked for me. :+1: :+1: :+1: 
no visible performance issue... even if there is, i would prefer using a bit more CPU over blurry text
you should put that on the project website :)

**Comment by davidgraeff** [comment]
I have the same problem. But not using transformations is not required. See:

https://googlechrome.github.io/samples/css-will-change-transform-rasterization/

You just need to remove "will-change".

**Comment by atomiks** [comment]
@davidgraeff this is a Popper.js issue, if `will-change` should be removed, you can visit their repo
