### ISSUE TITLE
Tooltip does not work for saved pages

### ISSUE THREAD

**Issue by KES777** [atomiks/tippyjs#167]
```
<span class="tippy" data-tooltipped="" aria-describedby="tippy-tooltip-1" data-original-title="&lt;span&gt;DPI&lt;/span&gt; - Deep Packet Inspection. Known to be used in some countries with restrictive internet policies">DBI</span>
```
while the in source
```
<span class="tippy" title="&lt;span&gt;DPI&lt;/span&gt; - Deep Packet Inspection. Known to be used in some countries with restrictive internet policies">DBI</span>
```
Start JS is:

```
  tippy('.tippy', {
      theme: 'safevpn',
      animation: 'shift',
      hideOnClick: 'persistent',
      zIndex: 40
  });
```

Tippy should understand that element is already processed and still add events

**Comment by atomiks** [comment]
I don't understand what you mean here?

When you click "view source" it doesn't execute the JS, so the elements will be unprocessed

**Comment by KES777** [comment]
>There shouldn't be a case where you save the processed version of the elements.

FF and Chrome both work in such way. If you are interested I can send full saved page

**Comment by atomiks** [comment]
Yeah I guess. Not 100% what you mean exactly
