### ISSUE TITLE
[question] best way to ensure popover is always on-screen?

### ISSUE THREAD

**Issue by aervin** [atomiks/tippyjs#171]
Tippy version: **`^2.0.9`**

I'm using Tippy in Angular 5 via a custom `@Directive` and it's been fantastic thus far. The only thing I'm having trouble with is altering the `placement` of popovers so they're always visible on-screen. I have a large grid of approx. 500 divs, and as the viewport shrinks, I need the divs on the right-hand side to display popovers to the `left` rather than the `right`. Perhaps there are programmatic workarounds, but I thought I'd check here first.

My config for each div
```js
{
        animation: 'shift-away',
        appendTo: this.element.nativeElement,
        arrow: true,
        arrowTransform: 'scaleX(1.5)',
        distance: 16,
        duration: 200,
        html: '#TIPPY_' + timeblockData.id,
        inertia: true,
        interactive: true,
        placement: 'right',
        trigger: 'click'
}
```

I've tried
```js
{
    /* ... */
    popperOptions: {
        placements: 'auto'
    }
}
```

and I've also tried removing all `placement`-related config options to see if the library would sort things out itself.

Anything I'm missing here? Thanks in advance for the help!

**Comment by atomiks** [comment]
I don't believe there's a direct way to do this (in Tippy or Popper)

One option might be: 
```js
tippy(el, {
  placement: window.innerWidth < 576 ? 'left' : 'right'
})
```

To make it "live" (aka dynamic), you'd need to use a listener:

```js
tippy(el, {
  placement: window.innerWidth < 576 ? 'left' : 'right'
})
window.addEventListener('resize', () => {
  el._tippy.popperInstance.options.placement = window.innerWidth < 576 ? 'left' : 'right'
})
```

**Comment by aervin** [comment]
Thanks @atomiks, I feel you've answered my question very well. And for anyone looking to change popover `placement` conditionally, I'd recommend your answer. However, I've run into further issues due to setting a fixed width on the popovers (via theming). Anyway, I have no problem w/ this issue being closed. And thanks again!
