### ISSUE TITLE
.show() inside an onclick not working, codepen reproduced

### ISSUE THREAD

**Issue by KayakinKoder** [atomiks/tippyjs#172]
Thanks for the great library, just getting into it and it's going to make our app much better. I must be reading the docs wrong about .show(), I can't seem to get it to work inside an onclick.

Codepen: https://codepen.io/cpj22/pen/qxBGRv?editors=1111

**js**
```js
var tippyEl = document.querySelector('#myButton');

tippy(tippyEl, {
  html: document.querySelector('#myTemplate'),
  trigger: 'manual'
});

tippyEl.onclick = function() {
  tippyEl._tippy.show();
  console.log('click occurred');
};
```

html
```html
<div id="myTemplate">
    <p>My Template</p>
</div>
<button id="myButton">My Button</button>
```

**Comment by atomiks** [comment]
You need this option:

```js
hideOnClick: false
```

Tooltips are closed on click by default, causing it to never show. Actually, with a manual trigger, I guess it shouldn't by default...
