### ISSUE TITLE
Blurred text if zoom is over/under 100%

### ISSUE THREAD

**Issue by bayramq** [atomiks/tippyjs#175]
Text gets blurred in every browser if the browser zoom is over/under 100%.

![bildschirmfoto 2018-02-01 um 15 57 58](https://user-images.githubusercontent.com/30617751/35684829-56bc01ce-0768-11e8-95b2-5cb8d4dec883.png)

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/issues/163#issuecomment-360077043
