### ISSUE TITLE
Delay Duration not working in Edge

### ISSUE THREAD

**Issue by vairamsvsjdo** [atomiks/tippyjs#176]
I am trying to run tooltip with delay duration enabled.

Steps to reproduce
1. Run the JSfiddle: https://jsfiddle.net/vairamsvs/z6a8qtgL/
2. Hover over button two and click the link in popup.
3. Frame x-deny error

Expected behavior
1. able to hover over button and navigate to tooltip and click the link

Actual Behavior
1. when focused over tooltip, tooltip disappears in Edge. It works correctly in Chrome and Firefox

**Comment by atomiks** [comment]
I don't have the means to test in Edge unfortunately! 😓 

Try setting `animateFill: false`

Also in the fiddle, the body element must stretch past the popper. There is a mouseleave listener on the body.

**Comment by vairamsvsjdo** [comment]
@atomiks 
That trick didn't help.
Also, I did not follow what you meant by *body element must stretch*. I dropped the code in "no wrap in body".
I created this github.io page and I see the same behavior: 
https://jaydevops.github.io/jaydevopswebcode/tippyjs.html
``` html

$(document).ready(function() {
--
  | tippy('.my-button2', {
  | animateFill: false
  | });
  | });

```
I added animateFill: false as above.

**Comment by vairamsvsjdo** [comment]
@atomiks 
changing it to data-toggle-trigger="click" makes it work in Edge also as in the example: *Tooltips can even contain HTML!  * https://atomiks.github.io/tippyjs/

**Comment by vairamsvsjdo** [comment]
Is bootstrap@4.0.0 css a requirement for this to work correctly?

**Comment by atomiks** [comment]
Add 

```css
html, body {
  height: 100%;
}
```

to ensure the elements fill the screen
