### ISSUE TITLE
tabing in IE11 will not remove tooltip

### ISSUE THREAD

**Issue by jburghardt** [atomiks/tippyjs#177]
tab the tooltips with  IE11  on: https://atomiks.github.io/tippyjs/
they will not disappear even when they lost focus.

i have a feeling that this is connected with the blur event.

**Comment by atomiks** [comment]
I think that `relatedTarget` is undefined on IE11 for `blur`. I believe `focusout` needs to be used.

**Comment by jburghardt** [comment]
Yep, it does fix it !

**Comment by atomiks** [comment]
Please see the new commit to test in case you didn't, as old FF (<52) doesn't support `relatedTarget` on `focusout`.

**Comment by jburghardt** [comment]
Tested with 
- Chrome 64
- IE11
- Firefox ESR 52
- Edge 41

All seems to work fine. Although FF and Edge are jumping in weird after they are shown for the first time. but i dont know if it is related to this issue.

**Comment by atomiks** [comment]
Jumping in weird? If you can, take a screenvid of it and make a new issue 😄

**Comment by jburghardt** [comment]
I can do that at the weekend.

But i noticed something else with this fix. 
A tooltip now wont disappear if it is tabed on and then another tooltip is focus on with the mouse.

**Comment by atomiks** [comment]
I think that's normal behavior? If a ref element is focused, the tooltip will still be visible even if another element is being hovered over. Is that caused by the fix or is it also happening on the current docs page?

**Comment by jburghardt** [comment]
its happening on the current doc pages, too, so not related to this fix.
well, the more i think about it ... it really is normal behaviour. focused element should keep tooltip when another element is hovered on.

tabbing now works correctly in ie11, i think this can be closed then

**Comment by jburghardt** [comment]
can we get a 2.1.2 with this fix ?
