### ISSUE TITLE
Each tooltip starts offset to bottom left and first trigger transitions it into position

### ISSUE THREAD

**Issue by mystrdat** [atomiks/tippyjs#179]
I'm seeing the following buggy behavior on all tooltips, both in v1 and now v2:
![2018-02-09_17-49-10](https://user-images.githubusercontent.com/1652895/36039030-9f0ead28-0dc1-11e8-9309-a5efbf7ae3e0.gif)

It seems every tooltip instance is somehow first transitioned from its initial position towards the target center, but not anymore once it has been loaded at least once.

**Comment by mystrdat** [comment]
I should add this behavior is fixed if I force `transition: none !important` on `.tippy-popper`, otherwise there is no code that would influence the visual outcome.

**Comment by atomiks** [comment]
Which browser / OS?

**Comment by atomiks** [comment]
The tooltip has the actual animation transition, the popper (parent of the tooltip) has a transition to make flips smooth. But it basically is just causing too many issues.

It is actually an option:
```js
updateDuration: 350 // make it 0
```

which will add a transition duration to the popper. It's only useful for flipping and `sticky` really, but I think I will make it `0` by default to avoid these issues.

**Comment by atomiks** [comment]
see #180
