### ISSUE TITLE
Delay and wait not working on the first time with event delegation

### ISSUE THREAD

**Issue by kosaruben** [atomiks/tippyjs#181]
When using event delegation, delay and wait are ignored when showing the tooltip for the first time. However, delay works well on hiding. The bug with delay can be seen in the fiddle below, the one with wait can be reproduced likewise: [https://jsfiddle.net/kosaruben/hzd7akau/](https://jsfiddle.net/kosaruben/hzd7akau/)

**Comment by atomiks** [comment]
The child tooltip is immediately shown without delays, doh 😓 
Won't be hard to fix I think as I already know what's wrong without looking at the code. Will get to it later today..
