### ISSUE TITLE
Interactive tooltip with HTML on Button does not close when button is in a Bootstrap modal window.

### ISSUE THREAD

**Issue by davemoore24** [atomiks/tippyjs#182]
I've tried just about everything to get this to work. Anytime I use trigger: 'click' inside of a modal window the tooltip will not close. I am using BS4 dropdown SCSS, not their JS. Any ideas?

![image](https://user-images.githubusercontent.com/6215968/36228711-96a63bb0-119a-11e8-8155-2bd65da97afd.png)

**Comment by atomiks** [comment]
Will not close upon clicking where? If all else fails, you can bind your own custom event listener somewhere to ensure it's closed.

**Comment by davemoore24** [comment]
I just doubled checked with a static HTML template using BS4 modals and it works... so, something else in my app is preventing it... Ill close. thanks.
