### ISSUE TITLE
Line-height of tippy-popper class cuts off some characters

### ISSUE THREAD

**Issue by ljosberinn** [atomiks/tippyjs#187]
Hi,

as seen in following screenshot, some letters will be cut off by the `line-height` of `.tippy-popper`.

<img width="269" alt="bildschirmfoto 2018-02-19 um 09 29 34" src="https://user-images.githubusercontent.com/29307652/36368493-cc34b5b6-1557-11e8-8916-f2b4f905f320.png">

This can be fixed by adding a `line-height` of at least `1.35`:

<img width="285" alt="bildschirmfoto 2018-02-19 um 09 33 08" src="https://user-images.githubusercontent.com/29307652/36368521-eaf97540-1557-11e8-98f1-2fa5104a690d.png">

**Comment by atomiks** [comment]
Made an issue myself already yesterday: #185! Thanks for reporting though

**Comment by atomiks** [comment]
`v2.2.3`, set `line-height: 1.4` on `.tippy-popper`
