### ISSUE TITLE
setting theme to 'light' doesn't have any effect

### ISSUE THREAD

**Issue by hirasso** [atomiks/tippyjs#189]
With the newest version of tippy, setting the theme to `light` doesn't have any effect anymore. Here's my code:
```javascript
$('.tooltip').each(function() {
  let $btn = $(this);
  let templateId = $btn.attr('data-template-id');
  let args = {
    arrow: true,
    trigger: 'click',
    theme: 'light',
    duration: 150,
    interactive: true,
    offset: '0, 30',
    // hideOnClick: false
  };

  if( $(templateId).length ) {
    args.html = templateId;
    $(templateId).click(function(e) {
      e.stopPropagation();
    });
  }
  tippy( $btn.get(0), args );
});
```

**Comment by hirasso** [comment]
![screenshot 2018-02-21 13 09 34](https://user-images.githubusercontent.com/869813/36479325-8864adca-1708-11e8-817e-256bc44724fc.jpg)

**Comment by atomiks** [comment]
Themes aren't included in the CSS by default. They are under the `themes` folder now.

**Comment by hirasso** [comment]
Great, thanks for your help!

**Comment by webwakko** [comment]
For those wondering where to find it : 
adding this  should do the trick ;) 
import 'tippy.js/dist/themes/light.css'

**Comment by Weber-D** [comment]
It would be great to add this in the documentation cause the _getting started_ section says: 
> tippy.all.js is all dependencies (Tippy + Popper + CSS) in a single file. The CSS is injected into the document head.

**Comment by Sam-DevZ** [comment]
Yep, definitely caused unnecessary confusion.

**Comment by atomiks** [comment]
Sorry for the confusion. The Themes demo showed they are included in `dist/themes` but yeah it was not worded clearly anywhere else! 😢

**Comment by spsaucier-bakkt** [comment]
For others like me, note that the themes are not in the `dist` folder anymore.
```
	<link rel="stylesheet" href="https://unpkg.com/tippy.js@5/dist/backdrop.css" />
	<link rel="stylesheet" href="https://unpkg.com/tippy.js@5/themes/light.css" />
```

**Comment by Benjoyo** [comment]
Not confusing at all :)

**Comment by jzyds** [comment]
> For those wondering where to find it : adding this should do the trick ;) import 'tippy.js/dist/themes/light.css'
Update, from the new version the file has move to tippy.js/themes/. The new import path is "tippy.js/themes/light.css"
