### ISSUE TITLE
Position incorrect when `position` is set on body

### ISSUE THREAD

**Issue by hirasso** [atomiks/tippyjs#190]
Hi there, another issue showed up:
![screenshot 2018-02-21 16 27 30](https://user-images.githubusercontent.com/869813/36488631-3d822b9a-1724-11e8-97a6-d8d9d4e7f609.jpg)

The tooltip overlaps the trigger button (The big green one, saying 'FOOBAR')

![screenshot 2018-02-21 16 28 59](https://user-images.githubusercontent.com/869813/36488677-586f5eb4-1724-11e8-9d4f-e1ac3ab24220.jpg)

...and if there isn't enough space to the top, it goes far too much away.

I haven't defined any `offset` or `distance` in the tippy options:

```javascript
$('.tooltip').each(function() {
  let $btn = $(this);
  let templateId = $btn.attr('data-template-id');
  let args = {
    arrow: true,
    trigger: 'click',
    theme: 'light',
    duration: 150,
    interactive: true,
  };

  if( $(templateId).length ) {
    args.html = templateId;
    $(templateId).click(function(e) {
      e.stopPropagation();
    });
  }
  tippy( $btn.get(0), args );
});
```

**Comment by hirasso** [comment]
...also happens if I only use a simple title attribute on the trigger instead of an HTML-template

**Comment by atomiks** [comment]
A CodePen would help.

**Comment by hirasso** [comment]
OK, I will try to build one.

**Comment by hirasso** [comment]
So, I have been able to re-produce the problem. It appears as soon as there is a `position="relative"` set on the `body`:

https://codepen.io/hirasso/pen/GQGXQX

**Comment by hirasso** [comment]
This could actually be a FAQ :)

**Comment by atomiks** [comment]
Does this occur with earlier Popper.js versions? Which one does `1.4.2` use? Or the one you were using last?

**Comment by hirasso** [comment]
I don't know what popper version I am using and can't find the version in the tippy package... I created a new Pen that uses tippy@1.4.2. It has the same issue:

https://codepen.io/hirasso/pen/wyxqbZ

**Comment by atomiks** [comment]
It's most likely a Popper issue then with one of the more recent versions. There's most likely an issue already made.

Btw I recommend not setting any kind of `position` on the body.

**Comment by hirasso** [comment]
> Btw I recommend not setting any kind of position on the body.

You are totally right – that's why I suggested putting this in a FAQ :)

Thanks for your quick response, and for this great tool!!!

**Comment by atomiks** [comment]
Ah right, yeah... I need to make a FAQ on the docs in a neat fashion.

Also if you put `margin: 0` from the body, it's fixed even with `relative`.

`normalize.css` fixes this kind of stuff which I recommend using.

**Comment by hirasso** [comment]
> Also if you put `margin: 0` on the body, it's fixed even with `position: relative`.

This is also helpful, thanks a lot!

**Comment by atomiks** [comment]
Closing Popper.js-related bugs, previously left them open for visibility.

If you experience problems with positioning please create an issue over at the Popper.js repo: https://github.com/FezVrasta/popper.js/issues
