### ISSUE TITLE
Dynamically update tooltip placement

### ISSUE THREAD

**Issue by tomparle** [atomiks/tippyjs#191]
Hi,

maybe I missed something but, how is it possible to update a tooltip's placement ?
Once it has been set in options (for ex: "top"), the tooltip placement does not change when I try to update to data-tippy-placement="right" for exemple.

Thanks for your amazing library !
Tom

**Comment by atomiks** [comment]
Change the `popperInstance` placement and update the position manually.

```js
const { popperInstance } = el._tippy 
popperInstance.options.placement = 'right'
popperInstance.update()
```

This will be documented in a sec 😄

**Comment by tomparle** [comment]
Wow, thank you for the quick answer Atomiks, you're great !

This actually works :-) 
I actually tried the update() method but on the Popper instance, which failed.
I also used update() directly on the _tippy object (which also failed) instead of wrapping it around a const { popperInstance } as you did. I do not really understand the difference actually, Indeed I think it'll be great to add this in the documentation !

Thank you again
Tom

**Comment by atomiks** [comment]
It's just destructuring but it confused me at first before I learnt it.

```js
// ES6
const { popperInstance, options } = el._tippy

// Same as
const popperInstance = el._tippy.popperInstance
const options = el._tippy.options
```

**Comment by tomparle** [comment]
Wow, I guess I'm not done with the new ES6 syntax. Thank for the tips !

Two more things : 
- it seems that it's preferable to call _scheduleUpdate()_ rather than _update()_ method in popperInstance, as stated in popper.js documentation
- I would expected that any change done to the tooltipped element should be reflected to the actual tooltip, as if every properties were dynamic like the "dynamicTitle" option does. 

This would allow us to write 
`el.dataset.tippy-placement = 'right'; // change tooltip placement dynamically`

**Comment by atomiks** [comment]
For a single update, it doesn't matter which one you use, it's mainly for the event listeners which fire rapidly.

I agree with the options thing. I need to list which ones are "live" (in that you can change them after they init and those changes will be reflected), versus which options can only be specified at init time.

Brief list:

Init time:
- `arrow`
- `placement`
- `animateFill`

Can be changed after init:
- `duration`
- `delay`
- `livePlacement`
