### ISSUE TITLE
Compatibility issue with Symfony?

### ISSUE THREAD

**Issue by Artusamak** [atomiks/tippyjs#195]
Hi, thank you for your lib, i'm eager to be able to use it, it looks perfect!

I'm trying to use it in a custom Symfony 3 app running encore and npm to manage js lib dependencies.
When i try to call and use your lib in my JS script file, the following issue happen:

> TypeError: document.querySelector(...) is null

![image](https://user-images.githubusercontent.com/201299/36816625-a590718c-1cde-11e8-9883-709ad5f20abe.png)

The code generating this issue is the following, i included just before a `console.log()` to show that a DOM element exists:

```
var Tippy = require('tippy.js');
a = document.querySelector('.btn.tippy');
console.log(a);
Tippy(a);
```

I don't really understand why the error is thrown so i'll be more than happy if you can help.

Thank you very much!

**Comment by atomiks** [comment]
Where does that error occur in the lib?

**Comment by atomiks** [comment]
You can open the file from the console there and it should highlight the line. All.js without min is not minified.

**Comment by Artusamak** [comment]
Oh yes, thank you.

Here is the incriminated line:

![image](https://user-images.githubusercontent.com/201299/36817616-0c7ac84a-1ce2-11e8-9e96-507b6cb890e7.png)

**Comment by atomiks** [comment]
That means the HTML template doesn't exist on the document

**Comment by Artusamak** [comment]
Yes it works! Excellent, thank you!

Yes it was for testing purpose, i saw that it was populated from the tippy() options.

Perfect!
