### ISSUE TITLE
Replace innerHTML properties with textContext?

### ISSUE THREAD

**Issue by bengarrett** [atomiks/tippyjs#197]
Hi, thanks for the great work on Tippy! I have a bit of a niche request.

With the [Mozilla web-ext lint tool](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext), Trippy triggers a few _UNSAFE_VAR_ASSIGNMENT_ warnings. These can revoke WebExtensions that include the Tippy dist from being submitted to the Mozilla Addons page.

If there are no conflicts the fix is pretty easy. Where an [innerHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) property is used to set a string value, replace these with the [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) property.

`content.innerHTML = title;` > `content.textContent = title;`

Mozilla suggests as textContent is not parsed, it's faster and also avoids potential XSS attacks.

![2018-03-08_10-57-15](https://user-images.githubusercontent.com/513842/37125258-e9e2b368-22bf-11e8-81d7-d5cd1570dc07.png)

**Comment by bengarrett** [comment]
Ahh I see. The Mozilla lint tool scans the source and I think it requires the removal of all `innerHTML` properties that set variables as values.

As a possible work around there is the `parseFromString(string, 'text/html')` function from DOMParser API that can parse markup text into elements?
https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

**Comment by atomiks** [comment]
Do you think we could trick it with something like:

`content[options.allowTitleHTML ? 'innerHTML' : 'textContent'] = title`

**Comment by bengarrett** [comment]
That's a nice little hack ;) I tested it and it seems to trick the linter.

**Comment by atomiks** [comment]
`2.3.0` (unminified though)

**Comment by marco-c** [comment]
I think this is happening again.

**Comment by marco-c** [comment]
https://github.com/atomiks/tippyjs/pull/307 should fix the problem.
