### ISSUE TITLE
Turn off all tippy animations

### ISSUE THREAD

**Issue by padi** [atomiks/tippyjs#198]
Desired API:
https://codepen.io/padi/pen/YaKYXy

Why?
For running browser testing more predictably. Right now I'm manually turning off transition-related duration by setting the defaults to 0s/false (duration, flipDuration, stickyDuration, animateFill)

Similar implementation: https://api.jquery.com/jquery.fx.off/

**Comment by atomiks** [comment]
EDIT: Yes this is a good idea. Although it should probably be a function instead?

```js
tippy.disableAnimations() // maybe?
```

`stickyDuration` and `flipDuration` from v1 are now `updateDuration` in v2 btw. And flipping transitions were removed recently unless it's sticky due to problems with the position being transitioned when it shows for the first time.

**Comment by padi** [comment]
Transitions can be tricky during browser testing. They sometimes introduce race conditions while automating some interaction (in my case I'm filling up a form within a tooltip). Also while I had an external test-only stylesheet that can set `0s important` across `*-duration` css rules, it can't override inline styles that were injected by javascript.

`tippy.disableAnimations()` would be good as well. :+1:

**Comment by atomiks** [comment]
`2.3.0`

**Comment by tusharshuklaa** [comment]
May be off-topic but I'm using **React Tippy** and I'm not able to find how to remove tippy animations. I don't want the tooltip to animate when moving from one tooltip to another. Any suggestions, please?

**Comment by atomiks** [comment]
`animation={false}`
