### ISSUE TITLE
Angularjs Directive?!

### ISSUE THREAD

**Issue by HashemKhalifa** [atomiks/tippyjs#20]

**Comment by HashemKhalifa** [comment]
There's no plan to create an angular js directive ?

**Comment by atomiks** [comment]
I've never used angular before, so not sure what that is?

**Comment by atomiks** [comment]
I've made some changes that might make it easier to integrate with libraries/frameworks like React, Vue, Angular, etc, with v0.4.0... but I personally won't make wrappers/directives for each framework

**Comment by nickbreaton** [comment]
@atomiks I am planning on making an AngularJS wrapper since I have a legacy angularjs app I am supporting. Would you be up for adding it to the official list once it is complete? I am trying to mirror the official React version as close as possible.

**Comment by theodev3478** [comment]
Hi @nickbreaton 
I just checked your https://www.npmjs.com/package/tippy-angularjs.
I have angularjs app and using bower.
How do I do to use your directive on my app?
