### ISSUE TITLE
How correctly to write?

### ISSUE THREAD

**Issue by mihabotanik** [atomiks/tippyjs#202]
Hello!
I'm setting a name for:
block 1 `<div id="<?php the_field(b1) ?>">text</div>`
block 2 `<div id="<?php the_field(b2) ?>">text-text</div>`

**How correctly to write here?**

`
tippy('....id block 1', {
	html: document.querySelector('......id block 2')
})
`

**Help me, plz)**

**Comment by atomiks** [comment]
You mean an ID selector? Use `#` before the id.
```js
// <div id="something">text</div>
tippy('#something')
```

Same goes for the `html` option.

**Comment by mihabotanik** [comment]
`tippy('#<?php the_field(b1) ?>', { html: document.querySelector('#<?php the_field(b2) ?>') })`

this? 

does not work

**Comment by atomiks** [comment]
It needs to be within `<script></script>` tags, see the `README.md` in the repo for more info.

**Comment by mihabotanik** [comment]
не помог(

**Comment by mihabotanik** [comment]
it works like this:
`tippy('#block1>', { html: document.querySelector('#block2>') })`

but it does not work like this:
`tippy('#<?php the_field(b1) ?>', { html: document.querySelector('#<?php the_field(b2) ?>') })`

**Comment by mihabotanik** [comment]
my id is this custom fields wordpress

**Comment by atomiks** [comment]
If you want to inject dynamic PHP data into the JS, you'll need to put an inline script on the document.

Minimal example (if I can remember PHP properly you also need to use `echo`):

```php
<?php
<div id="<?php the_field(b1) ?>">text</div>
<div id="<?php the_field(b2) ?>">text-text</div>

<script>
tippy('#<?php echo the_field(b1) ?>', { 
  html: document.querySelector('#<?php echo the_field(b2) ?>') 
})
</script>
?>
```
