### ISSUE TITLE
Calling tippy() with parameters not always works, no arrow or theme overwritten with defaults.

### ISSUE THREAD

**Issue by mother10** [atomiks/tippyjs#206]
I guess i am doing something wrong but i dont know what it is. I started with a very simple example i found. This is what i have:
````<!DOCTYPE html>
<html>
<head>
  <title>My-Tippy</title>
  <style>
    .tippy-tooltip.honeybee-theme {
      /* Your styling here. Example: */
      background-color: yellow;
      border: 2px solid orange;
      color: black;
    }  </style>
</head>

<body>
  <!-- Elements with `title` attributes -->
  tekst<br>tekst<br>
  tekst<button title="Tooltip">Text</button>
  <button title="Another tooltip">Text</button>

  <!-- This is for the Tooltips   -->
    <script src="dist/js/tippy.js"></script>  

    <!-- Initialize tooltips by calling the `tippy` function with a CSS selector -->
    <script>
      tippy('button', {
        theme: 'honeybee',
        placement: 'top-start',
        distance: 12,
        arrow:  true,
        arrowtype: 'sharp',
        arrowtransform: 'scale(0.7)' //skinny arrow
      })
    </script>

</body>
</html>
````
That gives me the correct colored tooltip, but no arrow and "glued" to the button:
![image](https://user-images.githubusercontent.com/33637841/37346894-df57adbc-26d0-11e8-8866-d4e7bf87b385.png)

I tried leaving out all parameters in the tippy call except for theme and placement:
````
   <script>
      tippy('button', {
        theme: 'honeybee',
        placement: 'top-start',
      })
    </script>
````
That gives me:
![image](https://user-images.githubusercontent.com/33637841/37347388-058b795e-26d2-11e8-997a-93090ce57d6f.png)

Now the tooltip is correctly placed but still "glued".
When i change this:
````
    <script src="dist/js/tippy.js"></script>
````
into this:
````
<script src="dist/js/tippy.all.js"></script>
````
I get a correct tooltip on the default distance, but immediately overwritten by the default one (flipped because of the size):
![image](https://user-images.githubusercontent.com/33637841/37347820-006247f4-26d3-11e8-96a2-2c64e67c9c99.png)

You can see that by the orange border that is still visible. When i use tippy.standalone.min.js i get nothing.
I dont want popper inside tippy, because i work with sass to compile my themes and have popper.js separately.
What am i doing wrong?

**Comment by atomiks** [comment]
Really not sure... if you're using tippy-standalone you need to include the CSS as well btw.

Paste this into a new .html file and it works as expected.

```html
<html>
<head>
  <title>My-Tippy</title>
  <link rel="stylesheet" href="https://unpkg.com/tippy.js/dist/tippy.css">
  <style>
    .tippy-tooltip.honeybee-theme {
      /* Your styling here. Example: */
      background-color: yellow;
      border: 2px solid orange;
      color: black;
    }  </style>
</head>

<body>
  <!-- Elements with `title` attributes -->
  tekst<br>tekst<br>
  tekst<button title="Tooltip">Text</button>
  <button title="Another tooltip">Text</button>

  <!-- This is for the Tooltips   -->
    <script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/tippy.js/dist/tippy.standalone.min.js"></script>

    <!-- Initialize tooltips by calling the `tippy` function with a CSS selector -->
    <script>
    tippy('button', {
  theme: 'honeybee',
  placement: 'top-start',
  distance: 12,
  arrow: true,
  arrowType: 'sharp',
  arrowTransform: 'scale(0.7)' //skinny arrow
})
</script>

</body>
</html>
```

**Comment by mother10** [comment]
Thank you so much, its working now.
Silly me forgot the tippy.css in the head and the popper in the bottom. It works with my local files too now:

![image](https://user-images.githubusercontent.com/33637841/37403862-7785bde4-2790-11e8-8161-9e671e348828.png)
Normal menu

![image](https://user-images.githubusercontent.com/33637841/37403869-7e4da61e-2790-11e8-8b04-49b9e80088a9.png)
Mobile menu

Just 2 remarks:
Wouldnt it be more logical to have a js AND a css sub-directory beneath the dist in your directory structure, and put all css files in the css subdirectory, and the js files in the js subdirectory.
Like bootstrap and others do?

Also:
You have two separate theme files in the npmpackage but 1 themes,css in the zipfile, but inside your main page on:
    https://atomiks.github.io/tippyjs
you use more themes than just those 2. It would be nice if they were all in one tippy-themes.css file inside your package to function as examples :)

**Comment by atomiks** [comment]
Great, I'm glad you got it working 😊

I want to make a themes + animation pack eventually that go way further than the default ones.

Check #174 for what I mean.
