### ISSUE TITLE
hide() issues

### ISSUE THREAD

**Issue by Abrman** [atomiks/tippyjs#21]
Hey,

I believe the `hide()` function isn't working reliably or I don't understand the documentation.
Am I doing something wrong? https://jsfiddle.net/dmgvcmy8/
(used keyup event to avoid built in event listeners)

Great work on tippy.js btw, one of my favorite libraries discovered over the past month!

**Comment by atomiks** [comment]
You're passing in the popper rather than the tooltipped element, so use:

```javascript
var popper = instance.getPopperElement(document.querySelector('button'));
```

Maybe the docs aren't clear enough on that, I will update it!

**Comment by Abrman** [comment]
Thanks for your fast answer!

I'm not a git guy, not sure if I should open another issue for this, but here's another thing I picked up: it's a iOS (maybe mobile in general) specific bug where a tooltip becomes unaccessible until another tooltip is opened if you click the popper twice on mobile.
[https://youtu.be/n8GYsbkKIwE](https://youtu.be/n8GYsbkKIwE)
[http://codepen.io/anon/pen/LyYMNx](http://codepen.io/anon/pen/LyYMNx)

I'm running iOS 10.2.1 on a 5S.

**Comment by atomiks** [comment]
Are you using v0.3.5?

**Comment by Abrman** [comment]
Yep, v0.3.5

**Comment by atomiks** [comment]
Interesting... on iOS simulator I'm not getting that issue

**Comment by Abrman** [comment]
I just tried it in a simulator too and found out that it doesn't happen if you don't click the "1x" before. Something to do with focusing a different element before it?
https://youtu.be/iGhKn_jtrII

**Comment by atomiks** [comment]
It shouldn't be closing when tapping the button again unless it's a click-triggered tooltip. And I can't seem to replicate the same issue

**Comment by Abrman** [comment]
Allright. I was able to fix this in my project by checking if user client is a mobile device and if so adding `trigger:'click'` to the tippy options.

`var tippy = !isMobile ? new Tippy(header , { position: 'right', theme: 'light'}) : new Tippy(header , { position: 'left', theme: 'light', trigger: 'click'});`

Thanks for your assistance!

**Comment by atomiks** [comment]
How are you detecting mobile, or I guess more accurately touch if that's the issue? You can access Tippy's own detection by using `Tippy.touchUser`, which uses a `touchstart` listener once

```javascript
var tippy = !Tippy.touchUser ? ...
```

should work

**Comment by Abrman** [comment]
I have a long if statement comparing the navigator.userAgent with a lot of devices. I got it from [http://stackoverflow.com/a/3540295/1906049](http://stackoverflow.com/a/3540295/1906049)

Do you think Tippy.touchUser is more reliable compared to it?

**Comment by atomiks** [comment]
Tippy.touchUser isn't available on page load when you create the instances, so you'd have to make your own `touchstart` listener detection I think. I guess your way works for the most part but not exactly failsafe.
