### ISSUE TITLE
tooltip changing position on onShow

### ISSUE THREAD

**Issue by comrade1** [atomiks/tippyjs#211]
I'm trying a few ways to have a tooltip with 'loading...' text, then when you hover it fetches the data remotely and updates the tooltip with the remote loaded text. I then cache the remote loaded text by replacing the inner html of the tip so that the next time I hover it doesn't have to refetch.

When I create the tooltip dynamically the initial 'loading...' tooltip appears correctly, but then when the text is replaced the tooltip changes position from the right side to the left, and the arrow changes position as well, from the left side to the right side. When it flips to the left most of the tooltip appears off the edge of the screen, which is why I set the position to be 'right' in the first place.

I wasn't having this flipping problem when I was cloning the template from a hidden div on the page, but if possible I'd like to create the template dynamically like below.

`
        const initialText = 'loading...';
        const templateS = document.createElement('div');
        templateS.innerHTML = initialText;

        const tip = tippy(divRowSelector, {
            animation: 'shift-toward',
            arrow: true,
            placement: 'right',
            html: templateS,
            delay: [500, 100],
            onShow(instance) {
                if (tip.loading || templateS.innerHTML !== initialText) return; // then it's loading or we already loaded it

                tip.loading = true;
                console.log("about to fetch recents from:" + url);
                fetch(url, {
                    credentials: "same-origin"
                })
                .then(function(response) {
                    return response.text();
                })
                .then(function(data) {
                    templateS.innerHTML = `<div class="recent-smss">${data}</div>`;
                    tip.loading = false;
                }).catch(function(e) {
                    console.log("error on fetch:" + e);
                    templateS.innerHTML = 'Loading recent messages failed';
                    tip.loading = false
                });
            },
            // //prevent tooltip from displaying over button
            popperOptions: {
                modifiers: {
                    preventOverflow: {
                        enabled: false
                    },
                    hide: {
                        enabled: false
                    },
                    placement: 'right'
                },
                placement: 'right'
            }
        });

`

initial hover:
![screen shot 2018-03-25 at 10 05 03](https://user-images.githubusercontent.com/1776208/37873028-34d69018-3014-11e8-9140-3a9a5528219c.png)

after the remote text comes in:
![screen shot 2018-03-25 at 10 05 30](https://user-images.githubusercontent.com/1776208/37873030-41c1bae6-3014-11e8-95ff-e20895cfa8f8.png)

If I remove the placement option and the popper options completely then the 'loading...' tooltip appears on the top, but then it flips to the bottom when the new text comes in.

The livePlacement option doesn't seem to change the behavior.

**Comment by atomiks** [comment]
You can disable flipping: `flip: false`

**Comment by comrade1** [comment]
Thanks. flip: false fixed it.
