### ISSUE TITLE
Html template doesn't work

### ISSUE THREAD

**Issue by dpatra** [atomiks/tippyjs#213]
Hi @atomiks ,

I need some help, I have been trying to use tippy for 3 days now. My usage is primarily showing html content in the tooltip. 

Important: The html content can have class names, and dynamic styles.

I tried replicating the example in the docs. Like the following

```
const template = document.createElement('div');
template.innerHTML = generatedHtml; //e.g. '<div class="cls_1">Content</div>'

tippy(node, {
	allowTitleHTML: true,
	flip: false,
	flipDuration: 0,
	animation: 'fade',
	dynamicTitle: true,
	delay: [200, 0],
	duration: [100, 300],
	placement: 'right',                    
	followCursor: true,
	popperOptions: {
		 modifiers: {
			 hide: { enabled: false },
			 preventOverflow: { enabled: false }
		}
	},
	html: template
});
```

I get the following error
`"Failed to execute 'querySelector' on 'Document': '[object Object]' is not a valid selector."`

BTW I am using v2.5.0

**Comment by dpatra** [comment]
The tooltip.js which is from popper.js seems to take title parameter as html content when "html: true". If we could have similar, that would be great.

**Comment by atomiks** [comment]
Hi @dpatra you have some conflicting options.

`allowTitleHTML` means the `title` attribute is allowed to contain HTML.
`dynamicTitle` means whenever the title attribute changes, the tooltip will be updated with the new content. This one in particular is causing the issue because it's only meant to be used in conjunction with a `title` attribute.

If you remove these options it will work.

**Comment by dpatra** [comment]
Hi @atomiks , thanks for a quick reply. That fixed the issue, the following options are working.

I changed the **allowTitleHtml** value to false, as the default value is true.
I removed the **dynamicTitle** option.

```
const template = document.createElement('div');
template.innerHTML = generatedHtml; //e.g. '<div class="cls_1">Content</div>'

tippy(node, {
	allowTitleHTML: false, //default is true; I had to explicitly assign false
	flip: false,
	flipDuration: 0,
	animation: 'fade',
	delay: [200, 0],
	duration: [100, 300],
	placement: 'right',                    
	followCursor: true,
	popperOptions: {
		 modifiers: {
			 hide: { enabled: false },
			 preventOverflow: { enabled: false }
		}
	},
	html: template
});
```

Yes, the configs options are conflicting and there is no doc for which option is required/not-required for specific usage. Phew.

The error I mentioned went away, after providing proper template. 

Thanks again, saved a lot of time.

**Comment by atomiks** [comment]
`allowTitleHTML` actually does nothing whether true or false here, I just meant it didn't need to be in there 😀 

Also `flipDuration` can be removed, as it's an option from v1
