### ISSUE TITLE
Tooltips in fullscreen?

### ISSUE THREAD

**Issue by cmann1** [atomiks/tippyjs#215]
Tooltips don't show up in full screen, is there a way to fix this?

Example: https://codepen.io/anon/pen/LdMxZv

**Comment by atomiks** [comment]
You can specify which element the tooltip is appended to:

```js
tippy('.reference', {
  appendTo: document.querySelector('#full')
})
```

**Comment by cmann1** [comment]
Thanks. Can this be changed dynamically?
I'd like it to use the document normally, but my wrapping element when in fullscreen.

**Comment by atomiks** [comment]
yes, that option can be changed before each show

```js
el._tippy.options.appendTo = ...
```

**Comment by cmann1** [comment]
Thanks, that works.

**Comment by IvanRF** [comment]
@atomiks I had the same issue and I found out that Chrome uses a high `z-index` when enters in fullscreen mode. So, another solution is to keep the default `appendTo: document.body` and use a higher `z-index` . For example:
```
tippy('[title]', {
	// Tooltips are hidden in fullscreen because Chrome defines
	// :-webkit-full-screen { z-index: 2147483647 !important; }
	zIndex: 2147483647
});
```

**Comment by nidhinkumar06** [comment]
> yes, that option can be changed before each show
> 
> ```js
> el._tippy.options.appendTo = ...
> ```

How to do the same in react js

**Comment by atomiks** [comment]
@nidhinkumar06  `<Tippy appendTo={element}>`, by default it is `document.body`

**Comment by nidhinkumar06** [comment]
If i use <Tippy appendTo='parent'> the tooltip style gets changed as below

![HawkEye (2)](https://user-images.githubusercontent.com/10459220/58557709-adf9f900-823c-11e9-878d-c726c2620331.jpg)


Without using appendTo i am getting the tooltip as below

![HawkEye (1)](https://user-images.githubusercontent.com/10459220/58557733-bd794200-823c-11e9-8f38-a08d8b16f53b.jpg)


Code:

```
<div id="full">
      <Tippy
        appendTo='parent'
        content={
          <div>
            <h5>{clusterId}</h5>
            <p>Total Devices: {totalNodes}</p>
            <hr style={{ borderColor: 'white' }} />
            <ol style={{ textAlign: 'left', paddingLeft: '10pt' }}>
              <li>Good: {good}</li>
              <li>Need Attention: {attention}</li>
              <li>Monitor Closely: {monitor}</li>
            </ol>
          </div>
        }
        arrow={true}
        animation="fade"
        theme="bootstrap"
        duration={0}
        hideOnClick={false}
      >
        <div
          id="marker"
          className="pin bounce"
          style={{ backgroundColor: color, cursor: 'pointer' }}
          onClick={handleClick}
        />
      </Tippy>
      <div className="pulse" />
    </div>
```

**Comment by KubaJastrz** [comment]
@nidhinkumar06 can you use issue that was made for this? https://github.com/atomiks/tippy.js-react/issues/93
thanks

**Comment by ohana88** [comment]
@atomiks  sorry to say ..please read and help me my issue
https://github.com/atomiks/tippyjs/issues/512

please ... I'm use time to fix 8hrs not work T_T
