### ISSUE TITLE
Positioning Error on Firefox

### ISSUE THREAD

**Issue by eli-crow** [atomiks/tippyjs#216]
I am experiencing a positioning error for the demo site on Firefox 59.0.2 on MacOS 10.13.1. Thought this was pretty important since the popover talks about the library's positioning engine. Thanks for your work on this library!

https://atomiks.github.io/tippyjs/

<img width="1425" alt="screen shot 2018-04-09 at 8 55 11 am" src="https://user-images.githubusercontent.com/19712894/38499038-61fa522a-3bd4-11e8-8ec4-709b28aa3937.png">

**Comment by atomiks** [comment]
That one uses the `sticky: true` option because of the animation, pretty sure it's a problem with `defer` and popper's positioning update, should be easy to fix...
