### ISSUE TITLE
Tippy doesn't show on first hover, only on second hover.  Using knockoutjs and AJAX

### ISSUE THREAD

**Issue by rcheung9** [atomiks/tippyjs#217]
https://codepen.io/anon/pen/rdPGGM

So I am using a knockout binding to dynamically generate some elements.  Each of these elements has a `OnMouseOver` to a function that uses ajax to fetch some data and generates the tippy.

It all works but only if I hover over the element a second time.  On first hover, no tippy is generated but on subsequent hovers it works as expected.

**Comment by atomiks** [comment]
It looks like you're creating the tippy on first mouseover, which is why it doesn't show the first time.

One way is to check if the element has a tippy instance already, and if not, create the tippy and then call the `show()` method.

```js
if (!el._tippy) {
  tippy(el, {
    html: myTemplate,
    interactive: true,
    //trigger: 'click'
  });
  el._tippy.show();
}
```
