### ISSUE TITLE
Destroy tooltip on click bug

### ISSUE THREAD

**Issue by robcrocombe** [atomiks/tippyjs#218]
I want to destroy the tooltip on a close button click inside the tooltip itself. When I try this with `.destroy()`, however, I get this error:

```
tippy.all.min.js:1 Uncaught TypeError: Cannot read property 'options' of undefined
    at HTMLDocument.<anonymous> (VM1792 tippy.all.min.js:1)
(anonymous) @ tippy.all.min.js:1
```

Here is an example:
https://codepen.io/anon/pen/mxvXEL

I can get around this by calling `hide()` instead, and having `.destroy()` on a `setTimeout`. Is this the right way to do it or is there a bug? Thanks

**Comment by atomiks** [comment]
Looks like that's because of the global `click` listener. I'll add checks inside to make sure that doesn't happen.

**Comment by robcrocombe** [comment]
Thanks for your quick response :)
