### ISSUE TITLE
Tippy not registering disabled attribute in Firefox

### ISSUE THREAD

**Issue by jburghardt** [atomiks/tippyjs#221]
Tippy will pop up on elements with disabled attribute in Firefox
Other browsers seem to work fine.

see: https://codepen.io/anon/pen/JLzxpE

Tested with firefox ESR 52 and firefox 58
im not even sure whether this is a tippy or a firefox bug...

**Comment by atomiks** [comment]
Probably browser-specific thing, yeah..

**Comment by jburghardt** [comment]
Thoughts on integrating a workaround in tippy?
