### ISSUE TITLE
While using EJS, Tippy does not render more than one word in the title attribute.

### ISSUE THREAD

**Issue by rogerogden** [atomiks/tippyjs#226]
I'm using EJS for a website I'm making, and I'd love to use Tippy. However, when I dynamically inject the title attribute in the DOM, Tippy is only rendering the first word of the injected string.

Here's an example of a div that has the title attribute injected:
`<img title=<%= users[i].title %> class="photo" src=<%= users[i].icon_url %>>`

In the below image, the title attribute should be "Launch Center Pro". I've confirmed that the EJS is currently returning the full title by injecting the same statement into a `p` element.

<img width="137" alt="screen shot 2018-04-16 at 7 26 35 pm" src="https://user-images.githubusercontent.com/5980704/38843430-2f0e2250-41ac-11e8-9e63-024a00e754b3.png">

Because I'm using EJS, I'm not sure how to make a CodePen. Please let me know if there's any additional information I can provide.

**Comment by atomiks** [comment]
Remove the `tippy()` call and hover over the image to see the native tooltip. Does it have the full string?

**Comment by rogerogden** [comment]
Interestingly, it does not. There seems to be some sort of concatenation happening with title attributes on images, since it's working in `p` elements. 

Thanks for eliminating Tippy from the equation! I'll dig deeper.
