### ISSUE TITLE
preventOverflow should be enabled by default

### ISSUE THREAD

**Issue by crazytonyi** [atomiks/tippyjs#227]
Based on [SO post](https://stackoverflow.com/questions/49882152/tippyjs-offset-not-working), it seems that large tooltips with embedded forms get clipped if they exceed browser window. 

![example screenshot](https://i.stack.imgur.com/TTTy1.jpg "Example Screenshot")

OP reported that issue was fixed by adding:

```
  popperOptions: {
    modifiers: {
      preventOverflow: {
        enabled: false
      },
      hide: {
        enabled: false
      }
    }
  }
```
Should this be the default behavior instead of having to explicitly set these options to avoid this scenario?

**Comment by atomiks** [comment]
I think I agree but this would be a v3 thing I believe

**Comment by atomiks** [comment]
This change caused problems with scrollable containers.
