### ISSUE TITLE
Tippy shows up on the wrong side of a [position:fixed, scrollable] element

### ISSUE THREAD

**Issue by mirraj2** [atomiks/tippyjs#228]
The placement should be on the left, but instead shows on the right.

See reproduction here:
https://codepen.io/anon/pen/NMKzOp

**Comment by atomiks** [comment]
That would be a Popper.js issue: 

You can test with this library exclusively:
https://github.com/FezVrasta/popper.js/issues

**Comment by atomiks** [comment]
Closing Popper.js-related bugs, previously left them open for visibility.

If you experience problems with positioning please create an issue over at the Popper.js repo: https://github.com/FezVrasta/popper.js/issues

**Comment by ilcasco-juanh** [comment]
Any plans to support popper v2 on tippy in order to correct this positioning issue?

**Comment by atomiks** [comment]
Yes, I was taking a small break for a week after working on Popper nonstop for 2 months
