### ISSUE TITLE
tippy.standalone 2.5.2 error on .hide(): Cannot read property 'disableEventListeners' of null

### ISSUE THREAD

**Issue by icd2k3** [atomiks/tippyjs#229]
I noticed a new issue upgrading from `2.5.0` to `2.5.2`. When using the standalone script, calling `.hide()` results in the error `Cannot read property 'disableEventListeners' of null`. Downgrading back to `2.5.0` fixes the issue.

The error is originating from ~L954 in tippy.standalone:
`this.popperInstance.disableEventListeners();`

In this case, `this.popperInstance` is null.

Note that I am using a React component wrapper for tippy which attempts to destroy the tippy instance when it unmounts:

Here's a simplified example of what I'm doing (again works in `2.5.0` but not `2.5.2`)
```
import tippy from 'tippy.js/dist/tippy.standalone';

// ...

componentDidMount() {
  tippy(this.tooltipDOM, this.props);
  this.tippy = this.tooltipDOM._tippy;
}

componentWillUnmount() {
  this.destroyTippy();
}

destroyTippy = () => {
  this.tippy.hide();
  this.tippy.destroy();
  this.tippy = null;
}

render() {
  return (
    <div ref={(tooltip) => { this.tooltipDOM = tooltip; }}>
      {children}
      <Portal>{this.props.render}</Portal>
    </div>
  );
}

// ...
```

**Comment by atomiks** [comment]
In the case of these sorts of components you should probably ensure the popper instance is available on init.

```js
componentDidMount() {
  tippy(this.tooltipDOM, {
    createPopperInstanceOnInit: true,
    ...this.props
  });
  this.tippy = this.tooltipDOM._tippy;
}
```

`disableEventListeners()` was moved outside of the `transitionend`, though I'm not sure if it's a good idea... 🤔

**Comment by atomiks** [comment]
Also note that `destroy()` will call hide if the tooltip is in the `visible` state, so you don't need to call it yourself. That way, it won't throw errors since the popper instance _will_ be created if it's visible. So just remove `.hide()` and you can keep the benefits of `createPopperInstanceOnInit: false`.

**Comment by icd2k3** [comment]
Thanks @atomiks removing `.hide()` on unmount and keeping `.destroy()` solved the issue for me. Cheers and thanks for the awesome work on this package!
