### ISSUE TITLE
Tippy is showing and hiding immediately

### ISSUE THREAD

**Issue by divmgl** [atomiks/tippyjs#230]
Latest version of Tippy (2.5). Kind of in a hurry so I haven't been able to create a CodePen. Tippy is showing and hiding immediately. Here's the code I'm using:

```js
tippy(ref, {
  trigger: 'manual',
  interactive: true,
  delay: [0, 2000],
  duration: 2000,
  animation: 'fade',
  onShow(instance) {
    console.log('showing')
  },
  onHide(instance) {
    console.log('hiding')
  },
  updateDuration: 350
})

this.secretKeyReference.on('success', () => {
  ref._tippy.show(2000)
})
```

When I trigger the callback, here's what appears in the console:

<img width="714" alt="screen shot 2018-04-18 at 7 01 06 am" src="https://user-images.githubusercontent.com/5452298/38936736-4debee70-42d6-11e8-87fb-190a004ece4b.png">

As you can see, the callbacks are triggered instantly. What am I doing wrong here?

**Comment by atomiks** [comment]
Something must be triggering `hide()` on the next animation frame, I'd guess (~16ms)?

Without a CodePen I don't think I can help :s

**Comment by atomiks** [comment]
@Aka4Code It's the global click event listener for the `hideOnClick` option

This catches many people off guard so I will make a prominent note in the docs about it soon.
