### ISSUE TITLE
Is it possible to use one instance with different html template by specifying html template div id

### ISSUE THREAD

**Issue by vairamsvsjdo** [atomiks/tippyjs#232]
Is it possible to use one instance with different html template by specifying html template div id
?
I would like to inject different html to each tooltip. Currently that i know is to inject that directly in title.
I would rather do it as separate html template as in code pen.

How I am looking to do:
https://codepen.io/vairamsvsjdo/pen/mLyNoX
I would like to see if it is possible to use a single tippy instance to display "tooltip using template 1" and "tooltip using template 2" like by specifying a data-tippy-html="myTemplate1" and data-tippy-html="myTemplate2"

**Comment by atomiks** [comment]
Sorry I don't know what you mean 😞

**Comment by atomiks** [comment]
You're missing `#` from `data-tippy-html` 

```html
data-tippy-html="#myTemplate2"
```

**Comment by vairamsvsjdo** [comment]
I updated the codepen to show this fix works
Thanks

**Comment by benface** [comment]
Was support for `data-tippy-html` removed at some point? I can't seem to make this work on the latest version (6.2.7).
