### ISSUE TITLE
What is new in version 3 branch?

### ISSUE THREAD

**Issue by vairamsvsjdo** [atomiks/tippyjs#233]
What is new in version 3 branch?
Is it semver to indicate breaking changes? If yes,  what are they?
Is there a referenced doc page or issue containing a list of issues or tasks that will identify breaking changes?
Thanks

**Comment by atomiks** [comment]
Yes V3 will have breaking changes

Follow this thread for updates: https://github.com/atomiks/tippyjs/issues/201

I've updated the OP today with a list of ideas for V3. 😀 Feel free to suggest things.
