### ISSUE TITLE
data-original-title change  no 

### ISSUE THREAD

**Issue by goodqd** [atomiks/tippyjs#235]
data-original-title  has been changed  
but tip is old

such as
title="title1"  render  data-original-title="title1"
change
dataset.originalTitle="title2"
but tip is title1

**Comment by goodqd** [comment]
bigger Bug

**Comment by atomiks** [comment]
In V3, this attribute will be removed as it doesn't solve a purpose if the instance is attached to the DOM node at all. Mutations are being minimized as much as possible in the future.
