### ISSUE TITLE
How to override tippy.defaults for all instances?

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#237]
```
import { defaults } from './tooltip.custom';

tippy.defaults = {
    ...tippy.defaults,
    ...defaults,
};

// in another external source
tippy('.js-tooltip');
```
This part of code not seems to work :(

**Comment by atomiks** [comment]
The internal code relies on the same object reference being used. In v3 there will most likely be a `setDefaults()` static method to avoid mutation.

For v2:
```js
Object.assign(tippy.defaults, defaults)
```

**Comment by 7iomka** [comment]
@atomiks, Thanks, it was not obvious)
