### ISSUE TITLE
Problem passing a variable to the tippy onshow() function

### ISSUE THREAD

**Issue by dunky11** [atomiks/tippyjs#239]
Hello, i got the following problem:

https://jsfiddle.net/jxwkxs9L/2/

As you can see all of them output "hello_5" on hover, how can i achieve it that they output "hello_1", "hello_2", "hello_3", "hello_4", "hello_5"?

thanks for any help in advance!

**Comment by atomiks** [comment]
You're encountering a JS hoisting issue.

Basic solution: use `const` or `let` instead of `var` (however, you will need to use Babel to transpile the code if you are supporting old browsers)

https://jsfiddle.net/jxwkxs9L/2/

**Comment by dunky11** [comment]
wow, the solution actually was rlly easy, dont know why i needed hours for that.

Thank you!
