### ISSUE TITLE
Issue with shadow DOM

### ISSUE THREAD

**Issue by akhilcjacob** [atomiks/tippyjs#241]
I'm trying to build a webcomponent with tippyjs in stenciljs.

```
    const target = this.host.shadowRoot.querySelector("#target") as HTMLDivElement;
    const template = this.host.shadowRoot.querySelector("#template") as HTMLDivElement;
    console.log(target);
    console.log(template);
    tippy(target, {
      html: template,
      onShow() {
        console.log("about to show");
      },
      onHide() {
        console.log("about to close");
      }
    });
```

This is the component will load function (basically on init), and this is the actual html.

```
          <div id="template" style={{ display: "none" }}>
          <h3>
            Cool <span>HTML</span> inside here!
          </h3>
        </div>

```
 Any help would be greatly appreciated.

**Comment by akhilcjacob** [comment]
This is what I get from the console.logs 
```
<button id="target" data-tippy=""> This is the target</button>

<div id="template" style="display: none;"><h3>Cool <span>HTML</span> inside here!</h3></div>
```

**Comment by atomiks** [comment]
Not familiar with this so I don't think I can help 😓

**Comment by miguelyoobic95** [comment]
Hey @atomiks, I commented on one of the issues before but I am not sure you saw the comment, I'm happy to help you with this since we have exactly the same use case and this will make your library compatible with things like Ionic4, StencilJS which have now started to heavily use shadow DOM. I'm happy to schedule a call or something if needed to discuss

**Comment by gino8080** [comment]
I also really need to use Tippy with shadow-dom, in particular with stencil js

**Comment by atomiks** [comment]
You can make PRs to make it compatible - all code is open source. I have no idea what to do since I'm not familiar with shadow DOM 🙂

**Comment by Ntuk** [comment]
A 'bit' late to the party but did you guys figure this out? :)
