### ISSUE TITLE
Throw an exception if title attribute is missed?

### ISSUE THREAD

**Issue by scofield-ua** [atomiks/tippyjs#242]
Hello. Maybe throwing an exception would be more helpful if title attribute is missed on the selected element(s), instead of just returning `undefined` :)

Here is an example: https://codepen.io/anon/pen/MGPJXb.

Spent some time today figuring out it when realized that I missed the title attribute.

**Comment by atomiks** [comment]
In V3 the API regarding tooltip content will be changed. In short, you won't use a `title` attribute anymore to avoid mutations like this.

**Comment by scofield-ua** [comment]
@atomiks thanks, but what about V2? Is it hard to implement, maybe PR would be welcome?

**Comment by atomiks** [comment]
Yes, sorry. I'll release `v2.5.5` soon with this change + a long standing problem fix that made it to v3
