### ISSUE TITLE
Keeping tippy tooltip in DOM.

### ISSUE THREAD

**Issue by kmanolis** [atomiks/tippyjs#243]
Is there any way to keep tippy tooltip into DOM?
When you hover a tippy enabled element, a new div with id {tippy-No} is created (our tooltip). When you hover out of the element, this tippy div (tooltip) is removed from the DOM. So, is there anyway to keep it?

I want to achieve this, in order to prevent multiple AJAX requests for the same tippy element.
(When a user hovers a username, a hovercard is created and user's data are loaded via AJAX. But when you hover again, the AJAX request is repeated, which is something i would like to prevent - i just want one AJAX request for each tippy enabled element.)
_(In qTip2 http://qtip2.com/guides you can achieve it with the **overwrite** option. Does tippy.js has anything similar?)_

**Comment by atomiks** [comment]
>When a user hovers a username, a hovercard is created and user's data are loaded via AJAX. But when you hover again, the AJAX request is repeated, which is something i would like to prevent

Cant' you store the AJAX response data in the tooltip instance so you don't need to repeat the request again? Just check if the instance has response data, and if not, do the request, otherwise use the existing data.

**Comment by kmanolis** [comment]
Thanks for replying! But, how can do this check?
The way i've implemented this:

const myTemplate = document.createElement('div');
myTemplate.innerHTML = 'Loading...';

const tip = tippy('#main', {target: '.user_link', //<= dynamically added elements
	allowTitleHTML: true,
	html: myTemplate,
	createPopperInstanceOnInit: false,
	interactive: true,

	onShow() {
		const content = this.querySelector('.tippy-content');
		const tipInstance = this._tippy;

		if(tipInstance.popper.innerHTML.indexOf("user_info_card")){
			console.log('already loaded');
			console.log(tipInstance.popper.innerHTML);
		} else {
			console.log('1st request');
		}

		$.ajax({
			url: '/ajax.php',
			type: 'POST',
			dataType: 'json',
			data: {blahblah}
		})
		.then(function(result) {
			content.innerHTML = result.tpl
		})
		/*
		.catch(e => {
		content.innerHTML = 'Loading failed'
		tip.loading = false
		})
		*/
	},
	placement:'left'
});

But it fails, and i guess it fails because i've applied my code at onShow() {}.
(By "fails" i mean it keeps doing the ajax request each time, although the tipInstance.popper.innerHTML contains the user_info_card text (which loaded via ajax)
Can you recommend me the proper way?

**Comment by atomiks** [comment]
```js
const myTemplate = document.createElement("div")
myTemplate.innerHTML = "Loading..."

const tip = tippy("#main", {
  target: ".user_link",
  html: myTemplate,
  interactive: true,
  placement: "left",
  onShow(instance) {
    const content = instance.popper.querySelector(".tippy-content")
    const hasAlreadyLoaded = instance.popper.innerHTML.indexOf("user_info_card") > -1

    // use an if condition that only executes the request if it's 
    // not already been loaded
    if (!hasAlreadyLoaded) {
      $.ajax({
        url: "/ajax.php",
        type: "POST",
        dataType: "json",
        data: { blahblah }
      }).then(function(result) {
       content.innerHTML = result.tpl
      })
    }
  }
})
```
