### ISSUE TITLE
Tippy pop-ups occur beneath <dialog> elements

### ISSUE THREAD

**Issue by jbmonroe** [atomiks/tippyjs#244]
https://codepen.io/brookmonroe/pen/aGgvYa

**Comment by atomiks** [comment]
Append the tooltip to the dialog element.

```js
appendTo: dialog
```

**Comment by jbmonroe** [comment]
Two things:

- Separate tippy() call just for the dialog?
- This only happens in Chrome.  Firefox works as expected.

**Comment by atomiks** [comment]
```js
const dialog = document.getElementById('myDialog')

tippy('.reference', { appendTo: dialog })

dialog.showModal()
```

**Comment by jbmonroe** [comment]
Firefox works with **dom.dialog element.enabled** set to true. Thanks for the code example!

Before I (potentially) post another "bug" item--does Tippy have bidi support?  I have a web app that requires both English and Arabic, and title attributes definitely don't do Arabic well.
