### ISSUE TITLE
Tooltips aren't hidden if the target is removed from the DOM

### ISSUE THREAD

**Issue by cmann1** [atomiks/tippyjs#245]
I'm using delegates and found that handleMouseLeave is never called if the target is removed from the dom, leaving the tooltip stuck on screen.

As a quick fix I changed the `handleDelegateHide` like so:
```js
var handleDelegateHide = function handleDelegateHide(event) {
	  var toElement = event.toElement || event.relatedTarget;
	  var tippyTarget = toElement ? closest(toElement, _this6.options.target) : null;
	  var delegateTarget = closest(event.target, _this6.options.target);
    if (delegateTarget) {
      _leave.call(!tippyTarget ? delegateTarget._tippy : _this6);
    }
  };
```

**Comment by atomiks** [comment]
I tested that code on the latest version and the tooltip stays stuck still, presumably because once the element is removed, it can't fire any events. 

I think this actually requires action from the developer by cleaning up tooltips if the element is removed manually.

```js
element._tippy && element.tippy.destroy()
element.remove()
```
