### ISSUE TITLE
How to deal with dynamic lists when each element needs its own popover?

### ISSUE THREAD

**Issue by victor-ponamariov** [atomiks/tippyjs#246]
Hi there, thanks for such an amazing library!

I use vuejs (not sure if it matters), and I display a list of categories. Each category has a list of subcategories. I need to display them in popover. So for example there are N categories and there should be N popovers with subcategories. I attached a screenshot

![image](https://user-images.githubusercontent.com/6241595/41203851-a4bb720a-6ce5-11e8-8254-6c8cf5fa28bc.png)

So I'm not sure how to achieve this. I don't think creating many unique ids (like "#category-1" in combination with "#subcategory-1") is a good idea.

I thought about delegation but not sure if it's what I need, since I have many parents (=categories) and many children (=subcategories), in 1-1 relationship between them.

Thanks in advance!

**Comment by atomiks** [comment]
Hi,

Not sure I can answer this without some example code. Feel free to post an example and I'll try to help as best I can.
