### ISSUE TITLE
Update tooltip content

### ISSUE THREAD

**Issue by aboumekh** [atomiks/tippyjs#247]
Hi,
I am using Tippy.js v2.5.2.
In my web page the tooltip content get dynamically created by the user with Javascript. the problem is that each time the user updates the same tooltip content, I have a new tooltip bubble displays upon the old one, and I end up with multiple tooltips display upon each other, rather than display just the latest.
Do you have any idea on how to display only the latest updated content ?

**Comment by atomiks** [comment]
```js
tippy(ref, { dynamicTitle: true })
ref.title = "new tooltip"
```

**Comment by aboumekh** [comment]
I am using html rather than title:
           tippy(ref, {
                 html: '#Template'
})
Is there a solution for this please ?

**Comment by atomiks** [comment]
Save the template to a reference to modify it later

```js
const template = document.querySelector("#Template")
tippy(ref, {
html: template
})
template.innerHTML = "new tooltip"
```

**Comment by aboumekh** [comment]
I am sorry, but that's exactly what I am doing. You can probably try a test on your side and reproduce this issue.
Thanks

**Comment by aboumekh** [comment]
It looks like tippy cumulate the content, and not just update it

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/aKWeOm

Here the template content is updated every 250ms. You must be doing multiple `tippy()` calls to cause the duplicate tooltips.

**Comment by aboumekh** [comment]
All right, thank you :)

**Comment by aboumekh** [comment]
Sorry, but still don't working. 
I am using  Tippy.js v2.5.2. in the line 3337 it take in consideration popper only and as pooper.innerText get stock with the first value, while reference.innerText get updated when I update the tooltip text, but it looks like only pooper.innerText is displayed in the tooltip.
Do you have any idea ??
Thanks

**Comment by aboumekh** [comment]
Here is my code snipet, it looks like the popper.innerText does not get updated when I update the comment content:
        myTemplate.innerHTML =comment;
         id = '#'+ myTemplate.id;
                    if(item.firstTip === 0){
                        item.firstTip = 1;
                        tippy(ref, {
                            html: id,
                        });
                     }
I use firstTip to not call tippy() a second time.
Do you have any idea ?
Thanks

**Comment by itsalb3rt** [comment]
@atomiks My humble opinion is that I will put this example in the documentation, this example is super easy to understand.

https://github.com/atomiks/tippyjs/issues/247#issuecomment-396778756

**Comment by atomiks** [comment]
@itsalb3rt current docs show this:

![img](https://i.gyazo.com/9f2578491b76a69eb50f11d7b0618b50.png)

Is that not easy to understand?

In V3, it's:

```js
tippy(ref, { content: 'Hello' })
ref._tippy.setContent('Bye')
```

**Comment by thiemeljiri** [comment]
Problem with this approach

    tippy(ref, { content: 'Hello' })
    ref._tippy.setContent('Bye')

is that the `_tippy` property isn't there untill the tippy is shown for the first time. Is this intentional, or am I doing somethng wrong?
