### ISSUE TITLE
Html template only displayed on the last element

### ISSUE THREAD

**Issue by Arkellys** [atomiks/tippyjs#248]
Hello,

I have three blocks using the same tooltip (HTML template), and I would like to change it's content depending on which block I clicked.

The issue is that my blocks are displaying empty tooltips exept for the last one declared in the DOM.

https://codepen.io/anon/pen/Vdrpba

I noticed that even without the click events and just the basic content, it is only displayed on the last element when the html template is declared via `document.querySelector('#template');` or `document.getElementById('#template');`

```
const template = document.querySelector('#template');

tippy('.reference', {
  html: template,
});
```

But it works fine if the template Id is declared directly : 

```
tippy('.reference', {
  html: '#template',
});
```
However, this one do not let me change the tooltips' contents...

Did I do something wrong or it is a bug ?

**Comment by atomiks** [comment]
When you specify an element for `html` it gets appended to the tooltip directly. If you need to use it multiple times, you need to clone it.

You can either use a query string, i.e. `html: '#template'` or use a function that returns the clone, i.e. `html: () => template.cloneNode(true)`

**Comment by Arkellys** [comment]
Thank you for your reply,
I have tried with the query string but how can I change the content of the tooltip in this case ?

**Comment by atomiks** [comment]
I see the issue here. You want to append the template to multiple different tooltips, but also update it at a later time and have all of them reflect the change?

You'll probably need to do something like this:

```js
const template = document.querySelector('#template')
const templates = []

tippy('.reference', {
  html(reference) { // current Element is passed as an argument
    const clonedTemplate = template.cloneNode(true)
    templates.push(clonedTemplate)
    return clonedTemplate
  }
})

// Later on...
templates.forEach(template => {
  template.innerHTML = 'new content'
})
```

By using a function as `html`, it allows you to change the template slightly based on each reference as well, as it gets passed the reference element.

**Comment by Arkellys** [comment]
Perfect, thank you !
