### ISSUE TITLE
Adding tooltip to dynamically generated elements

### ISSUE THREAD

**Issue by mikekok** [atomiks/tippyjs#25]
I'm having a tooltip template which I add to some elements in the document ready event.
Is it possible to add that tooltip to dynamically created elements that are generated afterwards?

**Comment by atomiks** [comment]
If you dynamically create elements, just create the instance after they've been appended to the DOM

**Comment by mikekok** [comment]
The problem is I frequently create elements dynamically at runtime (by appending them to another element through jQuery), not all of them are created at once.
I need a way to add tooltips to my dynamically generated elements every time a new element is added.

**Comment by atomiks** [comment]
You can't wait until all of them have been appended?

**Comment by mikekok** [comment]
No, let me explain why.
I'm using tippy for a socket.io chat client.
Every time a user sends a message, an element is appended to the chat box element.
Every single one of those elements needs to display a tooltip on hover, showing some information about that specific message.
Here is a preview:
![preview](http://i.imgur.com/6tHcXXz.png)

**Comment by atomiks** [comment]
That makes it clearer... you can't do `new Tippy(el)`, where el is the chat message once it's appended?

**Comment by mikekok** [comment]
I've already tried that, but this is what happens to the previous tooltips every time a new tooltip is added:
![preview](http://i.imgur.com/iKoQs0R.png)

Judging by its appearance and having not taken a look at tippy's code at all, I think that multiple tooltips are added over the old ones every time a new tooltip is added. Am I right?

**Comment by atomiks** [comment]
I don't think that should be happening, can you paste your source code here?

**Comment by mikekok** [comment]
Of course.
This is the html template I'm using:
```
<div id="bubble-options">
    <p>Sent 2 hours ago</p> // still working on the front-end, that's why time is not being updated yet
    <a id="btnCopy" class="button is-small">Copy</a>
</div>
```

These are my tooltip options:
```
var tooltipOpts = {
    html: '#bubble-options',
    delay: 800,
    interactive: true,
    position: 'right',
    theme: 'light',
    arrow: true
}
```
And this is how I add a tooltip every time a new element is appended:
`new Tippy('.bubble', tooltipOpts)`

**Comment by atomiks** [comment]
You should create a new, individual Tippy instance for each individual chat bubble. So instead of the class `.bubble`, use a unique ID, or pass in the DOM element directly.

**Comment by mikekok** [comment]
Oh, you are right, I feel pretty stupid.
Another quick question please, how can I get the element that the tooltip is added on? (e.g. #bubble1)

**Comment by atomiks** [comment]
Well, you can get the tooltip (popper) by calling the method `getPopperElement`, but the reverse isn't possible with the API

You can hack it though, by doing `Tippy.bus.refs[Tippy.bus.poppers.indexOf(popper)].tooltippedEl`, where `popper` is the tooltip popper

I assume you want to get the text of the chat bubble when you press copy, so do like

`var popper  = $(this).closest('.tippy-popper')` (I think, haven't used jQuery in a while), then do what I did above

**Comment by mikekok** [comment]
You are absolutely great! Thanks!

**Comment by atomiks** [comment]
Awesome, did you get it working with that?

**Comment by mikekok** [comment]
Ok, so is this what you mean?
```
$('body').on('click', '#btnCopy', function() {
    var popper = $(this).closest('.tippy-popper')
    console.log(Tippy.bus.refs[Tippy.bus.poppers.indexOf(popper)].tooltippedEl)
})
```
This gives me the following error:
_Cannot read property 'tooltippedEl' of undefined_

**Comment by atomiks** [comment]
Is it getting the popper? `console.log(popper)`

**Comment by mikekok** [comment]
Yes, it is.
![popper](http://i.imgur.com/pfN4BDw.png)

**Comment by atomiks** [comment]
Ah, I think you need to do `$(this).closest('.tippy-popper')[0]`

**Comment by mikekok** [comment]
Perfect, works like a charm!

**Comment by atomiks** [comment]
Just letting you know in v0.5.0, you can now do `instance.getTooltippedElement(popper)` to find the reverse reference

Your method will break now unless you do 

`Tippy.store.refs[Tippy.store.poppers.indexOf(popper)].el

**Comment by mikekok** [comment]
I was pretty sure you were gonna add this feature, I was just waiting for it.
Thanks for letting me know!
