### ISSUE TITLE
Using dynamicTitle and empty string doesn't update tooltip

### ISSUE THREAD

**Issue by gilbitron** [atomiks/tippyjs#251]
I'm using Tippy with Vue.js and came across the following issue: If you set `dynamicTitle: true` and use a variable for the `title` binding, it works if the title is not an empty string. However, if the string is updated to be an empty string then the tooltip continues to show the old string (instead of not showing the tooltip as expected).

```html
<!-- if (someVar == 'A string') : This works --> 
<span :title="someVar"></span>
<!-- if (someVar == '') : This shows the 'A string' tooltip --> 
<span :title="someVar"></span>
```

**Comment by atomiks** [comment]
Yeah, if the title is falsy nothing will happen and it won't be disabled.

Can you call `.disable()` on the tooltip instance if `someVar` is `''`, then `.enable()` if not?

**Comment by gilbitron** [comment]
@atomiks Seems a bit messy but it might be possible. Is there any way to do that using built-in callbacks?

**Comment by atomiks** [comment]
I don't think this problem exists in v3.
