### ISSUE TITLE
What does this do? CSS reflow?

### ISSUE THREAD

**Issue by alindsay55661** [atomiks/tippyjs#253]
This is not a bug, just seeking understanding. Feel free to close any time. 

What does the following line do?

https://github.com/atomiks/tippyjs/blob/c16ad2f72f946731e55834ebfaa6098e4c6fb061/src/js/core/Tippy.js#L130

Many thanks!

**Comment by atomiks** [comment]
I'm not sure if it's necessary, but I was trying different things to fix a Safari bug with the backdrop transition and just left it in in case.

**Comment by alindsay55661** [comment]
Ok, thanks, just trying to understand the source better.
