### ISSUE TITLE
Interactive tooltips inside scrollable container don't disappear correctly

### ISSUE THREAD

**Issue by katranci** [atomiks/tippyjs#255]
Thanks for the great library. Sorry if this has been asked before, I couldn't find anything related. How can I setup tooltips so that they disappear when mouse cursor leaves the tooltip target as I scroll in the container?

https://plnkr.co/edit/QYgxbD?p=preview

![interactive-tooltips-inside-scrollable-container](https://user-images.githubusercontent.com/61077/42098171-ffb5e5fc-7bb1-11e8-87ca-8522cbb7f2c8.gif)

**Comment by atomiks** [comment]
The docs mentions this

![img](https://i.gyazo.com/b0059b387fc1d04838c56683132f1713.png)

(I also need to add anchors to sublinks 😒 , should probably just use markdown...)

**Comment by katranci** [comment]
Thanks for the quick response, I've updated my plunk but nothing has changed.

https://plnkr.co/edit/QYgxbD?p=preview

**Comment by atomiks** [comment]
Okay yeah, sorry, I didn't click the link.

I think you're looking for Popper's `hide` modifier:

https://popper.js.org/popper-documentation.html#modifiers..hide which adds an `x-out-of-boundaries` attribute to the popper so you can `display: none` it or whatever when it's outside the scrollable container.

However you need `preventOverflow` enabled for that. And that seems to have a bug where the placement is incorrect.

😢 

If you add `position: relative` to the parent container, the Popper is positioned relative to that and is therefore clipped by the container, but that's also problematic.

**Comment by katranci** [comment]
Yeah clipping is definitely not an option. They are hidden correctly with `interactive: false` but I need the tooltips to stay when I hover over them.

**Behaviour with `interactive: false`:**
![non-interactive-behaviour](https://user-images.githubusercontent.com/61077/42099727-2d3ea01e-7bb6-11e8-92a1-f7e0ab11e192.gif)

**Comment by atomiks** [comment]
The only thing I can suggest for now is implementing your own custom logic with a `scroll` listener on the scrollable element that detects if the tooltip is within the boundaries. Obviously, this should be handled properly by Popper.js, so maybe make a bug report (using only Popper.js by itself).

**Comment by katranci** [comment]
Ok thanks

**Comment by atomiks** [comment]
I just revisted this with fresh eyes and I'm not sure why I didn't see the actual problem earlier.

So Tippy uses an `onMouseMove` handler for interactivity which means **the mouse needs to move** to hide any tooltips which are not within the `interactiveBorder`. So when you scroll down and the mouse enters a new reference you don't need move the mouse for them to show, but the old ones stay stuck because no `mousemove` event has fired.

A simple way to solve it is to use `onShow` to hide the other tooltips before the new one shows.

```js
tippy(referencesInScrollableContainer, {
  onShow() {
    [...document.querySelectorAll('.tippy-popper')].forEach(popper => {
      // Might need a check here to verify the popper belongs to one of the other
      // scrollable container references
      popper._tippy.hide()
    })
  }
})
```
