### ISSUE TITLE
trigger="focus" works only on pressing tab

### ISSUE THREAD

**Issue by alex-shatalov** [atomiks/tippyjs#258]
Is it right that tooltip opens by pressing tab, but if i trigger focus() on element nothing happens

**Comment by atomiks** [comment]
According to my testing, calling `.focus()` won't invoke listeners. 

`element.focus()` = give the element focus, don't invoke event listeners
`element.dispatchEvent(new Event('focus'))` = invoke event listeners listening for `focus`, but don't give the element focus

In Chrome, you can test it in the console:

```js
document.body.innerHTML = ''
const btn = document.createElement('button')
btn.textContent = 'new'
document.body.append(btn)
btn.addEventListener('focus', e => e.target.textContent = 'focused')

setTimeout(() => {
  btn.focus()
  console.log('Manually called:', document.activeElement)
  btn.blur()
}, 2500)

setTimeout(() => {
  btn.dispatchEvent(new Event('focus'))
  console.log('Dispatched event:', document.activeElement)
}, 5000)
```

**Comment by alex-shatalov** [comment]
@atomiks thanks a lot!!!! it helps. closing
