### ISSUE TITLE
Dynamic HTML (Angular usage)

### ISSUE THREAD

**Issue by denkomanceski** [atomiks/tippyjs#26]
So I am trying to wrap this library around an angular directive so people will be able to use it in angular as well, but the problem that I have is that the html property accepts and ID. Is it possible for the property to accept an HTML element? And than the problem is that this HTML can by dynamic, so if people change something during the lifecycle of a tippy, it should be changed. Any idea or workaround for this? Thanks

P.S. I can make all the other functionalities so I can publish it and you can add a link to it as an angular2 version. But I really want to support all the functionalities

**Comment by atomiks** [comment]
Good point, will allow you to use an element as well as an id for the template.

How aobut an `update(Element)` method or something that you can call? In fact that might solve the `wait()` callback thing too...

**Comment by atomiks** [comment]
Check v0.4.0, which has an `update()` method and `wait()` callback
