### ISSUE TITLE
removeOnDestroy option issue

### ISSUE THREAD

**Issue by worldofsites** [atomiks/tippyjs#261]
When we are testing tippyjs on **IE11**, we have found that after call .destroy() or .destroyAll() div's (.tippy-popper) doesn't removed from DOM. Even if we create tippy with 'removeOnDestroy: true' option.
![image](https://user-images.githubusercontent.com/23352829/42612146-d44f1110-85c3-11e8-8a26-3c67ced6e352.png)
Issue occurs because in function _createPopperInstance() option removeOnDestroy doesn't transfered to popper instance options.
**Possible fix:**
Adding 'removeOnDestroy: options.removeOnDestroy' to _extends in _createPopperInstance() function is solved that issue.
![image](https://user-images.githubusercontent.com/23352829/42612141-cae30fb4-85c3-11e8-8140-71290248d718.png)

**Comment by atomiks** [comment]
Was fixed in v2.5.4 with the `transitionend` change.
