### ISSUE TITLE
Tooltip not showing

### ISSUE THREAD

**Issue by acollazomayer** [atomiks/tippyjs#265]
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context i get this error when i make the tooltip tippy('.button')
in the appendTo function.

**Comment by atomiks** [comment]
CodePen? Not really sure why you're creating a tippy inside the appendTo function

**Comment by acollazomayer** [comment]
Cant make a codepen, im creating the tooltip inside a ionic angular project.
I just put the example code and when i examine the tippy function I saw that error

**Comment by acollazomayer** [comment]
In the landing page of the app i can get it to work. However in others views no

**Comment by dgroh** [comment]
I'm also having this problem! Is it inside a **ngIf** or *ngFor* ? If so this is the problem. The tooltip does not appear within neither in **ngIf** nor in **ngFor**...

If I remove **ngIf** it works
