### ISSUE TITLE
tooltip doesn't appear after scroll

### ISSUE THREAD

**Issue by FinnYoung** [atomiks/tippyjs#268]
https://codepen.io/anon/pen/jpmBBL

i used recommended way of hiding tooltip on scroll from here:
https://atomiks.github.io/tippyjs/
"Hiding tooltips on scroll"

for testing i used android studio, android 6.0, 5.1" screen, 1440x2560, built in browser

steps to reproduce:
1) touch `hover_me`
2) swipe down to make tooltip disappear 
3) touch `hover_me` again.

expected tooltip to appear again, but nothing happens.

the same issue happens with this example: https://codepen.io/anon/pen/KBmWrR

**Comment by FinnYoung** [comment]
another weirdness: https://codepen.io/anon/pen/GBmWzN
everything the same as above, but if you click on `hover_me2` - tooltip appear.
after swiping down and clicking on `hover_me2` again - tooltip don't appear for `hover_me2`, but appear after clicking on `hover_me`

**Comment by FinnYoung** [comment]
for testing i used android studio, android 6.0, 5.1" screen, 1440x2560

**Comment by atomiks** [comment]
Does it happen with Chrome on Android, or just the built it one?

**Comment by FinnYoung** [comment]
built in. browser version: 6.0-4729342
per https://atomiks.github.io/tippyjs/ "Browser Support" and
https://caniuse.com/#feat=mutationobserver Android 4.4+ should be supported

**Comment by atomiks** [comment]
Sorry for not replying.

Do you see any errors in the console?

**Comment by atomiks** [comment]
Yeah, I'm not sure...

Have you tried the same thing with V3 which was just released? Doubt it would have fixed it but might be worth trying.
