### ISSUE TITLE
Wrong "main" entry file in the package.json

### ISSUE THREAD

**Issue by Cryde** [atomiks/tippyjs#27]
Hello,

I'm trying to use this nice lib but I'm facing an issue : my packager doesn't find the "entry file"
I think you should specify a "main" file in your package.json

https://docs.npmjs.com/files/package.json#main
Example: 
https://github.com/select2/select2/blob/master/package.json#L32
https://github.com/jquery/jquery/blob/master/package.json#L6
https://github.com/enyo/dropzone/blob/master/package.json#L12
https://github.com/yabwe/medium-editor/blob/master/package.json#L20

In your case you should do : 
```
"main": "dist/tippy.js",
```

thanks !

**Comment by atomiks** [comment]
I just fixed that with v0.4.1! Thanks

**Comment by Cryde** [comment]
So fast ! 👊
