### ISSUE TITLE
Can't reuse the same HTML Element for multiple popups

### ISSUE THREAD

**Issue by LukeFarrawell** [atomiks/tippyjs#271]
I am using a HTML popup to display some data. There is some locations that require a popup that are of the same data. The idea was to create the popup element and reuse it for multiple locations.

In the codepen, there is two button that will get a popup, the popup is created in code and is applied to the both buttons. The last tippy instantiated element is the one that gets the popup.

https://codepen.io/anon/pen/BPOdMK

**Comment by atomiks** [comment]
You need to clone it

`html: popup.cloneNode(true)`

An element reference is appended to the tooltip directly

**Comment by LukeFarrawell** [comment]
I see.

I was thinking the element was also supposed to be cloned by tippy, after re reading the documentation I realised I got it mixed up.
