### ISSUE TITLE
How to position in the mouse click?

### ISSUE THREAD

**Issue by dgroh** [atomiks/tippyjs#272]
I finally managed to position using pure `popper` a div inside a SVG. I wish to do the same with `tippy` 

I'm trying the following approach which **does not work**:

```
  select(e: MouseEvent) {
    const ref = {
      getBoundingClientRect() {
        return {
          width: e.layerY,
          height: e.layerX,
          top: e.layerY,
          left: e.layerX,
          right: 0,
          bottom: 0
        }
      },
      clientHeight: 100,
      clientWidth: 100
    }

    tippy('.line', {
      target: 'polyline',
      trigger: 'click',
      arrow: true
    }, ref);
  }
```

**This worked** with popper:

```
  select(e: MouseEvent) {
    const ref = {
      getBoundingClientRect: () => ({
        top: e.layerY,
        right: e.layerX,
        bottom: e.layerY,
        left: e.layerX,
        width: 0,
        height: 0,
      }),
      clientWidth: 0,
      clientHeight: 0,
    }
    
    const pop = document.getElementById('template'); // the popup element

    this.popper = new Popper(ref, pop);    
  } 
```

What am I missing?

**Comment by davemoore24** [comment]
The reference is virtual so `.line` needs to be replaced with `ref`

`   const ref = {
        getBoundingClientRect: function getBoundingClientRect() {
          return {
            width: 0,
            height: 0,
            top: clientY,
            left: clientX,
            right: clientX,
            bottom: clientY
          };
        },
        clientWidth: 0,
        clientHeight: 0
      };

      tippy(ref, {
        target: 'polyline',
        trigger: 'click',
        arrow: true
      });`

**Comment by atomiks** [comment]
Yeah, you need to use the object as the actual reference itself.

But I see that you want to use the line as the reference for tippy to handle listeners for, but want a custom position where they clicked... that's a really valid use case that hasn't been added yet 😢 .

**Comment by dgroh** [comment]
That's is correct! I did it without the use of a library. I used this: http://www.cssarrowplease.com/ , then simply applied **absolute** positioning with **top** and **left**. pretty simple, but covers my use case for now.

**Comment by viveleroi** [comment]
I too need to be able to position the tooltip relative to the cursor, but *not* follow it. Is that what this issue is trying to address?

I would try the virtual ref approach but I need this to work with `dynamicTitle` too.

**Comment by atomiks** [comment]
@viveleroi Yes, it seems so.

So we've got **`followCursor: boolean`**, I think the option could be **`nearCursor: boolean`**. This is the same behavior as Wikipedia's new popovers , the only problem with them is they don't take into account the cursor moving while the delay timeout is still pending before showing it.

**Comment by viveleroi** [comment]
I would imagine you'd want the cursor position at the time of display. I'm ditching qtip2 in an enterprise app and unfortunately one of the design requirements is positioning the tooltip relative to the cursor, not the element itself. So far I'm impressed with tippy.

Should I file a specific issue/feature request or is this one good enough?

**Comment by atomiks** [comment]
> I would imagine you'd want the cursor position at the time of display

Yup, this is actually already done with `followCursor`, so I think some of the code can be reused, just modified a bit to remove the mousemove listener once it's shown.

> Should I file a specific issue/feature request or is this one good enough?

This one is fine. It shouldn't be too difficult to implement because of the above reason. Also note this will be a v3 feature, which I'll probably release out of beta this weekend. I think it's almost ready

**Comment by viveleroi** [comment]
Thanks, I would appreciate that! This weekend would be great timing too.

**Comment by atomiks** [comment]
I got the functionality working but there was one problem: resize doesn't work. It uses the mouse event + virtual popper reference, but when the window is resized the layout of the page can change, so the reference element can be in a totally different place. But there's no way to know that using the original mouse event used to position the tooltip...

**Comment by atomiks** [comment]
I'm going to leave this out for v3.0 but considering it for v3.1. I don't want to release a half-done feature without considering edge cases.

**Comment by atomiks** [comment]
This was fixed in Dec 2018 🤔
