### ISSUE TITLE
show() Method not working with HTML popover

### ISSUE THREAD

**Issue by starvin** [atomiks/tippyjs#273]
I have a header with icons, each icon has two tippy instances. One for mouseover to show a tooltip and one for click to show a popover. This works fine, but I can't get the show() method to work to show the HTML when clicking a separate button. It creates the tippy HTML, but it instantly goes to `visibility:hidden` and then won't do anything after that. I can't even get this to work if I put the tippy instances on two separate references.

https://codepen.io/starvin/pen/NBomVo

**Comment by atomiks** [comment]
`hideOnClick: false`

Problem exists because of a global event listener used to handle hiding tooltips

**Comment by starvin** [comment]
Thank you!

Incase anyone else is wondering, I kept normal hideOnClick functionality with the following options:

```
hideOnClick: false,
onShown(instance) {
    instance.options.hideOnClick = true;
},
onHidden(instance) {
    instance.options.hideOnClick = false;
}
```
