### ISSUE TITLE
reset/debounce leave/hide timer on interactive tooltip

### ISSUE THREAD

**Issue by cusxio** [atomiks/tippyjs#274]
## Current Scenario

![demo](https://user-images.githubusercontent.com/6487613/44093108-20e39680-a005-11e8-95c7-2666d95ae765.gif)

https://codepen.io/anon/pen/jpRxBY

Currently, `onMouseMove` executes immediately, therefore breaking any interactive tooltip that is further away from the reference.

## Possible Solution

If there is a way to debounce the `onMouseMove` event, only the **last** `onMouseMove` event will execute, and if the mouse is on top of the interactive element, the interactive element should not hide.

![demo](https://user-images.githubusercontent.com/6487613/44093289-ad50afe0-a005-11e8-9116-6e5d22e74a7b.gif)

The _gif_ above is from `medium.com`

## Related

#193

**Comment by atomiks** [comment]
#193 is now fixed in v3 `alpha.2` but need to tend to this now...

**Comment by cusxio** [comment]
Thanks.

Side question, is there a `hideOnClick` option for the interactive element?

**Comment by atomiks** [comment]
Could you clarify what you mean?

**Comment by cusxio** [comment]
Oh, there's a `hideOnClick` option for the reference element, but it seems like there isn't a `hideOnClick` option for the interactive element.

For my use case, I want to add an anchor tag in the tooltip, so it has to be interactive. And upon clicking the tooltip, I want to close it.

On second thought, I could probably call `tippInstance.hide()`..

**Comment by atomiks** [comment]
Please see `v3.0.0-alpha.3`. Added `interactiveDebounce` option (number in ms). Works nicely with 50-100 from my testing

**Comment by atomiks** [comment]
> Btw, did you remove maxWidth in v3?

Yeah. If you specify a max-width of more than the smallest mobile screen minus padding (i.e. 300px or so), it causes overflow.

You can add your own class to the popper element and use media queries to ensure it stays at an optimal width.

```js
const tip = tippy.one(ref)
tip.popper.classList.add('custom')
```

```css
.custom {
  max-width: 450px;
}

@media (max-width: 470px) {
  .custom {
    max-width: calc(100% - 20px);
  }
}
```
