### ISSUE TITLE
[v3] popperOptions not being used

### ISSUE THREAD

**Issue by ejdaly** [atomiks/tippyjs#276]
It seems the popperOptions option / prop is not being used at all in v3. 
(The only reference is in the Defaults object)

Typo on line2 of createPopperInstance()? 

The following would make sense:

```
<<< var props = tip.props.props;
---
>>> var props = tip.props.popperOptions;

```

**Comment by atomiks** [comment]
Yeah, it was an accident. I'm about to release `alpha.2` which fixes this + some other long-standing problems

Ironing out the bugs 🐛 🐞

**Comment by atomiks** [comment]
Fixed in `alpha.2`
