### ISSUE TITLE
can we cancel show tooltip if the value inside is not good ?

### ISSUE THREAD

**Issue by Jasminou** [atomiks/tippyjs#277]
Hi,

Just wanna know if there is a way to cancel or hide tooltip in onShow methode if the value  of the text is not good ? thx

**Comment by atomiks** [comment]
Hi,
Do you mean if `title` does not have the text you want?

There is an undocumented lifecycle function called `wait` (actually this might be one of the very few use cases for it):

```js
tippy(ref, {
  wait(show) {
    // not sure how you determine bad text
    if (!badText) {
      show()
    }
  }
})
```

Basically, it takes the `show` method as an argument so you can conditionally show the tooltip based on your own custom logic.

**Comment by Jasminou** [comment]
oh thx a lot :)

**Comment by Jasminou** [comment]
atomiks if there any way to have instance oh show method in wait method ?

**Comment by Jasminou** [comment]
my bad I figure it out, thx for your help and good job with tippy :)
