### ISSUE TITLE
Interactive content does not work in Tippy v3.0.0-alpha.2 

### ISSUE THREAD

**Issue by davemoore24** [atomiks/tippyjs#278]
Just pulled v3.0.0-alpha.2 and something broke from v3.0.0-alpha.1 regarding interactive tooltips and setting the trigger to click.

**In alpha.1**, when you clicked the reference and the tooltip is open, it acted just like a dropdown in which mouseleave would not close it.

**In alpha.2**, when you move the mouse outside of the content, the tooltip closes not matter what unless I am doing something completely wrong.

Check out the pen https://codepen.io/davemoore24/pen/QBRzLK/

**Comment by davemoore24** [comment]
Here is **alpha.1** working as expected https://codepen.io/davemoore24/pen/yqWGzp
The issue is mouseenter/mouseleave is being applied and fired on interactive "click" tips.
It looks like https://github.com/atomiks/tippyjs/commit/85c1d86e63fb18c08e11adb1e6d6025460105916#diff-1004d651d4491bebf2210950b5a85304R430 is the issue. 

This fixes it but I am not sure if it breaks https://github.com/atomiks/tippyjs/issues/193
```  
    if (!popperHasEventListeners && tip.props.trigger !== 'click') {
      tip.popper.addEventListener('mouseenter', prepareShow);
      tip.popper.addEventListener('mouseleave', prepareHide);
      popperHasEventListeners = true;
    }
```

**Comment by atomiks** [comment]
Yes you're right, it shouldn't apply to click tooltips.

**Comment by davemoore24** [comment]
lol... FYI, my fix above doesn't work. When I set the trigger to manual, it didn't work.

**Comment by atomiks** [comment]
Probably need to check `lastTriggerEvent` inside the event listener callback then. Only do it for `mouseenter` event

**Comment by atomiks** [comment]
Please see `v3.0.0-alpha.3`. I resolved many edge cases I tested but no doubt something might have slipped through...

**Comment by davemoore24** [comment]
Awesome. Thanks for implementing hideAllPoppers... This weekend I will fork the project, work on the docs to add some of examples I talked about and to a pull request.
