### ISSUE TITLE
InteractiveBorder does not work in Tippy v3.0.0-alpha.2

### ISSUE THREAD

**Issue by davemoore24** [atomiks/tippyjs#279]
InteractiveBorder does not seem to be calculating correctly. In the pen below, I set it to 300. Pen includes a few examples. 
Here is the pen https://codepen.io/davemoore24/pen/JBqxyG

**Comment by atomiks** [comment]
I think it's because of the #193 fix. Turns out it broke many things 😆

**Comment by davemoore24** [comment]
Lol. It sure did. I actually had to revert back to alpha.1.

**Comment by atomiks** [comment]
This seems to fix it:

```js
if (tip.props.interactive && tip.props.trigger !== 'click') {
  tip.popper.addEventListener('mouseenter', prepareShow)
  tip.popper.addEventListener('mouseleave', event => {
    if (
      isCursorOutsideInteractiveBorder(
        getPopperPlacement(tip.popper),
        tip.popper.getBoundingClientRect(),
        event,
        tip.props
      )
    ) {
      prepareHide()
    }
  })
}
```

Thank you for testing these alphas though that's the whole point of them!! I was worried no one was going to try them.

**Comment by davemoore24** [comment]
Lol. There are a few people like myself that prefer to always use yarn/npm @next for everything... lol. Makes QA angry but most orgs I worked in don't keep up with the latest versions and get so far behind it is a nightmare to refactor six months later. If you want to get more people testing, add a v3 page to the site, update it so people know what they will need to change. Maybe even provide an example of a bootstrap4 dropdown menu via click and an area to show the same menu via right click context menu (virtualReference)... You get like 20k downloads a month... I would assume a majority are using in products opposed to Wordpress blogs or marketing sites... lol... and every dev in the world hates dealing with menu positioning... just my 2cents... 

![image](https://user-images.githubusercontent.com/6215968/44175745-cbdede80-a0ac-11e8-84a2-c9d1daa4a74a.png)

**Comment by davemoore24** [comment]
Also... in the last v2 and maybe alpha.1... I have a context menu similar to the image below... in which the menu opens on contextMenu event and the menu item with a submenu opens on hover (the interactive border is king in this case) and I noticed that if I did not append the submenu tippy inside of the context menu tippy, the context menu would close leaving only the submenu showing... cause the submenu would append to the body, in which your tracking focus.... I don't think this is a bug, and there in an option to append it somewhere else... but it might be nice to note this in the docs. 

-thanks again for the quick fixes and replies.

**Comment by atomiks** [comment]
Please see `v3.0.0-alpha.3`. I resolved many edge cases I tested but no doubt something might have slipped through...
