### ISSUE TITLE
Unminified distribution codes

### ISSUE THREAD

**Issue by ismail-codar** [atomiks/tippyjs#28]
Currently dist folder contains minifed codes.
Mostly users need unminified code on their development environment for debugging. Users already minified all codes when theirs own production build. 

Please provide unminifed code on dist folder.
In package.json   "main": "dist/tippy.js" may be address unminified code.

**Comment by atomiks** [comment]
The unminified is available in `src/js/tippy.js`, is that not appropriate? Also unpkg.com uses the `main` I believe, so it should link to the minified

**Comment by ismail-codar** [comment]
https://github.com/atomiks/tippyjs/blob/master/dist/tippy.js looks minifed. I look for https://unpkg.com. 

It Says: 
A few examples:
https://unpkg.com/react@15.3.1/dist/react.min.js

There is no main property in https://github.com/facebook/react/blob/master/package.json

So I think: minified can be access unpkg.com/tippyjs/0.4.1/tippy.min.js. 

Also If main links dist/tippy.js (unminified)
const Tippy = require("tippy.js") can be return unminified version. Better for debuggin in development mode.

**Comment by ALPIXELMaiki** [comment]
I don't know if you use Webpack2 for your compilation, but you can do something like that in your configuration file :
```
...
  resolve: {
    alias: {
      'tippy$': 'tippy.js/src/js/tippy.js'
    }
  }
...
```

By this way, when you call `const Tippy = require("tippy.js")` it will return the uminified file in src/js/ folder

**Comment by atomiks** [comment]
You're right

https://unpkg.com/react => not usable
https://unpkg.com/vue => links to unminified

https://unpkg.com/tippy.js => uses "main"
https://unpkg.com/tippy.js@0.4.1/dist/ for the dist folder
https://unpkg.com/tippy.js@0.4.1/src/ for the src folder


For v0.5.0 (next ver), I will fix this up.
