### ISSUE TITLE
How to I explicitly show the tippy on contextmenu event?

### ISSUE THREAD

**Issue by abhigyantiwari** [atomiks/tippyjs#280]
Hi,
I'm working on a file explorer program and using tippy for context-menu. I can bind click event and show tippy. But, how can I show tippy on right click?

**Comment by atomiks** [comment]
Have you tried using the methods?

`reference._tippy.show()`

**Comment by abhigyantiwari** [comment]
Wow thanks! I will use this solution (a while before I was binding events similarly from onShown(instance) option). 
There is also another help I need. How do I bind tippy to new contents. For example If new folder was added I couldn't open tippy on that.

Thanks.

**Comment by atomiks** [comment]
> How do I bind tippy to new contents. For example If new folder was added I couldn't open tippy on that 

You can use event delegation. You only need to call tippy once.

Example:

```html
<div id="sidebar">
  <button>Create new folder</button>
  <div class="folder"></div>
  <div class="folder"></div>
  <!-- This new div was added after they clicked the button -->
  <div class="folder"></div>
</div>

<script>
tippy('#sidebar', {
  target: '.folder'
})
</script>
```

It's two steps:

1. Bind the tippy instance to the _parent_ container (it doesn't receive the tippy)
2. Specify a `target` option with the CSS selector that matches the child elements who will have a tippy instance automatically created for them when triggered

**Comment by abhigyantiwari** [comment]
Yes this worked. I should have read your documentation completely before asking (rush). Thank you very much author for your help. Please close the issue. Our product will be using tippy heavily. So, I'll post any issue or ask for help here. We'll also try to contribute if we can.

Thanks.

**Comment by atomiks** [comment]
No problem 🐝

**Comment by adriansimionescu83** [comment]
In case somebody else is having this issue, one fix I found to prevent the default behaviour of showing the context menu is having an event listener that prevents default inside the onCreate prop:

 ```
let props = {
      trigger: 'contextmenu',
      animation: 'shift-away',
      duration: 100,
      content: content,
      theme: theme,
      interactive: true,
      placement: 'bottom-start',
      maxWidth: 800,
      allowHTML: true,
      onCreate(instance) {
        element.addEventListener('contextmenu', (event) => {
          event.preventDefault();
        });
      },
      onDestroy(instance) {
        element.removeEventListener('contextmenu', (event) => {
          event.preventDefault();
        });
      }
    }
```
