### ISSUE TITLE
animateFill for arrow/box-shadow?

### ISSUE THREAD

**Issue by Ambient-Impact** [atomiks/tippyjs#281]
Hi there. I'm really liking this library, and 3.0 (#201) looks pretty good (though I haven't tried it yet). I'm wondering if there's a technical reason that the animateFill clip-path transition can't be applied to the whole tooltip, including the arrow and other stuff? I'm creating my own themes for 2.x, and I love the animateFill, but it looks odd not affecting the box-shadow. Any chance of this making it in? Is there anything I can do to help?

**Comment by atomiks** [comment]
So the animateFill technique uses overflow hidden on the tooltip so the backdrop doesn't overflow it, and the content has a clip path applied to it so the content doesn't overflow the backdrop.

This means a box shadow applied to the backdrop is clipped, same with the tooltip

The arrow is a separate element that isn't part of the tooltip so it's not part of the effect.

If you have any way to fix the animation then that would be awesome!

**Comment by Ambient-Impact** [comment]
Ah, I see how that would complicate things. This is probably an obvious question, but have you tried just doing a ```clip-path``` transition on ```.tippy-popper```? I see that Popper sets a ```transform``` on that element, so I'm guessing it would just overwrite anything set on it?

**Comment by atomiks** [comment]
@Ambient-Impact `clip-path` has been removed for now but that probably might work if you want to try it yourself. The property doesn't have enough browser support and causes some buggy behavior on some mobile devices

**Comment by Ambient-Impact** [comment]
That's a good idea. I'll have to give it a shot. Thanks!
