### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by enfascination** [atomiks/tippyjs#283]
Sorry if Issues isn't the venue for this (if not, let me know where to go instead).  I want to do something unconventional: define an element so that it can activate its tooltip and that of a sibling element, such that the sibling tooltip's state is totally slave to events on the main element. 
 Is this too weird for tippy?  If not, how would you start to approach this?  Thank you for your help.

**Comment by atomiks** [comment]
There's no "automatic" way to do this, but remember you can implement any kind of functionality you want using the methods of an instance.

So, if you have markup like this:

```html
<button class="master" title="tooltip">Master</button>
<button class="slave" title="tooltip">Slave</button>
```

You can add your own event listeners to the master element and show the slave tooltip.

```js
const master = document.querySelector('.master')
const slave = document.querySelector('.slave')

const masterTippy = tippy.one(master)
const slaveTippy = tippy.one(slave, { trigger: 'manual' })

// default trigger === 'mouseenter focus'
const showEvents = ['mouseenter', 'focus']
const hideEvents = ['mouseleave', 'blur']
showEvents.forEach(event => {
  master.addEventListener(event, () => {
    slaveTippy.show()
  })
})
hideEvents.forEach(event => {
  master.addEventListener(event, () => {
    slaveTippy.hide()
  })
})
```

https://codepen.io/anon/pen/BOowqg

**Comment by enfascination** [comment]
This is perfect.  It was very generous of you to prepare a demo.
