### ISSUE TITLE
Popper hide modifier not working?

### ISSUE THREAD

**Issue by Ambient-Impact** [atomiks/tippyjs#284]
After trying a bunch of things, I can't seem to get the expected behaviour of the [Popper hide modifier](https://popper.js.org/popper-documentation.html#modifiers..hide) to work. It's supposed to add an ```x-out-of-boundaries``` attribute to the element when scrolling moves it off screen, but it doesn't seem to be doing that. I've looked through the Popper docs, the [source of the hide modifier](https://github.com/FezVrasta/popper.js/blob/master/packages/popper/src/modifiers/hide.js), and checked that my instances seem to have the modifier enabled and in the correct order, but no luck. This is on 2.5.4.

**Comment by atomiks** [comment]
https://codepen.io/anon/pen/ZMQOjv

Not seeing any problems. The `.tippy-popper` element has the attribute added, which you can use to select the child tooltip element and hide it.

**Comment by Ambient-Impact** [comment]
Ah, I see. I poked around and it looks like setting ```popperOptions.modifiers.preventOverflow.boundariesElement``` to ```'viewport'``` makes it work, so it may be something about my site CSS that's throwing Popper off. The [Tippy site](https://atomiks.github.io/tippyjs/) seems to display the same issue when I open devtools and try it out on the click trigger one near the top of the page, so I just assumed it was an issue with the library as a whole. Thanks!
