### ISSUE TITLE
disabled buttons prevent the tooltip from showing

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#286]
When I set a `button` element to disabled, it's tippy never displays on click or hover event. Is there a workaround for this?

**Comment by atomiks** [comment]
Yes: use a wrapper element that isn't disabled and apply the tooltip to that.

```html
<div title="tooltip">
  <button disabled>btn</button>
</div>
```

```js
tippy('div')
```

**Comment by mreinstein** [comment]
sorry forgot to close this ticket. Definitely a good workaround, thanks!

**Comment by Weber-D** [comment]
I'm having problems that the tooltip has a lot of margin to the input element if a wrapping div is used for showing tooltips on disabled elements. 

Simle example: https://jsfiddle.net/xpvt214o/929062/

**Comment by Weber-D** [comment]
@atomiks My fault, I was in a hurry and didn't think about it. Now it works as expected 👍 
Maybe this workaround should be added in the documentation, when others may have the requirement of tooltips in disabled elements, too.

**Comment by avtarnanrey** [comment]
Don't use a `tabindex` on a non-clickable element. It will create an accessibility issue.
