### ISSUE TITLE
Interactive option fails for HTML popups in IE11.

### ISSUE THREAD

**Issue by LukeFarrawell** [atomiks/tippyjs#287]
https://codepen.io/anon/pen/YOVKKv

The example does not work at all in IE11. The zip attachment contains 2 .html files showing the bug.
[example.zip](https://github.com/atomiks/tippyjs/files/2344318/example.zip)

**Expected Behaviour**
Putting the mouse on the triangle will show a popup, as the mouse leaves the popup, the popup SHOULD stay on the screen. This can be seen in running the example in chrome with `interactive: true`.

IF `interactive: false`, then the popup SHOULD disappear when the mouse leaves the triangle.

**BUG**
Running the exact same code in IE11 with `interactive: true` will cause an error:
`SCRIPT5007: Unable to get property 'add' of undefined or null reference
tippy.all.min.js (1,36776)`

when you set `interactive: false` in IE11, it will show the same behaviour as chrome when chrome is doing `interactive: true`.

**Desired Behaviour**
The behaviour I am looking for is what chrome is showing for `interactive: true`.

Can this be fixed in 2.5.5?

**Comment by atomiks** [comment]
I'm guessing it has something to do with the SVG node used as the reference, I know that IE11 has some missing methods. What happens if you wrap it with a div and use that as the reference instead?

**Comment by LukeFarrawell** [comment]
Seems you are correct.

I had to add a .contains function to get tippy to work with svg's.

I did add a missing function to get it working, I guess there is another missing function somewhere within tippy or popper.

**Comment by LukeFarrawell** [comment]
IE10+ added support for .classList, but it was not added to SVG.

**Comment by atomiks** [comment]
Does it work if you add a `classList` polyfill for SVG for IE?

**Comment by LukeFarrawell** [comment]
Yes it does work with the polyfill. Was just trying to find one after my last message.

It also seems to fix the issue with `interactive: false` behaving the same as `interactive: true` in IE11.
