### ISSUE TITLE
Support `useCapture` option in bindEventListeners

### ISSUE THREAD

**Issue by gargrave** [atomiks/tippyjs#288]
Hi there,

We came across a small issue today.

In short, the issue is that we have some elements within our Tippy instance that, when clicked, will be removed and replaced by other elements. This causes Tippy to close, even with `interactive` set to true, and after some investigation, we found that the issue is [here](https://github.com/atomiks/tippyjs/blob/master/src/js/core/bindEventListeners.js#L57) because the element/target is being removed _before_ this code is reached, thus `popper` is `undefined` here, and the early return does not happen as expected.

However, adding `true` for the third arg (`useCapture`) [here](https://github.com/atomiks/tippyjs/blob/master/src/js/core/bindEventListeners.js#L98) fixed the issue for us, since it ensures this gets called before the target element is removed from the DOM.

So, I wanted to know:

- Is there a better, existing way to make this happen that we didn't see, without requiring `useCapture` to be true here?
- If not, would you entertain you a PR to add this as an option? We could set the default to `false` so it won't affect any existing implementations, of course.
  - If we do this, do you have a suggestion for the cleanest way to access the Tippy props/options here? I would like to pass it in as an optional prop, but it seems like accessing the Tippy options here is a little hairy (as seen in line 57 linked above).

For reference's sake, we are using a slightly-modified version of this fork of `react-tippy` to get Tippy/React working together: https://github.com/textpress/react-tippy

Happy to do any necessary legwork here--just wanted to get a sanity check before proceeding. Thanks!

**Comment by atomiks** [comment]
Could you make a CodePen reproducing the issue? It's hard for me to understand without the context. Thanks!

**Comment by gargrave** [comment]
Yep, totally understand! Let me put something together, and I'll update when I have a link. Thanks for the quick response!

**Comment by gargrave** [comment]
Unfortunately, I am not having much luck replicating the issue in a simplified example. Admittedly, our use case is pretty complex, and the content within our Tippy instance is a pretty hefty component tree, so it is difficult to properly replicate outside of my own dev environment.

The general gist of what we're doing is:
- One component within our Tippy instance says "Click to expand"
- When you click it, it gets removed and replaced by other elements

The click event on said component causes the component to be removed before the event reaches Tippy, so when Tippy is searching for the reference (in the line I linked to), there is nothing there, and thus Tippy closes even though we don't want it to. Enabling `useCapture` for the click event fixes this for us.

So yeah, having the option to enable `useCapture` as an optional Tippy config/option would be, and would definitely save us a lot of heartache, if it's something you're willing to consider.

**Comment by gargrave** [comment]
FWIW, I implemented a simple version of this request in a fork:
https://github.com/opallabs/tippyjs/commit/6a91b3cb90387d8b33c9f1138e104a4ee2f1040a

This really only takes into account our specific use case, but I would be happy to submit a PR with a more robust implementation.

**Comment by atomiks** [comment]
Yeah it's no big deal :^). I'd make it a static method and use an outer variable flag.

v2 is about to be replaced with v3 (I'll port this over) but I need to release a new v2 version with a fix anyway.

**Comment by atomiks** [comment]
`v2.6.0`
