### ISSUE TITLE
Choose the "tooltip" container

### ISSUE THREAD

**Issue by Cryde** [atomiks/tippyjs#29]
It would be nice if we could choose the tooltip container.

In my case I have some position issue : window scroller that contain another scroller where my tooltips are. If I scroll in by window, the position of the tooltip in the sub-scroller are incorrect... 
A solution could be to choose the "container" (or the parent (which will be used to calculate the tooltip position)

Is it possible ?
Thanks

**Comment by atomiks** [comment]
Could you provide a demo? Thanks 😀

**Comment by Cryde** [comment]
Here is the demo with the "bug" : https://github.com/Cryde/tippy-example

Sorry for the colors 😅

**Comment by atomiks** [comment]
Just letting you know.. v0.5.0's babel broke and didn't transpile it to es5 😢, I've rolled back to v0.4.1 while I figure out a fix

**Comment by Cryde** [comment]
Use yarn as package manager :)

**Comment by atomiks** [comment]
Anything to do with positioning is basically Popper's job, so take a look at the documentation and define settings inside `popperOptions`

https://codepen.io/anon/pen/qmbEZG

I'm not sure if it's possible @FezVrasta

**Comment by FezVrasta** [comment]
@Cryde that's a bug with Popper.js, may you open an issue in [the correct repository](https://github.com/FezVrasta/popper.js/issues/new) please?

**Comment by atomiks** [comment]
Closing since it's related to Popper
