### ISSUE TITLE
Close tooltips when mouse cursor is too far away

### ISSUE THREAD

**Issue by viveleroi** [atomiks/tippyjs#290]
We need the ability to close a tooltip (regardless of any delay) when the cursor is too far away. We currently use qtip2 which provides an option for hiding a tooltip when the cursor is greater than a set distance from the element.

**Comment by viveleroi** [comment]
Very closely related to this, there should be some sort of `inactive` setting, that only triggers the close delay once the user has stopped hover over the target element. We want the tooltip to show for the entire duration of cursor stay, and only start "closing" once the cursor has left the element.

**Comment by atomiks** [comment]
You can implement that yourself in userland. I'd like to avoid bloating the core library too much if things can be solved outside the core (trying to solve everyone's use case w/ a declarative option ends up leaving people including many kB that they don't need - which is already the case in many ways)

> Very closely related to this, there should be some sort of inactive setting, that only triggers the close delay once the user has stopped hover over the target element. We want the tooltip to show for the entire duration of cursor stay, and only start "closing" once the cursor has left the element.

I don't understand this one. Can you clarify what you mean?

**Comment by viveleroi** [comment]
Actually I was mistaken, I double-checked the library and it already does what I want. For some reason I thought it started the "close" timer/delay upon opening the tooltip, but I see it keeps the tooltip open as long as my cursor is over the target element.
