### ISSUE TITLE
Title fails to update when value is empty and dynamicTitle = true

### ISSUE THREAD

**Issue by viveleroi** [atomiks/tippyjs#291]
[CodePen](https://codepen.io/anon/pen/gdjoye)

Using `dynamicTitle: true` fails to clear the title when the "new" value is an empty string. We're using AngularJS (v1) interpolation for certain titles, so they initialize with something like `{ title }`, but if the subsequent values are empty, the tooltip keeps showing `{ title }`.

Everything works as expected for non-empty values.

**Comment by atomiks** [comment]
wontfix because v3 is releasing soon and replaces all of this behavior at a fundamental level
