### ISSUE TITLE
Line break in functionality in tippy

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#292]
When the title message is need to show with bullets.
Then I want show tooltip message containing line break
I tried with \n
also tired "&#013";
But line break didnt work in tippy

**Comment by atomiks** [comment]
You can use `<br>` as `title` can contain HTML

**Comment by Slapbox** [comment]
This doesn't work for me in the React version. Am I doing something wrong there?

**Comment by atomiks** [comment]
@Slapbox 

Can use fragments and `<br />` element

```jsx
<Tippy content={
  <>
    line 1
    <br />
    line 2
  </>
}>
  <button />
</Tippy>
```

**Comment by Slapbox** [comment]
Thank you @atomiks!

**Comment by WilliamVenner** [comment]
It would be nice if this was native to tippy, I don't see why `\n` isn't displayed properly. I do not want to use HTML in tippy because of potential XSS, and escaping it all in JavaScript seems like a lot of wasted effort.

Not everyone uses React.

Here's a workaround:

```css
.tippy-content {
    white-space: pre-line;
}
```

**Comment by atomiks** [comment]
I mean the library just uses `.textContent` to set content by default, which doesn't wrap newlines, and the CSS just uses browser defaults. So that's just a solution rather than a workaround.

**Comment by BeniFreitag** [comment]
Would appreciate if this is configurable via an addictional css-class on tippy
