### ISSUE TITLE
Not able to specify dynamic template ID in html attribute of tippy options

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#293]
Hi,
   How can I specify dynamic custom template ID in html attribute value of tippy options

`
<ng-template let-customer ngFor [ngForOf]="customerList" let-i="index">`

	`<div id="{{ 'my-template' + i }}"  style="display: none;">			

		<div *ngFor="let message of customer.ErrMessages">{{message}}<br/></div>	
		
	</div>

	<span class="alert-icon"  appTooltip [options]="{html: '#'my-template' + i'}"></span>

	<label> {{customer.name}} </label>`

`</ng-template>`

**Comment by gomteshhatgine** [comment]
Hi @atomiks,
But the issue is closed.
Please let me know when this fix is done
 Thanks

**Comment by gomteshhatgine** [comment]
Hi,
I had implemented in this way :
https://stackblitz.com/edit/hello-angular-6-tpd9bw?file=src%2Fapp%2Fapp.component.ts

**Comment by Teebo** [comment]
Great I will still that code 😜 thanks
