### ISSUE TITLE
Feature request: followCursor: 'horizontal'

### ISSUE THREAD

**Issue by jorre** [atomiks/tippyjs#294]
First of all, I really like the flexibility and ease of use of tippy!

The `followCursor: true` option is great, but I currently have a graph component with lots of datapoints where I'm showing a tooltip on hover. This works great, but I'd love the tooltip to remain on top of my graph (not in front of it), while following the cursor horizontally only. 

Not sure if that's even possible with the current latest build with some custom coding?

**Comment by atomiks** [comment]
I guess it might be possible, the custom `getBoundingClientRect()` would use the MouseEvent for the x-axis but the element for the y-axis?

**Comment by atomiks** [comment]
I was able to get this working using my idea above, it's now in the v3 branch. I hope to get v3 released this weekend.

**Comment by atomiks** [comment]
3.0.0
