### ISSUE TITLE
Current status of IE 11 support?

### ISSUE THREAD

**Issue by gargrave** [atomiks/tippyjs#295]
Hi there!

I am noticing that, in the current version, Tippy does not seem to work at all in IE 11. Even on the main [demo page](https://atomiks.github.io/tippyjs/), none of the demos work at all.

According to the [browser support section](https://atomiks.github.io/tippyjs/#browser-support), it _looks like_ IE 11 should be supported, so I was wondering if there was a possibility that something broke in the newest update? (We had previously tested a very old version of Tippy, and it did work, but we're talking 1.x, so I realize that's not super relevant.)

Any thoughts on this? Happy to help troubleshoot, although admittedly debugging in IE 11 is a pretty miserable experience. Unfortunately IE 11 support is a must-have for us.

Thanks for your help! Let me know if there is anything I can do to assist.

**Comment by gargrave** [comment]
Ah, ok, that makes sense. No, I'm not seeing any errors at all--just nothing at all happens when I click on the trigger element (same as what I see on the docs page).

FWIW, we are using our own customized version of [this wrapper](https://github.com/textpress/react-tippy), so the issue could definitely be on our end. (Hence why I was indeed doing the unthinkable and browsing the docs in IE11, as a way to test it without our React wrapper in the middle. 😄 )

So... yeah. I will continue troubleshooting on our end and see what I can dig up--just wanted to confirm that it _should_ still work in IE11, at least. I guess when we can go ahead and close this issue, although if you have any grand suggestions on what the issue might be, I'm all ears! Unfortunately debugging in IE11 is not a great development experience.

Anyway, thanks again for your quick response! Much appreciated! 👍

**Comment by atomiks** [comment]
Can you recreate the vanilla version of what you're using in React and test it with IE11? (That way we can 100% confirm there is no problem with the library itself, and can close the issue).

**Comment by gargrave** [comment]
So I managed to get a test in IE11 with vanilla TippyJS, and it does indeed work (unfortunately CodePen doesn't support IE, so I don't have anything to share).

Nonetheless, it does appear that this is an issue with our React wrapper. All of the lifecycle methods are firing as expected, but none of the trigger events are firing.

So anyway, I will close this issue and continue to investigate locally. Sorry for the false alarm, but thanks again for your help!

**Comment by kopacki** [comment]
@gargrave I'm trying to get tippy working in IE11, but no success so far. Would you be able to share the project config? I'm using webpack with babel.
