### ISSUE TITLE
Destroy tippy.js instance

### ISSUE THREAD

**Issue by shafikhaan** [atomiks/tippyjs#297]
I have the following code which shows a tooltip containing dynamic data. Its working fine, But it shows same tooltip for all.

<pre>
const template = document.querySelector('#template')
const initialText = template.textContent
const tip = tippy('.otherPostTags', {
   animation: 'shift-toward',
    arrow: true,
    html: '#template',
    onShow() {
        const content = this.querySelector('.tippy-content')
        if (tip.loading || content.innerHTML !== initialText) return
        tip.loading = true
        node = document.querySelectorAll('[data-tippy]');
        let id = node[0].dataset.postid;
        $.ajax({
            url: '/get/post/'+id+'/tags',
            type: 'GET',
            success: function(res){
                let preparedMarkup = '';
                res.tags.map(function(item) {
                    preparedMarkup +=
                        '<span class="orange-tag" style="background-color: '+item.color+'">'+
                            item.name +
                        '</span>';
                });
                content.innerHTML = preparedMarkup;
                tip.loading = false
            },
        });
    },
    onHidden() {
        const content = this.querySelector('.tippy-content');
        content.innerHTML = initialText;
    }
});
</pre>

I have used `tip._tippy.destroy()` bit didn't worked. What am i missing here ?

**Comment by atomiks** [comment]
What's this? Probably causes the issue

```js
node = document.querySelectorAll('[data-tippy]');
let id = node[0].dataset.postid;
```

**Comment by atomiks** [comment]
I'm not sure what you're trying to achieve, if you can explain the problem more clearly I can help a bit better
