### ISSUE TITLE
take DOM element as a param with the constructor

### ISSUE THREAD

**Issue by seiyria** [atomiks/tippyjs#3]
this would make it easier to wrap this library with angular et al

**Comment by atomiks** [comment]
Param, or just check the selector?

    // Check if selector is a DOM element
    if (selector instanceof Element) {
        this.tooltippedEls = [selector]
    } else {
        this.tooltippedEls = [].slice.call(document.querySelectorAll(selector))
    }

**Comment by seiyria** [comment]
that would be fine, too, although a bit misleading if it's still called selector, but I don't have anything better.

**Comment by atomiks** [comment]
Released as v0.1.9
