### ISSUE TITLE
ES6 import/linter error

### ISSUE THREAD

**Issue by StefanFeser** [atomiks/tippyjs#30]
Hi,

I just tried to install your library via NPM
```
npm install tippy.js
```
and import it like this:
```
import Tippy from 'tippy.js';
```

But I get a lint error after importing the lib. I'm using browserify for the bundling. Lint error looks like this:
```
SyntaxError: Unexpected token (4:7) while parsing /node_modules/tippy.js/src/js/tippy.js while parsing file: /node_modules/tippy.js/src/js/tippy.js
    at DestroyableTransform.end [as _flush] (/node_modules/insert-module-globals/index.js:96:21)
    at DestroyableTransform.<anonymous> (/node_modules/readable-stream/lib/_stream_transform.js:115:49)
...
```

After changing the path in your package.json for "main" to "dist/tippy.js" it works. But I don't think that's the way you would like to have it.

Cheers
Stefan

**Comment by atomiks** [comment]
Yes you're right, it should link the unminified es5 version, thanks

**Comment by StefanFeser** [comment]
Thanks @atomiks!

Did you also push it to NPM? Didn't get the changes after reinstalling it.

**Comment by atomiks** [comment]
About to push 0.6.0 right now with a bunch of changes, sorry haha

**Comment by StefanFeser** [comment]
Thanks! Really appreciate your work!

**Comment by atomiks** [comment]
Should be published now 😃

**Comment by StefanFeser** [comment]
Sorry to tell you but I still don't get the changes via npm install ;)

**Comment by Romick2005** [comment]
Hi, same here. Not works in version "0.17.0" also.

**Comment by atomiks** [comment]
@Romick2005 - It's just minified CSS, why would you get that error?

**Comment by darrensw777** [comment]
I had an issue with parsing the css separately as well, simple workaround for me was to full Tippy from the file which includes the css:

import tippy from 'tippy.js/dist/tippy.all.js';

**Comment by atomiks** [comment]
You need a webpack loader for the CSS import as well. But yeah the `<head>` CSS inject method using the `all.js` UMD version is a workaround.

**Comment by darrensw777** [comment]
> You need a webpack loader for the CSS import as well. But yeah the `<head>` CSS inject method using the `all.js` UMD version is a workaround.

I am using webpack, it doesn't like it for some reason, says there's a parse error - if you need more info please shout and I'll add it on here

**Comment by jgujgu** [comment]
For those using Tippy.js 6.x, similar to the advice above, just use this:

```js
import tippy from 'tippy.js/dist/tippy.umd.min.js';
```
