### ISSUE TITLE
Change tippy trigger dynamically, or prevent hiding the tooltip onHide

### ISSUE THREAD

**Issue by nadavshabtai** [atomiks/tippyjs#300]
Hi
is it possible to open tooltip with mouseenter and change the trigger to click?
or is it possible to prevent hide with onHide function? (say return false in onHide to prevent the tooltip from hiding)

**Comment by nadavshabtai** [comment]
I need it to be interactive, and only when clicking on button inside to turn to click, this event is only on the ref element... sorry I didn't explain myself very well

**Comment by atomiks** [comment]
Well you add listeners to the necessary elements and call the methods on the tippy instance to have the show/hide functionality you want.
