### ISSUE TITLE
setDefaults is ignored when it does not occur soon enough

### ISSUE THREAD

**Issue by viveleroi** [atomiks/tippyjs#303]
When AngularJS (1.x) is included on a page using RequireJS, tippy works, but anything set via `setDefaults` fails to apply.

https://codepen.io/helion3/pen/JagVxd

In the above codepen, the issue is resolved by removing `angular` from the require block/function. Changing the order of the includes doesn't have any effect. This does not occur when Angular is included via a script tag.

**Comment by troywoy** [comment]
I dug into this a little deeper and while I don't have an answer to *why* it's happening, I at least know a recreate-able scenario. For whatever reason, [angular.js](https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.10/angular) *works* and [angular.min.js](https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.6.10/angular.min) doesn't. If you remove `.min` from the `angular` path, you can see that "shown" is no longer logged.

Note: It appears like cache is a little finicky here, so just make sure you actually have `angular.js` vs `angular.min.js` loaded.

**Comment by viveleroi** [comment]
Troy and I worked together and narrowed this down to simple timing. If `setDefaults` is called after tippy initializes automatically, those defaults are ignored by tooltips already on the page.

This can be reproduced consistently with a simple timeout: https://codepen.io/helion3/pen/oavrzE

```js
setTimeout(() => {
  tippy.setDefaults({
    onShow() {
      console.log('shown'); // never fires
    }
  });
}, 100);
```

Angular specifically wasn't involved outside of the fact that *any* files we `require` had the potential to delay `setDefaults` enough to cause this.

**Comment by atomiks** [comment]
> Troy and I worked together and narrowed this down to simple timing. If setDefaults is called after tippy initializes automatically, those defaults are ignored by tooltips already on the page.

This was the intended behavior. You need to call it before any tooltips get initialized / it sets the defaults for future instances, not existing ones, which would be more expensive.

**Comment by viveleroi** [comment]
Is there a way to prevent tippy from automatically instantiating itself until it's been loaded properly?

**Comment by atomiks** [comment]
Using `data-tippy` the auto-initialization is deferred with `setTimeout(autoInit)`, so you can run sync scripts straight after importing Tippy, but otherwise no. That technique is for beginners who need a simple & fast way to create their tooltips on traditional web pages without hassle. If you're using something like Angular, I recommend using the `tippy()` function to create tooltips.

**Comment by viveleroi** [comment]
So how do we disable the auto-init functions? I don't mind instantiating everything ourselves, but I don't want the default one running pointlessly.

**Comment by atomiks** [comment]
[See here](https://atomiks.github.io/tippyjs/#creating-tooltips-method-2-function)

You don't give the element a `data-tippy` attribute, you just use plain JS to initialize it

**Comment by viveleroi** [comment]
Is `data-tippy-content` dynamic? Meaning if I replace the content, will the tooltip automatically pick it up? Trying it in my codepen appears not to be.

**Comment by atomiks** [comment]
It's not, you need to call `.setContent()` to update content for a tippy instance.

I highly recommend you create a wrapper for Angular like I did for React: https://github.com/atomiks/tippy.js-react/blob/master/src/Tippy.js

(Note the `componentDidUpdate` lifecycle). This handles everything for you in a simple API

I have zero experience with Angular but if you can create something similar for Angular I will gladly publish it under `@tippy.js/angular` for people to use

----

If you really want to make it dynamic like `dynamicTitle` in V2, you can create some kind of higher-order function like this (I don't know if this works I'm writing it quickly)

```js
function withDynamicContentAttribute(tippy) {
  return (...args) => {
    const tipCollection = tippy(...args)
    tipCollection.instances.forEach(instance => {
      // I'd make sure you can disconnect this somehow too in case of memory leaks?
      const observer = new MutationObserver(() => {
        instance.setContent(reference.getAttribute('data-tippy-content'))
      })
      observer.observe(instance.reference, { attributes: true })
    })
    return tipCollection
  }
}

const customTippy = withDynamicContentAttribute(tippy)
// use `customTippy()` from now on instead of `tippy()`
```

**Comment by viveleroi** [comment]
Unfortunately Angular mutates the dom and this means we'd have to add *watches* (Angular digests are way more expensive than React state changes) which is not a viable solution for our needs. Unfortunately v3 has made this a much less viable solution for us.

**Comment by atomiks** [comment]
Try the higher order function. V2 used the same technique internally.
