### ISSUE TITLE
Non-interactive tip is stuck on UI after mouseleave without default style

### ISSUE THREAD

**Issue by kenyerr** [atomiks/tippyjs#305]
[Example](https://codepen.io/anon/pen/NLQzYm)

The _mouseenter_ & _mouseleave_ handlers used for the interactive behavior cause that the tooltip is still shown on the UI even if it should have been hidden if:
- The default tippy.css is not included. (which would apply the _pointer-events: none;_ otherwise)
- The hide delay is more than 0. (with a delay the tip is still visible when the mouserenter event is fired on the tip so the prepareShow will cancel the hide timeout)

Of course it can be fixed to manually apply the _pointer-events: none;_ for example to the popper instance but maybe it would be better to just skip the two listeners added as a fix for the interactive behavior if that one is not enabled.
So in that line the options.interactive should be evaluated as well.
 https://github.com/atomiks/tippyjs/blob/b5495b19bade5bcf5104a770aa2dc7eeac056544/src/js/createTippy.js#L469

**Comment by atomiks** [comment]
I never thought you wouldn't include `tippy.css` 🤔, but I guess it should be possible to use tippy without the default CSS.

> So in that line the options.interactive should be evaluated as well.

The `set()` method will probably require this to be extracted into its own function, but that should work

**Comment by kenyerr** [comment]
Thank you very much!
