### ISSUE TITLE
popperInstance onCreate not working

### ISSUE THREAD

**Issue by nadavshabtai** [atomiks/tippyjs#309]
Hi

I need to register to onCreate event of popper, but it looks like tippy runs over it when I put onCreate function in popperOptions

is it possible to register to onCreate?

**Comment by nadavshabtai** [comment]
Yes' I have a problem with dynamic references in scroll able container, the popper is positioning the tooltip in the wrong place at the first show, and after the first show it's fine..
I want to scheduleUpdate to the popper onCreate

**Comment by atomiks** [comment]
Can you create a CodePen of the issue?

**Comment by nadavshabtai** [comment]
Unfortunately no, It's part of a very big project and I can't reproduce the problem... I can give you screenshot though

**Comment by nadavshabtai** [comment]
First show
![screenshot from 2018-10-03 12-42-37](https://user-images.githubusercontent.com/12856158/46403041-10c8de00-c70a-11e8-89aa-f81b20c6c33f.png)

Second show
![screenshot from 2018-10-03 12-42-49](https://user-images.githubusercontent.com/12856158/46403057-1aeadc80-c70a-11e8-907f-837dfc053e3d.png)

**Comment by atomiks** [comment]
Is this with v3 or v2? 

Try this

```js
tippy(ref, {
  lazy: false, // v3; for v2 use `createPopperInstanceOnInit: true`
  onShow({ popperInstance }) {
    popperInstance.scheduleUpdate()
  }
})
```

**Comment by nadavshabtai** [comment]
The thing is I want the popper instance to be created onShow, I also compile the html onShow for better performance, (The list in the picture could be very long and if all the tooltips are initialized at once, the scrolling is slow..)

About the update on show, As I wrote in my previous comment: it's working, but the tooltip is jumping to i'ts position after it's shown, and it's ugly, so I want it to start in the right position...

I'm using 2.5.2

**Comment by atomiks** [comment]
Have you tried with the latest v2, 2.6.0

**Comment by nadavshabtai** [comment]
No, you have breaking changes in the directories of the project in 2.5.3...

**Comment by atomiks** [comment]
The directories are the same between those versions...?

**Comment by nadavshabtai** [comment]
Sorry Sorry, I was confused with popper.js, they had breaking changes in 1.14.4, I'll try it now

**Comment by nadavshabtai** [comment]
I tried it now and the problem remains...

**Comment by atomiks** [comment]
Hmm, this hack should work if all else has failed.

```js
tippy(ref, {
  onShow(tip) {
    if (!tip.firstShow) {
      tip.firstShow = true
      tip.hide()
      tip.show()
    }
  }
})
```

**Comment by atomiks** [comment]
> I also compile the html onShow for better performance

I guess this must be the issue, because I haven't had any problems with "first show" positioning for a long time

I suggest you compile the HTML before `onShow` (synchronously), or just fork the library code and add in `popperOptions.onCreate()` `scheduleUpdate()` internally yourself (V2 isn't having any more releases).

**Comment by atomiks** [comment]
If a reproducible demo can be created to verify this problem I can reopen this
