### ISSUE TITLE
dist folder no longer available

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#310]
Hi, the dist folder is no longer available in this repo.

**Comment by atomiks** [comment]
GitHub repos shouldn't include a `dist` folder.

Distribution is via `npm` and the `unpkg` CDN.

**Comment by stratboy** [comment]
Mmmm, I'm using codekit app, and it users bower, not npm

**Comment by atomiks** [comment]
Bower recommends using npm for nearly 2 years now. Is there no way to download an npm package using codekit?

**Comment by stratboy** [comment]
:) I'm using direct npm for now. Thank you. And No, codekit still is under bower :) I'll write to Bryan.

**Comment by atomiks** [comment]
Great!

**Comment by JPustkuchen** [comment]
This could be easily solved by automation on Github now using releases and would make life of developers a lot easier in cases where you just need the dists!

Could you perhaps reopen the issue?

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository
