### ISSUE TITLE
`html` is not a valid option

### ISSUE THREAD

**Issue by bojanvidanovic** [atomiks/tippyjs#312]
Following the documentation [here](https://atomiks.github.io/tippyjs/v2/index.html#creating-html-templates), I'm trying to clone HTML template (method 1), but I'm constantly getting an error:
`Error: [tippy]: `html` is not a valid option`

Am I missing something?

**Comment by atomiks** [comment]
Those are the v2 (old) docs. Can I ask how you got there but are using v3 files because I noticed it makes up ~10% of the traffic. I think I will add a header at the top to notify users of the new version.

**Comment by bojanvidanovic** [comment]
Oh ok, I have no idea how I ended up on old docs without even noticing. I agree a small banner could notify the users. Anyway thank you.

**Comment by atomiks** [comment]
Added a notice..
