### ISSUE TITLE
tippy v2: use parent element as reference point.

### ISSUE THREAD

**Issue by sethwilsonUS** [atomiks/tippyjs#313]
Hello!

I'm using tippy v2 at the moment, though I'd like to refactor to v3. I've got a series of `<p>` paragraph elements, and some `<span` elements within those paragraphs as tooltips. However, I'd like the tooltip to appear to the right of the `<p>` element, not the `<span>`. I've looked into event delegation but I'm not exactly sure if this is what I want.

Thanks for your help.

**Comment by atomiks** [comment]
There is no automatic way to do it, but you can use `<p>` as the reference and manually add listeners to the `<span>`s

```js
const tip = tippy.one(p, { trigger: 'manual' })

const showEvents = ['mouseenter', 'focus']
const hideEvents = ['mouseleave', 'blur'] // IE should be `focusout` I believe
showEvents.forEach(e => {
  spans.forEach(span => {
    span.addEventListener(e, () => tip.show())
  })
})
hideEvents.forEach(e => {
  spans.forEach(span => {
    span.addEventListener(e, () => tip.hide())
  })
})
```

**Comment by sethwilsonUS** [comment]
So helpful. Thanks so much!
