### ISSUE TITLE
Delay + follow cursor (+placement) still makes the tippy "jump"

### ISSUE THREAD

**Issue by kfir124** [atomiks/tippyjs#314]
Newest Tippyjs: 3.0.3

Settings:
```     
{
        delay: [800, 20],
        placement: "bottom",
        arrow: false,
        followCursor: true,
        distance: 10,
        duration: [0, 0],
        content:'test',
      }
```
It is not 100% reproducible, which means in some cases the tippy will be created normally and in some other cases it will jump from the top part of the element to the bottom very fast.

It seems to me that the tooltip is created with one position in mind and then quickly goes to the mouse location, it is way more noticeable with `top/bottom` than `right/left` although it still happens with `right/left`

It also happens with `flip: false`

It may be related to this solved issue: https://github.com/atomiks/tippyjs/issues/140

**How to reproduce:**
*You must have a start delay of at least 500 ms
It seems to happen if you hover fast enough into the element and then wait the delay, so if you moved slowly into the element it will probably won't happen.
If you moved the mouse fast enough into the element it is very likely to happen (feels like the mouse has inertia on the tooltip)
It is **random** though

**Comment by atomiks** [comment]
I'm able to reproduce 100% of the time on Firefox.

However if I use `duration: 1` it doesn't occur, and is basically the same instant duration effect

**Comment by kfir124** [comment]
Hmm Interesting, I only tried in Chrome, I tried with `duration: 1` as well now and still encountered it (may be browser related)

**Comment by atomiks** [comment]
It happened once out of like 50 for me on Chrome 😝 

With `duration: 1` I haven't seen it once in Chrome and I've hovered dozens of times.. 🤔

**Comment by kfir124** [comment]
I feared that reporting it would make someone hover over buttons way too many times 😄 it may be addicting after a while!

It is interesting point, maybe bigger elements give you more room to have "inertia" with your mouse, very illusive this one! although it is mainly just triggering OCD 😝

**Comment by atomiks** [comment]
It's much less noticeable and not jumpy if it has the normal transition duration, which probably explains why I didn't catch this.. 😞

**Comment by kfir124** [comment]
Thanks for the quick reply and the great library!

Your PR seems to work 😄

**Comment by atomiks** [comment]
> EDIT: I wonder how did you find out what is bugging it?

The virtual reference gets positioned near the mouse cursor with Popper.js' `.scheduleUpdate()` method which defers the update to the next animation frame, but the tooltip's visibility state gets toggled first (the code is run synchronously after). The tooltip becomes visible on the next animation frame but the position update is sometimes deferred until the following animation frame which explains the 1 frame jump. The randomness due to the animation frame request depends on what the browser is doing, I think.

The refactored code in the PR (latest commit) ensures the position update happens first before the tooltip becomes visible.

**Comment by kfir124** [comment]
> > EDIT: I wonder how did you find out what is bugging it?
> 
> The virtual reference gets positioned near the mouse cursor with Popper.js' `.scheduleUpdate()` method which defers the update to the next animation frame, but the tooltip's visibility state gets toggled first (the code is run synchronously after). The tooltip becomes visible on the next animation frame but the position update is sometimes deferred until the following animation frame which explains the 1 frame jump. The randomness due to the animation frame request depends on what the browser is doing, I think.
> 
> The refactored code in the PR (latest commit) ensures the position update happens first before the tooltip becomes visible.

Thanks for the explanation and the fix 👍

**Comment by atomiks** [comment]
3.0.5
