### ISSUE TITLE
Gap when using distance: 0 on Chrome

### ISSUE THREAD

**Issue by Arkellys** [atomiks/tippyjs#316]
I came accross this bug while implementing the new Tippy version (which is amazing btw). I don't think that is it related to the version, though I have not tested with the V2.

![gap](http://image.noelshack.com/fichiers/2018/41/2/1539108553-tippybug.jpg)

The bug occurs only with the following settings :

- Browser : Chrome *(it's working fine on Firefox, not tested on Edge or IE)*
- The screen Display Size is > 100% *(on Windows, I can't test on macOS)*
- A `font-size` (or `line-height`) is set in the CSS *(removing these lines fix the problem)*

The tippy setting is simply : `{ distance: 0 }`

[Here is the Codepen to see the issue.](https://codepen.io/anon/pen/ePgXzJ)

I noticed that the gap is not always 1px, it sometimes looks smaller depending on the values in the CSS. And using the browser's zoom remove the gap. I am not sure that something can be done about it since it seems to come from the Display Size settings. Any idea ?

**Comment by Arkellys** [comment]
Oh oops sorry. I tried the new params but it doesn't work either.

Yes, I was thinking about a way to hide the overlapping if I use `distance -1` since my element and the tooltip don't have the same `background-color`. Adding a `border-top` on my tooltip with the element's `background-color` does the trick so I will go with that. :)

Thank you for your help ! Should we close this issue ?

**Comment by atomiks** [comment]
> Adding a border-top on my tooltip with the element's background-color does the trick so I will go with that. :)

That's a nice little hack 😉 

> Thank you for your help ! Should we close this issue ?

Since it's device + browser-related combination issue that doesn't seem fixable, & since positioning is controlled by Popper.js, I think so.
