### ISSUE TITLE
.setContent() resets tippy position when followCursor:true

### ISSUE THREAD

**Issue by NilsEnevoldsen** [atomiks/tippyjs#317]
Expected: Tippy says glued to cursor.

Actual: Whenever `.setContent()` is called, tippy position is reset to default position until cursor is moved.

Tested with v3.0.5.

https://codepen.io/anon/pen/NOpYBZ

**Comment by atomiks** [comment]
I think we need a whitelist of options that affect the `popperInstance` so we can only destroy it when necessary. I avoided that due to increased size but it will probably be necessary.

**Comment by atomiks** [comment]
3.0.6
