### ISSUE TITLE
Use Popper.js for the followCursor behavior

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#32]
Right now you have some custom logic:

https://github.com/atomiks/tippyjs/blob/master/src/js/tippy.js#L318

But you may simply use Popper.js passing an object with the mouse coordinates instead of a DOM node.

https://popper.js.org/popper-documentation.html#referenceObject

Doing so, you would get all the functionalities provided by Popper.js for free.

**Comment by atomiks** [comment]
Wasn't aware, thanks

Can you give an example of how to use it? It doesn't seem clear from the docs.

**Comment by FezVrasta** [comment]
Here it is
https://codepen.io/FezVrasta/pen/evoMrR?editors=1010

**Comment by FezVrasta** [comment]
You can find a working demo here:
https://codepen.io/FezVrasta/pen/bWezaY

**Comment by atomiks** [comment]
Appreciate the example! I just realized `pageY` is better than `clientY` (works with pinch-to-zoom in Chrome) and no need to get the offset

**Comment by atomiks** [comment]
After experimenting with this for a while I think it causes too many unwanted "glitches", at least in relation to how tooltips function in this library... going to put this off for now

**Comment by FezVrasta** [comment]
What kind of glitches? I'd like to investigate them

**Comment by atomiks** [comment]
It's not really Popper's fault, it's just the way follow cursor works... like it flips and causes the tooltip to hide because the cursor lands on the tooltip rather than the element, etc. The main benefit I saw was that it no longer caused the body to overflow (stuck within the viewport) although that kind of presented its own issues depending on how far away the element was from the edges...

**Comment by FezVrasta** [comment]
Does it happens even with you disable the flip modifier?

**Comment by atomiks** [comment]
I've implemented some basic viewport overflow prevention for v0.12.1 so I don't really think I need this now

**Comment by atomiks** [comment]
Hi @FezVrasta I was going to try and implement this again due to #188, but if the page can be scrolled the positioning becomes incorrect.

https://codepen.io/atomiks/pen/vRBMBE

(scroll down a bit and move the mouse)

**Comment by ivansieder** [comment]
Hij @FezVrasta, I have implemented this for v-tooltip (using popper.js), which has NOT been merged yet and by tweaking it a bit it works out pretty well, even with scrolling on pages!

https://github.com/Akryum/v-tooltip/issues/63
https://github.com/Akryum/v-tooltip/pull/143

Hit me up, if it's of interest also for popper.js.

**Comment by FezVrasta** [comment]
Cool, no I don't have any necessity, it as just a suggestion to have a better implementation here.

**Comment by atomiks** [comment]
FYI I switched to Popper.js for `followCursor` a couple days after I made that last comment, the change shortened the code a lot as well.

**Comment by FezVrasta** [comment]
Popper.js handles exclusively the positioning logic, everything else is deferred to other libraries such as Tippy
