### ISSUE TITLE
Event delegation doesn't work if "content" option is not set

### ISSUE THREAD

**Issue by sqal** [atomiks/tippyjs#321]
Hi. I would like to report a small bug in the library. Please take a look at simple reproduction:  https://jsfiddle.net/kjsdrvm3/. As you can see I use `target` option here for event delegation and everything everything seems to work properly, unless you remove option `content`, then tooltips don't show up. I think this is a bug because why do I have to set this option since I tooltip's content is retrieved from `data-tippy-content` attribute? 

And one more thing I would like to ask. v3 deprecated `dynamicTitle` option which was very useful to me in some cases. For example. I have a list with many tooltips, that can re-render very often so of course tooltip's content also can change during the update. It's not writtten in any JS framework, it's simple list where I use `innerHTML` to set a new content. In order to optimize performance a little bit, I use event delegation in tippy, but in order to have correct tooltip's content I use this hack in onShow callback which you can see in my reproduction. What I wanted to ask is if we can do it (dynamicTitle) easily somehow? Would you consider making `content` option a function that receives reference element? Then we smply use it like this:

```content: ref => ref.getAttribute('data-tippy-content')```

**Comment by atomiks** [comment]
I believe the `content` option must be specified so it can be shared between the children as "fallback" content.

> `content: ref => ref.getAttribute('data-tippy-content')`

This does work, just not with event delegation right now... 🤔

**Comment by sherzinger** [comment]
Curious about this as well. (Funnily enough I was the one who asked for the dynamicTitle option)

content does not replace this functionality in its current state:
`content: ref => ref.getAttribute('title')` will get the title attribute only once and ignore any changes to it. 

I'm stuck to 2.x for now

**Comment by atomiks** [comment]
Do you think there should be a `dynamicAttributes` option to solve this? I think that would help people using Angular etc, who rely on the DOM attributes instead of the actual JS instance.

**Comment by sherzinger** [comment]
@atomiks sorry for the late answer, I was gone for lunch.
Yes that's **exactly** why I was asking for this feature.
It's not impossible to update the title as you've demonstrated, but it adds unnecessary overhead for some people. (at least it does for me)

E.g. in my code the title is simply bound to the data model. The framework handles updating the title. Without `dynamicTitle` I have to add a onUpdate listener and write code to manage this update myself, in order for the tooltip to update.

**Comment by sherzinger** [comment]
Regarding your code solution above: Wouldn't that impact performance, especially when having many thousand elements? 
IIRC dynamicTitle only updated 'onShow', hence was very performant. Having several thousand Mutation Observers listen to every single change, whether they are being displayed or not, doesn't seem like a good idea.

**Comment by atomiks** [comment]
V2 used an individual one for each instance. Updating it onShow could work though (actually I'm pretty sure that was the original technique, but had to be changed for some reason)

**Comment by sherzinger** [comment]
@atomiks Following your advice from earlier this works for me with v3: https://git-r3lab.uni.lu/Fractalis/fractal.js/blob/master/src/vue/directives/tooltip.js

(s. update hook)

**Comment by atomiks** [comment]
I think that's recommended anyway. Each view library/framework should have its own wrapper around the vanilla library, rather than relying on DOM attribute changes.
