### ISSUE TITLE
tippy does not work in Firefox, MYBB

### ISSUE THREAD

**Issue by KeteTheme** [atomiks/tippyjs#322]
Hi, I have a problem. I am using your lib in the MYBB forum system, in which it works perfectly in Google Chrome, but in Firefox latest version or (the newest version). It does not work for me but the weirdest thing is that it creates a tippy theme and it works for me, I leave images.

**In google chrome, data-tippy**

![1](https://user-images.githubusercontent.com/37380981/46909646-c9113600-cf03-11e8-8a19-7cdec4ad1a1b.png)

**In Firefox, data-tippy**

![2](https://user-images.githubusercontent.com/37380981/46909687-8d2aa080-cf04-11e8-8127-9e0b3f9684cc.png)

**In Firefox, advanced JS, new tippy theme**

![3](https://user-images.githubusercontent.com/37380981/46909713-f6121880-cf04-11e8-9c23-49d5c4f0cd8a.png)
-----
That's why it's weird, because the tippy works in js. I mean, because it works in FIREFOX with this:

```
<style>
	.tippy-tooltip.New-theme {
		background-color: #ea8c00;
		max-width:800px;
	}
	
	.tippy-popper[x-placement^='right'] .tippy-tooltip.New-theme .tippy-arrow {
		  border-right: 8px solid #ea8c00;
		  border-top: 8px solid transparent;
		  border-bottom: 8px solid transparent;
	}
</style>


<script>
	tippy('.tooltip8k', {
	content: "{$forum['description']}",
  	delay: 100,
  	arrow: true,
  	arrowType: 'sharp',
  	size: 'small',
  	duration: 500,
  	placement: 'right',
	theme: 'New'

})
</script>

```

I really do not know why it does not work. I have entered its official site in firefox and it works for me, I also enter the codepen in firefox and it also works for me. Is there something that interferes? I comment for the second time I am using the MYBB forum system. Thanks and regards.

**Comment by atomiks** [comment]
Make sure the `tippy.js` script placed at the bottom of the page? And that the elements exist on the page server-rendered. Otherwise you'll need to use the function.

**Comment by atomiks** [comment]
You don't need the stylesheet if you're using `tippy.all.min.js`. If you're leaving it in `<head>` add a `defer` attribute:

```html
<script src="https://unpkg.com/tippy.js@3.0.6/dist/tippy.all.min.js" defer></script>
```

**Comment by KeteTheme** [comment]
Hello, thanks, now it works but I have a problem, I have a part that has a new theme (tippy) and that does not work, in the google console gives error

```
<script>
	tippy('.tooltip8k', {
	content: "{$forum['description']}",
  	delay: 100,
  	arrow: true,
  	arrowType: 'sharp',
  	size: 'small',
  	duration: 500,
  	placement: 'right',
	theme: 'New'

})
</script>
```

**Comment by atomiks** [comment]
Make sure that script is placed after the CDN script. It would be lowercase `tippy` though?

**Comment by atomiks** [comment]
If you have an inline script, you will need to move the CDN script to the bottom of the `<body>` _before_ that inline script, instead of using a `defer` attribute in `<head>`.  The error should say lowercase `tippy` though..

**Comment by KeteTheme** [comment]
yes is tippy, that is to say in lowecase.  Thanks, now it works for me, thanks for tippy! Greetings brother from Venezuela!
