### ISSUE TITLE
V3 : How to clone a HTML template and hide it from the DOM ?

### ISSUE THREAD

**Issue by Arkellys** [atomiks/tippyjs#325]
Hello !

On Tippy V2, it was possible to make a reusable HTML template by using `html: '#templateId'` or `html: () => templateId.cloneNode(true)`, and then hidding the original element with `display: none;`

When I am trying to do the same on V3, this time using the `content` option, **it seems that hidding the template `div` with `display: none;` also hides the tooltip's content.**

I am just trying to have several elements with the same tooltip content. [Here is a Codepen example](https://codepen.io/anon/pen/qJxVYy)

Is it a bug ? How can I achieve that knowing that I cannot use `Event delegation` because my elements do not share the same parent ?

Thank you.

**Comment by atomiks** [comment]
In V2 the string just used the template's innerHTML so you can do that if you want:

```js
tippy('.btn', {
  content: document.querySelector('#myTemplate').innerHTML
})
```

**Comment by Arkellys** [comment]
Oh well, I have to admit that I haven't thought about this option ahah.
Thank you @atomiks :)
