### ISSUE TITLE
IE11 not working

### ISSUE THREAD

**Issue by RitaDias** [atomiks/tippyjs#326]
Hey guys,
I was doing some tests on a page and when I went to test it out on IE11, I noticed that it wasn't working. Thought it might have been my code that was wrong so I decided to test with [the tippy page itself](https://atomiks.github.io/tippyjs/) and it's still not working.

From what I read on the documentation this is meant to work on IE11 and doesn't need a polyfil unless you are using a SVG element for a reference (which I'm not). Did I miss something? Did I need to add another script to make it work on IE11? 

(btw I can't even open the template codepen on IE11)

**Comment by RitaDias** [comment]
Hey @atomiks 
Here's a [fiddle](https://jsfiddle.net/vkzxpb1t/) with an example of it not working, when loading on IE11 the content is shown and the tippy doesn't work. There's no errors on the console.

The JavaScript that I'm using is the one from the tippy.js that you can get from the npm package and the CSS is the CSS + Light.theme (which I'm currently not using for this example's sake)

Thanks for the quick reply

**Comment by atomiks** [comment]
It's this:

```js
appendTo(ref) {
  return ref.parentNode
}
```

This is ES6 syntax which IE11 doesn't support. The docs make use of ES6+ syntax heavily and it's assumed you're using Babel to transpile it into ES5 for full support.

ES5 for IE11:

```js
appendTo: function (ref) {
  return ref.parentNode
}
```

_I should add a note to the docs about this_ 🤕
