### ISSUE TITLE
Sourcemaps in dist files

### ISSUE THREAD

**Issue by apriljunge** [atomiks/tippyjs#327]
Is there any reason why the tippy js dist files are delivered with source maps in it?

In our use case we bundle tippy with webpack. The sourceMappingUrl comment at the end of each file remains. Safari tries to load this source map, but can't find it, because it is not part of the bundle.
Can you remove this source maps? Or is there a real use case to have source maps in production?

**Comment by atomiks** [comment]
The source maps are generated by Rollup, exact same as Popper.js: https://unpkg.com/popper.js@1.14.4/dist/

See https://github.com/FezVrasta/popper.js/issues/426

**Comment by apriljunge** [comment]
Okay, that's one solution to avoid this problem.

Nevertheless i do not understand _why_ it does behave like this?
Why should someone need source maps in production? Wouldn't it make sense to configure Rollup in a way that in production mode source maps are not generated?

**Comment by atomiks** [comment]
I'm not sure what you mean by "production mode", the source maps are generated with the dist files for debugging purposes, for example when using the CDN minified file if an error occurs somewhere in the Tippy source runtime, you can see where it happened more clearly. Especially since there are very few warnings throughout the lib to conserve size.

**Comment by vukvukovich** [comment]
@atomiks I am getting:
```
DevTools failed to parse SourceMap: webpack:///node_modules/tippy.js/esm/index.all.js.map
DevTools failed to parse SourceMap: webpack:///node_modules/popper.js/dist/esm/popper.js.map
```
It looks like URL is wrong. I am not sure if this should be corrected in package or..?

**Comment by atomiks** [comment]
The sourcemaps are most likely correct since they're generated by Rollup, you probably have a problem with your webpack config, especially since no one else has filed an issue about this for over a year

**Comment by vukvukovich** [comment]
> The sourcemaps are most likely correct since they're generated by Rollup, you probably have a problem with your webpack config, especially since no one else has filed an issue about this for over a year

Sure, I'll debug it, thanks for the info. Info would be enough to isolate the problem. Cheers!

**Comment by vukvukovich** [comment]
Didn't noticed `exclude: /node_modules/` was set in webpack config. Removing it from rules fixed the issue. 

Just in case someone else encounters the same. :)

**Comment by catamphetamine** [comment]
@vukvukovich Where exactly did you remove `exclude: /node_modules/` in Webpack config?
