### ISSUE TITLE
ClipboardJS inside of a tippy stopped working in 3.0.3

### ISSUE THREAD

**Issue by wodim** [atomiks/tippyjs#328]
3.0.2: https://codepen.io/anon/pen/WaJvwM
3.0.3: https://codepen.io/anon/pen/oadXLX

It's exactly the same code but it stopped working in 3.0.3.

**Comment by atomiks** [comment]
It appears that clipboardJS is blurring the tooltip in some fashion. Probably part of the trick to copy to the clipboard?

In v3.0.3 click-triggered tooltips also receive focus compared to v3.0.2.

You can add this option as a hack:

```js
shouldPopperHideOnBlur: () => setTimeout(tip.hide)
```
