### ISSUE TITLE
TypeError when using html template element

### ISSUE THREAD

**Issue by mathieucivel** [atomiks/tippyjs#33]
Hello,

I use Webpack 2 to import Tippy, just with an alias: 

```js
resolve: {
    alias: {
      'tippy$': 'tippy.js/dist/tippy.js',
    }
}
```

Then when creating a new Tippy instance:

```js
import Tippy from 'tippy.js'
//...
new Tippy('.test', {
    html : document.querySelector('#test')  //It works fine with just the selector '#test'
})
```

I got the following error:

```shell
TypeError: Converting circular structure to JSON
    at Object.stringify (<anonymous>)
    at Tippy._applyIndividualSettings (webpack:///./~/tippy.js/dist/tippy.js?:2653:47)
```

It seems the HTMLElement is passed through the `JSON.stringify` method.

I have doubts on my way to import Tippy with webpack, but I'm running out of things to try..

**Comment by atomiks** [comment]
That error occurs when it tries to stringify itself: http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json

So I guess `.test` is the same element as `#test`?

**Comment by mathieucivel** [comment]
Well no, I added '.test' for the example but it was in fact a selector in a variable. Sorry I can't easily produce something for you to see the issue. Feel free to close this one :)

**Comment by atomiks** [comment]
For a second I was wondering how stringify handled HTML Elements being passed through, but it seems to work without errors here: https://codepen.io/anon/pen/aWmEZL

**Comment by mathieucivel** [comment]
Yes I started to test this way, that's why I have doubts with my webpack config. I just can't find why. I tried to export/expose Tippy as a global, but with the same result (a string with the selector works, but not an element).

**Comment by atomiks** [comment]
Can you paste the full code here?

...And I just noticed from that pen that if a tooltip is flipped, clicking on it causes glitchy behavior instead of a smooth hide... more fixes to come

**Comment by atomiks** [comment]
I've switched to using `Object.assign` to clone the individual settings now since a deep copy isn't needed (popperOptions can't be defined in the HTML), maybe it will work now.

Check v0.8.2: https://github.com/atomiks/tippyjs/releases/tag/v0.8.2

**Comment by mathieucivel** [comment]
Sorry I can't paste the code, so I made a new webpack projet. I can't reproduce the bug tough.. I'll try your last version thanks.

**Comment by atomiks** [comment]
Any luck?

**Comment by mathieucivel** [comment]
Well it works for me now :) Thank you.
