### ISSUE TITLE
Adding padding/margin, setting height and scrollbar

### ISSUE THREAD

**Issue by leenasn** [atomiks/tippyjs#332]
Hi,

Thank you for the plugin, it made it easier to show tooltip across different devices and platforms.

I would like to know how can I change the style of the tooltip to add:

* Adding margin/padding
* Setting a fixed height along with a vertical scrollbar

I tried setting the style through popper-options, but was not able to make it work. Can you let me know?

Here is the screenshot of the tooltip that I've. The tip is little too long, so prefer to add the margin and scrollbar especially on mobile devices.

https://trello-attachments.s3.amazonaws.com/5b6442c9143a0614ad2b97bc/5bb6f547b4d9f326cad0268e/b564e6ad3a21dfaeebe6445fb98bf902/AirPortExtra_and_Item-0_and_statusBarItem_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_AppleBluetoothExtra.png 

Thanks once again,
Leena

**Comment by atomiks** [comment]
You can style the tooltip in a custom way using a theme. https://codepen.io/atomiks/pen/BqPVPp

**Comment by leenasn** [comment]
Thank you. That solved the issue. 

I missed the [theme section](https://atomiks.github.io/tippyjs/#creating-custom-themes) in the docs.
