### ISSUE TITLE
Hitting ESC on nested dropdown throws console error

### ISSUE THREAD

**Issue by vitality82** [atomiks/tippyjs#333]
I have 10 dynamic tippies with nested tippies as well. All the references and menus have unique identifiers. Everything works great, there is not visible bug except for the dev console throwing an error:

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'isVisible' of undefined.

This is reproducible in one of the examples on the main [website](https://atomiks.github.io/tippyjs/) too: In the "Misc" section click on the Dropdown nesting example. Now hit ESC while the console is open.

Browser used: Chrome V69

**Comment by atomiks** [comment]
I can't reproduce it. There are zero key listeners in the whole library so it doesn't make sense. You might have a browser extension causing a problem. Can you reproduce it in incognito mode?

**Comment by vitality82** [comment]
My bad, it was caused by an extension. 
Sorry for the false alarm.
