### ISSUE TITLE
Allow custom props in options object.

### ISSUE THREAD

**Issue by Teebo** [atomiks/tippyjs#334]
In the previous versions of tippy.js we was able to pass custom props to the configuration object of a tippy.
like 
`tippy(ref, {
  name: 'MyTippy' // custom prop
})`

With the latest version, an error is thrown, the `name` prop `is not a valid type`.

**Comment by atomiks** [comment]
How were you using that?

**Comment by Teebo** [comment]
I am using some state management library for web applications.

I was using the custom prop like name to register the tippy instances with the state of an app. I thought of a work around though, but if you can remove the typings on the options object or allow custom props that would be nice.

**Comment by atomiks** [comment]
I don't think it's necessary, because you can create your own wrapper function to handle this, like attaching a `name` property to the instance instead of it getting stored in the props object.

**Comment by Teebo** [comment]
Thank you.
