### ISSUE TITLE
Is it possible to have an input field included in the tooltip?

### ISSUE THREAD

**Issue by stimilon** [atomiks/tippyjs#342]
I simply use Tippy capability to have an input field included in the tooltip. Everything works fine, except that it is impossible to write anything in the input field. Is it possible to do it? How?

Here is my code:
https://codepen.io/xaviermarichal/pen/ZqNopB
where one can see that the input field in the tooltip does lack all interactive capabilities...
BRs,
Xavier

**Comment by Eldair** [comment]
You have to set `interactive: true` option

**Comment by atomiks** [comment]
@Eldair answered it, thank you!
