### ISSUE TITLE
Adding tooltip to <area> in <map> applied to image puts the tooltip above the image instead of above the <area>

### ISSUE THREAD

**Issue by Actualization** [atomiks/tippyjs#343]
Adding tooltip to HTML area in HTML map element applied to image puts the tooltip above the image instead of above the HTML area element.

Codepen example (mousing over center of img displays a tooltip beside the img): https://codepen.io/Act-tion/pen/RemvLr

Showing on area position allows for multiple tooltips on one img.

**Comment by atomiks** [comment]
I can't see anything in the CodePen, it's just a blank page
