### ISSUE TITLE
non-passive event listener warning

### ISSUE THREAD

**Issue by apptaro** [atomiks/tippyjs#344]
we should use passive event listener for touchstart. currently chrome shows the warning:

```
tippy.standalone.js:1409 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. 
Consider marking event handler as 'passive' to make the page more responsive.

```

**Comment by atomiks** [comment]
Passive detection support would add some bloat I think, once a single event is fired there's only a single `if` branch checking a boolean value before an early return which would be virtually instant per event. The warning is not ideal though, although I haven't seen it before...

**Comment by rtvv** [comment]
@atomiks 

I have the same warning now
"@tippy.js/react": "^1.1.1",
"tippy.js": "^3.4.0",

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by atomiks** [comment]
`touchstart` is passive now so i don't know how that's possible

**Comment by rtvv** [comment]
It links me this line in console:
 ```
 /**
   * Adds an event listener to the reference
   */
  function on(eventType, handler, acc) {
    tip.reference.addEventListener(eventType, handler);
    acc.push({ eventType: eventType, handler: handler });
  }
```

**Comment by rtvv** [comment]
@atomiks maybe we should pass and passive object as 3-rd arg. here?
`tip.reference.addEventListener(eventType, handler);`

**Comment by atomiks** [comment]
ah I forgot about that `touchstart` 😞 , so you're using `touchHold: true`? Will need to add it there

**Comment by rtvv** [comment]
Yep.

**Comment by tettusud** [comment]
@atomiks I still get this warning in chrome console, any idea? am importing it from tippy.esm.js.
