### ISSUE TITLE
Where can I find the Tippy settings for "HTML Templates" in the docs?

### ISSUE THREAD

**Issue by awcchungster** [atomiks/tippyjs#345]
I've been trying to dig around, but the JS docs are super hard to read. 

Looking to see all the settings for the section around "Tooltips can contain HTML, allowing you to craft awesome interactive popovers.".

**Comment by awcchungster** [comment]
I think it would help for each example, if you listed the options/styling you used for that instance. The other option is just make the source easy to read for the doc page. 

To answer my question though, could you list out the tippy settings for the HTML template example? Specifically curious how you make the tooltip remain when the mouse leaves the button (probably interactive), how it uses the light theme, and how the tooltip can be top or bottom dynamically.

**Comment by atomiks** [comment]
That's a great idea, I'll see how I can add it in 😃

**Comment by awcchungster** [comment]
could you list out the tippy settings for the HTML template example please? How the tooltip can be top or bottom dynamically, and I’ll close this specific issue.

**Comment by atomiks** [comment]
Sorry I misread the last part of your comment.

The settings are basically:

```js
tippy(ref, {
  // Use an HTML element for the content
  content: document.querySelector('template'),
  // Allow it to be hovered over/clicked without hiding
  interactive: true,
  // Light theme is included in `dist/themes/light.css`, you need to import it
  theme: 'light'
})
```

The top/bottom flipping behavior is the default behavior.
