### ISSUE TITLE
HTML content with image issue

### ISSUE THREAD

**Issue by EpocDotFr** [atomiks/tippyjs#348]
Hello!

I have a tippy instance that fetches its content using Ajax before the tooltip is shown. That content is HTML (styled using CSS) plus an image. Everything is working fine, except the tooltip's width that is wrong, as you can see in this image:

![image](https://user-images.githubusercontent.com/2053431/48203514-fcf74400-e367-11e8-8963-dfec3a4e492d.png)

Its final width is lower than the maximum allowed (which should be reached), which is 350px. I suspect the image not to be taken into account when tippy is computing the tooltip width, **however** the image contained in the tooltip (the eagle) has `width` and `height` attributes, both set to `64`.

What am I doing wrong? Any help is appreciated! 👍

**Comment by atomiks** [comment]
The tooltip width is just CSS controlled by the browser. The tooltip has a `max-width` property. You might need to set the tooltip's `width` explicitly to `350px` with your custom theme.

```css
.tippy-tooltip.my-theme {
  width: 350px;
}
```

**Comment by EpocDotFr** [comment]
Thanks for your response!

I already tried to explicitly set the width of the tooltip: it's working fine, however when the tooltip's content width is shorter than 350px (e.g loading message), the tooltip is too large: it doesn't fit the content. How could I improve that?

**Comment by EpocDotFr** [comment]
I managed to fix my issue by explicitly setting the width of the columns in the tooltip content without touching the tooltip width.

Thanks!
