### ISSUE TITLE
Is it possible to conditionally render only the component?

### ISSUE THREAD

**Issue by SensationSama** [atomiks/tippyjs#350]
I'm using `tippyjs/react`. Sometimes I only wish to render my component, and not the tooltip as well. 

My solution seems like a bit of an anti-pattern:
```
{window.myVariable && <SomeComponent/>}
{!window.myVariable &&
<Tippy content={<div>hi</div>}>
    <SomeComponent/>
</Tippy>
}
```
I'm looking for something like an attribute I can attach to Tippy e.g. 
```
<Tippy showTip={!window.myVariable} content={<div>hi</div>}>
    <SomeComponent/>
</Tippy>
```

Thanks

**Comment by atomiks** [comment]
Yeah there's a few ways:

1. Conditional rendering as you're doing currently

```jsx
{window.myVariable ? (
  <SomeComponent />
) : (
  <Tippy content="Tooltip">
    <SomeComponent />
  </Tippy>
)}
```

2. Return `false` in `onShow` if you don't want to show it

```jsx
const onShow = () => !window.myVariable

<Tippy onShow={onShow}>
  <SomeComponent />
</Tippy>
```

3. Call `.enable()` / `.disable()` imperatively on the instance

_I think there should be React-specific props for this however_: like `isEnabled` which is part of the state object. Maybe `isVisible`, too

**Comment by KubaJastrz** [comment]
I think this is a good idea to have a component prop that, if specified, takes control over tooltip visibility and can be modified by providing custom `onShow`, `onHide` method callbacks.

**Comment by SensationSama** [comment]
Thanks!

**Comment by SensationSama** [comment]
Does anyone know why this no longer works after updating?
```
<Tippy onShow={onShow}>
  <SomeComponent />
</Tippy>
```
I just updated to
```
"@tippy.js/react": "^2.2.0",
"tippy.js": "^3.1.3",
```
I switched because I was experiencing this issue  `https://github.com/atomiks/tippyjs/issues/73`.

Updating also didn't appear to resolve that problem because `@tippyjs/react` package still is using `"rollup": "^1.1.2",` so the error persists.

**Comment by atomiks** [comment]
`@tippy.js/react@2` is dependent on `tippy.js@4` (v4 major)

**Comment by heavensloop** [comment]
> Yeah there's a few ways:
> 
> 1. Conditional rendering as you're doing currently
> 
> ```js-jsx
> {window.myVariable ? (
>   <SomeComponent />
> ) : (
>   <Tippy content="Tooltip">
>     <SomeComponent />
>   </Tippy>
> )}
> ```
> 
> 1. Return `false` in `onShow` if you don't want to show it
> 
> ```js-jsx
> const onShow = () => !window.myVariable
> 
> <Tippy onShow={onShow}>
>   <SomeComponent />
> </Tippy>
> ```
> 
> 1. Call `.enable()` / `.disable()` imperatively on the instance
> 
> _I think there should be React-specific props for this however_: like `isEnabled` which is part of the state object. Maybe `isVisible`, too

No. 1 is no longer working for tippy/react
