### ISSUE TITLE
Incorrect tooltip location for elements with 0 height if placement: 'bottom-start'

### ISSUE THREAD

**Issue by knstnt-dev** [atomiks/tippyjs#354]
Hello!

I am working with one text editor that producing elements with 0 height sometimes. It's actually an issue of this editor but it also produce strange behavior of tippy.

For example: if there is placement: 'bottom-start' in tippy config, then tooltip location is incorrect.
It's expected to be 'bottom-start' but it's located at the top of the page (please see details here https://codepen.io/anon/pen/ZmBorY).

Could you say is it possible to fix it using some default tippy settings or it is actually an issue?

**Comment by atomiks** [comment]
It would be a Popper.js issue, so maybe try making an issue over at their repo

**Comment by knstnt-dev** [comment]
Thanks @atomiks. I’ve created an issue at popper repo (https://github.com/FezVrasta/popper.js/issues/721)

**Comment by atomiks** [comment]
Since it's not related to Tippy specifically, I'm closing
