### ISSUE TITLE
Include SCSS files in release

### ISSUE THREAD

**Issue by davefmoore** [atomiks/tippyjs#355]
It would be awesome to have access to the scss files, ability to overwrite variables (ie colors) to match theme.

**Comment by nikolowry** [comment]
Somewhat off-topic, but injecting styles into the head as the first child produces the following W3C validation error: `Error: A charset attribute on a meta element found after the first 1024 bytes`.

It be great if we had the ability to disable rogue injections into the DOM

**Comment by atomiks** [comment]
@nikolowry this might work instead

```js
const firstStyleOrLinkElement = head.querySelector('style,link')

if (firstStyleOrLinkElement) {
  head.insertBefore(style, firstStyleOrLinkElement)
} else {
  head.appendChild(style)
}
```

**Comment by atomiks** [comment]
Don't think this is happening 🙈
