### ISSUE TITLE
Methods are not fired when outside triggering

### ISSUE THREAD

**Issue by fidelman** [atomiks/tippyjs#36]
Hello guys,
Thank you for your library, I like it so much and use it in every project with tooltips.

Now I've faced with the next issue:
If you set `click` triggering, so methods like `beforeHidden` are not fired if you click outside of the button. The version is v0.10.1, but it works at v0.5.0

How is it possible to fix?

You can see example here: https://jsfiddle.net/s6zcn7tx/

Thank you, looking forward to your answer

**Comment by atomiks** [comment]
Interesting... will take a look. Thanks for filing this issue

**Comment by atomiks** [comment]
Released fix in 0.10.2
