### ISSUE TITLE
How to contain tooltip inside the grid gutters in mobile?

### ISSUE THREAD

**Issue by geosenna** [atomiks/tippyjs#360]
I am trying to find a way to have my tooltip inside the gutter of my website in mobile?

Right now, even if the tooltip fit the viewport, it overlapse the right and left mobile gutters.

Is there any way to achieve this?

**Comment by KubaJastrz** [comment]
It's an option related to popper.js engine. I'm not able to test it right now, but you should be able to provide this "gutter padding" you're talking about in `popperOptions` parameter. More info here: https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.padding

**Comment by geosenna** [comment]
Thanks you very much, that was the think I was looking for. :)
