### ISSUE TITLE
Tippy.js V4

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#363]
Popper.js V2 is coming soon which will require Tippy to increment a major version. I believe the only outwardly facing breaking change for Tippy users is the fact that `data-placement` will be used instead of `x-placement` in selectors (and `x-out-of-bounds`). Themes will need to be updated.

The amazing part is it will only be like 3 kB apparently (down by over 50%) - **most likely the total size of Tippy will be around 11 kB** (including Popper.js and the CSS), reducing the size from 15 kB.

This is also a discussion for API changes you would like to see. I think V3 helped improve many areas, but since software is improving endlessly there are some changes we can make:

## Changes

1. ### Remove the idea of "collections" entirely, remove `tippy.one()`

The reason for the collection type is so a plain `tippy()` call always returns an object. I've seen other libraries return an array of the instances if there's more than one, or the instance itself if there's only one. However this can be unreliable if you're using a selector on some traditional pages because the number of elements can change, resulting in errors being thrown unless you check for the return type. I prefer the consistent return type. 

But there's one case we can be sure of: if you're passing a single Element. If that's the case, we can return the instance directly.

```js
tippy('string') // -> array of instances, even if only one was created
tippy(NodeList) // -> array of instances, even if only one was created
tippy(Element) // -> instance
```

2. ### Rename `performance` to `ignoreAttributes`

Actually describes what it's doing.

3. ### Remove `arrowTransform`

Bordered themes don't work with it, better to make the user define arrow transforms using a theme / CSS. Another benefit is we can remove the huge 0.5 kB gzipped worth of hackish regex parsing code to make this work dynamically.

4. ### Package

Avoid bundling in Popper.js. It made it "easier" to include a single script for beginners, but I think it should stay external even for the UMD / browser version. This will ensure people stay up to date.

To follow with Popper, maybe just rename the files to `index` as well.

I think it'll be something like this:
```html
<script src="https://unpkg.com/popper.js@2/dist/index.min.js"></script>
<script src="https://unpkg.com/tippy.js@4/dist/index.min.js"></script>
```

## More functional API to minimize file size

In an effort to continue adding needed features in core but keeping file size to a minimum, I suggest we move from the OOP/option-based API to a functional API. This way, tree-shaking can remove unused pieces of code, which isn't possible right now.

For example, to implement #81 in core, instead of:

```js
tippy(elements, {
  group: true
})
```

We export a function with this behavior:

```js
import tippy, { group } from 'tippy.js'

group(tippy(elements), {
  timeout: 500,
  delay: 1000
})
```

## Features

- What would everyone like to see?

**Comment by davidmerrique** [comment]
I've been using [`disconnected`](https://github.com/WebReflection/disconnected) in a few projects, maybe if you leverage this functionality, you'd be able to deprecate event delegation? 

Here's how I use it ([`regular-elements`](https://github.com/WebReflection/regular-elements) uses `disconnected`):

```javascript
import regularElements from 'regular-elements';
import tippy from 'tippy.js';

regularElements.define('[data-custom-tippy]', {
  onconnected() {
    tippy(this);
  },
  ondisconnected() {
    this._tippy.destroy();
  }
});
```

Now it doesn't matter when the
```html
<button data-custom-tippy data-tippy-content="I'm a tooltip!">Text</button>
```
is inserted into the DOM.

**Comment by atomiks** [comment]
Looks interesting, isn't that already possible using a `MutationObserver` on the body? Check for childList/subtree mutations and apply the tippy to the desired elements.

Event delegation has limitations as it currently stands, this would be a better solution if performance isn't a concern

```js
const toArray = value => [].slice.call(value)

const liveTippy = (match, options) => {
  const observer = new MutationObserver(mutations => {
    mutations.forEach(({ addedNodes, removedNodes }) => {
      toArray(addedNodes).forEach(node => {
        if (node.matches && node.matches(match) /* Element.prototype.matches needs polyfill */) {
          tippy(node, options)
        }
      })
      toArray(removedNodes).forEach(node => {
        if (node.className !== 'tippy-popper' && node._tippy) {
          node._tippy.destroy()
        }
      })
    })
  })

  observer.observe(document.body, { 
    childList: true, 
    subtree: true 
  })

  return () => observer.disconnect()
}

liveTippy('[data-custom-tippy]')
```

**Comment by davidmerrique** [comment]
@atomiks Yep, it's probably best left out of the library and up to the developer. Thanks!

**Comment by KubaJastrz** [comment]
@atomiks
I've seen you using `node._tippy.destroy()` pattern a lot. Maybe we can expose the `destroy` method to be used without accessing the "private" property object? Something like `tippy.destroy(node)`.
I haven't checked how it would look like in the code, but I think it should be fairly easy.

**Comment by atomiks** [comment]
@KubaJastrz The v0/v1 API was similar to that - it was dropped in favor of attaching the instance directly to the node for ease of use. The instance is actually public but it's prefixed with an underscore (not intended to convey privacy) since it's not a native property. The inspiration was taken from `flatpickr` (same with the lowercase factory function, etc)

**Comment by atomiks** [comment]
Seems like `popper.js` 2 has stalled development for now. I'd like to release this major to fix these problems...

I'll create a versioning system for the docs to keep v3 alive (v2 was killed in the move unfortunately, 💀RIP )

**Comment by atomiks** [comment]
v4 is out now! https://github.com/atomiks/tippyjs/releases/tag/v4.0.0
