### ISSUE TITLE
Dynamic HTML templates with multiple elements

### ISSUE THREAD

**Issue by AzukayFR** [atomiks/tippyjs#365]
Hello again ! You just closed the issue here https://github.com/atomiks/tippyjs/issues/364, but it still doesn't work... 
Look that when i add the .innerHTML parameter : [My website](http://foxgames.fr/aatrox/). 

You can try it :/

**Comment by atomiks** [comment]
You can still respond to closed issues.

It's working for me when I hover over the circle images

**Comment by AzukayFR** [comment]
It's working yes all tooltips are working, but the content is the same and he is show in the html page...

**Comment by atomiks** [comment]
The problem is you're selecting an element with the same ID for different reference elements but expecting a different template for each of them. You can only have 1 ID per page. 

See the bottom of this section: https://atomiks.github.io/tippyjs/#html-content

Use a `data-template` attribute to associate each one with a unique template. With this technique they won't be shown on the page also.

**Comment by AzukayFR** [comment]
Don't understand how to do that :/

**Comment by atomiks** [comment]
Add the attribute to the images with the `.prec_maitrise` class:

```html
<img class="prec_maitrise" src="http://foxgames.fr/wp-content/uploads/Masteries/CoupDeGrace.png" data-template="template1">
```

Then where you have the templates with the `presc_desc` id, change them to match the attribute's value with the necessary content:

```html
<div id="template1">
  content 
</div>
```

Then where you're calling `tippy`, use this (along with your other options):

```js
tippy('.prec_maitrise', {
  content: function (reference) {
    return document.getElementById(document.getAttribute('data-reference'))
  }
})
```

**Comment by atomiks** [comment]
Add the attribute to the images with the `.prec_maitrise` class:

```html
<img 
  class="prec_maitrise" 
  src="http://foxgames.fr/wp-content/uploads/Masteries/CoupDeGrace.png" 
  data-template="template1"
/>
```

Then where you have the templates with the `presc_desc` id, change them to match the attribute's value with the necessary content:

```html
<div id="template1">
  content 
</div>
```

Then where you're calling `tippy`, use this (along with your other options):

```js
tippy('.prec_maitrise', {
  content: function (reference) {
    return document.getElementById(reference.getAttribute('data-template'))
  }
})
```

**Comment by AzukayFR** [comment]
Well ! works ! Thanks man ! now i got a problem, but for myself x). I have to add more than 300 tooltips... Will be hard.. Thanks you so much !

**Comment by atomiks** [comment]
Glad I could help 💛
