### ISSUE TITLE
Hi, Is there any way to display the tooltip with an <a></a> link within it?

### ISSUE THREAD

**Issue by Noorprabh** [atomiks/tippyjs#366]
I am dynamically adding tooltips on an html page using Javascript. The javascript finds the required word and wraps the word in an A tag as follows:
< A tag> style= 'cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;' data-tippy-arrow='true' data-tippy-touch='true' href='#' class='tip'  data-tippy='" +  e.content +  "'>" +  e.key +
        "< A tag>"
Where e.content is the content to show within the tooltip and e.key is the word that gets the tooltip.
 However, there are a few instances in which e.content has the  e.key word which gets wrapped up in the < A tag> tag  as follows:
< A tag style= 'cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;' data-tippy-arrow='true' data-tippy-touch='true' href='#' class='tip'  data-tippy='Walter Hartwell White Sr., also known by his clandestine alias Heisenberg, is a fictional character and the main protagonist of Breaking Bad.helicopter < A tag style= 'cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;' data-tippy-arrow='true' data-tippy-touch='true' href='#' class='tip'  data-tippy='a person who qualified and holds a license to fly an aircraft'>pilot< /A tag>'>Walter</ A tag> 

 Here e.key is = Walter
and e.content = Walter Hartwell White Sr., also known by his clandestine alias Heisenberg, is a fictional character and the main protagonist of Breaking Bad.helicopter **pilot**

However, since pilot is also one of the words that is being searched it gets wrapped up in the tag aswell.(as shown)Now, when pilot gets wrapped up the tooltip automatically assumes that the > bracket is the closing bracket and hence, replaces the word in the html page as follows:
pilot'>Walter
and shows the tooltip on top of pilot. image attached.
![doubt](https://user-images.githubusercontent.com/41277598/48987071-8af86a80-f16f-11e8-9b7c-c20e4fee3425.PNG)

Is there any way to display the nested <a> tag? I don't want the tooltip to work on pilot but I want to display it without any errors in the tooltip.

**Comment by atomiks** [comment]
So your problem is that you have HTML inside the `data-tippy` attribute with quotes that aren't being escaped? Make sure you escape the quotation marks properly.

A quick solution is to use alternating quotation marks (outside = `"`, inside uses `'`)

```html
<a 
  href="#"
  class="tip"
  style="cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;" 
  data-tippy-arrow="true"
  data-tippy="Walter Hartwell White Sr., also known by his clandestine alias Heisenberg, is a fictional 
  character and the main protagonist of Breaking Bad.helicopter 
  <a 
    href='#'
    class='tip'
    style='cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;' 
    data-tippy-arrow='true' 
    data-tippy-touch='true'
    data-tippy='a person who qualified and holds a license to fly an aircraft'
  >
    pilot
  </a>'"
>
  Walter
</a>
```

For something like this I recommend using a template though, as the nesting is too difficult to read and type out.

```html
<a 
  href="#"
  class="tip"
  style="cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;" 
>
  Walter
</a>
<template id="tippy-template">
  Walter Hartwell White Sr., also known by his clandestine alias Heisenberg, is a fictional character 
  and the main protagonist of Breaking Bad.helicopter 
  <a 
    href='#'
    class='tip'
    style='cursor:help; border-bottom: 2px dotted black; color:inherit; text-decoration:none;' 
    data-tippy-arrow='true' 
    data-tippy-touch='true'
    data-tippy='a person who qualified and holds a license to fly an aircraft'
  >
    pilot
  </a>
</template>
```

(Note: use `div` instead of `template` if you need to support IE11)

```js
tippy('.tip', {
  arrow: true,
  content: document.getElementById('tippy-template')
})
```

See how to associate multiple different references with different HTML templates here: https://atomiks.github.io/tippyjs/#html-content

**Comment by Noorprabh** [comment]
Thank you, I'll try this.

**Comment by Noorprabh** [comment]
Thank you this worked beautifully.
See how to associate multiple different references with different HTML templates here: https://atomiks.github.io/tippyjs/#html-content
