### ISSUE TITLE
How can I add tippy.js in a javascript file?

### ISSUE THREAD

**Issue by Noorprabh** [atomiks/tippyjs#367]
Hi, 
I am working in a learning management system such as Canvas. I use Javascript files to update or modify existing content. I am currently injecting tippy.js from a javascript file through the following code:

 if(!document.getElementById('id1')) {
    var script = document.createElement('script');
    script.id = 'id1';
    script.src = 'https://unpkg.com/tippy.js@3/dist/tippy.all.min.js';
    document.body.appendChild(script);
}
 
However, the console throws the exception 'tippy not defined' (Since I'm using multiple instances of HTML). How can I add the tippy library within my Javascript so that I don't have to inject. Is there any other way to approach this issue?

**Comment by Egorvoz** [comment]
@Noorprabh hello - try this one approach 
https://stackoverflow.com/questions/13121948/dynamically-add-script-tag-with-src-that-may-include-document-write

It's too obvious but seems to me it will help you.
