### ISSUE TITLE
Support shifted properties, like bottom-start, top-end, as it made in popper.js

### ISSUE THREAD

**Issue by vladferix** [atomiks/tippyjs#37]
Currently shifted placement, like 'bottom-start', 'top-end' is actually working, but with several problems. 
1. I noticed that arrow is not showing, until I fix some css styles to match x-placement=bottom-start, etc
2. distance option is not working totally in this case

**Comment by atomiks** [comment]
Good point, I didn't consider those positions since they're not part of this library natively but you can extend the functionality...

The arrow CSS has this type of specificity:

```css
.tippy-popper[x-placement=bottom] .tippy-tooltip [x-arrow] {
    ....
}
```

so I'll need to add those other positions!

Can you show me your `popperOptions` settings object?

**Comment by vladferix** [comment]
That worked for me in css
`
.tippy-popper[x-placement^=bottom] .tippy-tooltip [x-arrow] {
    ....
}
`
My tippy options are the following:
` position: 'bottom-start',
   arrow: true,
   distance: -200
`

Distance didn't work

**Comment by atomiks** [comment]
> That worked for me in css
.tippy-popper[x-placement^=bottom] .tippy-tooltip [x-arrow] { .... }

Dude, I completely forgot about the `^=` thing, you just made my life way easier!

I can fix the distance thing easily. Thanks!

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/releases/tag/v0.11.0

**Comment by vladferix** [comment]
Dude, cool that it's so quick! 👍 Will check it now
