### ISSUE TITLE
Feature Request: followCursor once

### ISSUE THREAD

**Issue by dkulp2** [atomiks/tippyjs#373]
I would like the pop-up to appear near the cursor, but not follow it. In my situation, I have a pop-up associated with a row in a table that is the width of the screen. I'd like the pop-up to be near the mouse, but not jump around once it appears.

Maybe a new option 

followCursor: "initial"

or something like that. Thanks for a great little package!

**Comment by atomiks** [comment]
Shouldn't be too hard actually!
