### ISSUE TITLE
React data-tippy-content

### ISSUE THREAD

**Issue by BofEmptiness** [atomiks/tippyjs#375]
In docs sad: "The data-tippy attribute only works on initial page load. If you have dynamically generated elements or are using a view library/framework (React, Vue, Angular), use Method 2 below, using data-tippy-content instead of data-tippy."

Code example:
```
<button class="btn" data-tippy-content="Tooltip A">Text</button>
<button class="btn" data-tippy-content="Tooltip B">Text</button>
<button class="btn" data-tippy-content="Tooltip C">Text</button>
tippy('.btn')
```

But where to place all of this in react?

I've tryed this, pageYOffset is changing on scroll, but tooltip is not...
```
export default function Home() {
  const { pageYOffset } = useContext(someContext)
  tippy('.btn')

  return (
    <div>
      {pageYOffset}
      <button data-tippy-content={pageYOffset}>
        Text
      </button>
<div>
)
}
```

**Comment by atomiks** [comment]
Use the [@tippy.js/react](https://www.npmjs.com/package/@tippy.js/react) package

**Comment by BofEmptiness** [comment]
Oh, didn't see it, thanks!
