### ISSUE TITLE
tooltip outside boundary in a weird and complex layout after a breaking line

### ISSUE THREAD

**Issue by AndreKelling** [atomiks/tippyjs#377]
tippy version 3.3.0
chrome 70
----

https://codepen.io/AndreKelling/pen/rQgbWZ

----
In that codepen the first tooltip (the grey Info next to the red Text) is going outside the right boundary.
It also does not happens all the time, but most of the time. Depends on where the tooltip (grey info) is located on the window. It's not a 100% rebuild of what i got on my original website.

I guess I will find a solution by changing my layout CSS, because it's weird.
But just to let you know...

**Comment by atomiks** [comment]
It's because of the `overflow-y: scroll` rule. Popper.js's boundary setting by default will prevent the tooltip from overflowing its "scroll parent".

```js
tippy.setDefaults({
  popperOptions: {
    modifiers: {
      preventOverflow: {
        boundariesElement: 'window'
      }
    }
  }
})
```

Or to avoid setting it globally, you can add it as an attribute for each case:

```html
<span data-tippy-popperOptions='{"modifiers": {"preventOverflow": {"boundariesElement": "window"}}}'>
  content
</span>
```

**Comment by AndreKelling** [comment]
awesome! works superb.

I don't get `will prevent the tooltip from overflowing its "scroll parent".` as it's overflowing it's parent to the left side of it's parent, in the example.

**Comment by atomiks** [comment]
Actually yeah hmm that's kinda weird, not really sure?

**Comment by AndreKelling** [comment]
seems to be `viewport` doing it a bit better...

```
tippy.setDefaults({
  popperOptions: {
    modifiers: {
      preventOverflow: {
        boundariesElement: 'viewport'
      }
    }
  }
})
```

more: https://popper.js.org/popper-documentation.html#modifiers..preventOverflow.priority
