### ISSUE TITLE
Always Visible Tooltip

### ISSUE THREAD

**Issue by TheSayantan96** [atomiks/tippyjs#380]
How to achieve always visible tooltip using data attributes?

**Comment by atomiks** [comment]
This will work:

```html
<button
  data-tippy="Tooltip"
  data-tippy-showOnInit="true"
  data-tippy-hideOnClick="false"
  data-tippy-trigger="manual"
>
  text
</button>
```

Note: I've noticed [this transition bug](https://stackoverflow.com/questions/14389566/stop-css3-transition-from-firing-on-page-load) can cause problems with `showOnInit` on page load, among a few other things. The solutions posted in the link seem to work though.
