### ISSUE TITLE
hideAllPoppers not hiding all poppers, just the ones that has hideOnClick == true

### ISSUE THREAD

**Issue by Deses** [atomiks/tippyjs#382]
I have a question about the behavior of `hideAllPoppers`:

The docs say `Hides all visible poppers on the document` but in reality, it only hides those that have the prop `hideOnClick` set to true, contradicting the documentation...

Here's `hideAllPoppers` code:
```
/**
 * Hides all visible poppers on the document
 */
var hideAllPoppers = function hideAllPoppers(excludeTippy) {
  toArray$1(document.querySelectorAll(Selectors.POPPER)).forEach(function (popper) {
    var tip = popper._tippy;
    if (tip && tip.props.hideOnClick === true && (!excludeTippy || popper !== excludeTippy.popper)) {
      tip.hide();
    }
  });
};
```

Am I misunderstanding something about hideOnClick? I have it set to false because I don't want any tippy to go away when clicked, just when I programatically tell the tippy to `.hide()`.

**Comment by atomiks** [comment]
You can just use this:

```js
[...document.querySelectorAll('.tippy-popper')].forEach(popper => popper._tippy.hide())
```

`

**Comment by Deses** [comment]
Yes, I did something similar, but the method name and its description are not doing what they are saying they are doing...

I think the problem is more semantics than anything else, maybe that method should be called something else and do a new one that really hides all.

**Comment by atomiks** [comment]
Fixed in `v4` 😃
