### ISSUE TITLE
tippy not working for dynamic added DOM Elements

### ISSUE THREAD

**Issue by QJan84** [atomiks/tippyjs#384]
Hello,
i have some html like 
`<input class="js--tippy" data-tippy-content="Minimum series per unit" data-tippy-placement="bottom">` and javascript: 

```
          // Tooltip defaults
          tippy.setDefaults({
            a11y: false,
            delay: 0,
            arrow: true,
            arrowType: 'sharp',
            size: 'small',
            duration: 500,
            animation: 'shift-away'
          });
          // Select elements
          tippy('.js--tippy');
```
Now I clone the HTML with [cloneNode](https://developer.mozilla.org/de/docs/Web/API/Node/cloneNode) and add it to the DOM. Tippy does not work for the newly added items.

I have complied with the specifications, right? ([Method 2: Functions](https://atomiks.github.io/tippyjs/#creating-tooltips-method-2-function))

**Comment by atomiks** [comment]
You need to call the function every time you create new elements to give them a tippy.
