### ISSUE TITLE
Manuall events and interactive = true

### ISSUE THREAD

**Issue by Klainer** [atomiks/tippyjs#385]
Hello. 
I Have this setting:

`{ interactive : true, trigger: "manual" }'`

And  I Have custom event mouseEnter / mouseLeave events with these handlers:

```JS
    onTippyMouseEnter(e){
      if(e.target._tippy != null && (e.target.offsetWidth < e.target.scrollWidth)){
        e.target._tippy.show();
      }
    },
    onTippyMouseLeave(e){
      if(e.target._tippy != null && (e.target.offsetWidth < e.target.scrollWidth)){
        e.target._tippy.hide();
      }
    }
```
In this situation interactive not work beacause I´m using my events.
It is there any way how to make it work in this situation?.
Thanks!

**Comment by Klainer** [comment]
Ok thanks. It is a possibillity to another solution ?
I basically do this due to fact that I neeed to show tooltip only if size of text in data-grid cell is overflowed. 
So I wrote my custom mouseEnter event above: **onTippyMouseEnter**...

**Comment by atomiks** [comment]
Closing as stale: if you need additional help, feel free to create a CodePen of the problem
