### ISSUE TITLE
Unable to update the contents displayed in tooltip

### ISSUE THREAD

**Issue by Altamill** [atomiks/tippyjs#386]
system：IOS
vue：2.5.9
tippy：3.3.0
phenomenon：
1、Unable to update content
2、Tooltip has been applied to all TD elements, regardless of conditional filtering
How to solve this problem?

![a](https://user-images.githubusercontent.com/22368026/50267510-65a30780-0462-11e9-8f58-da1cbad98c5c.png)
![b](https://user-images.githubusercontent.com/22368026/50267511-663b9e00-0462-11e9-86a0-bd02fc0ffe60.png)

**Comment by atomiks** [comment]
You're calling `tippy()` on elements that already have an instance (after the first call), which won't do anything if `multiple: false` (it is by default). You need to call `.setContent()` on their instances. If you're sticking to the technique in the picture (I don't recommend it btw, I think you should be using a wrapper for Vue), then you can do:

```js
[...document.querySelectorAll('.customTooltip')].forEach(el => {
  if (el._tippy) {
    el._tippy.setContent(label)
  } else {
    tippy('.customTooltip', {
      content: label,
      ...
    })
  }
})
```

**Comment by Altamill** [comment]
Thank you very much for your help. Content can be changed. But there's a problem... I want to achieve the effect of long press triggering tooltip.

1. When the page has just been loaded, I need to click td to trigger the long-click display tooltip effect.

2. Because the click takes effect, it will cause the need to click td to trigger the long-click update content.

**Comment by Altamill** [comment]
Sorry, I've solved it. Click changed to touch start. It seems that my basic knowledge needs to be strengthened. Thank you very much.
