### ISSUE TITLE
tippy-popper zIndex Issue

### ISSUE THREAD

**Issue by TheSayantan96** [atomiks/tippyjs#387]
I have set zIndex: 99 as setDefaults for tippy. But still tippy poppers are overlapping div with z-index: 9999.
Please Help!

**Comment by atomiks** [comment]
Maybe you don't have a `position` set on the div. `z-index` has no affect unless a positioning context has been established

**Comment by atomiks** [comment]
I can't help without a CodePen reproducing the issue.

**Comment by TheSayantan96** [comment]
Sir it'll be really dificcult to reproduce the issue on codepen. I am putting all my codes here.

**This is the anchor tag with tippy tooltip**
`<a href="javascript:void(0);" class="country-hotspot country-in active" data-slide="1"
                                        data-tippy="Fleapo India" data-tippy-arrow="true" data-tippy-showOnInit="true"
                                        data-tippy-hideOnClick="false" data-tippy-trigger="manual"></a>`

**This is my sticky header styling**

`.site-header-sticky {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 99999;
}`
![capture](https://user-images.githubusercontent.com/17963422/50382721-f2043300-06cb-11e9-9c28-e06e15b713ae.PNG)

**Comment by TheSayantan96** [comment]
Sir you can Check the problem here at http://nayafleapo.herokuapp.com/

**Comment by atomiks** [comment]
Lol I was just reading this issue again and you made a comment (14 days after!). Thank you for the link, I will investigate it now

**Comment by atomiks** [comment]
It's because you have a `.sitewrapper` that wraps everything. The tooltip gets appended to the body which is outside of it.

Try this:

```js
tippy.setDefaults({
  appendTo: function() {
    return document.querySelector('.sitewrapper')
  }
})
```

**Comment by TheSayantan96** [comment]
Thank You so much sir...
