### ISSUE TITLE
text-align in HTML templates

### ISSUE THREAD

**Issue by skazhikadyadya** [atomiks/tippyjs#39]
Hi, thank you for that plugin.

How I can use CSS text-align property in tooltip? When I try to use that code in my HTML template like 

```
<p style="text-align: left">....</p>
```
Code was anyway centered?

**Comment by skazhikadyadya** [comment]
Solved with `.tippy-tooltip[data-template-id="myID"]` CSS rule.

**Comment by s-a** [comment]
@skazhikadyadya nice one 😃 ty!

**Comment by kevincaradant** [comment]
Hi

Is it working with latest versions ? I  my case, that seems to doesn't work as expected :/

Thank you
