### ISSUE TITLE
How can I steal the focus on a touch ? 

### ISSUE THREAD

**Issue by kyro38** [atomiks/tippyjs#390]
On iOS I encountered the following problem : 
I have a input with a tippy next to it.
I tap on my input, it gets the focus and displays a blinking cursor. Then, I tap on the `span` where I specified my tippy which opens on top of my input. 

The problem is that, on iOS, the cursor of the input appear above the tooltip and not beneath. 

So my solution would be to steal the focus from the input on the tap. 

But how could I achieve this ?

**Comment by atomiks** [comment]
Could you make a CodePen demo of the issue?

**Comment by atomiks** [comment]
I'm not exactly sure of the issue here, but all focus handling is removed in v4 and left up to the developer, chances are it fixes it
