### ISSUE TITLE
Interactive tooltip should not be auto-focused

### ISSUE THREAD

**Issue by jschuler** [atomiks/tippyjs#391]
I want to have a tooltip that remains open when i hover away from the reference element and hover over the tooltip. I can do this by setting interactive option to true.
However, I noticed that when this option is set to true, the tooltip will receive focus as soon as it opens.
This causes an a11y issue with screen readers, as the reading of the reference element text is interrupted by the tooltip text.
I'd like to keep focus on the reference element.

Example: https://codepen.io/jschuler/pen/maXqZQ

**Comment by jgiardino** [comment]
Adding to @jschuler's description, the behavior he describes is based on [WCAG 2.1 item 1.4.13](https://www.w3.org/WAI/WCAG21/quickref/#content-on-hover-or-focus):
> Hoverable: If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;

Also, the screen reader issue he describes was noticed in Voiceover on Mac.

**Comment by atomiks** [comment]
Hm I assumed that the reference element would finish being read before swapping to the tooltip. I guess not.

How should we handle focus inside the tooltip but still allow the reference element to be read out (with `focus` trigger). It seems `click` is a lot more accessible.

**Comment by atomiks** [comment]
`.3.4.0`

**Comment by atomiks** [comment]
`3.4.0`
