### ISSUE TITLE
[Q] can destroy() restore the tooltip content? 

### ISSUE THREAD

**Issue by aaarichter** [atomiks/tippyjs#397]
Hi,

With tippy removing the tooltip content from the DOM is there a way to restore the content? When calling the `destroy()` method, the tooltip content is unfortunately completely lost 😿 .

**Comment by atomiks** [comment]
I'm not sure what you mean exactly, do you have a CodePen demo for me? The `destroy()` method doesn't touch the content. If you have the instance stored somewhere you can still access it (but you should delete reference to it later to allow for GC)
