### ISSUE TITLE
When Target Element is split between Two Lines, Tooltip Appears in the Middle

### ISSUE THREAD

**Issue by AlexCanCode** [atomiks/tippyjs#398]
I am adding a span as the target element to player names, with first name and last name. When the first name appears at the end of a line and the last name appears on the next line, the tooltip's positioning is in the middle. Is there a way I can circumvent this behavior and have it "pick" a side? 

If this is not possible in the current implementation, does anyone know if there are there calculations within tippy or popper that could help me write my own workaround? 

Here is an example screenshot of the issue (the green names are wrapped with the target element, a <span>:

https://imgur.com/a/mWIoIDe 

Please let me know if you need more details

**Comment by atomiks** [comment]
`white-space: nowrap` on the name is one workaround

**Comment by AlexCanCode** [comment]
Thanks for the response. This works okay but does create some awkwardness on some sites where it breaks headlines oddly. Do you happen to have any other suggestions?

**Comment by atomiks** [comment]
You could use: `followCursor: 'initial'` (v3.4)

This will position the tooltip right where the cursor is upon showing, which will solve that problem.

**Comment by AlexCanCode** [comment]
That also solves the problem, but having the tooltip following around the cursor is a bit awkward for my purposes. I think I will go with the nowrap solution or live with the split because I also realized it will be likely be hard to determine when text is wrapping or not (at least in a clean way). Thanks for the support, I will mark this as closed. 

p.s. really loving tippyjs. I was searching around forever for a good tooltip implementation library and its honestly been a joy to use.

**Comment by atomiks** [comment]
`followCursor: 'initial'` won't follow the cursor continually, it will position the tooltip where the cursor exactly was initially upon showing, but not follow it

**Comment by AlexCanCode** [comment]
When I put followCursor: 'initial', it does follow the cursor around... Is there any other configuration needed to prevent that? 

The rest of my tippy configuration is:


                  ` placement: "top", 
                       allowHTML: true,
			zIndex: 9999999, 
			interactive: true,
			arrow: true,
			arrowType: "sharp",
			followCursor: "initial"`

Plus the custom HTML element I am adding.

**Comment by atomiks** [comment]
It was only released in v3.4, are you on that version?

Actually I investigated Wikipedia's tooltip, and it's more like `initialHorizontal` which I think is more appropriate for what you're trying to do. (It shouldn't place itself vertically near the cursor, only horizontally).

**Comment by AlexCanCode** [comment]
I am on 3.0.1, so that would explain that. I will try upgrading and see how it works.

**Comment by AlexCanCode** [comment]
Nice, it works now. Thanks for the help!

**Comment by atomiks** [comment]
I've added a section on this (better than `followCursor: 'initial'`): https://atomiks.github.io/tippyjs/misc/#anchor-links

It took me a while to work out a solution on it, and it's not 100% robust. It's kind of finnicky and depends on the line-height being larger than the font-size. It's also more boilerplate to setup. Despite that, I still think it's the best solution to it.

**Comment by atomiks** [comment]
I've updated the solution to that ^ it was buggy before 🤦‍♂ 

I think it's free of edge-cases now (and also the code is way shorter):
https://codepen.io/atomiks/pen/GeBoyW?editors=0110
