### ISSUE TITLE
Event delegation - multiple instances

### ISSUE THREAD

**Issue by 2x2xplz** [atomiks/tippyjs#399]
Hi I am using Tippy v3, via event delegation, in a Vue application. I'd like to run multiple instances on different target elements, to have tooltips with different look/behaviors, but any declaration after the first seems to be ignored:

```
mounted() {
    // the first declaration works great!
    tippy('.customerlist', { target: '.active' , 
      arrow: true , duration: 600 , theme: 'light-border' });

    // the second declaration doesn't work at all  :(
    tippy('.customerlist', { target: '.inactive' , 
      duration: 100 , theme: 'dark' , delay: [500], size: 'small });
}
```

I also used different parent elements but that didn't make any difference.

Am I doing something wrong?

(the workaround of course is to use an if/then or similar logic to check the target class and then choose from one of multiple options objects {} - it works but it's ugly )

**Comment by atomiks** [comment]
Add `multiple: true`

**Comment by 2x2xplz** [comment]
Doh!

**Comment by decadence** [comment]
Do we have this options in version 6? Or this works without `multiple: true`?
