### ISSUE TITLE
Creating a Tippy instance without a DOM element

### ISSUE THREAD

**Issue by maxkfranz** [atomiks/tippyjs#40]
Popper now allows for [specifying a custom object](https://github.com/FezVrasta/popper.js/issues/193) instead of a DOM node for positioning.

Would it be possible to allow passing in a Popper instance instead of a DOM element, i.e. `new Tippy( popper )`?  If not, maybe instead pass the reference object instead of the DOM element, i.e. `new Tippy( popperRef )`?

Thanks

Ref : https://github.com/cytoscape/cytoscape.js-qtip/issues/28#issuecomment-300488586

**Comment by atomiks** [comment]
Hey, sorry for the late reply

That should be possible,  I'll look into adding it for the next release =]

**Comment by atomiks** [comment]
Added this in v0.12.0, however I'm not 100% sure how you're using it. Feel free to let me know if you need changes/fixes etc and I'll change it up

**Comment by maxkfranz** [comment]
Basically, I'm looking to do something like this:

```js
let ref = { clientWidth, clientHeight, getBoundingRect };  // see https://popper.js.org/popper-documentation.html#referenceObject

let popper = new Popper( ref );

let tippy = new Tippy( popper );
let tippy2 = new Tippy( ref ); // or maybe this it's easier
```

**Comment by atomiks** [comment]
I see -- so you only want Tippy for its events and what not? Your popper is custom-styled? The content div also won't have the transitions unless your popper has `tippy-popper` with an inner `tippy-tooltip` class

**Comment by maxkfranz** [comment]
I made a mistake in the code. My intention is to use typical Tippy tooltips but just not on dom nodes -- custom positioning is needed for Cytoscape.js elements as they're in a visualisation. I'm just on my phone right now, but I can correct/clarify the code example on Monday.  Thanks

**Comment by maxkfranz** [comment]
@atomiks It should probably look more like this:

```js

let ref = { clientWidth, clientHeight, getBoundingRect };  // see https://popper.js.org/popper-documentation.html#referenceObject

let popper = new Popper( ref, someContentDiv, options );

let tippy = new Tippy( ref );

```

**Comment by atomiks** [comment]
That makes more sense... will work on adding it for next release

**Comment by maxkfranz** [comment]
Great; thanks!

**Comment by atomiks** [comment]
I'm confused how you're setting the title if it's not on an actual element? Do you need to pass in the title as well?

**Comment by maxkfranz** [comment]
The content/title of the tooltip would be manual in this case.  So basically

```js
let ref = { clientWidth, clientHeight, getBoundingRect };  // see https://popper.js.org/popper-documentation.html#referenceObject

let contentDomEle = document.createElement('div');

let tippy = new Tippy( ref, {
  html: contentDomEle
} );
```

The usecase I'm thinking of is creating an [extension](http://js.cytoscape.org/#extensions) for [Cytoscape.js](http://js.cytoscape.org/).  The extension would wrap the Tippy API and have its own options object for event handling, e.g. 

```js
node.on(extensionOptions.showEvents, evt => tippy.show());
```

**Comment by atomiks** [comment]
Hmmm alright... maybe you could try to modify the source yourself and send in a pull request?

**Comment by maxkfranz** [comment]
@josephst is working on the extensions, so hopefully he can make a PR while he's working on the Tippy extension.

**Comment by hmtinc** [comment]
#102 

I added an option to pass in a custom reference object that should allow users to manually override the  position. Which should provide the ability to use tippy with plugins like cytoscape.js

Sample Usage 

```
//Reference object allows for custom positioning
  var refObject = {
    getBoundingClientRect: function (data) {
      return {
        top:  5 + window.pageYOffset,
        left: 5 + window.pageXOffset,
        right: 5 + window.pageXOffset,
        bottom: 220 + window.pageYOffset,
        width: 1,
        height: 1,
    };
    },
    get clientWidth() {
      return 30;
    },
    get clientHeight() {
      return 30;
    },
  };

  var tip = tippy('#object', {}, refObject);
```

The element id which in the example is #object, refers to any DOM element and mainly just serves as a basis to create the popper element.  The reference object actually provides the position .

**Comment by atomiks** [comment]
Released as `1.4.0`

**Comment by dgroh** [comment]
That is why I'm exactly trying, but the tooltip keeps in the same position:

```
      const refObject = {
        getBoundingClientRect: function (data) {
          return {
            top:  5 + window.pageYOffset,
            left: 5 + window.pageXOffset,
            right: 5 + window.pageXOffset,
            bottom: 220 + window.pageYOffset,
            width: 100,
            height: 100,
        };
        },
        get clientWidth() {
          return 30;
        },
        get clientHeight() {
          return 30;
        },
      };

      tippy('.btn', {}, refObject);
```

**Comment by atomiks** [comment]
@DaJoTo you need to pass it as the first argument, `tippy(refObject)`. The docs show that. Instead of a DOM element, you use a virtual element.

**Comment by DaJoTo** [comment]
@dgroh I imagine the above is for you

**Comment by atomiks** [comment]
Haha sorry. The name autocomplete must have done that.
