### ISSUE TITLE
[Error] Not working in IE11 ?

### ISSUE THREAD

**Issue by Fenny** [atomiks/tippyjs#400]
Works in all browsers, but not on IE11 :-(

```
<i class="fas fa-question-circle" data-tippy="Some information"></i>
<script src="//cdnjs.cloudflare.com/ajax/libs/tippy.js/3.4.0/tippy.all.min.js"></script>
```

![Image](https://i.imgur.com/75aRpqh.png)

![Image](https://i.imgur.com/NO3RSNE.png)

![Image](https://i.imgur.com/byDZyR4.png)

Any ideas?

**Comment by atomiks** [comment]
Maybe something to do with the `<i>`. Did you try a wrapper `<span>` instead?

**Comment by atomiks** [comment]
Here's the version that works on Browserstack using the minimal example from OP

![IE11 version](https://i.gyazo.com/ce56c6ad356384f84fb04e342e5a2257.png)

Maybe adding a global `classList` polyfill (not just for SVGs) will fix the issue.
