### ISSUE TITLE
[a11y aria] Update aria option to be null

### ISSUE THREAD

**Issue by jburghardt** [atomiks/tippyjs#401]
v3.4 aria option is either "describedby" or "labelledby", which is fine.

We often do not want screen-readers to read out the tooltip, often because a describtion is given somewhere else.

The aria option forces the tooltip to be one of the aformentioned strings, but we need an option to disabled the aria-describedby or aria-labeledby somehow.

right now, initalising a tippy instance with  ... { aria: null } will put a aria-null attribute in the html tag.

aria: null should probaly remove the aria attributes completely,
and any non standardised aria- attribute should not be possible

**Comment by atomiks** [comment]
Yeah I agree here. I'm not sure about validating the attributes though.

**Comment by jburghardt** [comment]
Validation is a bit tricky here, i know.

any aria validation tool would throw an error though when encountering a non valid aria- attribute.
i dont know what would be best. throw a warning maybe ?

**Comment by atomiks** [comment]
btw, `aria-describedby` had been hardcoded since v0.8 so you couldn't actually choose between them (or disable it) before anyway

**Comment by jburghardt** [comment]
yes, we remove the 'describedby'  with removeAttribute('aria-describedby') on most occasions,
but that did not work with tippy ^3. A bit hacky, yes.

i'll check that commit out on the weekend.
Thanks!

**Comment by atomiks** [comment]
> but that did not work with tippy ^3

Should work if you use the `onShown()` lifecycle

**Comment by jburghardt** [comment]
yes, it kinda did, NVDA reads the tooltips non the less, which is strange
