### ISSUE TITLE
Add examples for every option

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#405]
https://atomiks.github.io/tippyjs/all-options/

Every option should have a little example dropdown button you can use to see the code and the effects different values have. The demo is nice but can't possibly cover all options + missing code used to create them.

[All Options page is just a markdown table](https://github.com/atomiks/tippyjs/blob/d59ac8450232b745c80c487c296d81c9d4e7174d/website/src/pages/all-options.mdx). Hopefully we can embed a little button next to the option name to expand a modal to show an example and code for each.

**Comment by andreasvirkus** [comment]
You could maybe store links to codepen or codesandbox examples in the markdown table and dynamically create an embed in a dialog/popup if user requests to see an example?
Codesandbox has [git integration](https://codesandbox.io/docs/git) available, so you wouldn't lose out on the benefits of VCS :)

**Comment by atomiks** [comment]
I think I'll use a modal for this. I can work on it after v5 is out next month some time...

The modal markdown will look something like this, if you click `animateFill` it opens up like this:

### animateFill

#### `true`

```jsx
// This will be an actual live demo on the page, not raw code
<Tippy animateFill={true}>
  <Button>Text</Button>
</Tippy>
```

```js
tippy(ref, {
  animateFill: true
});
```

#### `false`

```jsx
// This will be an actual live demo on the page, not raw code
<Tippy animateFill={false}>
  <Button>Text</Button>
</Tippy>
```

```js
tippy(ref, {
  animateFill: false
});
```

**Comment by KubaJastrz** [comment]
^ In `code` section we could also include the React version
