### ISSUE TITLE
HTML Tooltip don't work - Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by Radzio1615** [atomiks/tippyjs#406]
Why code below don't work? Have I made a mistake?

Console show error: **Cannot read property 'innerHTML' of null**

```
<script>
  const myTemplate = document.getElementById('example');
  tippy.one('#test', { content: myTemplate.innerHTML });
</script>
```
```
<div id="test">Hover me to see HTML Content</button>
```
```
<div id="example" style="display: none;">
  <strong>HTML Content</strong>
</div>
```

**Comment by KubaJastrz** [comment]
HTML file is interpreted from top to bottom, therefore your script runs before any `div`s are created and it throws an error. Assuming that you have in the same order as posted above.

**Comment by Radzio1615** [comment]
I changed the order and everything works well. Thanks for fast answer :)
