### ISSUE TITLE
data-tippy-onShown not working

### ISSUE THREAD

**Issue by lajomjohndel** [atomiks/tippyjs#407]
How to use onShown option as an inline attribute?

Here's the sample code:

&lt;th data-tippy="Clear column values" 
	data-tippy-arrow="true"
	data-tippy-onShown="function() { alert() }"
	data-tippy-interactive="true"&gt;
&lt;/th&gt;

![image](https://user-images.githubusercontent.com/26918229/51101276-f0cead80-1814-11e9-9657-fbffa7b31953.png)

**Comment by atomiks** [comment]
Only JSON-serializable values are valid, i.e.

- strings
- numbers
- booleans
- null
- arrays and objects containing the above types

Functions are not part of JSON, so you should use the `tippy()` function instead
