### ISSUE TITLE
export 'Props' was not found in 'tippy.js'

### ISSUE THREAD

**Issue by nadavshabtai** [atomiks/tippyjs#408]
Hi

I'm using tippy 3.4.1 and I'm having trouble importing tippy Props and Instace using typescript because I get the following warning:

```
WARNING in [path]
"export 'Props' was not found in 'tippy.js'
[stack trace]
```
am I importing it wrong?
`import tippy, {Instance, Props} from 'tippy.js';`

**Comment by KubaJastrz** [comment]
This should work, can you post your `tsconfig.json`?

**Comment by nadavshabtai** [comment]
this is my tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "es2016.array.include", "dom"],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "src/main-prod.ts"
  ]
}
```
I managed to solve this problem using the following code in d.ts file, but I don't think it's pretty... 

```
declare module 'tippy.js/dist/tippy.standalone' {
    import { Tippy } from 'tippy.js';
    export { Instance, Props, BasicPlacement, Placement, Content, Targets, Collection } from 'tippy.js';
    const tippy: Tippy;
    export default tippy;
}
```

**Comment by KubaJastrz** [comment]
I can't reproduce this. So you're importing tippy via `tippy.js/dist/tippy.standalone` now?

Btw, you can also do `export * from 'tippy.js`.

**Comment by nadavshabtai** [comment]
1. Yes, because of the 'module' in the package.json it's using standalone, but I import from tippy.js just as I wrote on the top.

2. You're right :) stupid me

**Comment by atomiks** [comment]
Is this a problem in v4?

**Comment by atomiks** [comment]
If you can provide a reproduction repo I'll repon!
