### ISSUE TITLE
TypeError while testing with jest

### ISSUE THREAD

**Issue by nadavshabtai** [atomiks/tippyjs#409]
Hi, 

I'm using jest for testing, and I'm having trouble with tippy.one in the testing:
```
TypeError: Cannot read property 'one' of undefined
                  tippy.one(el, tippyOptions);
```
the error occurred in the directive I'm testing and not in the test file itself... 
In the directive I import tippy like this:

import tippy, {Instance as TippyInstance, Props as TippyOptions} from 'tippy.js/dist/tippy.standalone';

In the testing I use the following tsconfig.json file:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "module": "commonjs",
    "target": "es5"
  }
}
```
which is using commonjs and not es2015 (The rest of the project is using es2015), and I don't have this problem with the rest of the project

the tsconfig of the project is the following:
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "declaration": false,
    "skipLibCheck": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2018", "dom"],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "src/main-prod.ts"
  ]
}
```

**Comment by atomiks** [comment]
`tippy.one` no longer exists in v4, this probably isn't an issue now?
