### ISSUE TITLE
How to use tippyjs with custom attribute (instead of title)

### ISSUE THREAD

**Issue by cohenu** [atomiks/tippyjs#411]
Hey Guys, :-)

I'm trying to use tippyjs with attribute other than title, something like:
selector: [rel-tooltip]
tooltip content: [tooltip]

This is my current setup:

```html
	tippy('[title]', {
		arrow: true,
		animation: 'fade',
		theme: 'general',
		delay: [0, 0],
		duration: [0, 0],
		maxWidth: '210px',
		dynamicTitle: true
	});
```

I'm using the library on chromium app with a lot of dynamic content and pages sometimes between destroy and initialization of the library the default behavior of the title attribute come up and I'm trying to get rid of it.

I tried this with  no luck:

```html
	tippy('[rel-tooltip]', {
		arrow: true,
		animation: 'fade',
		theme: 'general',
		delay: [0, 0],
		duration: [0, 0],
		maxWidth: '210px',
                content: '[tooltip]'
		dynamicTitle: true
	});
```

**Comment by atomiks** [comment]
That looks like v2. Have you tried using v3?

**Comment by cohenu** [comment]
you probably right, I replaced the script and I got `dynamicTitle` is not a valid option, is it not supported in the new version?

**Comment by anthony0579** [comment]
Is it possible to use the 'title' attribute for the tippy content rather than 'data-tippy-content'? 

Looking at the 'content' option, only string or element is allowed, but can we maybe do something like this:
tippy('button', { content: this.getAttribute('title') })

Thanks

**Comment by KubaJastrz** [comment]
If you used `title`, then you'd have both tippy and default browser tooltip.

**Comment by atomiks** [comment]
It's possible:

```js
tippy('button', {
  content(reference) {
    const title = reference.getAttribute('title')
    reference.removeAttribute('title')
    return title
  }
})
```

**Comment by atomiks** [comment]
If you want this as default behavior, feel free to "enhance" the tippy function.

```js
function withTitleAttributeContent(tippy) {
  return (targets, options = {}) => tippy(targets, {
    ...options,
    content(reference) {
      if (options.content) {
        return options.content
      }
      const title = reference.getAttribute('title')
      reference.removeAttribute('title')
      return title
    }
  })
}

window.tippy = withTitleAttributeContent(tippy)
```

**Comment by anthony0579** [comment]
Thanks @atomiks 
Had been trying the content function but it wasn't working and just seen your Edit 2 fix - I'll give that a go - many thanks!

**Comment by atomiks** [comment]
I will add this to the FAQ page

**Comment by anthony0579** [comment]
All working great - thanks!
