### ISSUE TITLE
Trigger a tippy with another Element

### ISSUE THREAD

**Issue by choletjonathan** [atomiks/tippyjs#414]
Hi, and thanks for the awesome library that is Tippy <3

Taking this codepen, where I have a tippy bound to an element, and a side text:
https://codepen.io/anon/pen/RvNYMN

What I try to acheive is to trigger the tippy also when interacting with the side text (the tippy arrow must target the `?`).

I added listeners to the parent button (`mouseenter, focus / mouseleave, blur`) to show/hide the tippy bound to the `?` element. (with the option `trigger: 'manual'`)

On mobile it's a bit tricky because the events behave differently. I added a `'click'` event to show the tooltip on Chrome mobile devices because it wouldn't show otherwise. (works on mobile Chrome/iOS)

So it does the job as seen in the Codepen, but I wondered if I took the right approach. Especially for touch devices and the events I chose to bind. Although it seems to work, I fear of side effect(s) I could have missed.

Would you have done it differently? Is there some options I missed that could fulfill this use case?

Thank you for your time.

**Comment by atomiks** [comment]
Yup that's how you do it, or at least how I've done it before

Maybe try `hideOnClick: false` so you don't need the `click` event, the default events should work 🤔

**Comment by choletjonathan** [comment]
Indeed it behaves even better that way. Thank you for the quick answer!
