### ISSUE TITLE
Follow element when DOM changes

### ISSUE THREAD

**Issue by Exocomp** [atomiks/tippyjs#419]
I've created an example here:  https://codepen.io/anon/pen/WPoNBE

To reproduce the issue:

* Change the window size so it is greater than 992px
* Click "My button"
* You'll see the tippy tooltip
* Resize the window less than 992px
* Tippy goes to the top left and doesn't track to the new element with id 'element'

What's the best solution for this issue, so that either tippy follows to the new location of the element (ideally) or a work around so that I can gracefully show tippy in the new location?

**Comment by atomiks** [comment]
It's not possible to change the reference of the instance after creation (only the instance's props).

You should destroy it and create a new one for the appropriate element when necessary on resize once it matches the condition

**Comment by Exocomp** [comment]
Gotcha. It would be nice if this was a built in to tippy:

- Once it detects the element has changed position, it should track it (or just appear in it's new location)
- If the element is no longer on the screen to just destroy/hide gracefully because currently it just goes to the top left

Consider these as my feature request :)

**Comment by atomiks** [comment]
I think that behavior is out of the scope of tippy's core and not common enough to warrant it, going to close
