### ISSUE TITLE
Offset both X and Y

### ISSUE THREAD

**Issue by richardbushell** [atomiks/tippyjs#420]
Is there any way to offset both X and Y? It only seems to allow offset in the axis determined by the position. So, if I set position "right" then it ignores the Y offset. If I set "top" then it ignores the X offset. Any way to use both X and Y at the same time?

**Comment by atomiks** [comment]
The syntax is: `"x, y"`

```js
{ offset: '50, 20' }
```

The new docs don't seem to mention this

**Comment by richardbushell** [comment]
Yes, I guessed that must be the format to avoid a comma within the value.
BUT it does not work as expected for me.
When "placement:top", it offsets x,y BUT x gets limited to about 50px (or does NOT go beyond where "right" placement would be).
When "placement:right", it uses y,x (other way round) BUT y gets limited to about 50px (or does NOT go beyond where "bottom" placement would be).

**Comment by atomiks** [comment]
It's Popper.js' `keepTogether` modifier, maybe you want to disable it:

```js
tippy(ref, {
  popperOptions: {
    modifiers: {
      keepTogether: { enabled: false }
    }
  }
})
```

**Comment by KubaJastrz** [comment]
@atomiks what do you think about converting two dimensional `offset` to array? It would be clearer and more consistent with other options (`delay`, `duration`).

**Comment by atomiks** [comment]
@KubaJastrz  `offset` is a Popper.js API
