### ISSUE TITLE
Append to target instead of selector

### ISSUE THREAD

**Issue by iamtekeste** [atomiks/tippyjs#421]
I want to start out by saying great library and delightful landing page!

In order for the tooltips to show for elements that get append later on, I have delegated it to `body` and set the target option.

My question is how do I make sure that the tippy gets appended to the current link/target. 
Adding the `appendTo` function gets `body` as its argument instead of the anchor tags which are the correct targets.
```js
tippy('body', {
    content: template.innerHTML,
    placement: 'top',
    arrow: true,
    theme: 'tomato',
    target: 'a[href^="mailto:"]'
});
```

**Comment by atomiks** [comment]
I believe this was mentioned in #363 - in v3 this is not possible. However, I will change this in v4 so it will use the target instead

**Comment by iamtekeste** [comment]
Thanks for getting back to me!n I will close the issue now.
