### ISSUE TITLE
Styling the arrow

### ISSUE THREAD

**Issue by anthony0579** [atomiks/tippyjs#425]
v4.0.1 has the arrow element changed it's class name from 'tippy-arrow' to 'arrow-regular'?

https://atomiks.github.io/tippyjs/themes/#styling-the-arrow

![image](https://user-images.githubusercontent.com/12558152/52640472-743ff500-2ece-11e9-94dc-b1a3f57e6579.png)

**Comment by atomiks** [comment]
That's v1 I'm pretty sure 😅 , how did you end up with that?

**Comment by anthony0579** [comment]
My god you're right! Bloody npm package got reverted! 🙈🤣

Apologies - close and burn this!

**Comment by atomiks** [comment]
No problem!
