### ISSUE TITLE
Distance option not working

### ISSUE THREAD

**Issue by marioMadunic** [atomiks/tippyjs#428]
Hi,
The option distance is not working for me.

I'm trying to place the tooltip closer to its context but no matter what value I use for distance it remains the same distance above its context, a substantial gap between the tooltip and its context. Even when I use placement, the y axis never makes the tooltip closer to its context but using a large value and the tooltip will be positioned according to that value.

If I set distance to -1 the tooltip will move to below its context. 

(Windows 8.1, Firefox Quantum, Chrome, and Palemoon)

Codepen https://codepen.io/marioMadunic/pen/daQeNv

Any help will be appreciated.
Thanks
Mario

**Comment by atomiks** [comment]
It appears to be a bug when setting distance in `setDefaults`. If you remove the default distance and set it in the `tippy()` call, it works. I think I know why

**Comment by marioMadunic** [comment]
Thanks for the quick reply and worked like a charm.
