### ISSUE TITLE
Error from appendTo: Uncaught TypeError: (intermediate value)(intermediate value).contains is not a function

### ISSUE THREAD

**Issue by charlotte-murray** [atomiks/tippyjs#430]
I'm trying to use tippy to generate tooltips programmatically on a series of input boxes that are generated with specific IDs. In the `.fail()` part of an ajax call that saves what's in these fields, each input tag should generate a tooltip with the reason for failure. 

The tooltips are showing up in the top left corner of the screen and I'm not sure why, so I've been using the appendTo option to specify the specific ID the tooltip should aim for. I'm getting this error though:
```
createTippy.js:563 Uncaught TypeError: (intermediate value)(intermediate value).contains is not a function
    at VM6010 index.all.min.js:1
    at Object.xt [as show] (VM6010 index.all.min.js:1)
    at Object.<anonymous> (ReviewQueueFrame.aspx?ArtifactID=1039468:1)
    at n (jquery.js:2)
    at Object.fireWith [as rejectWith] (jquery.js:2)
    at w (jquery.js:4)
    at XMLHttpRequest.d (jquery.js:4)
```

Codepen: https://codepen.io/anon/pen/qgvawO

**Comment by KubaJastrz** [comment]
1. jQuery `$(...)` returns an array, so you need to get the input element like this:
```js
var el = $('#someid')[0];
```
2. by `appendTo: el` tippy appends itself into the `input` element and that is an invalid html and won't be rendered. You need to either create a div around the `input` or don't set the `appendTo` option.

**Comment by charlotte-murray** [comment]
Incredible, thank you - solved my issue!
