### ISSUE TITLE
Default dark theme causes issues with custom theme

### ISSUE THREAD

**Issue by Semaho** [atomiks/tippyjs#433]
Here's my use case. I have two kinds of popovers :
- custom popovers / floating menus, so I want to have control over their look&feel,
- regular tooltips, then I'm fine with default dark theme.

Problem is: some parts of the default dark theme have on effect on my custom tippys.  
For example, `.tippy-backdrop` is not prefixed by `.dark-theme` so its black background is visible on my custom tippys.

The following CodePen is inspired by the doc, and you can see `tomato` olor being replace by a dark color : https://codepen.io/anon/pen/MxYerG

**Suggestion:** make all default CSS dependent of the `.dark-theme` CSS class.

**Comment by Semaho** [comment]
Ps: I'm aware you are overriding `.tippy-backdrop` id the doc example, but why not make it theme-specific instead of overriding :)

Ps2: anyway in my project I also had z-index and text color issues that are not visible in my CodePen.

**Comment by Semaho** [comment]
Ok now I've noticed that I'm losing CSS needed for animation if I don't include default CSS at all.  
How about just making the bg-color of `.tippy-backdrop` dependent of `.dark-theme` ?

**Comment by Semaho** [comment]
Well, we still have CSS having an effect on custom themes, like directly on `.tippy-tooltip`. [https://pasteboard.co/I2YjwOt.png](https://pasteboard.co/I2YjwOt.png)

In this case, I think every properties (except `position: relative` which seems to be needed to see the effect of `position` parameter) should be specific to the dark theme.

Sorry for flooding, I comment as I discover things :)

**Comment by atomiks** [comment]
I'm not really sure what you're asking -- you need to follow the CSS in the themes section so that the `backdrop` gets properly styled and doesn't affect the different color.

```css
.tippy-tooltip.tomato-theme[data-animatefill] {
  background-color: transparent;
}

.tippy-tooltip.tomato-theme .tippy-backdrop {
  background-color: tomato;
}
```

**Comment by Semaho** [comment]
> Not sure if that would be a breaking change since by default the tooltip gets that class name.

I agree.

> Although to be fair the only "dark-theme" specific thing there is the background-color.

I don't agree :)  

Please have a look at the image in my last post before your replay, there are CSS properties like `font-size`, `padding`, `text-align`, ..., that will also apply to custom themes.  
They apply directly on `.tippy-tooltip`, without being a child of `.dark-theme`. You would have to override all those properties in a custom theme, in case they don't fit your needs.

I could work on a PR if you'd like !

**Comment by atomiks** [comment]
@Semaho but most basic themes would like to inherit to use those values. They can be overridden easily if need be

**Comment by atomiks** [comment]
@Semaho but most basic themes would probably like to inherit those values. They can be overridden easily if need be

**Comment by Semaho** [comment]
Ok, maybe I just should have used Popper for the custom one, I came with Tippy first and didn't think about this solution before now. Thank you for the quick answers 👍
