### ISSUE TITLE
maxWidth option - make possible to pass an element selector whose width to take

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#434]
Hey.
I want to make a drop-down submenu using your plugin.
Submenus can be of 2 types - normal (with a fixed maximum width), and on the "fullwidth" - the entire width of the container from the main menu. Due to the individual settings of the template, I cannot use `appendTo: 'parent'` due to overlap (overflow) problems, so I use the option `appendTo: 'body'`. But now I have lost the opportunity to set the dynamic value of the maximum width, which in my case corresponds to the width of the container of the main menu.
If it were possible to pass as the value of the string - the selector of the element, the current width of which would serve as the calculated one (the plug-in would calculate the new value when resizing), this would solve my problem.
For example: `maxWidth: '.main-menu'`
At the moment, the only way to make a working version is to specify the static width in combination with the maximum width in percent, but these percentages will be calculated relative to the entire width of the page body, and this option will not work if I, for example, were not the entire width of the page.

I am very happy if I managed to convey the idea of my problem!
Thanks!

**Comment by atomiks** [comment]
You should be able to do something like this instead:

```js
const mainMenu = document.querySelector('.main-menu')

tippy(ref, {
  popperOptions: {
    onUpdate(data) {
      // more convoluted to grab the instance here
      const instance = data.instance.reference._tippy
      const maxWidth = mainMenu.getBoundingClientRect().width
      instance.set({ maxWidth })
    }
  }
})
```

v4.0.3+ only though

**Comment by atomiks** [comment]
Please see https://codepen.io/anon/pen/OqXBKO

**Ignore** the comment above, calling `.set()` in `popperOptions.onUpdate` causes an infinite loop because `.set()` calls `.update()` itself.

Instead you'll need to manually manipulate the elements

**Comment by sabetAI** [comment]
How to perform this with the new API?
