### ISSUE TITLE
Is there a way to handle trigger and exit without being forced to use "manual"?

### ISSUE THREAD

**Issue by madjennsy** [atomiks/tippyjs#436]
How do you recommend to create a tooltip with the following:
Trigger: Hover
Exit: Click
and
Trigger: Click
Exit: Hover

Thank you!

**Comment by Gumidefektet** [comment]
🔟

**Comment by Gumidefektet** [comment]
Re: [atomiks/tippyjs] Is there a way to handle trigger and exit without
being forced to use "manual"? (#436)

Gumidefektet <notifications@github.com> ezt írta (időpont: 2019. febr. 28.,
Cs 21:15):

**Comment by Gumidefektet** [comment]
#436

**Comment by atomiks** [comment]
Should be possible like this

Trigger: Hover
Exit: Click

```js
tippy('button', {
  onShow(instance) {
    instance.set({ trigger: 'click' })
  },
  onHide(instance) {
    instance.set({ trigger: tippy.defaults.trigger })
  }
})
```

Trigger: Click
Exit: Hover

```js
tippy('button', {
  trigger: 'click',
  onShow(instance) {
    instance.set({ trigger: tippy.defaults.trigger })
  },
  onHide(instance) {
    instance.set({ trigger: 'click' })
  }
})
```

**Comment by Gumidefektet** [comment]
18-12-22 18

**Comment by madjennsy** [comment]
It works, thank you so much!

**Comment by madjennsy** [comment]
Did something changed? for some reason this stopped working after 4.2.1. I tried 4.3.0 and I still can't set click as trigger after tippy shows up.

**Comment by atomiks** [comment]
Both examples still work fine for me on latest. Are you sure it's the versions and not other code?
