### ISSUE TITLE
Tippy with Click Trigger, Unable to Hide Tippy via Function called From Anchor

### ISSUE THREAD

**Issue by sfhaney** [atomiks/tippyjs#437]
Hard to describe exactly in the title, but basically I have a tippy that is click driven.  The content contains a hyperlink that has an onclick calling a function.  I'd like after the function runs to hide the Tippy as well.

I have a code pen recreating and I can't see anything glaring that I'm doing wrong but maybe I'm missing something obvious.  The Tippy Instance that I fetch appears to be found but the hide event just isn't hiding the popup.

https://codepen.io/sfhaney/pen/ZPQGGP

**Comment by atomiks** [comment]
There's a couple problems I'm seeing:

1. `tippy()` is a call to create tooltips (and return their instance(s)), not retrieve existing ones

2. The wrong item is being selected. The instance is attached the parent popper (`.tippy-popper`) to it via its `_tippy` property (just like reference elements).

This will work:

```js
function closeMe(item) {
  var tippyInstance = $(item).closest('.tippy-popper')[0]._tippy;
  tippyInstance.hide();
}
```

**Comment by sfhaney** [comment]
Sorry I didn't reply sooner.  Thanks much for the great assistance.  Works perfect!
