### ISSUE TITLE
Expand doc over lifecycle callbacks

### ISSUE THREAD

**Issue by tiaagosr** [atomiks/tippyjs#438]
First of all, thanks for this amazing lib!

I recently used it and had a hard time over finding a way to init the tooltip on hover, but to only show it after specific condition (ajax content request, for instance).

As a last resort, I did research the source code and found out that `onShow()` and `onHide()` callbacks can cancel out their respective state changes if they return `false`. It really made everything quite easy and solved my problems. On this sense, I think it is a shame to not have it written somewhere visible, like on [All Options page](https://atomiks.github.io/tippyjs/all-options/).

Suggestion:
Improve  **onShow** and **onHide** descriptions by including something like `Tippy stays hidden/visible if onShow/onHide returns false`, which would be quite helpful.

**Comment by atomiks** [comment]
Yes the new website forgot to transfer that over!

Actually, maybe the `wait` option might suit your usecase better?

**Comment by tiaagosr** [comment]
Ok, cool to know it is going to be included soon.

As for your suggestion: There is no native delay before triggering `wait` callback, and `onHide` only happens after tippy is shown, so it had me doing manual lifecycle control, and thus, giving up some niceties already provided by the lib. 

I just wanted to apply some classes on the hovered element, and remove it after un-hovering. Since ajax was not complete yet, and the element was not shown, `onHide` was never called.
