### ISSUE TITLE
Is possible to use trigger: hover on non-touch devices && trigger: click on touch devices?

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#439]
Is possible to use trigger: hover on non-touch devices && trigger: click on touch devices?
Now if i set trigger:hover - it not works on touch devices.

**Comment by atomiks** [comment]
Just wondering why you'd want `click`on touch devices? The default trigger works fine on touch devices (mouseenter/focus)

**Comment by 7iomka** [comment]
> Just wondering why you'd want `click`on touch devices? The default trigger works fine on touch devices (mouseenter/focus)

Oh, sorry, my mistake that I did not see in the list of possible values:  `"mouseenter", "focus",  "click", "manual"` value `hover`.
Thanks!
