### ISSUE TITLE
Illegal Invocation

### ISSUE THREAD

**Issue by saurishkar** [atomiks/tippyjs#440]
Receiving *Illegal Invocation* error on tooltip. When tried to debug, it seems to be coming from the below code in tippy.js
```
/**
 * Ponyfill to get the closest parent element
 * @param {Element} element - child of parent to be returned
 * @param {String} parentSelector - selector to match the parent if found
 * @return {Element}
 */
function closest(element, parentSelector) {
  var fn = Element.prototype.closest || function (selector) {
    var el = this;
    while (el) {
      if (matches$1.call(el, selector)) {
        return el;
      }
      el = el.parentElement;
    }
  };

  return fn.call(element, parentSelector);
}
```
Looks like the ```this``` context gets lost which causes the error.
Any suggestions?

Browser: Chrome 60.0.3112.101
MacOS Mojave

**Comment by saurishkar** [comment]
Surprisingly, i have got errors on only the exact Chrome version specified above and no other.

**Comment by atomiks** [comment]
Chrome 60 is pretty old at this point. Not sure it really matters..

**Comment by atomiks** [comment]
Tested Chrome 49, 60, 61 on Browserstack on the website (v4) using event delegation & interactivity & clicking around (where `closest` gets invoked), didn't see the warning in the console.  Guess it might be a false positive.
