### ISSUE TITLE
Placement auto removed ? 

### ISSUE THREAD

**Issue by miguelyoobic95** [atomiks/tippyjs#448]
I was previous using the `placement: "auto"` option in my code and it has suddenly stopped working after upgrading to the latest version of the library.

Is this functionality still available or is there a new way to implement the use case where the tooltip itself should work out the correct position ?

Thanks in advance. Best

Miguel

**Comment by atomiks** [comment]
@KubaJastrz I guess we're missing a type for `"auto"`
We should import the types from popper.js
