### ISSUE TITLE
Bundle popper.js in ESM builds and/or provide version without dependency

### ISSUE THREAD

**Issue by brettz9** [atomiks/tippyjs#457]
Distribution files are generally supposed to be ready for consumption without the need for build steps, but with recent releases of tippy.js, one must perform some Rollup or the like due to a dependency on "popper.js".

Please add back at least one distribution which bundles popper.js and/or which removes it. (One might use such as https://github.com/jetiny/rollup-plugin-re to strip out optional import directives for such cases.)

And thanks for the great library!

**Comment by atomiks** [comment]
Feel free to make a PR to create a bundled version
