### ISSUE TITLE
A virtual positioning referance is not working with delay

### ISSUE THREAD

**Issue by kGk13** [atomiks/tippyjs#460]
Hello,

I've used your example from codepen for a vistual positioning referance, all the options are working except the delay. I'm doing something wrong ? This is the code that i'm using:

`
function initTippy(els){
    for (let index = 0; index < els.length; ++index) {
        demo(els[index]);
    }
}
initTippy(document.querySelectorAll('article #post-content .text a, .birdviewminimal-container .categories a'));

function demo(anchor){
    anchor.addEventListener('mouseenter', show);
    anchor.addEventListener('mouseleave', hide);
    anchor.addEventListener('focus', event => {
        if (!instance.state.isVisible) {
        show(event)
    }
    })
    anchor.addEventListener('blur', hide)

    function createVirtualReference() {
        return {
            getBoundingClientRect: () => anchor.getBoundingClientRect(),
            clientWidth: anchor.clientWidth,
            clientHeight: anchor.clientHeight,
    }
    }

    const virtualReference = createVirtualReference()

    const template = document.getElementById('tooltip-template');
    const container = document.createElement('div');
    container.appendChild(document.importNode(template.content, true));

    function show(event) {

        if (event.type === 'mouseenter') {

            const LINE_HEIGHT = 24
            const rect = anchor.getBoundingClientRect()
            const cursorPoint = Math.round(event.clientY - rect.top)
            const lineIndex = Math.floor(cursorPoint / LINE_HEIGHT)

            const top = rect.top + lineIndex * LINE_HEIGHT
            const bottom = top + LINE_HEIGHT

            Object.assign(virtualReference, {
                clientHeight: bottom - top,
                delay: [1600, 0],
                getBoundingClientRect() {
                    return {
                        width: 0,
                        height: bottom - top,
                        top,
                        bottom,
                        //delay: 10000,
                        delay: [1600, 0],
                        left: event.clientX,
                        right: event.clientX,
                    }
                },
            })

            // Prevent the tooltip from following scroll
            setTimeout(() => {
                instance.popperInstance.disableEventListeners()
        })
        } else {
            // For `focus`, we don't have client coords. Just use the anchor.
            Object.assign(virtualReference, createVirtualReference())
        }

        instance.show()

    }

    function hide() {
        instance.hide()
    }

    const instance = tippy(virtualReference, {
        content: container.innerHTML,
        arrow: true,
        theme: 'light',
        arrowType: 'round',
        placement: 'top',
        boundary: 'window',
        delay: [1600, 0],
        animation: 'shift-away',
        interactive: true
    })
}
`

Thanks.

**Comment by atomiks** [comment]
Yeah, `delay`/`wait` won't work because `show` immediately shows it.. Maybe we should expose the internal `scheduleShow` / `scheduleHide` methods to the public API to make these options work.

**Comment by kGk13** [comment]
Thanks, i've managed to add a settimeout and reset it on mouseleave. Thanks
