### ISSUE TITLE
How to keep open on click

### ISSUE THREAD

**Issue by DominicTobias** [atomiks/tippyjs#465]
hi,

Thanks for the lib. This is a question not a bug.

I want to show the tooltip on hover, but if clicked I want it to stay open.

I tried playing around with `onShown`, `onHide` and trigger etc but couldn't get anything to work. Thanks!

**Comment by atomiks** [comment]
`hideOnClick: false`

**Comment by DominicTobias** [comment]
Thanks for the fast reply but that option doesn't seem to do anything: I hover over a top element, the tooltip shows, I click the element, then move the mouse away and the tooltip disappears

**Comment by atomiks** [comment]
Ah ok, that's an interesting case...

When do you want it to hide then? After clicking outside of it?

```js
const button = document.querySelector('button')

const instance = tippy(button, {
  hideOnClick: false
})

// Upon clicking, remove all trigger event listeners
button.addEventListener('click', () => {
  instance.set({ trigger: 'manual' })
})

// Add this to make it hide when we click outside the tooltip or reference element
// to reset the trigger and hide the tooltip
document.addEventListener('click', event => {
  if (
    !instance.popper.contains(event.target) && 
    !instance.reference.contains(event.target)
  ) {
    instance.set({ trigger: tippy.defaults.trigger })
    instance.hide()
  }
})
```

**Comment by DominicTobias** [comment]
That's what I was after yep, thanks!
