### ISSUE TITLE
Different position for popup

### ISSUE THREAD

**Issue by tudor-coderz** [atomiks/tippyjs#471]
Hi!

It's possible to set different position for tooltip? (Like on screenshot below)

![Artboard](https://user-images.githubusercontent.com/668451/56365471-3d999a00-61f1-11e9-915d-8b71601c753d.png)

In qTip I used:
```js
        $(this).qtip
          position:
            target: $(this).find('img')
```

**Comment by atomiks** [comment]
Yes, it's possible if you add the tippy to the image element and store the instance, then add event listeners to the outer element, and inside the listeners call the instance's `.show()` / `.hide()` methods. 

However, this is not ideal and I'm currently working on a way to simplify this for both virtual references and this particular case in the next `4.3.0` release which should be out in the next few days.

**Comment by tudor-coderz** [comment]
>I'm currently working on a way to simplify this
Thank you!! <3

**Comment by atomiks** [comment]
In v4.3.0+

```js
tippy(innerImageElement, {
  triggerTarget: outerButtonElement
})
```
