### ISSUE TITLE
Hide tooltips and remove all instances

### ISSUE THREAD

**Issue by Kearsan** [atomiks/tippyjs#473]
Hi,

First of all, thank you for this amazing plugin.

I'm loading each page of my website via ajax, this way the user never refresh the document. But of course I've to take care of memory overload on client side since JS is not cleaned up during navigation between pages.

So it's why I'm asking if there is a way to hide all tooltips and destroy all instances. The idea is to reinit tippy when the user load a new content.

Thanks for your help and keep up the good work!

**Comment by atomiks** [comment]
## Option 1

Note: does not handle nodes with multiple tippys:

```js
[...document.querySelectorAll('*')].forEach(node => {
  if (node._tippy) {
    node._tippy.destroy();
  }
});
```

## Option 2

Keep some global variable:

```js
window.tippyInstances = [];
```

Every time you call `tippy()`, push the instances into it

```js
const instances = tippy('.button');
window.tippyInstances = tippyInstances.concat(instances);
```

When you want to destroy it:

```js
tippyInstances.forEach(instance => {
  instance.destroy();
})
```

**Comment by Kearsan** [comment]
Thanks a lot! I'll go with option 2 :)

**Comment by Volmarg** [comment]
Option 1 - `._tippy` works like a charm.
