### ISSUE TITLE
Trigger tooltip with event listener on element that already has tooltip

### ISSUE THREAD

**Issue by Null-Amount** [atomiks/tippyjs#474]
Using the tippy.js library (version 4.2.1), I'm trying to display a tooltip on a single element using event listeners. 

Currently I'm displaying tooltips when users hover over a `tippy('.menuButtons');` and the tooltip text is being auto-populated from an attribute I've given my elements that looks like `data-tippy-content: "myTooltipText"`.

I've recently added a new element in the `.menuButtons` class called `#newMenuItem` and want to display it when the user does certain actions using event listeners that I already have implemented. 

Looking through the documentation, I see that there's a `trigger` option in which I can set the type to `manual` to display it that way, however, I'm not sure how to go about it. 

In my JS file, for tippy I have the following:
````javascript
	function applyTooltips()
	{
		tippy.setDefaults(
			{
				placement: "top-start",
				animation: "fade",
				duration: 500,
				arrow: true,
				size: "large",
				theme: "light",
			}
		);
		tippy('#newMenuItem',
			{
				trigger: "manual",
				content: "This is a new feature! Try it out today."
			});
		tippy('.menuButtons'));
	}
````
I'm unsure of:

a) Since #newMenuItem already has a tippy when you hover over it, if you can create a new tippy that appears there on eventlisten as well. Or will the customized attributes of the new tippy cause the default on-hover tippy to disappear/not display the on-hover text defined in the `data-tippy-content` attribute in the HTML. 

b) How to define what the `manual` trigger is (i.e. when a user does a specific action, display the tippy)

To test, I've tried just creating a new function that looks like this:
```javascript
function testTooltip()
{
    tippy('#newMenuItem');
}
````
but now the default on-hover tooltip doesn't appear, and a tooltip doesn't appear when I try to call `testTooltip()` in the console. I've also tried `tippy('#newMenuItem').show();` to no avail.

**Comment by atomiks** [comment]
So I'm not 100% sure what you're asking here, but hopefully this will help:

a) To attach multiple tippys to a single reference element, make sure you add the option `multiple: true`

b) You need to call the `.show() / .hide()` on the instance

```js
tippy.setDefaults({
  placement: 'top-start',
  animation: 'fade',
  duration: 500,
  arrow: true,
  size: 'large',
  theme: 'light',
});

// This will be the default on-hover tippy
tippy('.menuButtons', {
  multiple: true,
});

// This will be the custom manually-controlled tippy
const el = document.querySelector('#newMenuItem');
const newMenuItemTippy = tippy(el, {
  trigger: 'manual',
  content: 'This is a new feature! Try it out today.',
  multiple: true,
});

// Now call `newMenuItemTippy.show()` or `newMenuItemTippy.hide()` when need be. 
// I'm not sure what you're actually doing, so this is up to you
```

**Comment by atomiks** [comment]
So I'm not 100% sure what you're asking here, but hopefully this will help:

a) To attach multiple tippys to a single reference element, make sure you add the option `multiple: true`

b) You need to call the `.show()` / `.hide()` methods on the instance

```js
tippy.setDefaults({
  placement: 'top-start',
  animation: 'fade',
  duration: 500,
  arrow: true,
  size: 'large',
  theme: 'light',
});

// This will be the default on-hover tippy
tippy('.menuButtons', {
  multiple: true,
});

// This will be the custom manually-controlled tippy
const el = document.querySelector('#newMenuItem');
const newMenuItemTippy = tippy(el, {
  trigger: 'manual',
  content: 'This is a new feature! Try it out today.',
  multiple: true,
});

// Now call `newMenuItemTippy.show()` or `newMenuItemTippy.hide()` when need be. 
// I'm not sure what you're actually doing, so this is up to you
```

**Comment by Null-Amount** [comment]
Is it possible to call the `.show()` method from outside the instance?

I have them initializing from within the `applyTooltips()` function. However, I can't call `newMenuItemTippy.show()` from a separate function since it's outside of the scope of the variables `el` and `newMenuItemTippy`.

**Comment by atomiks** [comment]
`ignoreAttributes: true`
