### ISSUE TITLE
Hide tooltip properly

### ISSUE THREAD

**Issue by Kearsan** [atomiks/tippyjs#476]
Hello,

In some situations I want to hide the tooltip properly, for example when you can click in the tooltip to open a popup. Currently when I click in the tooltip (a tooltip triggered by click), the tooltip remain visible. If I set `$('.vktip-popper').hide();` to hide the tooltip, the tooltip can't be reopened then. If I set `$('.vktip-popper').remove();` it works but we have to click twice to reopen the tooltip. So I'm looking for a cleaner way to hide a tooltip.

Thanks for your help !

**Comment by atomiks** [comment]
I don't know what you're asking, please make a CodePen demonstrating your problem

**Comment by Kearsan** [comment]
I'm just asking to close tooltip on demand when it doesn't close automatically.

Here's a codepen : https://codepen.io/anon/pen/WWgqro

Click on the button to open the tooltip, click in the tooltip to open the popup, see that the tooltip remains open. I want to close the tooltip !

**Comment by atomiks** [comment]
You can utilize the `_tippy` property on popper elements

```js
$(document).on('click', '.open-popup', function(e) {
  $('.popup').show();
  $(e.target).closest('.tippy-popper')[0]._tippy.hide();
});
```

**Comment by lyndseypadget** [comment]
I came across this issue because I wanted to hide the tippy x ms after the click (and tippy show) occurred.  In case it's helpful for someone, I have a slightly different, JQuery-free solution.

```
  tippy('#searchButton', {
    content: 'heyo',
    trigger: 'click'
  });

  let searchButtonEl = document.getElementById('searchButton');
  searchButtonEl.onclick = function(e) {
    setTimeout(function(){
      let tippyId = e.target.getAttribute('aria-describedby');
      let tippyEl = document.getElementById(tippyId);
      tippyEl._tippy.hide();
    }, 2000);
  };
```
