### ISSUE TITLE
Programatically show tippy anywhere on screen

### ISSUE THREAD

**Issue by IonutArhire** [atomiks/tippyjs#478]
Hi. I've got an issue with trying to open up a tippy programatically and the documentation doesn't cover it (as far as I am aware). I want to be able to open a tippy after 1s, and it should position itself at the cursor.

html:
```
<div id="popover">
        test
</div>
```

js:
```
const body = document.getElementsByTagName('body');
const template = document.getElementById('popover');

const instance = tippy(body, {
    arrow: true,
    content: template,
    followCursor: 'initial',
    interactive: true,
    trigger: 'manual',
});

setTimeout(() => {
    instance.show();
}, 1000);
```

As you can see, I made sure to set followCursor to "initial" so that it opens up at the cursor position, and that I set the trigger to 'manual'. What happens is that the popover is always shown, not inside the tippy, but as a regular html element.

**Comment by atomiks** [comment]
Your `body` variable is a HTMLCollection, not a NodeList or Element type which are the ones tippy accepts. So it won't work like that - use `document.body` instead.

You can use a mousemove listener on the document + [virtual reference element](https://atomiks.github.io/tippyjs/misc/#virtual-elements) for this

```js
const instance = tippy({}, options);

document.addEventListener('mousemove', ({ clientX, clientY }) => {
  Object.assign(instance.reference, {
    clientWidth: 0,
    clientHeight: 0,
    getBoundingClientRect: () => ({
      top: clientY,
      bottom: clientY,
      left: clientX,
      right: clientX,
    })
  });
});

setTimeout(() => {
  instance.show();
}, 1000);
```

**Comment by atomiks** [comment]
Your `body` variable is a HTMLCollection, not a NodeList or Element type which are the ones tippy accepts. So it won't work like that - use `document.body` instead.

You can use a mousemove listener on the document + [virtual reference element](https://atomiks.github.io/tippyjs/misc/#virtual-elements) for this

```js
const instance = tippy({}, options);

document.addEventListener('mousemove', ({ clientX, clientY }) => {
  Object.assign(instance.reference, {
    clientWidth: 0,
    clientHeight: 0,
    getBoundingClientRect: () => ({
      width: 0,
      height: 0,
      top: clientY,
      bottom: clientY,
      left: clientX,
      right: clientX,
    })
  });
});

setTimeout(() => {
  instance.show();
}, 1000);
```

**Comment by IonutArhire** [comment]
Thank you very much. Didn't see that part in the Misc section about virtual references.
