### ISSUE TITLE
How can i add this to an Electron app?

### ISSUE THREAD

**Issue by schroef** [atomiks/tippyjs#479]
I just found this on the webs and like it a lot. I first used data-title in an Electron app but run inito issues when its to close to the borders of the app.

I tried adding this but nothing is showing. Im using all the basic elements according to the example page. Than in the index.html ive place the 3 scripts above the end body tag

**Comment by Arkellys** [comment]
Can you describe the issue you are encountering a bit more?
I am using the library with Electron as well and I didn't see any problem.

**Comment by schroef** [comment]
Ill try to explain it as good as possible. I used the code I found on the FAQ page where it says the add the 2 scripts, poppy and tippy, at the bottom of the page. Below that is the script tippy('button'). This is the index.html which is used as the base from the app. Than in the buttons inside tax files which generate content in the app in the the HT l page I've add data-tippy="test something".

When I tedt the app with either development or package mode through visual studio code. The first time I got a warning from my app which checks outgoing links. That how I know the links at the bottom did fire. But I don't see a hover appear over buttons. 

Could it be that other items like popuoit or fallout inside the app are blocking it?

**Comment by Arkellys** [comment]
I am not sure how you are rendering your HTML, but did you try using `data-tippy-content` instead of `data-tippy`?

As settled in [Auto-initialization](https://atomiks.github.io/tippyjs/creating-tooltips/#auto-initialization) section of the doc:

> If your web page has regular server-rendered HTML, and you aren't using a front-end framework like React or Vue, then you can bypass the function call and use the data-tippy attribute

When using `data-tippy` the tooltip is created automatically while using `data-tippy-content` require a `tippy()` function call.

**Comment by schroef** [comment]
Sorry im kinda new to this app building. Im using something which is build by Electron and also uses React parts.

Perhaps i need to pass on this untill i understand how to add this properly.

**Comment by Arkellys** [comment]
If you are using React maybe you should take a look at [Tippy.js for React](https://github.com/atomiks/tippy.js-react)

**Comment by schroef** [comment]
Thanks, i think the app is indeed. Ill check out that info. sorry for the fuzz
