### ISSUE TITLE
Tippy flickers on the border of an anchor element in a shadow DOM

### ISSUE THREAD

**Issue by andreasvirkus** [atomiks/tippyjs#480]
This occurs with version `tippy.js@4.2.1`.
It's quite cumbersome to create a separate repl, since I'm using Tippy in a browser extension's content script which injects a custom element/web component - so the Tippy is isolated in a shadow DOM. I don't see the same behaviour in a normal browser environment (Tippy is used in the same exact Vue component in both scenarios). I'll share a GIF and will start working on the repl if it's still necessary:

![flicker](https://user-images.githubusercontent.com/9140811/56961576-c3f09d00-6b5c-11e9-815d-1d1a43e4bde7.gif)
(the flickering happens at a much faster frequency than indicated in the low-FPS GIF)

The tippies are initiated like this:
```
const tooltips = this.$el.querySelectorAll('.rate-tippy')

;[].forEach.call(tooltips, tooltip => {
  if (!tooltip || tooltip._tippy) return
  tippy(tooltip, {
    content: tooltip.querySelector('[data-template]'),
    appendTo: tooltip.closest('.categories'),
    theme: 'light',
    placement: 'top',
    duration: 0,
    arrow: false,
    animateFill: false,
    popperOptions: {
      modifiers: {
        preventOverflow: {
          boundariesElement: 'window',
          escapeWithReference: true
        }
      }
    }
  })
})
```

and the relevant element/anchor:
```
<div class="rate-tippy">
  <label>
    <thumbs-up-icon class="icon-m"/>
    <input type="radio">
  </label>
  <div data-template>
    <div>
      <ul v-if="category.goodReviewCount > 0">
        <li v-for="(person, i) in category.goodReviewPersons" :key="i" v-text="person"></li>
      </ul>
      <span v-else>Not rated</span>
    </div>
  </div>
</div>
```

**Comment by andreasvirkus** [comment]
I also tried stripping down the options passed in and still see the flicker (although not sure why I'm missing the dark theme's CSS here - I thought `import tippy from 'tippy.js'` should also include that?)

```
;[].forEach.call(tooltips, tooltip => {
  if (!tooltip || tooltip._tippy) return
  tippy(tooltip, {
    content: tooltip.querySelector('[data-template]'),
    appendTo: tooltip.closest('.categories')
  })
})
```

![minimal-options-flicker](https://user-images.githubusercontent.com/9140811/56962207-aa505500-6b5e-11e9-92cd-a38e5c1f9ee6.gif)

**Comment by atomiks** [comment]
I'm guessing the index CSS is not getting injected into the `<head>` properly (since it's inside a shadow DOM?) The `src/css.ts` injectCSS function might rely on the global owner document to work. But basically, you'll need `pointer-events: none` on `.tippy-popper` when it's not interactive

**Comment by andreasvirkus** [comment]
🤦‍♂ That did it! Thank you so much for a quick solution. And yes, I can see the tippy styles injected to the document's `head`.

![success](https://user-images.githubusercontent.com/9140811/56987088-25ccf900-6b95-11e9-93f5-13f1a2203b43.gif)

Would you be willing to consider using `Node.getRootNode()` to append the CSS to either the document's head tag or just to the shadow DOM's root?

**Comment by atomiks** [comment]
Yea I'm not sure how to fix it, a PR is welcome
