### ISSUE TITLE
Focus not set correctly : input type text + interactive: true

### ISSUE THREAD

**Issue by DarkMikey** [atomiks/tippyjs#481]
If you have an interactive tippy tooltip, a click to an input type textfield doesn't set the focus correctly, as this [codepen](https://codepen.io/toxy1337/pen/Lvobdo?editors=1010) shows. It does focus for a second though. It works for other input elements like radio, buttons, links, dropdowns and other tippys. 

Without interactive it works, but I have to user interactive set to true, in order to use buttons in my tooltip.

Would be glad if there was an option I could use, but it seems to me like a bug. Any ideas? :)

**Comment by atomiks** [comment]
In v4 all focus handling was removed in favor of letting the developer handle it if necessary, so this problem doesn't exist now.

In v3 (version in the CodePen) you can use `autoFocus: false`
