### ISSUE TITLE
Ability to pass custom style tag

### ISSUE THREAD

**Issue by jasondibenedetto** [atomiks/tippyjs#482]
I'm dealing with a specific case where I need to be able to query the style tag generated by tippy. Does anyone see any problems with adding an option here to allow for a custom style tag to be passed through, so that a class or id attribute could be added.

https://github.com/atomiks/tippyjs/blob/dce36f820ce22d0a68a21f26fc387b0706c155a7/src/css.ts#L6-L19

**Comment by atomiks** [comment]
Interested to hear your specific case?

Also related: #480 - seems like this function could use some improvement

**Comment by jasondibenedetto** [comment]
I'm currently working on app that requires calling [stylesheet.disabled](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet/disabled) to remove some unwanted stylesheets (It's not ideal, but it's just the way it needs to be unfortunately). 

I'm using https://github.com/atomiks/tippy.js-react, and I just need a bit more control over the stylesheet element so I can prevent it from being disabled with the rest of the unwanted stylesheets. e.g.

```
<style type="text/css" class="app">.tippy { ... }</style>
```

I know it's a bit of an edge case feature, so I thought I'd just ask first.

**Comment by atomiks** [comment]
Can a hardcoded selector work:

`class="tippy-stylesheet"` (className)
or 
`data-tippy-stylesheet` (attribute)

Not sure which would be better?

**Comment by jasondibenedetto** [comment]
Yeah that should work as well. I would be happy either way, maybe class is more suited?

**Comment by jasondibenedetto** [comment]
Would you like me to make a PR?

**Comment by atomiks** [comment]
Ha yes was going to say if you wanted to, I think it's only one line but you can be added to the contributors 🙂

**Comment by jasondibenedetto** [comment]
https://github.com/atomiks/tippyjs/pull/483
