### ISSUE TITLE
issues with including tippy.js as a 3rd party library

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#484]
Tippy is amazing! I've used it on a few personal websites. 

I'd like to be able to use it in a 3rd party library ( a widget that is embedded on someone else's website.) One of the requirements of doing this is being able to namespace css declarations to reduce the likelihood of polluting global scope. Some questions around this:

* would it be possible to namespace all of the classes tippy declares? e.g., `.CUSTOM_NAMESPACE-tippy-tooltip { ... }`
*  Is it possible to embed another style into the tippy bundle (I don't want the dark theme baked in, I want one of the light themes.)

much thanks for a phenomenally good component!

**Comment by atomiks** [comment]
`tippy` acts as its own namespace (apart from `.dark-theme`, in that case you can set `theme: ''` or something else. For the light theme you need to reference its stylesheet separately

**Comment by mreinstein** [comment]
doesn't tippy already include the dark theme by default? It gets embedded into the tippy bundle, right?
Is there a way for me to instead build tippy with another theme embedded and set to the default?

**Comment by atomiks** [comment]
There's no `dark-theme` selector, that's just the base styling of `.tippy-tooltip`. The CSS is only 1.6 kB minzipped, and there are no selectors in the CSS not prefixed with `.tippy-*` so conflicts should be minimal

**Comment by mreinstein** [comment]
I hate to be a pest, but I think maybe the use case isn't clear. 

I'm embedding my component in someone else's website. That website has lots of other content on it that I don't control:
* if the the website already has tippy components on it, and they are themed differently, I don't want to affect the look of those, because it's someone else's content.
* these websites really don't like having their 3rd party integrations inject unprefixed styles directly into their documents. My organization has an assigned prefix (`e.g., all my classes and ids must start with `acme123-`)
* a given website frequently has several or dozens of these 3rd party components. asset space is a premium. I know 1.6 kb minzipped is very light, but it adds up.

Anyway, I know this is an extremely uncommon use case, I don't expect most people will run into these problems. I'm not expecting a big engineering effort to support this use case. I was just hoping that given there's not much css that maybe I could build my own copy by passing some parameters to rollup to namespace stuff, or at least replace the embedded theme.

Thanks again!

**Comment by atomiks** [comment]
The problem is all the elements have the `tippy-*` prefix hardcoded in the JS and CSS. If you don't want to run into edge cases then unfortunately a fork might be needed. 

Maybe maintaining your fork would be easier if we refactored it to use a prefix variable in the CSS and JS, so merging the upstream into your fork would have minimal or no conflicts each update?

**Comment by mreinstein** [comment]
> Maybe maintaining your fork would be easier if we refactored it to use a prefix variable in the
> CSS and JS, so merging the upstream into your fork would have minimal
> or no conflicts each update?

Yeah, perhaps! I looked at all of the `.ts` source files in tippy, and actually there are only 2 files that have hardcoded references to the `.tippy-` classes: `constants.ts` and `popper.ts`. Like maybe a dozen references total!

I'm wondering if we could use https://www.npmjs.com/package/rollup-plugin-replace to have an optional `NAMESPACE` option. Something like:

in rollup.config.js:
```javascript
const plugins = {
  replace: replace({
    __NAMESPACE__:  process.env.NAMESPACE || ''
  }),
  babel: babel({
    exclude: 'node_modules/**',
    extensions,
  }),
  minify: terser(),
  resolve: resolve({ extensions }),
  css: cssOnly({ output: false }),
  json: json(),
}
```

Then in the the code (constants.ts for example):
```javascript
export const POPPER_SELECTOR = '.__NAMESPACE__tippy-popper'
export const TOOLTIP_SELECTOR = '.__NAMESPACE__tippy-tooltip'
export const CONTENT_SELECTOR = '.__NAMESPACE__tippy-content'
export const BACKDROP_SELECTOR = '.__NAMESPACE__tippy-backdrop'
export const ARROW_SELECTOR = '.__NAMESPACE__tippy-arrow'
export const ROUND_ARROW_SELECTOR = '.__NAMESPACE__tippy-roundarrow'
```

And then when building tippy, I could do this:

```bash
NAMESPACE=Acme-123 npm run build
```
I didn't prototype out or think through how the `.scss` would be handled, but I'm sure there must be a similar plugin/namespacing capability for that part too.

I think something like this would actually be enough that I wouldn't have to fork tippy, I could just build my own bundle with whatever namespace I want. 

Thoughts? Is this crazy?

**Comment by mreinstein** [comment]
@atomiks now that we have an elegant mechanism for passing configuration options to the npm build command, do you think it's reasonably to add a config to set the embedded theme? I'm thinking something like this:

```javascript
NAMESPACE=Acme-123 THEME=light-border npm run build
```

**Comment by mreinstein** [comment]
If this is a lot of work, it's not a show-stopper for me. The fact that I can generate namespaced stylesheets means I can pull them in without fear of interfering with stuff already on the web page. This is definitely in the nice-to-have-but-not-crucial bucket. :)

**Comment by atomiks** [comment]
> This is definitely in the nice-to-have-but-not-crucial bucket

Yeah it seems like it might be a bit difficult. I probably won't work on it but feel free to make a PR if necessary 🙂

**Comment by mreinstein** [comment]
> I probably won't work on it 

No worries, I can live without it. Thanks again for all of your hard work!
