### ISSUE TITLE
Weird CSS behavior on example.com

### ISSUE THREAD

**Issue by miketheman** [atomiks/tippyjs#488]
Hello!

I've been exploring your interesting library, in hopes of incorporating it into a Chrome Extension I'm playing around with, and the simple interface appears really nice.

As part of evaluation, I've been using tippy to add a tooltip to either existing text in a page, or even adding a new element to test this out.

Sample JS:
```javascript
  const newSpan = document.createElement("span")
  newSpan.className = "new-tooltip"
  newSpan.textContent = "blah"
  newSpan.setAttribute("data-tippy-content", "flargle raggle")
  document.body.appendChild(newSpan)

  ...

  // Initialize all Tippys:
  const els = document.querySelectorAll(".new-tooltip")
  console.log(els)
  tippy(els, { interactive: true, arrow: true })
```

When running this against https://example.com - this is the type of visual element created:

<img width="158" alt="Screenshot 2019-05-05 08 07 04" src="https://user-images.githubusercontent.com/529516/57193763-ceb88280-6f0c-11e9-88b6-430bb92278f5.png">

This led me on a wild goose chase, thinking I was doing something wrong, when I tried a different page, and everything works just fine (whew!).

I don't know exactly what's going on here, and totally understand that your library can't account for whatever this site may be producing - but I figured I'd let you know and see if there's something I can do to help figure out what's going on.

**Comment by atomiks** [comment]
Probably because they target the `div` selector (no scoping) and apply some styles to it, which messes it up, since tippy uses divs

![view source:example.com](https://i.gyazo.com/1af2258b5e3c15c5258ef75bc92ab34b.png)

**Comment by miketheman** [comment]
Ah - so if I understand this correctly, Tippy is creating new `div` elements on the fly, and they are being mangled by the page's top-level `div` declaration?
I'm guessing that's not a common behavior, right?

**Comment by atomiks** [comment]
Yes basically. If you're in control of a site, you probably aren't going to apply global width/color to all divs, and instead leave that selector empty, so Tippy won't be affected. In the case of a 3rd party extension, you aren't in control of their CSS so if they're adding global styles like that then it will be affected..

Adding this might work:

```css
div[class^='tippy'] {
  all: initial;
}
```

**Comment by miketheman** [comment]
Makes total sense. I tried out this snippet, as well as changing to `all: unset` - but that then appears to break Tippy a bit.

Initial:

<img width="182" alt="Screenshot 2019-05-05 08 51 15" src="https://user-images.githubusercontent.com/529516/57194282-13471c80-6f13-11e9-8776-6278d90b3f51.png">

It's better than before, but gives me a way to continue to poke at the problem if I discover it on another real site within the scope of my extension (it's not meant to run on every web page).

Thanks for helping me understand what's going on here, and for your cool library!

**Comment by atomiks** [comment]
I think you'll need to ensure that rule gets placed before Tippy's stylesheet, but also after the site's own styles (at the bottom of the page?)

`index.all.js` will inject tippy's styles to the top of `<head>`, so you'll need to use the `index.css` stylesheet separately + `index.js`
