### ISSUE TITLE
Tippy version 2.6.0 has no dist folder!

### ISSUE THREAD

**Issue by senterright** [atomiks/tippyjs#492]
Hi, the 2.6.0 release seems to have removed the dist folder

https://github.com/atomiks/tippyjs/releases/tag/v2.6.0

we're just locking it to 2.5.4, but it seems like maybe you're using a new release process.

i tried referencing the src/js directly, but the styles are missing so i need dist/tippyjs.all or whatever i was.

here's the folder that exists in 2.5.4 but is missing in 2.6.0

https://github.com/atomiks/tippyjs/tree/v2.5.4/dist

thanks!

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/issues/310
