### ISSUE TITLE
Custom Animation

### ISSUE THREAD

**Issue by ckizer** [atomiks/tippyjs#493]
How would I go about customizing the animations? I'd love to shorten the shift-away animation and make it more subtle but I'm having trouble figuring out how to get started.

Does it support CSS animations?

**Comment by atomiks** [comment]
https://atomiks.github.io/tippyjs/misc/#custom-animations

**Comment by ckizer** [comment]
Thank you so much. I'd love to see it moved from in the documentation from navitem misc to a new nav item called animations. I looked but couldn't find the animation section when I looked under "all options". **Thanks again!**

**Comment by atomiks** [comment]
I have some plans for better animation integration etc soon.

**Comment by atomiks** [comment]
Improved custom animations support in 5.0
