### ISSUE TITLE
Content transition animation

### ISSUE THREAD

**Issue by Alecyrus** [atomiks/tippyjs#494]
For now, the height of popper will adjust to its content instantly, so it seems abrupt. Is it possible to animate the change of height smoothly.

**Comment by atomiks** [comment]
Yes, take a look at the `AJAX` page (down the very bottom, you'll see the example), there's a CodePen link. 

I'm working on some things that will make all of this stuff (particularly all animations, including integrating with FLIP libraries and using spring animations) more seamless for the next major. This is definitely a missing area that needs to be solved.

**Comment by Alecyrus** [comment]
@atomiks Actually, if the content could be a reactive web component (Vue, React, Angular...) , all animation on the content changes could be implemented easily through computed parameters and css transitions rather than operating DOM properties directly (element.style.width...).

I try that before, binding computed parameter `contentHeight`  calculated by the actual content  size to `style` property of  the content DOM element, and applying `transition: height 0.3s ease` on the content dom element. But it does not work, 

In a word, I do not know how to use tippyJS in `Vue` project for some advanced scenarios. Like `floating menu with dynamic content`

**Comment by Alecyrus** [comment]
Yeah, it works. Now I know how to animate popper when content changes. Thank you, @atomiks .

**Comment by atomiks** [comment]
How'd you do it? (for future visitors)

**Comment by Alecyrus** [comment]
As I just mentioned above, using computed property and css transitions. The reason why I failed to implement it before is that I use it in a wrong way.  So in theory,  we can using some framework features that Vue, React and Angular supports, like computed property to control the popper content dynamically and reactively, including animating and changing content.
