### ISSUE TITLE
For Dynamic tippy DOT come on tippy tooltip

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#495]
I using tippy in my angular app, its work fine for me 
but when I apply **dynamicTitle** property then small dot come in tooltip

` <a (click)="preserveState();" [attr.title]="ds.name" appTooltip [options]="{ dynamicTitle: true }">{{ds.name}}</a>`

![test2](https://user-images.githubusercontent.com/10737306/57859963-97ea4280-7811-11e9-99b4-241301db6375.png)

**Comment by atomiks** [comment]
`dynamicTitle` is a v2 option which isn't being maintained anymore

**Comment by gomteshhatgine** [comment]
So How can I implement Dynamic title using Tippy in angular

**Comment by atomiks** [comment]
Vanilla:

```js
const instance = tippy(element, {
  content: 'tooltip content here'
});

// Later on
instance.setContent('new content here');
```

In React, this is achieved via `componentDidMount` / `componentDidUpdate` lifecycles or the `useEffect` hook. I don't know Angular so unfortunately I can't help there
