### ISSUE TITLE
Uncaught TypeError: t is not a constructor

### ISSUE THREAD

**Issue by Archmonger** [atomiks/tippyjs#496]
## Bug description
![image](https://user-images.githubusercontent.com/16909269/57967428-a1f46a00-7913-11e9-8131-09a21e6046e4.png)

For some reason Tippy causes this error in console. This does not appear every time, perhaps every 1 out of 4 times I visit my site. Not entirely sure what it's caused by but just looking for a solution.

## Reproduction
It is currently being used like this.
```js
$.getScript('https://unpkg.com/popper.js');
$.getScript('https://unpkg.com/tippy.js', function() {
	tippy(".allTabsList", {
		placement: 'right',
		boundary: document.getElementById('page-wrapper'),
		touch: false,
		theme: 'bbf'
	})
});
```

**Comment by KubaJastrz** [comment]
Maybe tippy gets loaded before popper in those cases?

**Comment by Archmonger** [comment]
I'll try throwing it into a promise like this. Will report back on if that fixed it.
```js
var getTippy = new Promise(function() {
	$.getScript('https://unpkg.com/tippy.js', function() {
		tippy(".allTabsList", {
			placement: 'right',
			boundary: document.getElementById('page-wrapper'),
			touch: false,
			theme: 'bbf'
		})
	});
});

var getPopper = new Promise(function() {
	$.getScript('https://unpkg.com/popper.js');
});

getPopper.then(getTippy);
```

**Comment by Archmonger** [comment]
Just tested, That did not seem to fix it.

**Comment by KubaJastrz** [comment]
Don't you need to resolve the promise in the $.getScript callback?

**Comment by atomiks** [comment]
Yeah, you need to make sure `tippy.js` is always loaded after `popper.js`, without any race conditions

This should work:

```js
function onTippyScriptLoaded() {
  tippy(".allTabsList", {
    placement: 'right',
    boundary: document.getElementById('page-wrapper'),
    touch: false,
    theme: 'bbf'
  });
}

$.getScript('https://unpkg.com/popper.js', function() {
  $.getScript('https://unpkg.com/tippy.js', onTippyScriptLoaded);
});
```

**Comment by atomiks** [comment]
Also you need to be adding the version numbers `popper.js@1` and `tippy.js@4` otherwise when a new major is published for either your site will break.

**Comment by Archmonger** [comment]
Yeah my bad, new to JS. This seemed to fix it.
```js
$.getScript('https://unpkg.com/popper.js@1', function() {
	$.getScript('https://unpkg.com/tippy.js@4', function() {
		tippy(".allTabsList", {
			placement: 'right',
			boundary: document.getElementById('page-wrapper'),
			touch: false,
			theme: 'bbf'
		});
	});
});
```

**Comment by colepeters** [comment]
I'm running into this same issue, but I'm using Tippy via yarn and including it in my application scripts in a Rails app.

I'm requiring Tippy in my application.js:
```js
//= require tippy.js/umd/index.all.min.js
```

And my view is (apologies for the Slim markup):
```slim
button.pointer.js-mobileMenuTrigger
  span.fal.fa-bars.width3.pr2
  span.fw600 Menu

#test-content style='display: none'
  <strong>Here</strong> is some test content

javascript:
  tippy('.js-mobileMenuTrigger', {
    content: document.querySelector('#test-content').innerHTML,
    interactive: true,
    trigger: 'click'
  })
```

When I click my button, I get:

![image](https://user-images.githubusercontent.com/1713932/63546642-e03f8d80-c4ef-11e9-9795-dbe355f1f44b.png)

**Comment by colepeters** [comment]
Update: I've fixed this by installing Popper as a dependency and including it along with Tippy in my application.js:

```js
//= require popper.js/dist/umd/popper.min.js
//= require tippy.js/umd/index.all.min.js
```

This seems weird to me though, as Popper is already a dependency of Tippy. Is it not included in the Tippy bundles…?

**Comment by HShiDianLu** [comment]
Using version 2.x of Popper seems to also cause this issue. Tippy.js requires Popper version 1.x.
