### ISSUE TITLE
Tooltip hides on hover with "hideOnClick: false"

### ISSUE THREAD

**Issue by edgargaza** [atomiks/tippyjs#497]
## Bug description

When setting the `showOnInit: true` property along with `hideOnClick: false` property, when hovering the referenced element, the tooltip hides when the cursor leaves out of it.

## Reproduction

Try moving the cursor over the tooltip. How do you do to avoid hiding the tooltip when hovering?

https://codepen.io/anon/pen/aryoXb

**Comment by atomiks** [comment]
Are you trying to keep it visible permanently? You can use `trigger: 'manual'` and add your own event listeners that call the `.show()` / `.hide()` methods if needed

**Comment by edgargaza** [comment]
Yeah, it will work then. I couldn't find different triggers than click or focus. Thanks for the quick answer!
