### ISSUE TITLE
Problem with Safari (mobile)

### ISSUE THREAD

**Issue by lorraineS** [atomiks/tippyjs#498]
With the CDN, Tippy doesn't work on Safari IOS. 

```
[Error] Refused to execute https://unpkg.com/popper.js@1 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] Refused to execute https://unpkg.com/tippy.js@4 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.
[Error] ReferenceError: Can't find variable: tippy
	(fonction anonyme) (app.js:235)
```

So I wanted to install via NPM, but I do not know which file imported into the **@node_modules**.
I end up with an ESM folder, Themes, UMD, each with dozens of javascript files.

Is not there a simple .js file to import? I'm lost.. I have a very basic configuration without webpacker etc.

Thank you.

**Comment by atomiks** [comment]
Might be an unpkg problem

You can do `import tippy from 'tippy.js'` (if using something like Parcel), otherwise use the `umd/index.all.js` file

**Comment by atomiks** [comment]
https://github.com/unpkg/unpkg.com/issues/107
