### ISSUE TITLE
update() is not a function error

### ISSUE THREAD

**Issue by sefaYavuz** [atomiks/tippyjs#50]
The following code: 

```
$('#js-tooltip-project').attr('title', data.data);

const instance = new Tippy('.js-tooltip', {
position: 'right',
arrow: true
});

const popper = instance.getPopperElement(document.querySelector('#js-tooltip-project'));

instance.update(popper);
instance.show(popper);
```

```
<button class="js-tooltip" id="js-tooltip-project" title="x"></button>
```

Gives me the following error:

> Uncaught TypeError: instance.update is not a function

**Comment by atomiks** [comment]
Could you make a codepen that reproduces the problem?

There are no errors here: https://codepen.io/anon/pen/OmKeZL

**Comment by sefaYavuz** [comment]
Nevermind, was using a old version. It seems like this site ([cdnjs](https://cdnjs.com/libraries/tippy.js)) has version 0.3.0 as the latest version. 

Closing

**Comment by atomiks** [comment]
Use unpkg instead since it's synced with npm, allowing you to always use the latest version

**Comment by sefaYavuz** [comment]
Already switched to it, after this problem!
