### ISSUE TITLE
Unable to get one tooltip template working for multiple elements

### ISSUE THREAD

**Issue by mviens** [atomiks/tippyjs#500]
I have searched the issues and found [#99](https://github.com/atomiks/tippyjs/issues/99) and  [#89](https://github.com/atomiks/tippyjs/issues/89), but neither of those helped. I also looked at several Codepen's but nothing. The documentation overall is very good, but the examples need some work (as mentioned by [#405](https://github.com/atomiks/tippyjs/issues/405)).

I need a page where I will have multiple templates, which so far is working. In addition, I need those templates to be applied to multiple elements. What I am getting is only the last one is getting it. I have tried both with and without `.cloneNode()`, but neither work. Could you please let me know what I am doing wrong?

```
<!DOCTYPE html>
<html lang='en'>
    <head>
        <meta charset='UTF-8'/>
        <title>Tippy Playground</title>
        <style>
            html,body {font-family:Roboto,sans-serif;font-size:1em;}
            tt {color:royalBlue;font-size:1.4em;}
            #box {align-items:flex-start;display:flex;flex-wrap:wrap;justify-content:space-evenly;}
            .hide {display:none;}
        </style>
    </head>
<body>
    <h3>This is a simple test for Tippy.js tooltips</h3>
    <div id='box'>
        <button class='t1'>Tooltip #1</button>
        <button class='t1'>Tooltip #1</button>
        <button class='t2'>Tooltip #2</button>
        <button class='t2'>Tooltip #2</button>
    </box>
    
    <div class='hide'>
        <main id='myTip1'>
            A simple tooltip that contains very basic HTML, but is long enough to cause a line wrap - <tt>something special here</tt>.
        </main>
        <main id='myTip2'>
            This is tip #2.
        </main>
    </div>

    <script src="https://unpkg.com/popper.js@1"></script>
    <script src="https://unpkg.com/tippy.js@4"></script>
    <script>
        tippy.setDefaults({
            allowHTML: true,
            animation: 'scale',
            arrow: true,
            delay: [100, 0],
            flip: true,
            flipBehavior: ['bottom', 'top'],
            ignoreAttributes: true,
            maxWidth: '30em',
            multiple: true,
            placement: 'bottom-end',
        });
        tippy('.t1', {
            content: document.querySelector('#myTip1'),
        });
        tippy('.t2', {
            content: document.querySelector('#myTip2').cloneNode(true),
        });
    </script>
</body>
</html>
```

**Comment by atomiks** [comment]
What you're doing here is passing a single element (even though it's cloned) to `content`:

```js
tippy('.t2', {
  content: document.querySelector('#myTip2').cloneNode(true),
});
```

What you want instead is a function that returns a new one for each reference element:

```js
tippy('.t2', {
  content: () => document.querySelector('#myTip2').cloneNode(true),
});

// or
tippy('.t2', {
  content: document.querySelector('#myTip2').innerHTML,
});
```

**Comment by mviens** [comment]
Thank you, @atomiks. It worked perfectly.

**Comment by victorsilent** [comment]
Sorry to reopen the thread, but what is the workaroubd when your elemens are controller by a framework? I can't use cloneNode cuz It loses the event listeners.
@atomiks

**Comment by MatheusRich** [comment]
@atomiks How can I use a dynamic template?

What I'm attemping to do:
```
button1 => click -> display tooltip with google maps
button2 => click => update data => display tooltip with google maps but updated data
```
I wanna keep only one template because I have to keep event listeners.

**Comment by victorsilent** [comment]
@MatheusRich do you use any frontend framework?

**Comment by MatheusRich** [comment]
@victorsilent No. (actually Stimulus.js, but I think it won't be a problem)
