### ISSUE TITLE
html option for Tempale in tippy 4 using angular 

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#501]
I was previously using tippy 2.6.0

But due to few issues like dynamic title I using tippy 4 in my angular application for that I was using tippDirective in which I am passing parameter to tippy 

`<div appTooltip [options]="{ html:'#my-template-' + datasetId, maxWidth:'900px' }"> Test name</div>`

So from options i was passing parameter into directive
but in tippy  4 How can I pass Html template parameter like "html"  property in tippy 2  

TippyDirective  is:

`import { Directive, ElementRef, Input, OnInit, OnChanges } from '@angular/core';

@Directive({
  selector: '[appTooltip]'
})
export class TooltipDirective implements OnInit, OnChanges {

  @Input() options: object = {};
  @Input() titleText: any = '';

  public _el: any;
  public _host: any;

  constructor(el: ElementRef) {
    this._el = el.nativeElement;
    this._host = el.nativeElement;
  }

  ngOnInit() {
    this.detectHostNode();
    tippy(this._el, this.options);
  }

  // Re-create the tooltip on changes
  ngOnChanges(changes) {
    let commonOption = {content : this.titleText };
    let options = Object.assign(commonOption, this.options);

    // if (changes.options) {
    //   options = changes.options.currentValue;
    // }

    this.detectHostNode();

    tippy(this._el, options);
  }

  // Detects if the directive is placed on an angular component
  // host node. The tooltip will not display correctly, so
  // instead we will transfer all data-attributes and title to the first
  // child of the component.
  detectHostNode() {
    const attrs = this._el.attributes;

    let hostNode = false;
    for (let i = 0; i < attrs.length; i++) {
      if (attrs[i].name.indexOf('_nghost') > -1) {
        hostNode = true;
      }
    }

    if (hostNode && this._el.children.length > 0) {
      this._el = this._el.children[0];
      this.xferAttributes(this._host, this._el);
    }
  }

  // If we are transfering the tooltip from the host component
  // node to the first child node, we'll need to copy all the data attributes
  xferAttributes(fromEl: HTMLElement, toEl: HTMLElement) {
    const daList = [
      'position',
      'trigger',
      'interactive',
      'interactiveborder',
      'delay',
      'animation',
      'arrow',
      'arrowsize',
      'animatefill',
      'duration',
      'html',
      'size',
      'distance',
      'theme',
      'offset',
      'hideonclick',
      'multiple',
      'followcursor',
      'inertia',
      'flipduration',
      'sticky',
      'stickyduration',
      'appendto',
      'zindex',
      'touchhold',
      'performance',
      'dynamictitle',
      'popperoptions'
    ];

    // Copy data attributes from the input element to the target element
    daList.forEach(da => {
      if (fromEl.dataset[da]) {
        toEl.dataset[da] = fromEl.dataset[da];
      }
    });

    if (fromEl.hasAttribute('title')) {
      toEl.title = fromEl.title;
      fromEl.title = '';
    }
  }
}
`

**Comment by gomteshhatgine** [comment]
Reolved problem

**Comment by gomteshhatgine** [comment]
But using 
 const template = document.getElementById(this.options['html'])
      delete this.options['html']
      this.options['content'] = template.innerHTML
      let options = Object.assign(commonOption, this.options);

problem get solved but page rendering is too slow as compare to "html" option in tippy 2

**Comment by atomiks** [comment]
Can you post a performance profile screenshot with DevTools to see what's slowing down?

**Comment by gomteshhatgine** [comment]
I mean sorting is done faster as like previously but that html rendering takes some time to reflect after adding tippy 4
![image1](https://user-images.githubusercontent.com/10737306/58260109-80700400-7d93-11e9-9c9a-1c97985b68e3.png)

**Comment by atomiks** [comment]
#502 
Feel free to post repro case but for now can't debug the rendering perf and likely isn't tippy's fault anyway

**Comment by gomteshhatgine** [comment]
Yes Thanks for reply
I had seperatley tried for reproduce issue with table sorting rendering here,

https://stackblitz.com/edit/hello-angular-6-tpd9bw?file=src%2Fapp%2Fapp.component.ts

but there I didnt found issue with tippy, So that I checked with angular rendering issue
So in my case I need manually trigger for change detection in angular like
`  this.ref.detectChanges();`
is solve my problem
