### ISSUE TITLE
Redering become slow when use for list pages: tippy 4

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#502]
## Bug description
Previuosly I was using  "tippy.js": "^2.6.0 in my angular application. it was working fine for list page i.e on every row of table tippy is used.
But due to issue for dynamic title in table rows, I am trying to use tippy 4 then it is working as I expected using tippy 4

but new issue found that when I try to **sort table column** then rendering goes slow which is not happen with tippy 2

what exactly goes wrong i.e. rendering table containg tippy goes slow when sorting columns of table 
Work fine for tippy 2 but issue in tippy 4

**Comment by gomteshhatgine** [comment]
I mean sorting is done faster as like previously but that html rendering takes some time to reflect after adding tippy 4
![image1](https://user-images.githubusercontent.com/10737306/58260051-6504f900-7d93-11e9-9bc8-18cb6957cef0.png)

**Comment by atomiks** [comment]
This isn't really possible for me to debug without a reproduction case..

It very likely isn't a problem with tippy anyway but the wrapper/technique you've created

**Comment by gomteshhatgine** [comment]
Yes Thanks for reply
I had seperatley tried for reproduce issue with table sorting rendering here,

https://stackblitz.com/edit/hello-angular-6-tpd9bw?file=src%2Fapp%2Fapp.component.ts

but there I didnt found issue with tippy, So that I checked with angular rendering issue
So in my case I need manually trigger for change detection in angular like
`  this.ref.detectChanges();`
is solve my problem
