### ISSUE TITLE
tippy doesn't position where I'd expect with large html content

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#503]
## Bug description
I have single tippy element on a page (the red image is the button that the tippy is attached to.)
<img width="909" alt="Screen Shot 2019-05-22 at 2 14 08 PM" src="https://user-images.githubusercontent.com/718067/58209589-2e988280-7c9c-11e9-98e1-a908c487c7da.png">

actual result:
<img width="912" alt="Screen Shot 2019-05-22 at 2 14 16 PM" src="https://user-images.githubusercontent.com/718067/58209629-407a2580-7c9c-11e9-9a40-c38b0ff4ffca.png">

expected result:
<img width="413" alt="Screen Shot 2019-05-22 at 2 21 54 PM" src="https://user-images.githubusercontent.com/718067/58209979-ff364580-7c9c-11e9-8cfa-9cbc6260e96f.png">

My config:
```javascript
const button = document.createElement('button');
button.setAttribute('style', `
                position: absolute;
                left: 364px;
                top: 149px;
                border-radius: 26px;
                width: 32px;
                height: 32px;
                z-index: 1;
            `);
const config = {
    arrow: true,
    flipOnUpdate: true,
    interactive: true,
    boundary: 'viewport',
    theme: 'light-border',
    trigger: 'click',
    zIndex: 999999
};

tippyInstance = tippy(button, config);

const productDetail = document.createElement('div');
productDetail.innerHTML = `bunch of stuff in here to flesh out the tippy content`;

tippyInstance.setContent(productDetail);
document.body.appendChild(button);
```

Is this a bug, or am I mis-configuring this?

**Comment by atomiks** [comment]
Maybe it's the `boundary: 'viewport'`?

**Comment by mreinstein** [comment]
I just found the `popperOptions` field, and _this_ works!

```javascript
const config = {
    arrow: true,
    flipOnUpdate: true,
    interactive: true,
    boundary: 'viewport',
    popperOptions: {
       placement: 'auto'
    },
    theme: 'light-border',
    trigger: 'click',
    zIndex: 999999
};
```

<img width="488" alt="Screen Shot 2019-05-22 at 3 24 23 PM" src="https://user-images.githubusercontent.com/718067/58213081-bc2ca000-7ca5-11e9-9312-0f004726d9a4.png">

I'm suprised that this is not the default setting for the underlying popper as it seems to magically just make the position work.

 I have a new problem, I'm trying to dynamically load the popper contents upon first open of it. Here's my current attempt:

```javascript
const button = document.createElement('button');

const config = {
    arrow: true,
    flipOnUpdate: true,
    interactive: true,
    boundary: 'viewport',
    popperOptions: {
       placement: 'auto'
    },
    theme: 'light-border',
    trigger: 'click',
    zIndex: 999999
};

const tippyInstance = tippy(button, config);

let productDetail;

button.onclick = function (ev) {
   if (!productDetail) {
      productDetail = document.createElement('div');
      productDetail.innerHTML = `... html content in here ...`;
       tippyInstance.setContent(productDetail);
       tippyInstance.show();
   }
}

```

what I see on first click:
<img width="454" alt="Screen Shot 2019-05-22 at 3 28 34 PM" src="https://user-images.githubusercontent.com/718067/58213263-5260c600-7ca6-11e9-8448-4d80a93bcd4f.png">

Any ideas?

**Comment by atomiks** [comment]
`placement: 'auto'` (not nested in `popperOptions`) should also work btw 😛 

As for the new problem, does that only happen on first click? Seems like the position isn't being updated even show it should (by both `.setContent()` and `.show()`). Can you make a CodePen reproducing it?

**Comment by mreinstein** [comment]
Yeah I'll put a codepen together tonight. It might be challenging because there's a lot of junk running on these pages, but I'll try to isolate the minimum example with the problem.

thanks for your help!

**Comment by mreinstein** [comment]
Here's the codepen that I have so far https://codepen.io/anon/pen/XwZLQy

only certain dimensions of the preview pane seem to exhibit the problem.

I'm wondering if this is caused by media within the html content not being fully loaded when show is called, and that in turn causes the popover to not have the right dimensions to position itself?

**Comment by mreinstein** [comment]
> placement: 'auto' (not nested in popperOptions) should also work btw

It seems that `placement: auto` and `{ popperOptions: { placement: 'auto' } }` seems to have slightly different behavior, which I've also explored in the codepen

**Comment by atomiks** [comment]
> I'm wondering if this is caused by media within the html content not being fully loaded when show is called, and that in turn causes the popover to not have the right dimensions to position itself?

Yeah that would be the reason, so the `sticky: true` option solves the problem. As for `placement` being different, I'll check it out later

**Comment by mreinstein** [comment]
> sticky: true option solves the problem

oh, how does that solve the problem? I'm not familiar with the behavior of that option

**Comment by atomiks** [comment]
It updates the position of the tippy on every animation frame, even if it might not need to be. If performance is fine, you can use it

**Comment by atomiks** [comment]
So it looks like `placement: 'auto'` retains the `auto` placement forever, but `popperOptions.placement: 'auto'` reverts back to a basic placement after the first show. I know why the second one is broken but not sure it matters to fix it since the base-level option works fine?

To recap:

- Use `sticky: true` if your tippy can change its size while showing at any point (e.g. dynamic image loading) but isn't the result of calling `.setContent()`
- Use the base option `placement: 'auto'` instead of `popperOptions.placement: 'auto'` for actual auto behavior
- Change `boundary: 'viewport' or 'window'` depending on the type of behavior you want here

**Comment by mreinstein** [comment]
thank you for the clarification! 

> `popperOptions.placement: 'auto'` reverts back to a basic placement after the first show

One thing that might be nice is to detect when placement is set in the `popperOptions` and "hoist" the `placement` option up. I'm having trouble envisioning a scenario when one would want only the first placement to be auto and then revert back to basic placement. Kind of an unexpected API behavior.

thanks a lot for digging in on this, super helpful!

**Comment by atomiks** [comment]
It's a bug technically but since it's not a core base-level option and it's already covered by `placement` it's not a priority for now... 🤪
