### ISSUE TITLE
setcontent method showing tippy and tooltips both, it should show only tippy

### ISSUE THREAD

**Issue by gomteshhatgine** [atomiks/tippyjs#505]
## Bug description
I had made wrapper changes for tippy.s to use in my angular 6 application.
but when I dynamically changing the content of tippy then change is reflected but showing HTML tooltip as well

like in image on hover of **8** it is showing both tippy and tooltip

![111](https://user-images.githubusercontent.com/10737306/58347121-ac19e980-7e7a-11e9-9425-404c184e050c.png)

 
## Reproduction
I had reproduced the issue in below link 

stackblitz link: https://stackblitz.com/edit/hello-angular-6-jucmgt?file=src%2Fapp%2FTooltipDirective.ts

in third column name **Count** showing two toolips.

in above code link I had added evenListner funtion for mouseover event i.e for this event content will update in **ngOnChanges** method 

     `this._el.addEventListener('mouseover', function () {
 
       tippy(this, { content: this.title })
        this._tippy.setContent(this.title)
      });`

please help

**Comment by atomiks** [comment]
Avoid the `title` attribute, use a `data-tippy-content` attribute instead

**Comment by gomteshhatgine** [comment]
But how can I bind for **data-tippy-content** in angular code

`data-tippy-content="{{el.count}}" `

and 

`data-tippy-content="el.count" `

because both syntax not working

**Comment by atomiks** [comment]
You need to get the attribute like you were doing with the title

**Comment by gomteshhatgine** [comment]
Yes I had tried with 

`<td  appTooltip attr.data-tippy-content="{{el.count}}">{{el.count}}</td>`

` this._el.addEventListener('mouseover', function () {
       
        var titleText = this.getAttribute('data-tippy-content')
       
        tippy(this, { content: titleText })
        this._tippy.setContent(titleText)
      });`


not working 
please check 

https://stackblitz.com/edit/hello-angular-6-uyzzje?file=src%2Fapp%2Fapp.component.html
