### ISSUE TITLE
How to show Tippy in fullscreen mode

### ISSUE THREAD

**Issue by nidhinkumar06** [atomiks/tippyjs#508]
I have used the Tippy library which works well. but when it is shown in fullscreen mode the tooltip is not shown. after looking into the issues i came to know about appendTo.

If i use `<Tippy appendTo='parent'>` the tooltip style gets changed as below

![HawkEye (2)](https://user-images.githubusercontent.com/10459220/58557709-adf9f900-823c-11e9-878d-c726c2620331.jpg)

Without using appendTo i am getting the tooltip as below

![HawkEye (1)](https://user-images.githubusercontent.com/10459220/58557733-bd794200-823c-11e9-8f38-a08d8b16f53b.jpg)

Code:

```
<div id="full">
      <Tippy
        appendTo='parent'
        content={
          <div>
            <h5>{clusterId}</h5>
            <p>Total Devices: {totalNodes}</p>
            <hr style={{ borderColor: 'white' }} />
            <ol style={{ textAlign: 'left', paddingLeft: '10pt' }}>
              <li>Good: {good}</li>
              <li>Need Attention: {attention}</li>
              <li>Monitor Closely: {monitor}</li>
            </ol>
          </div>
        }
        arrow={true}
        animation="fade"
        theme="bootstrap"
        duration={0}
        hideOnClick={false}
      >
        <div
          id="marker"
          className="pin bounce"
          style={{ backgroundColor: color, cursor: 'pointer' }}
          onClick={handleClick}
        />
      </Tippy>
      <div className="pulse" />
    </div>
```

**Comment by atomiks** [comment]
Likely, the parent `<div>` does not stretch the full width of the container it's in, you should inspect the CSS in DevTools

**Comment by nidhinkumar06** [comment]
@atomiks  i have tried to set the width and position for the div which shows the tooltip but the tooltip goes behind if we hover it at the corner like below

![HawkEye (3)](https://user-images.githubusercontent.com/10459220/58625487-32598400-82f0-11e9-87dd-85f425768183.jpg)

Expected output:

![HawkEye (4)](https://user-images.githubusercontent.com/10459220/58625511-3b4a5580-82f0-11e9-94c0-b9162b7e294b.jpg)


Code:
```
<div className="tooltip-fullscreen">
      <Tippy
        content={
          <div>
            <h5>{clusterId}</h5>
            <p>Total Devices: {totalNodes}</p>
            <hr style={{ borderColor: 'white' }} />
            <ol style={{ textAlign: 'left', paddingLeft: '10pt' }}>
              <li>Good: {good}</li>
              <li>Need Attention: {attention}</li>
              <li>Monitor Closely: {monitor}</li>
            </ol>
          </div>
        }
        arrow={true}
        animation="fade"
        theme="bootstrap"
        duration={0}
        hideOnClick={false}
      >
        <div
          className="pin bounce"
          style={{ backgroundColor: color, cursor: 'pointer' }}
          onClick={handleClick}
        />
      </Tippy>
      <div className="pulse" />
    </div>
```

Css:

```
.tooltip-fullscreen {
  position: relative;
  margin-left: calc(50% - 50vw);
  width: 100vw;
}
```

**Comment by atomiks** [comment]
It's being clipped by the div since that's what it's appended to..

**Comment by nidhinkumar06** [comment]
@atomiks where should i have to use boundary: fullscreenContainer in css?

**Comment by atomiks** [comment]
It's the `boundary` option, `boundary={element}`

This isn't a problem with the library tho, so going to close

**Comment by nidhinkumar06** [comment]
@atomiks i want to show the tooltip in overflow

**Comment by atomiks** [comment]
You have to keep it appended outside the fullscreen container then, and use a really high zIndex value as suggested in the other issue I think
