### ISSUE TITLE
Scroll bar flicker in IE11 when a container's height is 100%

### ISSUE THREAD

**Issue by lozinsky** [atomiks/tippyjs#509]
In the case when a container's height is 100%, when you hover over the tippy reference in IE11, a scroll bar appears then immediately disappears. Is there any way to solve this problem?

**How to reproduce:**
1. Open https://jsfiddle.net/12amsko5 in IE11
2. Hover over some box

**Preview:**
![Preview](https://user-images.githubusercontent.com/15981489/58569068-172e3c00-823e-11e9-9cbe-82a056fbfc92.gif)
(low fps, in real case reproduced more often)

**Comment by atomiks** [comment]
Maybe:

1. `overflow-y: scroll` to keep scroll bar visible at all times
2. `lazy: false` to create the popperInstance on init - if this does solve it, there may be a way to keep lazy behavior with a fix (which is preferred for performance reasons)

**Comment by atomiks** [comment]
Found a fix

(Unless the element is positioned right next to / under the scroll bar, it flickers still -- not sure if that one can be fixed. The ones to the left are fixed)

It's pushed to the `v5` branch - I don't know/think I can backport all of the fixes made in v5 into v4 since it's quite a big effort (especially the tests)... we'll see.

**Comment by lozinsky** [comment]
The problem is reproduced again in 4.3.4 version, if `followCursor` and `delay` options are passed.
Without `delay` option everything works correctly.

**How to reproduce:**
1. Open https://jsfiddle.net/8jswqv09 in IE11
2. Hover over some box

**Preview:**
![Preview](https://user-images.githubusercontent.com/15981489/60176563-5b056880-981f-11e9-99e0-cbd0ae48b6e5.gif)
(low fps, in real case reproduced more often)

**Comment by atomiks** [comment]
Is it reproducible in 4.3.3 as well?

**Comment by lozinsky** [comment]
No, in 4.3.3 everything works correctly.

**Comment by atomiks** [comment]
Does it only happen w/ `followCursor`?  I don't easy access to IE to test

try these maybe

```js
lazy: false
```

```js
popperOptions: {
  modifiers: {
    computeStyle: {gpuAcceleration: false}
  }
}
```

**Comment by atomiks** [comment]
Can you try this?

```js
tippy(".box", {
  content: "Tooltip",
  followCursor: true,
	delay: [500, 100],
  animateFill: false,
  popperOptions: {
  	modifiers: {
    	applyStyle: {
      	enabled: false
      }
    }
  }
});
```

Is it positioned in the top left corner in IE11 without a jump?

**Comment by lozinsky** [comment]
> Does it only happen w/ followCursor?

Yep, with `gpuAcceleration: false` flickers only bottom scroll bar, `lazy: false` in this case does not affect.

> Is it positioned in the top left corner in IE11 without a jump?

Yep, a jump is reproduced only from the right window border in IE11.

**Comment by atomiks** [comment]
IE11 is the worst tbh.

Feel free to edit node_modules code to debug it cuz I can't test it for a while. Relevant functions are `function createPopperElement()` utility (and how it assigns position absolute and top/left 0 initially) and `function mount()` + `currentMountCallback` inside the createTippy factory function.

**Comment by atomiks** [comment]
Is it reproducible in `tippy.js@next` version?

https://jsfiddle.net/1kjhdvns/

**Comment by lozinsky** [comment]
Yes, the problem is reproduced in `tippy.js@next`.

**Comment by atomiks** [comment]
I downloaded a VM again for IE11 lol (new computer). As far as I can tell it only flickers (using `@next`) when hovering over the element right under/next to the scroll bar. I would consider that not too bad considering:

1) it's IE11, 6 year old browser where weird glitches are expected
2) it's an aesthetic not functional bug, not a big deal 
3) only happens in a very specific configuration at a very specific placement

**Comment by lozinsky** [comment]
In version 5.0.2 the problem no longer reproduces.
Thanks so much for this release 🎉

**Comment by atomiks** [comment]
Interesting..

**Comment by usb248** [comment]
@atomiks  flickering come back in last release. The tooltip jump to top-left of the window... Any workaround for IE ?

**Comment by atomiks** [comment]
You'll have to submit a PR if you want any more IE fixes lol. Not investigating that browser ever again

**Comment by usb248** [comment]
This is not the answer I expected :sweat_smile:
