### ISSUE TITLE
V0.16.1 don't activate tooltips

### ISSUE THREAD

**Issue by FernandoBoza** [atomiks/tippyjs#51]
I updated the js file from V0.11.2 to the latest released v0.16.1 and it didn't work for me, the css is good. 

Chrome V 58.0.3029.110 (64-bit)
Mac OS Sierra 10.12

**Comment by atomiks** [comment]
Can I see your code?

**Comment by atomiks** [comment]
If you were using tooltips on SVGs then it was indeed broken, it's now fixed in v0.16.3

**Comment by FernandoBoza** [comment]
at the moment we just stuck with v0.11 but thanks for letting us know
