### ISSUE TITLE
Cannot access instance methods

### ISSUE THREAD

**Issue by hunfatal** [atomiks/tippyjs#510]
Hi,

Do I need to get the `_tippy` property from an element to get tippy instance?

Let's say I have an element with an id `some-element`.

I bind a tippy instance to it with the following:
`tippy(document.getElementById("some-element"), { content: "some tooltip content" });`

And at a later phase I want to access the tippy instance by `tippy(document.getElementById("some-element"))` but it returns `undefined` so I cannot call the instance's `destroy` method.

However `document.getElementById("some-element")._tippy` returns the instance and it's `destroy()` method works fine.

What did I miss here?

**Comment by atomiks** [comment]
The `tippy()` is a constructor to _create_ a tippy instance, not retrieve one if it's already been created. You can either store the first one from the first invocation or use the `_tippy` property.

**Comment by hunfatal** [comment]
I misunderstand the documentation then. 

Thank you for the quick answer. :)
