### ISSUE TITLE
Please Help me...How to open Tippy pop only one by one  same as accordion.

### ISSUE THREAD

**Issue by ohana88** [atomiks/tippyjs#512]
How to open Tippy pop only one by one same as accordion.
Today i find Tippy the best popover plugin but i have Question please help me
when click open Tippy I want to hide Tipper opened

![Inkedpop1_LI](https://user-images.githubusercontent.com/17563661/58803931-cf8f2200-863a-11e9-9038-aa9d17aad201.jpg)

![hf](https://user-images.githubusercontent.com/17563661/58805084-89878d80-863d-11e9-9641-797ad126452c.PNG)

**Comment by atomiks** [comment]
`hideOnClick` should be `true` if you want the previous one to close

**Comment by ohana88** [comment]
ok Thanks 
https://github.com/atomiks/tippyjs/issues/260#issuecomment-462031748
it's work !!!
