### ISSUE TITLE
*-start/*-end placement with followCursor option reversed + incorrect offset (v4.3.2)

### ISSUE THREAD

**Issue by lozinsky** [atomiks/tippyjs#513]
## Bug description

Thanks for the backport v5 fixes to v4 (#511).
In the case where the `placement` option has `*-start`/`*-end` value and `followCursor` option is defined, tippy is placed on the other side of the cursor in 4.3.2 version. Is this a new expected behavior or bug?

## Reproduction

CodePen link (4.3.1): https://codepen.io/lozinsky/pen/MdLzwo
CodePen link (4.3.2): https://codepen.io/lozinsky/pen/JqxeYa

**Comment by atomiks** [comment]
I think it's actually correct now. Before, the virtual reference had zero size but now it actually has a "fake size" of 100 pixels which prevents some issues. It looks like that ended up reversing the behavior though.

**Comment by atomiks** [comment]
If you add `arrow: true` and comment out `followCursor: true`, you'll see the placement seems to actually be correct in 4.3.2. But I don't know about the slight pixel offset now.

**Comment by lozinsky** [comment]
If I want tippy to be near the cursor as in version 4.3.1 I need to add `offset: "50, 0"`?

**Comment by atomiks** [comment]
I think the reversement of placement is correct now (although kind of a breaking change of expected behavior? 😕), but the offset problem is a bug. It changes based on the tooltip element's size.

**Comment by ohana88** [comment]
@atomiks sorry to say ..please read and help me my issue
#512

please ... I'm use time to fix 8hrs not work T_T

**Comment by ohana88** [comment]
> I think the reversement of placement is correct now (although kind of a breaking change from previous behavior? 😕), but the offset problem is a bug. It changes based on the tooltip element's size.

@atomiks sorry to say ..please read and help me my issue
#512

please ... I'm use time to fix 8hrs not work T_T
