### ISSUE TITLE
How can one make a scrollable Tippy?

### ISSUE THREAD

**Issue by anault** [atomiks/tippyjs#517]
How can one make the content of a Tippy scrollable if the parent/viewport doesn't allow enough space for the Tippy to display in full?

Here's a [Codepen](https://codepen.io/anault/pen/qGzqaB)

![ok](https://user-images.githubusercontent.com/6646230/59066454-1a987780-887d-11e9-84fe-acca20cab52e.png)

![not-ok](https://user-images.githubusercontent.com/6646230/59066460-1d936800-887d-11e9-96b3-32904b95e7ee.png)

Setting a CSS `max-height` would work, but not with dynamic heights such as the viewport.

Thanks for everything you do for this lib, it is awesome!

**Comment by atomiks** [comment]
That's an interesting and difficult question, I don't think it's easy to do with CSS.

I think you could add some code in `popperOptions.onUpdate` that calculates the distance between the bottom of the reference element and the bottom of the viewport (and also all the different variations/placements it can have) and set the `max-width` based on that

**Comment by anault** [comment]
Alright, I got it working - it's pretty limited, but it works: https://codepen.io/anault/pen/WqeaYZ I'm sure it's less than ideal @atomiks Anything that could be improved?

Also, would it be interesting to natively support this kind of functionality in Tippy?

**Comment by atomiks** [comment]
Nice work! Only thing I noticed is it transitions by default and lags behind the resize (because the tooltip styles transition everything, including `max-height` by default in CSS). In upcoming v5, the tooltip elements specifies `transition-property` explicitly which you could specify as well to fix that.

> Would it be interesting to natively support this kind of functionality in Tippy?

There are probably sooo many edge cases to consider that I don't think I'd work on it for a while lol. Keeping Tippy's core surface area as small as possible is better for maintenance, especially if something like this can be externally-added.

**Comment by guanzo** [comment]
I'm running into this too. Are there any alternative solutions besides dynamically detecting overflow, shrinking the tippy to fit, and adding a scrollbar? My app is forced to be 320px by 500px, so Im encountering a lot of overflowing when tippys have lots of vertically stacked content.

**Comment by atomiks** [comment]
I don't think so, isn't it an inherent problem regarding 2D space haha.

In any case you can use https://www.npmjs.com/package/popper-max-size-modifier to do the size detection for you.

**Comment by Crispae** [comment]
I also ran into this issue, adding a constant height limit and scroll  works. Hope it help!

```javascript
parentContainer = document.createElement("div");
parentContainer.style.maxHeight = '300px';
parentContainer.style.overflow = 'auto';
