### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by diomed** [atomiks/tippyjs#519]
hey

could you maybe make few of new themes: 

one where background is blue
`#679EFE`

and text is white

---

and one that is translucent

**Comment by atomiks** [comment]
There's already a `translucent` theme available in `themes/`. I'm only doing b/w themes because they fit in most designs easily. You can create your own custom blue theme very easily, so I don't think this needs to be included in the package by default 🤙

**Comment by diomed** [comment]
I omitted existence of translucent one. I see that now. 
Is there any way to get in touch with you via chat?
Do you have Discord maybe?

**Comment by diomed** [comment]
@atomiks ⁉️

**Comment by atomiks** [comment]
What do you need help with?
