### ISSUE TITLE
Virtual Reference Content from Attribute and not Content Parameter

### ISSUE THREAD

**Issue by GraphicOwls** [atomiks/tippyjs#520]
This is regarding the anchor link example. I know you had mentioned on Twitter that the virtual ref should be used for a single `triggerTarget` element, so using the `content` option is recommended. 

I would still like to grab the content from the data-attribute if possible. I like having the position and reference point working only if I want to use this to better explain things on a pricing chart for example then I can't because there are multiple list items on a pricing chart and some wrap two lines. I would have to have multiple instances of this semi long piece of code  when I can just use it one time and get the content from the attribute. 

So is it possible to help me with a way within the code for the anchor link example to grab the content from the attribute instead of the content parameter?

I really appreciate it! Thank you!
-Noah

**Comment by atomiks** [comment]
Are you able to make a CodePen demo of this? Kinda kard to understand what you are trying to achieve

Anyway, remember that you can make your own proxy/wrapper functions that extend functionality to tippy if it's not in the core library / yet

```js
function yourFunc(selector, optionalProps) {
  Array.from(document.querySelectorAll(selector)).forEach(element => {
    const virtualReference = {
      getBoundingClientRect: () => {...}
    };

    tippy(virtualReference, {
      content: element.getAttribute('data-tippy-content'),
      triggerTarget: element,
      // ...etc
    });
  });
}
```
