### ISSUE TITLE
Support multiple triggerTarget elements

### ISSUE THREAD

**Issue by rodw** [atomiks/tippyjs#527]
Using the `triggerTarget` option one can create a tooltip that appears next to the reference element based on the mouseenter/focus/etc. events of a different element.

For example given div_a and div_b I can add a tooltip to div_a but use div_b as the triggerTarget and tooltip will appear for div_a when the user hovers over div_b.

I want to do exactly this, but with more than one element playing the role of div_b. Unless I'm missing something that doesn't seem to be supported currently.

For an arbitrary example/use-case: given a table, imagine I want the tooltip to appear over the `th` element whenever the user hovers over one the the `td` cells associated with that column.

A workaround is to set `multiple:true` and create many tippy instances on the `th` -- one for each `td` we want to act as triggerTarget -- but that's obviously not very efficient.

It looks like this could be supported relatively easily (and in a backwards compatible fashion) by tweaking the logic in createTippy.ts to support `getEventListenersTarget` returning an Array (or NodeList) rather than a single element. Conceptually this is pretty simple but there are a large number of references to getEventListenersTarget in createTippy.ts.

PS: On a related note I wish I could use a selector (string) for triggerTarget in addition to a DOM node. That way the `data-tippy-triggertarget` attribute could be used. As it stands I think you need to use JavaScript to "manually" select the triggerTarget element. But that is different feature request.

**Comment by atomiks** [comment]
So like this:

```js
tippy(thElement, {
  triggerTarget: [tdElement, tdElement, ...]
})
```

> A workaround is to set multiple:true and create many tippy instances on the th -- one for each td we want to act as triggerTarget -- but that's obviously not very efficient.

To me it seems okay. Depends what you mean by "efficient"?

**Comment by rodw** [comment]
> So like this:

```
tippy(thElement, {
  triggerTarget: [tdElement, tdElement, ...]
})
```
Yes. Exactly like that.

>> A workaround is to set multiple:true and create many tippy instances on the th -- one for each td we want to act as triggerTarget -- but that's obviously not very efficient.
>
> To me it seems okay. Depends what you mean by "efficient"?

I meant it seems like that creates a lot more instances than are "needed", and they only differ by the triggerTarget attribute.

Suppose the table in this example has 100 rows, then `<th>` has 100 distinct tippy instances, one for each `<td>`. Is that a cause for concern? 1000 rows? 

Based on other features/docs/comments I had the impression that creating a large number of tippy instances is discouraged.  If nothing else, just from a raw HTML/JS perspective churning thru a large number of objects or creating a lot of DOM nodes and event listeners can cause performance and/or memory problems.

**Comment by atomiks** [comment]
The triggerTarget as an array would create tons of event listeners as well, but be slightly more efficient by reusing one instance yes.

What you want is probably event delegation or windowing if perf is a concern. I would use Performance DevTools to verify that it's actually a problem first, then you can optimize using those techniques if it is

**Comment by rodw** [comment]
Thanks. I appreciate your help (and your library :) ).

To be honest my current, specific use case won't have more than ~15-20 triggerTargets, so I'm not concerned about the performance/scalability in practice.

The code/logic to implement the workaround I described is a bit clunky, so I still think this would be a useful API change, but if it complicates createTippy.ts too much (and I can see how it might in the current form) then it may not be worth it. I admit it's not a super-common use case (but it's not a super-rare one either).

**Comment by atomiks** [comment]
Supported in 5.0 due to `createSingleton()`
