### ISSUE TITLE
Empty Content

### ISSUE THREAD

**Issue by swampthang** [atomiks/tippyjs#528]
I hesitated to post this as a bug because there might be something I'm doing wrong. What's confusing is the same code works for one set of buttons and not for another. I've triple-checked that the selectors are returning the elements correctly. Both the one that works and the one that doesn't work are in the same function that runs when the document has finished loading. Also, I'm setting the data-tippy-content attributes dynamically as you can see in the code. Here's one tippy instance that works fine...
```
let cmdCntrl = process.platform === 'darwin' ? 'Command' : 'Control';

let timelineZinBtn = document.querySelector('.control-buttons .zoom-buttons i#in');
  timelineZinBtn.setAttribute('data-tippy-content',`Zoom in timeline. Shortcut: ${cmdCntrl} + Left Arrow`);
  tippy(timelineZinBtn, {
    theme: 'light',
    animation: 'scale',
    placement: 'bottom',
    duration: 0,
    arrow: true,
    delay: [500, 200],
  });
```
Here's a screenshot of what I see when mousing over the tip above...
![Screen Shot 2019-06-25 at 10 54 21 AM](https://user-images.githubusercontent.com/428757/60114053-a1cc6300-9738-11e9-8447-482ad674cd94.png)
Just below that, I have the following code...
```
let stageZoomInBtn = document.querySelector('.zoom-settings img.zoom-in#stage-zoom-in');
  stageZoomInBtn.setAttribute('data-tippy-content',`Zoom in stage. Shortcut: ${cmdCntrl} + Plus Sign`);
  tippy(stageZoomInBtn, {
    animation: 'scale',
    placement: 'right',
    duration: 0,
    arrow: true,
    delay: [500, 200]
  });
```
Here's a screenshot of what I see when mousing over that element... 
![Screen Shot 2019-06-25 at 10 53 54 AM](https://user-images.githubusercontent.com/428757/60114351-4ea6e000-9739-11e9-8ba5-b4c0e7e1672c.png)

I can see using inspector that everything is there except for the content. Here's a screenshot showing the element that gets created...
![Screen Shot 2019-06-25 at 11 11 40 AM](https://user-images.githubusercontent.com/428757/60114915-6337a800-973a-11e9-8810-670c5f1bfafe.png)

I've tried using the content property within the tippy options instead of setting the attribute prior to initializing the tippy instance but with the same results. Any idea what I might try to get this to work?

**Comment by swampthang** [comment]
Here's something interesting. After the document loads and the instance is created, I inspected the element to see what was in the _tippy property. I saw where there was a setContent function. So, I added a setTimeout just below the tippy init like this and it works now...
```
let stageZoomInBtn = document.querySelector('.zoom-settings img.zoom-in#stage-zoom-in');
  let stageZoomInContent = `Zoom in stage. Shortcut: ${cmdCntrl} + Plus Sign`;
  stageZoomInBtn.setAttribute('data-tippy-content',stageZoomInContent);
  tippy(stageZoomInBtn, {
    animation: 'scale',
    placement: 'right',
    duration: 0,
    arrow: true,
    delay: [500, 200],
  });

  setTimeout(()=>{
    stageZoomInBtn._tippy.setContent(stageZoomInContent);
  });
```

**Comment by atomiks** [comment]
Try this to debug it
```js
const instance = tippy(stageZoomInBtn, {
  animation: 'scale',
  placement: 'right',
  duration: 0,
  arrow: true,
  delay: [500, 200]
});

const observer = new MutationObserver(mutations => {
  console.trace(mutations);
});

observer.observe(instance.popperChildren.content, {
  childList: true,
  subtree: true
});
```

**Comment by atomiks** [comment]
CodePen repro required to further resolve this issue
