### ISSUE TITLE
Tippy is not triggered when elements are on top

### ISSUE THREAD

**Issue by laoneo** [atomiks/tippyjs#529]
## Bug description
When another element is over an element where a tippy instance is created of, then no tooltip is shown. This happens with when using the fullcalendar library in a special rendering mode.

## Reproduction
The code pen is here, but includes also fullcalendar, to illustrate the issue correctly. For each event is a div created per row, so all elements are above each other.

https://codepen.io/anon/pen/rEGaZo

**Comment by atomiks** [comment]
Not a bug with tippy.js since there's an element blocking the element where the tippy is applied to, so the event listeners don't fire. You'll need to apply `pointer-events: none` on the overlaying elements, or apply the tippy to the overlaying element itself

**Comment by laoneo** [comment]
Ok, thanks for the explanation.
