### ISSUE TITLE
Using template for tippy content kills custom events

### ISSUE THREAD

**Issue by thorhanks** [atomiks/tippyjs#53]
Hey, I love tippy.js, great work. Found it after pulling my hair out trying to do a simple popup with popper.js.

But, when using the custom html template to add content for the tippy popper I wasn't able to do what I needed. I wanted to make an interactive popper that was a list of elements the user could select. It, however, did not work. I tracked it down to the use of innerHTML to copy over the template instead of appendChild. Just copying using innerHTML blew away any event handlers I had and the custom data props I had added to the template html elements.

I've submitted a pull request and would love for this feature to be added. Currently I've got my own modified copy sitting in our app. I'd love to switch it back to using the main npm version.

Thanks and awesome work!

Or perhaps I'm just missing something.

**Comment by FezVrasta** [comment]
I'm sorry if I contributed to your premature balding 🙂 If you think the documentation of Popper.js could be improved please feel free to send a PR.

Btw I'm happy you moved to Tippy.js since it's meant for exactly what you need.

**Comment by thorhanks** [comment]
No offense intended. Popper, by all accounts is an incredible library. 🥇  Just couldn't figure out how to do some basic things like show an arrow and have it auto positioned. Tippy.js more like what I need but it's likely not meant for the rich interactive popups I'm looking to use it for. :)

**Comment by atomiks** [comment]
v0.16.2
