### ISSUE TITLE
tippy.js does not work on XAMPP localhost, but it works on JS Bin

### ISSUE THREAD

**Issue by Brian1111** [atomiks/tippyjs#533]
## Bug description

I tried both your cdn and npm.  I copied and pasted your own code.  None works on xampp localhost.  It works only JSBin.  Here is the link:  https://jsbin.com/vasetiqedu/edit?html,js,output

It doesn't work on CodePen either.  Here is the link:  https://codepen.io/brian1111/pen/BgvQMY

**Comment by atomiks** [comment]
the codepen is missing closing tag `</script>` for tippy.js link

**Comment by Brian1111** [comment]
If fixed it.  I also removed the comma after `animation: 'fade' ` Now it shows also on CodePen.  Here is the link:  https://codepen.io/brian1111/pen/BgvQMY

But still it doesn't show on xampp local host.

**Comment by Brian1111** [comment]
Here is the picture of my code on xampp localhost:  


![tippyjs_bug](https://user-images.githubusercontent.com/12651236/60903519-58930d80-a226-11e9-9767-19be0bfd6834.jpg)

**Comment by atomiks** [comment]
[See here](https://atomiks.github.io/tippyjs/faq/#my-tooltip-is-not-working-using-data-tippy), the script needs to be placed after the elements in the DOM order

**Comment by Brian1111** [comment]
I did it.  Now it works.  But the tooltip shows at the bottom of the text.  Is it the default?

**Comment by atomiks** [comment]
No, it's just flipped to the bottom because there's not enough space above it for it to fit in the codepen example

**Comment by Brian1111** [comment]
I just noticed it after putting `<br>` tags.   Thanks!
