### ISSUE TITLE
css inside head

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#536]
Hi, 
i see tippyjs is adding a ```<style data-tippy-stylesheet=""> ...</style>``` inside the ```<head>```.
Can this css be loaded from a css file? I'm using some virtual dom and it's causing some problems.
Thanks

**Comment by atomiks** [comment]
Yes, you can use `index.js` + `index.css` instead of `index.all.js`

https://unpkg.com/tippy.js@4/umd/index.js
https://unpkg.com/tippy.js@4/index.css

**Comment by Wyzix33** [comment]
How can i do that with webpack?

```import tippy from 'tippy.js';```
and 
```@import '~tippy.js/tippy.css'```

Thanks

**Comment by atomiks** [comment]
```js
import tippy from 'tippy.js/esm'
import 'tippy.js/index.css'
```

**Comment by Wyzix33** [comment]
Ok, it works!
Can this be done with v5 as well?
We have about 3 months till we go live with our app so it's enough time for tests

Thanks

**Comment by Wyzix33** [comment]
Hi, 
It works in v5 as well
```
import tippy from 'tippy.js/esm/tippy';

@import ~tippy.js/tippy.css
@import ~tippy.js/backdrop.css
@import ~tippy.js/themes/light.css
```
 
Thanks

```
