### ISSUE TITLE
Escape to close interactive tooltips

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#537]
## Problem

When a tooltip is open with  ```interactive: true``` option, there is no way to close it from within like a ```x``` button or a close button .

## Solution

Close the tooltip on Esc keydown or add a close button option and return focus to ref element.

**Comment by atomiks** [comment]
You can supply your own X / close button inside the content. And you can add an event listener to `instance.popper/popperChildren` elements to handle esc keypress

**Comment by Wyzix33** [comment]
OK, thanks, it works :)

**Comment by jdwallace12** [comment]
Hey there, I was curious if it is possible to add a close icon if populating the content through the data-tippy-content attribute via javascript.  A recent accessibility audit mentioned we needed a mechanism to dismiss the tooltip.  Thanks!

**Comment by chalisegrogan** [comment]
FYI, docs now include this as a custom plugin example: https://atomiks.github.io/tippyjs/v6/plugins/#hideonesc
