### ISSUE TITLE
Scroll problem, boundary related

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#538]
## Bug description

I removed the animations and the tooltip is jumping after scrolling out and back in the viewport

## Reproduction

I found in  #198  that there was a ```tippy.disableAnimations()```
that is missing now.
I'm trying to remove all animations and i've done this:

tippy.setDefaults({
  animation: null,
  duration: 0,
  animateFill: false,
  distance: 20,
  arrow: true
 });
It seems to work, but i think there is one bug when the tooltip is shown again after scrolling out and in of the parent element.

After some tests it seems that it's the same bug with or without the animation...

I've made a codepen:

```https://codepen.io/wyzix33/pen/bPyMdL```

press any status button and scroll until the tooltip is hidden, than slowly bring it back.

You will see this
![tippy](https://user-images.githubusercontent.com/13553412/61186351-c4350a80-a66c-11e9-8848-00eee068fb2e.jpg)

right as it appears, and if you stop scrolling it will stay there... if you continue it will jump to the right place.

Thanks

**Comment by atomiks** [comment]
Use `opacity: 0` instead, probably to do w/ the fact that it no longer has layout and its dimensions can't be measured any longer with `display: none`

**Comment by Wyzix33** [comment]
Great, it works :)
Thanks
