### ISSUE TITLE
Tooltip doesn't follow dragged element

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#540]
Made a quick pen: 
https://codepen.io/wyzix33/pen/yddVgN

Using tippyjs v5
Click any input and drag to another position.
 
When i drag an element with open tooltip the tooltip doesn't follow...

Is there an option i must add to popper or tippy  to make it work?
Thanks

**Comment by Wyzix33** [comment]
For now i solved it by destroying  the tooltip when dragging starts, but it would be nice to have the tooltip follow the element while dragging something like the example on ```https://popper.js.org/index.html```  or maybe at least hide it while dragging and show it when element dragging ended (onEnd event), didn't try it yet, but soon 
Thanks

**Comment by Wyzix33** [comment]
It works hiding and showing the tooltip on drag start and on drag end, for now i'll leave it like this.
Let me know if you have a better idea for solving this problem.
Thanks

**Comment by Wyzix33** [comment]
After a few tests i can say it's not OK, if i drag reference element 3-4 times, the tooltip position is way off... i'm back at destroying / recreating it ...
Thanks

**Comment by atomiks** [comment]
Think you're looking for `sticky: true` and `flipOnUpdate: true` props for that. It still wouldn't follow the "cloned" element though since that's not what's been initialized

**Comment by Wyzix33** [comment]
It's not working, but i just tried to add a scroll to the codepen after dragging the element when you scroll  it goes to the right place.
Or if i resize the page, same result, tooltips jumps to the right position.
Is there a reposition function i can call manually?

**Comment by atomiks** [comment]
It does work cuz I tried it in the pen. You probably only added it to the first one not the second as well.

**Comment by Wyzix33** [comment]
Yes, it works 👍 
Thanks
