### ISSUE TITLE
Any way to reposition the tooltip if content width change?

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#541]
Hi, 
I just run into another problem, I have a tooltip with labels and a way to add/remove labels from it, and if a new column of labels is added the tooltip arrow is pushed to the right ,,,
I need to reposition the tooltip after each add, or maybe just after the ones that create a new column.
Here is a screenshot of the problem, if you need i can create a quick codepen

![initial](https://user-images.githubusercontent.com/13553412/61310804-af3bb100-a7fd-11e9-9c2d-6b82392b3468.jpg)

![after](https://user-images.githubusercontent.com/13553412/61310814-b498fb80-a7fd-11e9-9310-cd7f5bbf52e8.jpg)

As you can see the arrow moved to the right as the tooltip width changed, I want to reposition the tooltip after i press the button to add new labels, hopefully without destroying / recreating it :).

Let me know if there is such an option or i need to solve it some other way.
Thanks

**Comment by Wyzix33** [comment]
Same thing if i delete a full column,, the tooltip getting smaller and the arrow get's further away from the reference... 

But i just noticed that if i resize the page or if i scroll the content it jumps back to the good position...
I just need to call that function manually

Thanks

**Comment by atomiks** [comment]
`instance.popperInstance.update()`

**Comment by Wyzix33** [comment]
Ok, it's working
