### ISSUE TITLE
It is possible to disable tippy appear after delay if target will disappear before?

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#542]
Hi!
It is possible to disable tippy appear after delay if target will disappear before?
I attached tippy on action links. When I click to action link, it disappear, but if I have delay option, I see strange behavior! (Demo video)

My question is - how to prevent this?
Current options via data-attributes
```
data-tippy-distance="10",
data-tippy-trigger="mouseenter",
data-tippy-delay="[500, 20]",
```

Or answer the alternative question - how to turn off the plugin for all touch devices through the date-attributes? I actually need hints only when hovering over the mouse, and your plugin, in spite of the `trigger: mouseenter`, works on touch devices, that have not mouse events! Thanks a lot for awesome plugin!

**Comment by 7iomka** [comment]
Demo: https://youtu.be/rpzbJcX1Bek

**Comment by atomiks** [comment]
You'll need to destroy the instance once the action link disappears. And you can use `touch: false` to disable it from appearing on touch input.
