### ISSUE TITLE
How to only show child most Tippy for mouseover event

### ISSUE THREAD

**Issue by cvuong** [atomiks/tippyjs#544]
Hello, I am using Tippy to render a tooltip for the child most element that the user has hovered on, but I have an issue with overrendering Tippys. If I have a list element on the page, my code is rendering Tippys for all of the list element's ancestors in the DOM tree. What's the best way to only render one TIppy at a time? Here's a code example to demonstrate what is happening: http://jsfiddle.net/6qwar0gn/

Also, I have tried to use tippy.hideAll() inside of the onShow option, but it doesn't render a Tippy for the unordered list element when hovering from a list element to its parent unordered list element.

**Comment by Wyzix33** [comment]
If i understand correctly you just want to  show the tooltip on the elements that has no child elements.
You can achieve this by setting a simple check before showing the tooltip like this
```
const onMouseover = e => {
  let elem = e.target;
  console.log('onMouseover elem', elem)
  if(!elem.firstElementChild){
    console.log('adding tooltip to this elem', elem)
    const tooltip = tippy(elem, {
      content: 'test',
    });
  }
}

document.addEventListener('mouseover', onMouseover);
``` 

Here is your fiddle with the changes:
http://jsfiddle.net/wyzixg/32ych1rv/4/

Hope it helps

Good luck

**Comment by cvuong** [comment]
I would like to show the tooltip on any element, not just the child most element. In your example, the tooltip wouldn't show up if I am hovered over the `<ul>` element, which is something that I am looking for.

**Comment by Wyzix33** [comment]
Ok, then you need to keep track of what you show and only show one at a time, see if this is what you want:

http://jsfiddle.net/wyzixg/32ych1rv/27/

```
var instance;
const onMouseover = e => {
  let elem = e.target;
  console.log('onMouseover elem', elem)
  if(instance) instance.destroy();
  if(elem.nodeName.toLowerCase() === 'html') return;
  instance = showtippy(elem);
  instance.show();
}
let showtippy = function(elem) {
  return tippy(elem, { content: 'test' });
}

document.addEventListener('mouseover', onMouseover);
```
Basically we have a global variable,( or you could wrap everything in a closure if you don;t want to use global variable) where we will keep the tooltip instance, and everytime the mouse is over a element you check to see if another instance exists, if it does you destroy it and create another for the element currently hovered. I only set a condition so the tooltip doesn't show when you hover on body :) you can add more there if you don't want the tooltip to show over certain elements, or you could add a class to the elements that you want tooltip to show and check only that, for example you can have 5 divs with class="tippy" and your condition would be : 
if(!elem.classList.contains('tippy') ) return;
I've made a demo: http://jsfiddle.net/wyzixg/32ych1rv/31/  with the class condition

**Comment by cvuong** [comment]
Thank you so much! It's working perfectly now.

**Comment by kunalahirrao** [comment]
Best solution using css is to apply style on children's  **style="pointer-events: none"**.It will prevent  bubbling on child
