### ISSUE TITLE
Tippy breaks when used alongside Vue

### ISSUE THREAD

**Issue by terryupton** [atomiks/tippyjs#548]
## Bug description
I am trying to use this alongside some Vue Js code but when these are combined together the tippy instances stop working.

## Reproduction

I have put together some simplified pens to illustrate this. In my actual project I am using Laravel Mix and ES6 imports etc.

Here is a pen with just tippy working as it should.
CodePen link: https://codepen.io/amasci/pen/YmxKeo

Here is a pen with just tippy alongside Vue and it is broken.
CodePen link: https://codepen.io/amasci/pen/bXrdEd

Please tell me what I am doing wrong. It must be me as I cannot see any other related issues.

**Comment by KubaJastrz** [comment]
You posted the same link for both examples.

**Comment by terryupton** [comment]
@KubaJastrz - sorry about that. I have updated the message with the correct second link.

**Comment by KubaJastrz** [comment]
It's definitely not a tippy bug. If you look at the DOM that Vue outputs, you can see that there are no `<template>` tags anywhere. It's because Vue automatically treats them as blank tags and renders what's inside them.

If you move the `<template>` tags outside of the Vue instance element (`#app`), then everything works properly.

I don't know Vue that well to propose another solution.

**Comment by terryupton** [comment]
Thanks @KubaJastrz - thats the solution I have come up with for now as well. as I am not that up to Speed with Vue or JS (learning in progress). I will see if I can figure a better approach. Thanks for the speedy response.

**Comment by KubaJastrz** [comment]
No problem. And remember that debugging tools are your best friend :)

**Comment by terryupton** [comment]
@KubaJastrz is there a way to use this without it being a <template> but a <div class="hidden"> intead?

I am using the example from the docs.
```
content(reference) {
    const id = reference.getAttribute('data-template')
    const container = document.createElement('div')
    const linkedTemplate = document.getElementById(id)
    const node = document.importNode(linkedTemplate.content, true)
    container.appendChild(node)
    return container
  },
```

But when I swap from a <template> to a <div> I get the error:
`Uncaught TypeError: Failed to execute 'importNode' on 'Document': parameter 1 is not of type 'Node'.`

**Comment by KubaJastrz** [comment]
`content` seems to be only available in `<template>` elements. When you switch to divs you can use the `linkedTemplate` directly:
```js
const node = document.importNode(linkedTemplate, true)
```

ref: https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement/content

**Comment by atomiks** [comment]
You need to use element refs and place any tippy calls within `mounted()`

As for the second question, should be like this:
```js
content(reference) {
    const id = reference.getAttribute('data-template')
    const container = document.createElement('div')
    const linkedTemplate = document.getElementById(id)
    container.appendChild(linkedTemplate)
    return container
  },
```

But remember these are very vanilla-y suggestions, if you're using Vue you need to adopt different patterns

**Comment by terryupton** [comment]
Perfect thanks @atomiks - I am not using Vue for the tippy stuff, just want it to be able to existing within the Vue container/instance. This has solved it swapping from `<template>` to `<div>`
