### ISSUE TITLE
Create a instance was error in Tippy new version

### ISSUE THREAD

**Issue by tatthang96** [atomiks/tippyjs#549]
I have used TippyJS by add your CDN link, it work fine yesterday, but now it's not working and log the error: 
Uncaught (in promise) TypeError: a.getBoundingClientRect is not a function
    at tippy.js?ver=3.0:1
    at A (tippy.js?ver=3.0:1)
    at Et (tippy.js?ver=3.0:1)
    at Object.onCreate (tippy.js?ver=3.0:1)
    at t.k (popper.js?ver=3.0:4)
    at t.value (popper.js?ver=3.0:4)
    at popper.js?ver=3.0:4
Here is my code:
     
      var instanceTooltip;
      $('.menu-item-bar').bind({
        mouseenter: function () {
            var $this = $(this);
            var parentWidth = $this.find('.item-title').innerWidth();
            var childWidth = $this.find('.menu-item-title').innerWidth();
            var title = $this.find('.menu-item-title').text();
            
            if (parentWidth < (childWidth + 10)) {
              instanceTooltip = tippy($this, {
                content: title,
                sticky: true,
                offset: "0, 35",
                arrow: true,
                zIndex: 99999999,
                maxWidth: 220
              })
              instanceTooltip.show() 
            }
          },
          mouseleave: function () {
            if(instanceTooltip){
              instanceTooltip.hide();
            }
          }
      }); 
i don't know why but when i backup the old version it's still work fine.

**Comment by atomiks** [comment]
You can't pass jQuery objects to Tippy: `tippy($this`, you need to pass the DOM node itself: `$this[0]`. The positioning worked before because Popper unwraps it, and I guess there were weren't other assumptions about the type of `reference`?

**Comment by tatthang96** [comment]
@atomiks thank you for your help, it works for me.
