### ISSUE TITLE
svg not working in latest

### ISSUE THREAD

**Issue by skokenes** [atomiks/tippyjs#55]
Not sure when it broke; I've reverted to v0.11.x for svg support. In latest version (v0.16.x), svg elements will not show tooltips

**Comment by atomiks** [comment]
I think this is because `document.querySelector('svg').title` is `undefined` which I switched to, you need `getAttribute('title')` ... woops.

**Comment by atomiks** [comment]
Tooltips work on SVGs again now in v0.16.3... sorry about that. Don't fix what isn't broken I guess 🙈
