### ISSUE TITLE
[sample] tippy v5:  "process not defined" error when people 

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#551]
## Bug description
When building my code that imports tippy, the code builds with no errors but I get an error when I run the bundle in my browser:

<img width="456" alt="Screen Shot 2019-08-03 at 5 22 42 PM" src="https://user-images.githubusercontent.com/718067/62417978-564c8500-b613-11e9-857a-4a54dee5432e.png">

## Reproduction

index.js:
```javascript
import tippy from 'tippy.js'

console.log('ok nice!', tippy)
```

rollup.config.js:
```
import resolve from 'rollup-plugin-node-resolve'
 
export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'myApplication'
  },
  plugins: [
    resolve()
  ]
}
```

index.html:
```html
<!DOCTYPE html>
<html>
<body>  <script src="bundle.js"></script>  </body>
</html>
```

I build the command with this:

```bash
rollup -c rollup.config.js
```

great, bundles with no errors 👍  :

<img width="406" alt="Screen Shot 2019-08-03 at 5 29 51 PM" src="https://user-images.githubusercontent.com/718067/62418023-5c8f3100-b614-11e9-95f6-90971b13c0f4.png">

Then I open `index.html` in my browser, and in the dev console I see that red error. What gives? Am I doing something wrong?

**Comment by atomiks** [comment]
Hello sample user,

Thankfully your issue has an easy fix.

```bash
npm i -D rollup-plugin-replace
```

```js
import resolve from 'rollup-plugin-node-resolve'
import replace from 'rollup-plugin-replace'
 
export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'iife',
    name: 'myApplication'
  },
  plugins: [
    replace({ 
      // If you would like DEV messages, specify 'development'
      // Otherwise use 'production'
      'process.env.NODE_ENV': JSON.stringify('production') 
    }),
    resolve()
  ]
}
```

For more info, there's information on the [FAQ](https://github.com/atomiks/tippyjs/blob/v5/website/src/pages/faq.mdx#rollup) page about this issue you're facing.
