### ISSUE TITLE
[sample] v5: "process not defined" is getting thrown in the browser when my module is imported

### ISSUE THREAD

**Issue by mreinstein** [atomiks/tippyjs#552]
## Bug description
I author a popular module called `my-module`.  It's a time keeping widget specifically for remote workers that live in Antartica. Tippy is great! I use it to show a popup window in some parts of the widget. Recently I updated to v5, and I'm seeing some errors in the browser console when people include `my-module` in their own apps.

## Reproduction

my module is actually pretty simple, here are all the files:

```index.js
import tippy from 'tippy.js'

export default function myModule () {
	const dom = document.createElement('div')
	console.log('yes!')
         // tippy related setup code is here...
	return { dom }
}
```

I'm using rollup to generate the distributable code for `my-module`.
rollup.config.js:
```javascript
import resolve from 'rollup-plugin-node-resolve'
 

export default {
  input: 'index.js',
  output: {
    file: 'dist/my-module.esm.js',
    format: 'esm',
    name: 'MyModule'
  },
  plugins: [
    resolve()
  ]
}
```

before I `npm publish` on this, I run the build step to produce the packaged versions:

```bash
npx rollup -c rollup.config.js
```

<img width="343" alt="Screen Shot 2019-08-03 at 5 45 38 PM" src="https://user-images.githubusercontent.com/718067/62418103-9f520880-b616-11e9-8951-a7663326d7c5.png">

nice, ok it seems to build still without errors. I `npm publish` this sucker.

Now, when people pull in my new version of `my-module` they get this error in their browser:

<img width="426" alt="Screen Shot 2019-08-03 at 5 47 24 PM" src="https://user-images.githubusercontent.com/718067/62418113-ce687a00-b616-11e9-9030-54f34aa216fc.png">

 I'm getting a lot of angry messages from people that use `my-module` that their apps are broken. What gives?

**Comment by atomiks** [comment]
> I'm getting a lot of angry messages from people that use my-module that their apps are broken. What gives?

Hmm sample package author that sounds kind excessive and overblown 🤔 

If you're publishing your module with `tippy.js` as an external dependency, you can point your users to our helpful [FAQ page](https://github.com/atomiks/tippyjs/blob/v5/website/src/pages/faq.mdx#im-getting-uncaught-referenceerror-process-is-not-defined). 

If you're bundling tippy in (which I don't recommend), then you can use the replace plugin as detailed here: https://github.com/atomiks/tippyjs/issues/551 and set it to `production` if Tippy's DEV messages are not helpful for your package's consumers.
