### ISSUE TITLE
Slight delay when using animation: false

### ISSUE THREAD

**Issue by Wolfr** [atomiks/tippyjs#558]
When no animation is specified, there is a slight delay when closing an interactive tippy (a popup).

You can see the effect at http://johanronsse.be/demo-tippy/ . Try the popups or listboxes.

Is this normal? Any ideas on the best way to migitate this? Going to do a further investigation tomorrow.

BTW, great work on Tippy, I reallly like it!

**Comment by Wolfr** [comment]
Trying to get rid of the transitions makes it weirder, not better.

````.tippy-tooltip {
    transition: none !important;
}

.tippy-tooltip.jungle-theme .tippy-content {
    transition: none !important;
}````

**Comment by KubaJastrz** [comment]
try
```js
duration: 0
```

**Comment by atomiks** [comment]
^^
When using `duration: 0`, all animations become false or "none"
