### ISSUE TITLE
CDNJS, jsDelivr entries out of date

### ISSUE THREAD

**Issue by mcandre** [atomiks/tippyjs#559]
## Bug description

https://cdnjs.com/libraries/tippy.js and https://www.jsdelivr.com/package/npm/tippy.js have entries for earlier releases of Tippy, but no entries for the v4.x series.

Please publish v4 releases to CDNJS and jsDelivr, matching unpkg.com entries.

**Comment by KubaJastrz** [comment]
jsdelivr already has latest version: https://cdn.jsdelivr.net/npm/tippy.js@4.3.5/umd/index.all.min.js

**Comment by MartinKolarik** [comment]
jsDelivr CDN always has the latest version immediatelly after publishing but the website listing may have a few minutes delay.

**Comment by atomiks** [comment]
I've never actually published anything to CDNs they just automatically catch up to npm or something don't they? Anyway I recommend unpkg everywhere which is always updated..
