### ISSUE TITLE
Lazy load image inside Tooltip?

### ISSUE THREAD

**Issue by jinch** [atomiks/tippyjs#562]
Is it possible to lazy load an image that is in the tooltip to reduce the initial load time of the page? I prefer to load the tooltip content within the HTML and not with separate javascript as I have allot of these things. I have tried the AJAX onshow() example but was not able to get to work in my case.

Can anyone provide any pointers? Here is a codepen (without) lazy loading images: https://codepen.io/jinch/pen/aboNOvP?editors=1010

And here is an alternate post to stackoverflow if you want to answer there:
https://stackoverflow.com/questions/57500003/lazy-load-image-in-tippy-js-tooltip

Any guidance is much appreciated.

**Comment by atomiks** [comment]
Put `<img src=""` as `<img data-src=""` then swap the attribute to `src` onShow.

**Comment by jinch** [comment]
I did try this but I was not able to get it to work. Was not able to target the image source with javascript using - fetch('$(this).find("img").data("data-src")'). Can you take a look at the codpen and let me know how I may be able to do this with that type of setup?

**Comment by atomiks** [comment]
```js
tippy('body .tippy', {
  touchHold: true,
  hideOnClick: false,
  interactive: true,
  placement: 'left',
  distance: 20,
  arrow: true,
  animateFill: false,
  animation: 'shift-away',
  // In ES5 as you don't have a transpilation step(?):
  onShow: function(instance) {
    var img = instance.popper.querySelector('img');
    img.src = img.dataset.src;
  }
});
```

**Comment by jinch** [comment]
Thank you so much!!! This worked like a charm :)

**Comment by jinch** [comment]
Do you know a way to have a place holder image or spinner image before the src is replaced? I'm getting some content reflow issues before the image finishes loading.

**Comment by atomiks** [comment]
If you know the height/dimensions of the image before it loads, you can set that as CSS for the image - that way it won't cause reflow once it loads in. Otherwise, there's a host of other techniques you can use if you search online.

Lazy loading images isn't a concept that's part of this library though, as handling of content inside the tippy is offloaded to the developer

**Comment by jinch** [comment]
No worries, you have been a huge help. Thank you for that tip and I will look into other solutions as well. Cheers.

**Comment by twd3** [comment]
Could you please let me know how to do this with ES6? This isn't working for me...
`import Tippy from 'tippy.js';

var tippy = new Tippy('[data-tippy-content]', {
    touchHold: true,
    arrow: true,
    animateFill: false,
    animation: 'shift-away',
    onShow: function(instance) {
      var img = instance.popper.querySelector('img');
      img.src = img.dataset.src;
    }
});`
