### ISSUE TITLE
Delay in Firefox on initial rollover

### ISSUE THREAD

**Issue by jinch** [atomiks/tippyjs#563]
## Bug description

Previewing tippy.js on Firefox v68.0.1 on macOS Mojave, I am noticing it does not initiate right away when I roll-over the element. I either have to click it or rollover / off / than over again before the tool tip appears. Once the tip appears it works flawlessly.  This only seems to be an issue in Firefox and not sure if it's because of my setup or if its like this across the board. 

## Reproduction

CodePen link: https://codepen.io/jinch/pen/GRKZydb

To reproduce:
1. Preview codePen in Firefox
2. Roll over any of the tool tip links
3. Notice that the tooltip does not display
4. Roll off the tool tip link
5. Roll back on the tool tip link
6. Notice how the tool tip displays

**Comment by jinch** [comment]
I determined this was due to my particular setup and NOT anything to do with tippy.js. Long story short I had to initiate the tippy script inside a $('body').on('mouseenter', '.tippy', function(e) {..} in order to work around an issue to get the tooltip to work with stacktable tables (using stacktable.js). This fixed the issue but also created the delay in Firefox on the inital load. To fix this I just initated the tip as normal and used a media query to detect when small and reinitiat the tip.

**Comment by atomiks** [comment]
Right - with your event listener wrapper, the mouseenter event is fired and bubbles up the DOM tree where it reaches the `body` at which point you create the instance, but it's too late for the event listeners that are attached to the element itself to fire until you exit then re-enter.
