### ISSUE TITLE
Close Button?

### ISSUE THREAD

**Issue by jinch** [atomiks/tippyjs#564]
Is there a feature to add a button inside the tooltip to only close it when clicked? The reason I ask is that I want to make this more obvious on mobile so people can get out of the tooltip in other ways besides clicking outside of it.

**Comment by atomiks** [comment]
You can add one yourself that onclick, invokes `instance.hide()`

**Comment by jinch** [comment]
Thank you, I will give that a try.

**Comment by realjjaveweb** [comment]
so there is no plan to add this feature?
