### ISSUE TITLE
Weird shape when tooltip has a lot of text

### ISSUE THREAD

**Issue by Kell-Stack** [atomiks/tippyjs#568]
## Bug description

I was doing some style testing and noticed that if a lot of text is added to content, the shape breaks.

```   
      var tippyAttr = {
        placement: 'top',
        animation: 'fade',
        theme: 'light-border',
        inertia: 'true',
        animation: 'scale',
        content: text,
      }
      tippy(spacer, tippyAttr)
```

## Reproduction

![Uploading Screen Shot 2019-08-29 at 2.35.21 PM.png…]()

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/issues/566

https://github.com/atomiks/tippyjs/issues/352
