### ISSUE TITLE
v0.16.3 Tippy is not activating

### ISSUE THREAD

**Issue by shezo-khan** [atomiks/tippyjs#57]
I was really excited to use Tippy by reading the documentation. It dosnt effect the element which you are applying tool tip  to. Before i was using a library where it adds the tool tips to :before and :after which effected the DOM. So the problem i am facing with Tippy is that it works fine on some pages. and on some pages its not triggering. The environment we have is

VS2015
KnockoutJS

I intiated the Tippy(.selector) in the head, in the bottom of body. none of that work on those pages. the way i want to use is to have one selector class for Tippy(.tippy) and when i add that class to element which i want to add tooltip to triggers the tooltip. Any suggestions what i am doing wrong. The code is due to legal issues i cannot show on public plateform but can shot snippets.

**Comment by atomiks** [comment]
If you dynamically add the class to the element, you need to call `Tippy(...)` again in order for it to instantiate the tooltips

**Comment by shezo-khan** [comment]
The html is added dynamically via knockout components. now i have to find a way to call Tippy() when DOM is ready or completed. document ready and onload is not working in my case. Thanks
