### ISSUE TITLE
Uncaught TypeError: gax.GoogleProtoFilesRoot is not a constructor

### ISSUE THREAD

**Issue by ChoyCheeWei** [atomiks/tippyjs#570]
I' trying to use Google Vision Api in vue js but when I view what I get in console, it shows this error

``Uncaught TypeError: gax.GoogleProtoFilesRoot is not a constructor``

this is my main.js

``const vision = require("@google-cloud/vision");``
`// Creates a client`
`const client = new vision.ImageAnnotatorClient({`
 ` keyFilename: "./ApiKey.json"`
`});`

`// Performs label detection on the image file`
`client`
  `.labelDetection("./maybank2u.png")`
 ` .then(results => {`
   ` const labels = results[0].labelAnnotations;`

   ` console.log("Labels:");`
   ` labels.forEach(label => console.log(label));`
    `console.log(results);`
 ` })`
  `.catch(err => {`
   `console.error("ERROR:", err);`
 ` });`

![a](https://user-images.githubusercontent.com/33800659/64012452-56776c00-cb50-11e9-9ddc-fd1027901dbb.PNG)

Can anyone help me solve this please?

**Comment by atomiks** [comment]
How is this related to tippy.js?

**Comment by ChoyCheeWei** [comment]
> How is this related to tippy.js?

sry I don't know how to create an new issue under another topic, can you help?

**Comment by atomiks** [comment]
You need to find the repos of the libraries you are using and make an issue there. I don't understand how you found this particular repo randomly if you aren't using it tho 🤔

**Comment by ChoyCheeWei** [comment]
> You need to find the repos of the libraries you are using and make an issue there. I don't understand how you found this particular repo randomly if you aren't using it tho 🤔

I searched my error and this post shows at the top
