### ISSUE TITLE
Sticky Tippy with dynamic template issue

### ISSUE THREAD

**Issue by sn3p** [atomiks/tippyjs#571]
I have several Tippy instances in my app, that are initialized as `sticky` and with a dynamic html template as `content`. In **v4.3.4** the tooltip positions and aligns nicely after updating the content. But after updating to **v4.3.5** the position and alignment is off.

v4.3.4 👍 | v4.3.5 👎
-|-
![Sep-03-2019 18-27-54](https://user-images.githubusercontent.com/935529/64192252-8ab59a00-ce7a-11e9-9eb9-0b5cdbc7077d.gif) | ![Sep-03-2019 18-28-07](https://user-images.githubusercontent.com/935529/64192253-8ab59a00-ce7a-11e9-9ded-38457fba4db4.gif)
[CodePen](https://codepen.io/snap/pen/aboLQNz?editors=1010) | [CodePen](https://codepen.io/snap/pen/vYBePQp?editors=1010)

I'm not sure if this is considered a bug, because without `sticky: true` both version have the same behaviour (broken). But for me this is a breaking change, and should probably find another way to update/render the content.

**Comment by atomiks** [comment]
Conceptually, `sticky` was added to be used when the reference element was changing position or size (e.g. animations) as explained in the docs, rather than act as a way to keep the tippy position updated after updating content like that. I can understand using in the way you have since it's easy, but its perf was bad and should have been used as a last resort (you might not have been aware of this).

A check was added in 4.3.5 to only call `.update()` if the reference element's client rect changed. For this scenario you should be calling `instance.popperInstance.update()` after every content update (assuming you aren't using `.setContent()` which does it for you -- even if you pass the same HTML element in)

**Comment by sn3p** [comment]
> Conceptually, `sticky` was added to be used when the reference element was changing position or size (e.g. animations) as explained in the docs

This is exactly why I'm using `sticky` in my app: having draggable spots on an image that open tippy when clicked :)

> For this scenario you should be calling `instance.popperInstance.update()` after every content update (assuming you aren't using `.setContent()` which does it for you -- even if you pass the same HTML element in)

Thanks for the suggestion, will give this a try 👍

**Comment by atomiks** [comment]
> This is exactly why I'm using sticky, to create draggable spots on an image that open a tippy when clicked or dragged :)

I'm assuming 4.3.5 still works in this case?

I guess it could be useful to have something like `sticky: true` = check both ref and popper rects on each animation frame, or `sticky: 'popper' / 'reference'` to check one of them. That way you wouldn't need to think about manually updating. Popper already does this for `scroll/resize` but those aren't aware of layout changes like the scenario in your gifs for example.

**Comment by sn3p** [comment]
> I'm assuming 4.3.5 still works in this case?

Yes sticky still works perfectly! I was just relying on a pleasant side-effect for my case :)

> I guess it could be useful to have something like sticky: true = check both ref and popper rects on each animation frame, or sticky: 'popper' / 'reference' to check one of them. That way you wouldn't need to think about manually updating.

Making Tippy aware of layout changers would be nice, especially when using dynamic templates. Would it make sense to introduce a new option, e.g. `dynamic`? This way you can apply it alongside or without `sticky`, and `sticky` remains responsible for its sole purpose.

**Comment by atomiks** [comment]
Fixed in 5.0, using new `sticky` plugin behavior
