### ISSUE TITLE
"click focus" trigger flickers on click

### ISSUE THREAD

**Issue by kjchiu** [atomiks/tippyjs#573]
## Bug description

In browsers where a click implicitly focuses, button tooltip with `click focus` trigger flickers on/off when unfocused button clicked.

## Reproduction

CodePen link: https://codepen.io/kjchiu/pen/zYOaepv

reproed in chrome, ie11,  firefox focus, firefox preview

**Comment by atomiks** [comment]
`hideOnClick: false`

`focus` is fired before `click` but the `click` handler checks if the tooltip is visible already, in which case it will hide with `hideOnClick: true`
