### ISSUE TITLE
Border round 3 edges

### ISSUE THREAD

**Issue by mikehobson** [atomiks/tippyjs#574]
Hi, Im using tippy to show an iframe on a table of data, the user moves the mouse over a cell on a table and tippy then pops up a box in which I display a graph, for some reason I seem to have a border round 3 sides of the popup and not the 4th
![tippy](https://user-images.githubusercontent.com/2518239/65053102-5904fe80-d963-11e9-8103-8d83845f991b.png)

Ive attached a screen shot of the issue, any help would be appreciated

**Comment by atomiks** [comment]
Maybe a `box-sizing` issue. To debug content inside tippy elements, use `trigger: 'click'` then inspect via DevTools
