### ISSUE TITLE
Attaching Tippy to ref element in parent component

### ISSUE THREAD

**Issue by narrative1st** [atomiks/tippyjs#575]
I'm struggling to find a way to attach Tippy to a parent ref element (actually a parent's parent's parents!)

With Popper I could do this:

`this.popper = new Popper(this.$parent.$parent.$refs.newTooltip, this.$refs.dropdown, {`

But can't find the right option to do the same with Tippy (which, I assume, works about the same).

Thanks!

**Comment by narrative1st** [comment]
Re-opening because Vue-tippy is silent...

I'm struggling to find a way to attach Tippy to a parent ref element (actually a parent's parent's parents!)

With Popper I could do this:

`this.popper = new Popper(this.$parent.$parent.$refs.newTooltip, this.$refs.dropdown, {`

But can't find the right option to do the same with Tippy (which, I assume, works about the same). Where is the `ref` element for Tippy?

Thanks!

**Comment by atomiks** [comment]
```js
this.tip = tippy(this.$parent.$parent.$refs.newTooltip, {
```
?

**Comment by narrative1st** [comment]
Sry. I was omitting for the sake of brevity - the Popper that worked fine in my component was this:
`this.popper = new Popper(this.$parent.$parent.$refs.newTooltip, this.$refs.dropdown, {
    placement: "bottom",
    modifiers: {
        offset: {
           enabled: true,
            offset: "0, 10"
         },
      preventOverflow: {
         boundariesElement: 'viewport',
         padding: 0
      }
  }
 });`

I know the `$parent.$parent.$parent` is dirty, but that should give you an idea of where the Tooltip component is, in relation to where I want it to attach it.

I'm also using `vue-tippy` with `v-slot` like this:

` <tippy 
        interactive
        placement="top"  
        theme="select" 
        animation="fade"
        delay="50,0" 
        trigger="click" 
        hide-on-click
        :on-show="open"
        :on-shown="opened"
        maxWidth=440
        >
        <template v-slot:trigger :id="'select-for-' + currentSelect">
          <button :data-template="'select-for-' + currentSelect">
             {{ currentButton }}
          </button>
        </template>
        <div>
            
        </div>
        </template>
      </tippy>
`

Hope that makes more sense!

**Comment by atomiks** [comment]
maybe
```js
this.tip = tippy(this.$parent.$parent.$refs.newTooltip, {
  content: $this.refs.dropdown
});
```
