### ISSUE TITLE
Using `target` tippy still shows when `data-` attribute is removed

### ISSUE THREAD

**Issue by davestewart** [atomiks/tippyjs#577]
## Bug description

I'm using the `target` option to run Tippy on a table and show tooltips per table cell.

We're using a 3rd party grid library which is very able. Using events, we set and remove the `data-tippy-content` attribute on each table cell as it is re-rendered. Unfortunately, after the attribute has been removed, a "ghost" tippy remains!

Tippy config

```js
      // set up tippy
      tippy(this.$refs.table, {
        target: '.htInvalid',
        arrow: true,
        animateFill: false,
        animation: 'fade',
      })
```

Render event on table:

```js
      afterRenderer (td, row, column, prop, value, props) {
        if (props.valid === false) {
          td.setAttribute('data-tippy-content', [row, column, prop])
        }
        else {
          td.removeAttribute('data-tippy-content')
        }
      },
```

This fires for each `TD` as the table is re-rendered and will add a tippy attribute only if the cell is marked as "invalid" after a previous validation run.

- a tippy attribute is added to nodes where user input was bad
- correcting errors causes the attribute to be deleted 

## Reproduction

![screencast](http://g.recordit.co/E2farojkuS.gif)

**Comment by atomiks** [comment]
You probably need to destroy the instance after the render?

**Comment by davestewart** [comment]
Hey, thanks for the quick reply.

If I've passed a `target` property though, shouldn't this only be triggered each time there's a mouse over ?

What's weird is that even though the attribute has been deleted, Tippy still thinks it's there.

**Comment by atomiks** [comment]
That's because once the instance is created it doesn't know it should show or not.

One of these should work

```js
else if (td._tippy) {
  td._tippy.destroy() // you're only destroying the child target instance
}
```

```js
onShow(instance) {
  return instance.reference.hasAttribute('data-tippy-content')
}
```

**Comment by davestewart** [comment]
Oh... it creates an instance per rollover? Yikes!

I suppose you need that for the animation.

Anyway, yes, that works.

Thank you!

**Comment by davestewart** [comment]
Crap. 

Tippy doesn't seem to be able to get the current attribute.

![image](https://user-images.githubusercontent.com/132681/65625516-d8c64500-dfc3-11e9-94f6-2d33e5bc01cb.png)

Is this not derived using `event.target` ?

**Comment by atomiks** [comment]
Hard to say without a full CodePen demo, I don't exactly know the steps that are occurring for that result

**Comment by davestewart** [comment]
Sure. Is there a sample one I can start with?

**Comment by atomiks** [comment]
The issue template you used has it

**Comment by davestewart** [comment]
My apologies! I hoped the gif and code would be enough. 

Here you go:

https://codepen.io/davestewart/pen/NWKJOrV?editors=0010

Note that the tooltip content reads the attribute, it seems to get baked-in the first time it is triggered. Subsequent clicks do not update the content.

**Comment by atomiks** [comment]
Thanks for the link!

You can use `onShow()` + `.setContent()`

```js
onShow(instance) {
  instance.setContent(instance.reference.getAttribute('data-error'))
},
```

**Comment by davestewart** [comment]
Thanks! That will do for the time being :)
