### ISSUE TITLE
Tippy does not always load

### ISSUE THREAD

**Issue by lorraineS** [atomiks/tippyjs#581]
I guess i am doing something wrong but i dont know what it is. I started with a very simple example i found. This is what i have:

```
<html>
<head>
  <title>My-Tippy</title>
  <!-- My CSS (i've imported the Tippy stylesheets)  -->
  <link rel="stylesheets" src="/files/fr/css/style.min.js"></script>
</head>

<body>
  <!-- Tippy Btn -->
  <span class="tag tag-style tag-style-more" data-tippy="Electro <br> Reggae <br> Cumbia <br> Hip-Hop <br> Hip-Hop <br> Hip-Hop <br> Hip-Hop <br> Hip-Hop <br> Hip-Hop">Text</span>

  <!-- This is for use jQuery   -->
  <script src="/files/fr/javascript/jquery.min.js"></script>

  <script src="https://unpkg.com/popper.js@1"></script>
  <script src="https://unpkg.com/tippy.js@4"></script>
    <script>
      tippy.setDefaults({
      arrow: false,
      animateFill: false,
      placement: 'bottom',
      maxWidth: '275px',
    })
    </script>

</body>
</html>
```

This code should work without problems.

BUT, I use, apart from Tippy a dozen other libraries (Slick, Tabs, Clipboard, NouiSlider, Simplebar ... etc) and there is often a problem when initializing Tippy.

Once in two the animation is triggered in a strange way, and if the text is too long, it is cut. 
Ex:

![Capture d’écran 2019-09-27 à 17 37 31](https://user-images.githubusercontent.com/6030502/65782252-8e70cf80-e14d-11e9-854e-13f03d5050b4.png)

When I delete all the libraries and keep only those related to Tippy, it works. Well it is not possible of course...

What am i doing wrong?

Thank you.

**Comment by atomiks** [comment]
I would avoid using `data-tippy` attribute now with the `setDefaults()`, as it's being removed in next major. 

But yeah, the `animateFill: false` you have fixes that issue, just initialize via `tippy()` constructor itself. If the script is right below the tippy link, it should work though.
