### ISSUE TITLE
Was event delegation removed in 5?

### ISSUE THREAD

**Issue by sporto** [atomiks/tippyjs#584]
In 4 you could do this https://github.com/atomiks/tippyjs/blob/623e8416fbb314741db603c997081512105c0d96/website/src/pages/misc.mdx#event-delegation

We use Elm to render our DOM and then use the event delegation technique in 4 to add the tooltips. This works great.

No tooltips show if we upgrade to 5. Has this been removed in 5?

Thanks

**Comment by atomiks** [comment]
[It was moved to a separate piece of code](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-target)

**Comment by sporto** [comment]
Thanks
