### ISSUE TITLE
Working with position fixed

### ISSUE THREAD

**Issue by philfontaine** [atomiks/tippyjs#589]
I'm trying to use a manual tooltip on a fixed position element, just like in this codepen: https://codepen.io/philfontaine/pen/GRKVpEX?editors=1111. However, when I scroll, the tooltip is moving and flickering a lot in a ugly way.

On the popper.js documentation website, there is a tooltip attached to the fixed navigation bar, just as I want (and it's not moving in a weird way) : https://popper.js.org/tooltip-documentation.html 
![image](https://user-images.githubusercontent.com/16233697/65998259-f5052e80-e468-11e9-8c22-6b76bb10414b.png)

I guess I just don't know the proper options for this to work. Help would be appreciated. Thanks.

**Comment by atomiks** [comment]
```js
  popperOptions: {
    positionFixed: true
  }
```

**Comment by philfontaine** [comment]
Well that was easy, sorry for not finding it in the documentation, thanks a lot.
