### ISSUE TITLE
Grey box shows up around interactive tooltip with HTML?

### ISSUE THREAD

**Issue by malonesadmin** [atomiks/tippyjs#59]
<img width="287" alt="screen shot 2017-06-11 at 10 13 34 pm" src="https://user-images.githubusercontent.com/23674651/27010923-4c64eeee-4ef3-11e7-8f75-02c21b951df5.png">

    Tippy('#myId', {
        html: '#my-template-id',
        position: 'right',
        size: 'big',
        interactive: true,
        theme: 'light'
    })

    <div id="my-template-id" style="display: none;">
        <p>Fun <strong>non-interactive HTML</strong> here</p>
    </div>

    <button id="myId" title="Tooltip text">Button text</button>

**Comment by atomiks** [comment]
That's because the popper receives focus to make it keyboard navigable. You can disable the default outline styling with `outline: 0`

```css
.tippy-popper {
  outline: 0;
}
```

**Comment by malonesadmin** [comment]
It still happens with an outline of 0 

It does not occur when HTML is used in the title, it only happens when a HTML template is used with interactive

**Comment by atomiks** [comment]
With outline 0 the blue outline goes away: https://codepen.io/anon/pen/Rgayvx 

Why is yours grey? Haven't seen that style before.

You probably have some other styling interfering with it.

**Comment by atomiks** [comment]
`outline: 0` is now applied to the popper in `v1.0.0`
