### ISSUE TITLE
Can't scroll on iPhone with many tippys in usage

### ISSUE THREAD

**Issue by nicmare** [atomiks/tippyjs#592]
I use tippy for some color palettes here:
http://help2buy.de/produkt/apple-airpods-2-mit-kabellosem-ladecase2/
password is "user" at the moment.
when i open that page on my iphone and want to scroll thru the colors available, it is very hard because it seems all these tippys on them are preventing the default scrolltouch behaviour?! so for mobile users it is nearly impossible to see all colors. hope you understand what i am talking about. any idea how to fix this?
kind regards
Nic

**Comment by atomiks** [comment]
I think I can reproduce that on Chrome mobile DevTools as well. When you try and scroll down with "mousedown + scroll" it fires a mouseenter/focus event on the color buttons which prevents the scroll?

It's very likely to be standard browser behavior

**Comment by atomiks** [comment]
> It's also occurring when I destroy all the instances

Try deleting the code that invokes `tippy()` for those elements which should be equivalent as above. If the problem still reproduces it's not tippy causing it, I can reopen if the bug is not reproduced after that

**Comment by nicmare** [comment]
excuse me. you are right. problem is not tippy but the tiles itself which seems to have touch event too. thanks for that hint!
