### ISSUE TITLE
Dimensions transition documentation

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#593]
## Problem

When updating content, it would be nice if the dimensions could transition from one size to another. This makes singleton transitions and dynamic content look more natural.

## Solution

[Seen experimentally here](https://atomiks.github.io/tippyjs/animations/#fully-dynamic)

Since the solutions I've worked on don't work for every case, this will likely be documentation only.

**Comment by atomiks** [comment]
So this is a **very** complex issue 👀, but there's progress. This is such an awesome feature, which allows you to create something like the [Stripe dropdown](http://stripe.com) with the `createSingleton` API. The dimensions of the tippy will smoothly transition from one size to another.

### Basic example

<img src="https://media.giphy.com/media/ch7WUYTU3Q28ebVDx6/giphy.gif" alt="singleton smooth transitions" />

There's about a billion edge cases to consider. Tweening the popper translation to match the dimensions spring animation with the ability to have it be canceled mid-transition without glitches was already difficult but I got that working a few months ago. However there are 3 core things that need to be considered.

### Problem 1: Transitioning content inside the tippy

This is left up to the user but is really important to complete the smooth animation look. Usually, some fading and translating can work. There'll be callbacks available via `onStart`, `onComplete`, `onSpringUpdate` callbacks provided by `flip-toolkit`.

In the above example, there's no transitioning of the content - it instantly changes and could look better.

Here's Stripe's dropdown mid-transition:

<img src="https://i.imgur.com/x5ae8qY.png" height="400" />

The content boxes are kept in the DOM and fade out while the active one fades in. Plus, there's a translation offset so it appears to stay "put" while the dropdown moves to the next location. 

### Problem 2: Arrow

They use `overflow: hidden` on the dropdown so that content gets clipped. With tippy, the arrow is part of the tooltip so it cuts it off. Instead, you'd need to move the arrow to be a child of the popper instead of the tooltip.

 This would require you to write out the arrow CSS to accomodate for that - or maybe, it can be included in the core CSS provided it doesn't bloat it much. 

This can cause issues with opacity transitions since the arrow overlaps the tooltip by 1px to prevent gaps on some browsers - so there's darkening due to overlapping (which is why it's not default).

### Problem 3: FLIP distortions

Since `flip-toolkit` uses transforms, things like `border-radius` and `border-width` get distorted if there's a large change in dimensions. I think `border-radius` can be masked a bit, but I'm not sure borders. Transitioning `height` and `width` instead of using FLIP techniques doesn't have these problems - however there are problems with using plain CSS (like creating callbacks for the transition, jitters with `top` placement if the height changes since height can't use subpixels, and lack of real spring animation).

**Comment by atomiks** [comment]
Open to PRs, closing for now

**Comment by madjennsy** [comment]
I remember you were working on this! yes that's exactly what I want to do.
