### ISSUE TITLE
Option to not destroy the linked HTML template

### ISSUE THREAD

**Issue by ivanbozic** [atomiks/tippyjs#595]
I am using Tippy to display footnotes. In order to accomplish this, I am using template linking as outlined here: https://atomiks.github.io/tippyjs/html-content/#template-linking.

After Tippy is done with its ✨ _magic_, the templates it is pulling the HTML from are removed from the DOM. Is there (could there be?) an option to disable this behavior, so that it only pulls the content from the template and not remove the actual HTML afterwards.

I would like to keep this HTML, so I can style it differently and still make it visible at the bottom of the article.

Here is how my HTML looks like:

`<a data-template="article-footnote-1">[ 1 ]</a>`

And the template / footnote at the bottom of the article:
```
<div>
    <ol>
        <li id="article-footnote-1">Lorem ipsum.</li>
        <li id="article-footnote-2">Dolor sit amet.</li>
    </ol>
</div>
```

**Comment by atomiks** [comment]
That example should have `.innerHTML` at the end (pass as string, rather than the element itself)

**Comment by ivanbozic** [comment]
Yep, works great now, thank you!

I'll leave the issue open, not sure if you want to use it to update the documentation.

**Comment by lockiechen** [comment]
> That example should have `.innerHTML` at the end (pass as string, rather than the element itself)

this way can not support event listener, how can i preserve event listener @atomiks
