### ISSUE TITLE
How to use Tippy with Webpack?

### ISSUE THREAD

**Issue by ryancwalsh** [atomiks/tippyjs#596]
I'm using Laravel-mix, which uses Webpack, and I'm used to requiring libraries like this:

```
var $ = require('jquery');
var time_helper = require('time_helper');
var moment = require('moment');
```

I would LOVE to install Tippy v5 but have been unable to get it working over the past few hours.

https://dev.to/iggredible/what-the-heck-are-cjs-amd-umd-and-esm-ikm leads me to think that I need the CJS version.

I thought maybe `const tippy = require('tippy.js/dist/tippy.cjs');` and then `tippy(myTooltip, tippySettings);` would work, but there seems to be no effect (and no error).

Do you know what I'm doing wrong?

Sorry for being such a newbie.

**Comment by atomiks** [comment]
The default import should work?:

```js
var tippy = require('tippy.js');
```

**Comment by ryancwalsh** [comment]
Thanks for your quick response. I was just about to reply that I see https://atomiks.github.io/tippyjs/faq/ mentions `const tippy = require('tippy.js');`. 

But it's not working for me. I get no error but no tooltip either. 

Tippy 2.6 used to work with `const tippy = require('tippy.js');`.

**Comment by atomiks** [comment]
What is

```js
console.log(tippy)
```

**Comment by ryancwalsh** [comment]
Logging it, I see:

```
Module {…}
animateFill: (...)
createSingleton: (...)
createTippyWithPlugins: (...)
default: (...)
delegate: (...)
followCursor: (...)
hideAll: (...)
inlinePositioning: (...)
roundArrow: (...)
sticky: (...)
Symbol(Symbol.toStringTag): "Module"
__esModule: true
get animateFill: ƒ ()
get createSingleton: ƒ ()
get createTippyWithPlugins: ƒ ()
get default: ƒ ()
get delegate: ƒ ()
get followCursor: ƒ ()
get hideAll: ƒ ()
get inlinePositioning: ƒ ()
get roundArrow: ƒ ()
get sticky: ƒ ()
__proto__: Object
```

I'm using "laravel-mix@4.1.2", which seems to use "webpack": "^4.27.1".

**Comment by atomiks** [comment]
You need to append `.default` it seems (v4 was the same):

```js
const tippy = require('tippy.js').default;
```

However I don't recommend using CJS version, because treeshaking doesn't work. Use ES module imports:

```js
import tippy from 'tippy.js'
```

**Comment by ryancwalsh** [comment]
I'd love to learn how to use ESM with Laravel Mix but haven't been able to figure it out after hours and hours.

For now, it seems `const tippy = require('tippy.js').default;` is getting me in the right direction. Thanks!

Now I see that I just need to change the settings and the object and whatever else has changed since a few versions ago.
