### ISSUE TITLE
Change showOnCreate to ShowOnInit in props sections of documentation

### ISSUE THREAD

**Issue by tilonorrinco** [atomiks/tippyjs#598]
## Bug description

Hello! Found a bug here:
https://atomiks.github.io/tippyjs/all-props/

Here in description the name of prop is incorrect: 
![image](https://user-images.githubusercontent.com/25035421/66341914-9ad10580-e961-11e9-868e-9f34deabaf23.png)
Correct name of this option is showOnInit.

**Comment by KubaJastrz** [comment]
Actually, it is correct. It was [renamed in v5](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-showoninit) to better represent lifecycle methods.
