### ISSUE TITLE
onShown and onHidden not triggered in React app in Chrome

### ISSUE THREAD

**Issue by Robloche** [atomiks/tippyjs#599]
## Bug description

`onShown` and `onHidden` are not triggered on Chrome but they are still correctly triggered in Firefox.

## Reproduction

When I code a simple CodePen example, it works but in my React application, it does not.
What can I have possibly done to get this behaviour?

I think the problem happened with the release of version 3.0.0.

**Comment by atomiks** [comment]
> I think the problem happened with the release of version 3.0.0.

Can you try 2.x?

CSS that force removes transitions, when having `duration: >0` will cause them to never be called. Inspect via DevTools to see if the transition properties on the tippy are stroked out

**Comment by Robloche** [comment]
`transition-duration` is not stroked out but the value is `0ms`, despite `duration: [250,175]` at creation.
Although, switching to `manual` triggering and using `show(1000)` shows the tooltip but without any duration. It opens right away.

I'm gonna try version 2.x and let you know the outcome.

**Comment by Robloche** [comment]
After having downgraded to 2.2.3, I confirm that it works as expected.

But going back to v3.0.1, I discovered that `interactive` is also broken in 3.x.
If I create the tooltip with `interactive: true`, it simply not shows...
The tooltip's state is OK, though:
```currentPlacement: "bottom"
isDestroyed: false
isEnabled: true
isMounted: true
isShown: false
isVisible: true```
I can see it in the DOM with the attribute `data-state="visible"` and the CSS property `visibility: visible`.
But I can't see the tooltip.

If I create the tooltip with `interactive: false`, then open it, then use `instance.setProps({interactive: true});`, I can click in my tooltip (it's a contextual menu).

**Comment by Robloche** [comment]
I appears I misread the doc and skipped the part where I need to import `scale.css` for my animation...
So, now, `onShown` and `onHidden` are both correctly triggered.

But my issue with `interactive` remains.
I will open a new bug report for this one.
