### ISSUE TITLE
SVG support has got broken in 0.16.3+

### ISSUE THREAD

**Issue by dmishh** [atomiks/tippyjs#60]
Tooltip created with an SVG DOM node is not displayed on mouse over.

`0.16.2`: works like a charm
`0.16.3`, `0.17.0`: tooltip is not rendered on `mouseover`

HTML:
```html
<svg>
  <defs></defs>
  <text>
    <tspan class="word"> <!-- tooltip node -->
      <tspan style="fill: rgb(255, 0, 0);">A</tspan>
      <tspan style="fill: rgb(255, 255, 255);">B</tspan>
    </tspan>
  </text>
</svg>
```

Tooltip is created with `tspan.word` DOM element:
```js
const tooltip = Tippy(wordDOM, {
  arrow: true,
  interactive: true,
  theme: 'light',
  distance: 0,
  position: 'top',
}
```

**Comment by atomiks** [comment]
Hmm.. I need to see a Codepen, that doesn't look complete. Where is the `title` attribute on the node?

Virtually all that changed between 0.16.2 and 0.16.3 was `(element).title` was replaced back with `(element).getAttribute('title')` since the SVG element doesn't have the title attr

**Comment by dmishh** [comment]
Oh, I see now. My little hack for SVG support stopped working:
```js
wordDOM.title = 'some title'

const tooltip = Tippy(wordDOM, {
// ...
})
```

I explicitly set `title` attribute on a `tspan` element and it works in `0.17.0`.
This can be closed now.

Thanks for the help!
