### ISSUE TITLE
From vs 2 → vs 5: strange extra symbols

### ISSUE THREAD

**Issue by acwolff** [atomiks/tippyjs#601]
I use currently an old version of Tippy and like to update to the current version 5.
I made a small test program, see https://www.andrewolff.nl/TippyTest/ 

If I run this, I get strange extra symbols:
<img width="394" alt="TippyKnipsel" src="https://user-images.githubusercontent.com/8150784/66502192-16979300-eac5-11e9-821b-c27ec1d893f7.PNG">

I have two questions:

How can I remove these extra symbols?

The example uses CDN:
    <script src="https://unpkg.com/popper.js@1"></script>
    <script src="https://unpkg.com/tippy.js@5/dist/tippy-bundle.iife.js"></script>

I like to use a local tippy.min.js or tippy.js file as I do now, but I have no experience with NPM, Webpack etc.

Where can I just download the required js files?

**Comment by acwolff** [comment]
There is no simple method to suppres all tippys without contents?

**Comment by atomiks** [comment]
The reason it was changed is because you can forget to give one content, then wonder why it wasn't created/showing up. Happened to me countless times. Seeing the weird shape shows you it was created but you forgot to give it content. This could also be a DEV warning as well.

`tippy('[data-tippy-content]')` works in your case

**Comment by acwolff** [comment]
Yes that removes indeed the extra symbols, see [here](https://www.andrewolff.nl/TippyTest/), but now I don't get a type for the first button with the title attribute. 

This is my code:

`       &lt;p&gt;&lt;button title="Button tooltip"&gt;Text button&lt;/button&gt; &lt;/p&gt;
    &lt;p&gt;&lt;span data-tippy-content="Another Tooltip"&gt;Text span&lt;/span&gt; &lt;/p&gt;
    &lt;p&gt;
        &lt;div data-tippy-content="Another Tooltip for a div"&gt;Text in div&lt;/div&gt;
    &lt;/p&gt;
    &lt;p&gt;&lt;a href="#" data-tippy-content="link tooltip"&gt;link&lt;/a&gt;&lt;/p&gt;
 &lt;/p&gt;
    
    <script>
        tippy('[data-tippy-content]', {
            content(reference) {
                const title = reference.getAttribute('title');
                reference.removeAttribute('title');
                return title;
            },
            touchHold: true,
            arrow: true,
            flipBehavior: ['top', 'right'],
            size: 'large',
            duration: 500,
            theme: 'user',
            animation: 'scale',
            zIndex: 99999
        });
    </script>`

What should I add or change to get a tippy for the button with the title attribute?
The content(reference) function is apparently not working now.
