### ISSUE TITLE
Change Tippy content/html on the fly

### ISSUE THREAD

**Issue by vukvukovich** [atomiks/tippyjs#603]
Hi @atomiks,

First thanks for the awesome lib. 🙌🏻
Is it possible to change content inside already loaded/shown tooltip with some event delegation or similar? 

Thanks, cheers!

**Comment by atomiks** [comment]
[`instance.setContent()`](https://atomiks.github.io/tippyjs/methods/#setcontent) will update content - you can pass a string or element in

**Comment by vukvukovich** [comment]
@atomiks Thanks for the answer, I am aware of set content. What if I don't have access to instance, and it is always on tooltip. More like live tooltip customizer. Any ideas?

**Comment by atomiks** [comment]
> and it is always on tooltip. More like live tooltip customizer

hmm, not sure what you mean, without a CodePen, it's difficult to understand properly what you're trying to achieve

**Comment by vukvukovich** [comment]
Sorry I meant, Tooltip is never hiding, has `tooltip_always_on='true'` option.

**Comment by Robloche** [comment]
I don't understande how could you not have access to the instance...
When you created the tooltip, you gave an HTML element to the constructor, like:
```tippy(element, {content: 'Yeah!'});```
So, now, if you need the instance again, you simply do:
```element._tippy```
And from there, you can update the content:
```element._tippy.setContent(...)```

Does that help you?

**Comment by vukvukovich** [comment]
> I don't understand how you could not have access to the instance...
> When you created the tooltip, you gave an HTML element to the constructor, like:
> `tippy(element, {content: 'Yeah!'});`
> So, now, if you need the instance again, you simply do:
> `element._tippy`
> And from there, you can update the content:
> `element._tippy.setContent(...)`
> 
> Does that help you?

It was rather specific use case. I've totally had to change logic due WordPress limitations, but I've solved it. Thank you all anyways!

**Comment by salvisb** [comment]
What would be a feasible way to access an instance of one particular element and update its content, considering that tippy was initialized like so:
`
tippy('body', {
        target: '*[data-tippy-content]:not([data-tippy-content=""])',
});
`
I have access to the element in quoestion after clicking on it, but I struggle to locate the tippy instance.
Thanks
