### ISSUE TITLE
Tooltip HTML content cannot be removed from DOM in React app

### ISSUE THREAD

**Issue by Robloche** [atomiks/tippyjs#604]
Hi,

In my React app, I create a tooltip in a component like this:
```tippy(element, {content})```
with `content` being an HTML element.

So, when the tooltip is created, the `content` element is moved from its initial place in the DOM to the tooltip itself.

My problem is when my React component is unmounted.
The `content` element does not exist anymore and cannot be removed from the DOM, resulting in a crash of my app with the following error:

> DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

I tried to use the `destroy()` method but this does not restore the element to its original place.
I tried using template and, basically everything on this [page](https://atomiks.github.io/tippyjs/html-content/) but to no avail.

Am I using this the wrong way?

**EDIT:** As a (very ugly) workaround, I encapsulated my component in an error boundary but I'd rather have something cleaner like either restoring the tooltip content so that it can be removed, or telling the DOM that it's not there anymore and do not need to be removed.

**Comment by atomiks** [comment]
> Am I using this the wrong way?

I would use `@tippy.js/react` for React apps, not this library

**Comment by Robloche** [comment]
That's of course what I'm using.

Sorry, I totally missed the other github!
I'll close this issue and open one in the correct place.
