### ISSUE TITLE
Allow extra class or multiple themes

### ISSUE THREAD

**Issue by coreyworrell** [atomiks/tippyjs#61]
Would be cool to add support to specify an extra CSS class or theme to apply to tips.. For example, a site has normal tooltips, and then some tooltips have menus in them.. Menu tooltips don't need the default padding of the tooltip, but are otherwise the same.

If you create a custom theme for this purpose, you would need to copy the theme you're already using just to modify one rule (including all styles for each of the arrow positions).

To work around this now I have set `theme: 'menu-theme light'`, that way I get the light theme and am able to override with the `menu-theme` class now as well.. This works fine, but might be worth including in an official way.

Thank you for great library!

**Comment by atomiks** [comment]
I'll add that in to next release. Next release will be `1.0.0` with some breaking API changes to simplify things

**Comment by coreyworrell** [comment]
Awesome, thank you!

**Comment by atomiks** [comment]
So do you just want something like:

`theme: 'menu light'`? And have the `-theme` suffix added automatically?

**Comment by coreyworrell** [comment]
Yeah I think that would work well.

**Comment by atomiks** [comment]
`v1.0.0`
