### ISSUE TITLE
Overlapping elements

### ISSUE THREAD

**Issue by zippy84** [atomiks/tippyjs#612]
I have a set of overlapping elements that are used by a Singleton. When I move my mouse from one element to another, the content should be updated. But onHide will be called with the new hovered element as first argument. How can I prevent that? onTrigger should be called, but not onHide.

**Comment by atomiks** [comment]
Maybe it's a bug. Have you got a CodePen to demonstrate it?

**Comment by leibbrandt** [comment]
## Bug description
I think a have same problem. Can you check the following scenario?
![Tippy](https://user-images.githubusercontent.com/29915507/89047403-a78a7400-d34e-11ea-9373-22ad6740ea5f.gif)


## Reproduction

```
<html>
<head>
    <title>Tippy</title>
</head>
<body>

<div class="tooltip" style="min-width: 250px; min-height: 50px; border: #1b1e21 1px dashed; padding: 20px">
    <div class="tooltip" style="min-width: 250px; min-height: 50px; border: #1b1e21 1px dashed; padding: 20px">

    </div>
</div>


<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script>
    let instances = tippy('.tooltip', {
        content: 'My tooltip!',
    });
    const singleton = tippy.createSingleton(instances);
</script>
</body>
</html>
```

**Comment by atomiks** [comment]
@leibbrandt I think the issue is `mouseenter` event doesn't detect it "re-enters" the outer element because it doesn't bubble like `mouseover` (it never actually left it). You might need to add your own event listeners in this case.
