### ISSUE TITLE
Improve CI infrastructure

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#616]
Remaining:

- Type tests
- Build tests (`build/` files), especially the UMD versions

**Comment by KubaJastrz** [comment]
Sounds like fun. I can definitely take a look on automating those processes.

Maybe we can even use GitHub Actions for this. I've only used Jenkins so far, so this will be interesting to learn.

**Comment by atomiks** [comment]
Travis seems to have disappeared on GitHub UI but it's still running in the background

**Comment by atomiks** [comment]
Travis disappeared yet again 🙄

**Comment by atomiks** [comment]
FYI I've added image snapshot tests for the `next` branch (thanks to @FezVrasta I copied lots of his setup 🤣) however they're failing on CI by a few 0.3%-5% and I don't know why. I think it might be due to the text rendering on Linux vs Mac, but at the same time, I kind of need to test text color for the themes... I don't know how to access the diffs without uploading them to a service either to see why they're actually different, but it's probably the text. 

I think we had that issue on Popper and we had to make it transparent.

**Comment by FezVrasta** [comment]
You may setup a docker image to run the tests locally, so that the snapshots are identical on CI and locally.

**Comment by atomiks** [comment]
I worked it out — the button styling on Linux is different, I used `all: unset` and they're passing now. The docker thing would be good but too complex for me to set up at the moment :-\

**Comment by atomiks** [comment]
@KubaJastrz doesn't seem like `release: v6.0.1` triggered a docs build?

**Comment by KubaJastrz** [comment]
@atomiks, it did. But you haven't provided the `GITHUB_TOKEN` variable in [travis ui settings](https://travis-ci.com/atomiks/tippyjs/settings). 
https://travis-ci.com/atomiks/tippyjs/jobs/295120942

**Comment by atomiks** [comment]
Fixed 👀

**Comment by atomiks** [comment]
Most of this is done now, can track the remaining work in the type test PR
