### ISSUE TITLE
Interactive tooltips show on first hover despite mouseleave being fired before delay finishes

### ISSUE THREAD

**Issue by skuby2** [atomiks/tippyjs#62]
If you have 2 or more tooltip'd elements near each other, and they are interactive tooltips with a show delay (I'm using 500 milliseconds), then the tooltips will show at times when they shouldn't. It's possible the problem also exists on a single tooltip'd element, but it's easier to reproduce with multiple.

I'm using version 0.17.0. To reproduce move your mouse quickly over two or more tooltip'd elements, then quickly stop moving the mouse and let it rest. The tooltip of the last element the mouse crossed over is showing when the mouse lands a long ways away from where the tooltip'd elements are. I'm guessing the issue is in the if(interactive) block inside the handleMouseLeave listener.

**Comment by atomiks** [comment]
Can you please make a Codepen for me?

Not seeing issues here: https://codepen.io/anon/pen/rwjMLp

**Comment by skuby2** [comment]
atomiks, thank you for responding so quickly! That's amazing really.
I'm seeing the issue on the Codepen you put together with Chrome 58.0.3029.96 (64-bit) on Linux and Firefox 36.0.4 on Linux. I might have mischaracterized it, though. It seems to be more of an issue with the first time an element's tooltip is activated. On a fresh page load of the Codepen if you mouse over Interactive A pretty quickly from above it to below it, then stop the mouse movement after you get past it, then the tooltip shows when the mouse is below Interactive A. After that you you go top to bottom over Interactive A as much as you want and it doesn't happen. Then if you try top to bottom on Interactive B it will do it as well the first time.
It may be that the issue I've been seeing is that, rather than the problem being interactive elements right next to each other. I have 30 or more tooltip'd elements on the page I've been seeing it on, so I probably came to the wrong conclusion on what the issue was.

**Comment by atomiks** [comment]
You're right, just noticed it. Thanks for pointing it out! I'll investigate wha the issue is...

**Comment by skuby2** [comment]
Awesome. Thank you for the great library and for looking into this.

**Comment by atomiks** [comment]
Found the issue. Since the popper instance is created on first mount/show, the `cursorIsOutsideInteractiveBorder` function returns returns false if it doesn't have an `x-placement` (popper instance not created yet). I'm guessing the mouseleave is fired before popper can update the DOM element and set the attribute. 

If I change it to `return: true` if it hasn't been created yet it solves the issue.

**Comment by atomiks** [comment]
Please see `v1.0.0`

**Comment by skuby2** [comment]
Thank you! I'll pull 1.0.0.
