### ISSUE TITLE
Template linking not working on IE11

### ISSUE THREAD

**Issue by er40** [atomiks/tippyjs#620]
## Bug description

Template linking HTML content doesn't seem to be working on IE11. I noticed with my own code, but then tried using the code from the docs and that doesn't work either. I don't see any errors in the console so I'm not sure how to narrow it down. 

## Reproduction

CodePen link: https://codepen.io/er40/pen/wvvJEPO

**Comment by KubaJastrz** [comment]
You need to use old syntax for content method in IE11:

```
content: function(reference) {
  const id = reference.getAttribute("data-template");
  const template = document.getElementById(id);
  return template.innerHTML;
}
```

**Comment by er40** [comment]
@KubaJastrz That did it! Thanks...I suspected this was the case but couldn't find anything online that showed the older syntax.
