### ISSUE TITLE
ARIA compliance?

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#63]
It would be cool to comply with the ARIA spec.

**Comment by atomiks** [comment]
This was added in v0.8.1: The reference elements have `aria-labelledby` pointing to the ID of the popper tooltip element which changes from `aria-hidden="false"` to `aria-hidden="true"` when appended.

Thing is, I don't know how to test it if it works properly.. so would like some guidance

**Comment by FezVrasta** [comment]
Sorry, you are right, I missed it. 👍

**Comment by atomiks** [comment]
Is there a way to test if it works?

**Comment by FezVrasta** [comment]
I think it's enough to test that the right attributes are applied to the elements.
