### ISSUE TITLE
Typing problem with new native props + plugins

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#631]
A user created a plugin with name `x` that takes a `number`:

```js
tippy(reference, {
  x: 1000,
  plugins: [x]
});
```

We introduce a new native prop with name `x` that takes a `string`

```js
tippy(reference, {
  x: 'content'
})
```

```ts
interface Props {
  // ...
  x: string;
}
```

With a runtime bailout check we can prevent errors and add a warning that their plugin now conflicts with a native prop (I expect this to be very rare):

```js
bailIfPlugin(plugins, 'x', () => {...});
```

But for types, there is a problem. If they weren't typing their plugin prop, they will now get an error since `Props` now has `x` types as `string`, but they are passing in `number`.

Is it fine that types can suddenly emit errors/warnings upon minor updates? Or do we need to remove `[key: string]: any` and force strict types (which will still emit errors if they weren't strict typing their plugin prop, but only for that release, not future ones that introduce new props)?

 Looking at the DefinitelyTyped repo, changes in types happen frequently for correctness between minors and aren't considered breaking changes. Even TS itself introduces breaking in minors.

/cc @KubaJastrz

**Comment by KubaJastrz** [comment]
I'm in favor of stricter types. Maybe TypeScript itself doesn't encourage strict typing by default (exhibit [1](https://twitter.com/sindresorhus/status/1118025528894611456) and [2](https://github.com/Microsoft/TypeScript/issues/30825#issuecomment-523668235)), it is a good idea to promote strictness wherever possible (exhibit [1](https://twitter.com/jessidhia/status/1097845261416554496)). If you don't want types, you can just use plain JS.

**Comment by atomiks** [comment]
I think all interfaces that use `Props` need to become generic? That interface is used to type `LifecycleHooks`, `Instance`, etc.

```ts
// Haven't tested this example

const tippyExtended: Tippy<Props & FollowCursorProps> = (targets, props) => {
  return tippy(targets, props);
}

const instance = tippyExtended(reference, {
  followCursor: true,
  // This would need to take Instance<Props & FollowCursorProps>
  onShow(instance) {}
}); // Instance<Props & FollowCursorProps>

// type error
instance.setProps({followCursor: 'invalid'});
```
