### ISSUE TITLE
`showOnCreate` prop & `delegate` should respect `delay`

### ISSUE THREAD

**Issue by AngelCastellanosSegundo** [atomiks/tippyjs#634]
## Bug description

We have created a method to show tooltips everywhere in the app. I call this method where we want to show the tooltip but this don´t show it the first time we put the mouse over the element (we call the method in a "onMouseOver" event).
If we don´t put the "showOnCreate:true" property, we only see the tooltip on the second time we put the mouse over an element; if we put the "showOnCreate:true" property, we see the tooltip the first time we put the mouse over an element, but it doesn´t have any properties like "followCursor:'initial'" or "delay: [500, 0]" (it is shown in the middle of the element and it appears instant).

This is my method:
```
function tipOnMouseOver (selector, text, theme)
{
    if(text){
        tippy(
            selector,
            {
                content:'<div>' + text + '</div>',
                theme:!theme ? 'MyTooltipDefaultTheme' : theme,
                followCursor:'initial',
                sticky:true,
                distance:3,
                delay: [500, 0],
                showOnCreate:true
            }
        );
    }
}
```

**Comment by atomiks** [comment]
- `showOnCreate` should be respecting `delay`, but it's being ignored. (It exists in the first place to respect delays, instead of just calling `.show()` which ignores the show delay). 
- `followCursor: "initial"` appears to work on first show for me though.

This means it affects `delegate()` which uses this type of technique.

In your case though, I would refactor that function to avoid being invoking `tippy()` on `mouseover`, and instead invoke it when the elements get created (on the DOM or JS), so you can delegate that behavior to the `trigger` prop instead of using `showOnCreate`.

**Comment by AngelCastellanosSegundo** [comment]
Thanks for the quick reply.
We are using this type of delegated behavior because we do not want to create all the tooltip when creating the table on which they are going to be displayed, since the volume of data is very large in some of the pages and not in all cases we want it to be displayed.
On the other hand, as for the followCursor plugin, it seems that it is behaving in the first execution of the onMouseOver as followCursor: false, since it is shown in the center of the cell. However, the next execution of the onMouseOver is correctly displayed at the point where it should be done.

Asi se ve la primera vez, siempre en el centro de la celda
![1st](https://user-images.githubusercontent.com/57346749/68119458-0f687700-ff03-11e9-9263-df5bb809af1f.jpg)

This is what it looks like the second time, at the point where the cursor points
![2nd](https://user-images.githubusercontent.com/57346749/68119459-10010d80-ff03-11e9-95df-a66daf17c4c0.jpg)

**Comment by atomiks** [comment]
Have you got a CodePen repro? For me using your function, `followCursor` works but `delay` does not https://codepen.io/atomiks/pen/wvvyQmQ

**Comment by AngelCastellanosSegundo** [comment]
Thanks for the quick resolution.

Maybe the difference between the example you give me and the code we have is the way to create the event. We created the event like this:

```
mygrid_pruebas.attachEvent("onMouseOver",
        function (row_id, cell_ind)
        {
            var selector = mygrid_pruebas.cells(row_id, cell_ind);
            tipOnMouseOver(selector.cell, selector.getValue());
        });
```

We create the event for each cell in the table to get the text and position.

We do not have CodePen repro, we will try to reproduce it there so we can have it.

**Comment by AngelCastellanosSegundo** [comment]
In case it helps, we have seen that in all tested browsers (Firefox, IE and Chrome) the delay property fails as commented. However, as for the followCursor property, it fails with our code in Chrome and Firefox, but it works correctly in IE.
We are using IE version 11, Chrome version 78 and Firefox version 70.
