### ISSUE TITLE
Accessing child elements in a delegate to update their content

### ISSUE THREAD

**Issue by KronemeyerJoshua** [atomiks/tippyjs#635]
I'm using Vue and dynamic elements in a row basically.

```
<div class="parent">
<div class="child" v-on:drop="drop($event)" :data-tippy-content="$somevar">Content</div>
<div class="child" v-on:drop="drop($event)" :data-tippy-content="$somevar">Content</div>
</div>
```

On mount of Vue I setup Tippy with

```
delegate('.parent', {
                    target: '.child',
                    content: 'Loading...',
                    followCursor: true,
                    plugins: [followCursor],
                });
```

This works great until I modify that div to have a different image, text, etc. inside it.
I drag another picture over that div, drop it, and it updates the div with the new picture. Tippy doesn't grab the new data-tippy-content though. :(
Now vue has already updated the attribute data-tippy-content on the div, I just need to reset or refresh it in that childs tippy instance.

I figured I could grab the calling element from the drop function and use .setContent() on it, but haven't had any luck with figuring it out.

**Comment by atomiks** [comment]
Can you querySelect the child elements, and use the `_tippy` property to access the instance to `.setContent()` whenever Vue changes `$somevar`?

**Comment by KronemeyerJoshua** [comment]
Actually, this doesn't work if you have duplicate items with the same id. >.<

**Comment by KronemeyerJoshua** [comment]
Okay, I was able to get it working. I think vues caching was getting in the way.

Since all my setups are the same, instead of grabbing the div by id.
I traversed through the event calling and grabbed the element that way.

```
<div class="parent">
<div class="child" v-on:drop="drop($item, $event)" :data-tippy-content="$somevar">Content</div>
<div class="child" v-on:drop="drop($item, $event)" :data-tippy-content="$somevar">Content</div>
</div>
```

```
drop(src, ele) {
let doc = ele.path[2]; // This is where my "child" container div is located
if (!doc._tippy) {
tippy(doc); // Occasionally there is no active tippy instance associated, I think vue caches it
}
doc._tippy.setContent(Content);
}
```
