### ISSUE TITLE
Remaining type issues

### ISSUE THREAD

**Issue by atomiks** [atomiks/tippyjs#636]
@KubaJastrz  if you're up to it, couldn't really get these working 🙂 

These are the main ones I'm aware of currently:

1.  Functions should be typed with exported interface types from `types.ts`: `Tippy` & `Delegate`. I'm not sure how to get this working with the new function overload types however. I think it will require some refactoring.

```js
// This
const tippy: Tippy = (...) => {};

// Instead of current
function tippy(...) {}
```

2. `Tippy` will return `undefined` if called a second time with `multiple: false` (default) - currently not typed at all. How can we type that correctly?

```ts
// Assuming reference is an Element.
const instance1 = tippy(reference); // Instance
const instance2 = tippy(reference); // undefined
const instance3 = tippy(reference, {multiple: true}); // Instance
```

3.  Remove `@ts-ignore` comments and type correctly (there are currently a few) 

https://github.com/atomiks/tippyjs/blob/cc0fa207df2a841d9152265e4746f51af5955b1a/src/utils.ts#L268-L270

https://github.com/atomiks/tippyjs/blob/cc0fa207df2a841d9152265e4746f51af5955b1a/src/createTippy.ts#L222-L231

https://github.com/atomiks/tippyjs/blob/cc0fa207df2a841d9152265e4746f51af5955b1a/src/index.ts#L135-L137

**Comment by KubaJastrz** [comment]
I will take a look later today

**Comment by KubaJastrz** [comment]
1. Yes, unfortunately there is no other way I know of.
2. We could set return type as `Instance | undefined` and let the user take care of it. However, I think this behaviour is slightly weird, shouldn't we return the existing instance from first call when called the second time? Not sure about this...

**Comment by KubaJastrz** [comment]
3. Created #638 for first case. 

Second is actually not possible to remove right now, because `args[1]` consists of three types not compatible with each other and TypeScript has issues with that 😐. 

Not sure what is going on in the third case. `Type 'Instance<Props> | Instance<Props>[]' is not assignable to type 'Instance<Props>'` but it should technically work as this is the exact `ReturnType` of `Tippy`.

**Comment by atomiks** [comment]
These are fixed on `next`
