### ISSUE TITLE
Canvas element supported?

### ISSUE THREAD

**Issue by VidKraner** [atomiks/tippyjs#639]
I have problem getting canvas element to work. Is it supported?

**Comment by atomiks** [comment]
Two possibilities:

- You use a virtual element (ReferenceObject) whose `getBoundingClientRect` method returns the bounds of the canvas element (I don't know how this works or if it's possible)
- Use `followCursor` + a library that detects mouseenter/mouseleave events on canvas element to be able to `.show()` / `.hide()` the tippy when necessary, so it doesn't have "bounds" (if the above isn't possible). This came up a few weeks ago in an issue

**Comment by VidKraner** [comment]
Thank you for answering, however I couldn't get it to work, therefore I implemented simple tooltip myself.

**Comment by atomiks** [comment]
I'd like to investigate how to get this lib working with canvas. Most canvas libs/implementations probably use canvas tooltip elements instead of the DOM tho.

**Comment by VidKraner** [comment]
So from my tests, the result was, that inside tooltip content was just:
`<canvas id="xyz">`
I've tried all approaches for HTML content, described at official documentation.

My goal was, to display Chart.js graph inside Tippy tooltip.

**Comment by atomiks** [comment]
Seems we had different ideas here 😅, I thought you were trying to get a tippy to show when hovering over an "element" within the canvas (since it's drawn, there's no DOM to use), rather than place a canvas element inside the tippy itself. There's shouldn't be anything limiting you from doing that since the content inside a tippy is free to be whatever. If you post some code we might be able to get a solution

**Comment by VidKraner** [comment]
Oh I am sorry, I didn't explain it well in my initial question.

Basically what I am doing:
- generating html (also icon for tippy, graph container
- initializing all graph containers with relevant data
- initializing tippy with content parameter, where I am finding and setting the graph container element
- the result was as I explained above, empty canvas tag
- if removing tippy code, the graph was correctly initialized, just messing the look
