### ISSUE TITLE
It is slow when first triggered to show.

### ISSUE THREAD

**Issue by Alecyrus** [atomiks/tippyjs#640]
When I click to trigger a `dropmenu` based on tippy after the app is launched, the animation of the menu is always slow, and if i click it again, it will appear quickly and smoothly. I recorded the performance in devtools, and found that the first click call a function to create popper instance, and the second click do not. 

But, I initialize the tippy instance immediately after the page is  loaded, why the popper instance is created when the menu is first triggered to show.  Is that a bug? What I expect is that the popper instance should have been initialized in the process of tippy instance initialization. 

As you can see, after the first click, it do a lot of things to get popper instance ready, which causes the FPS is low and do harm to user experience,

### first click
<img width="1109" alt="截屏2019-11-1213 48 46" src="https://user-images.githubusercontent.com/13865581/68645487-289ca380-0553-11ea-94f8-7d4bece52bac.png">

### second click
<img width="1080" alt="截屏2019-11-1213 49 27" src="https://user-images.githubusercontent.com/13865581/68645518-40742780-0553-11ea-8146-ea5aabf24a26.png">

**Comment by atomiks** [comment]
It's expected. The popper instance is lazily created only when necessary (i.e. triggered/shown for the first time), which greatly improves perf when you initialize lots of different tooltips. You can disable it with `lazy: false` but then you're worsening perf for first load, potentially significantly, depending on how many tippies you have.

The graph is showing it takes from 2516ms to 2536ms to initialize, or only 20ms. Users perceive things that take less than 100ms as "instant", so even with 5x slower CPU or such, it's within the budget.

**Comment by Alecyrus** [comment]
Agree with your points. There is no unrelated to `will-change: transform`, cuz it has the property already. What I mean is,  it does take some time before the animation begins, which could lead to laggy situations in some edges cases. for example, when developers add some expensive codes in hooks. For me, I will carefully arrange every module to initialize itself in different idle time, and guarantee the application's visual feedbacks are instant and consistent.  

Sorry for that I did not notice the 'lazy' property, which enables me to achieve what i want and expect.  Thank you for creating the awesome library! Good job.
