### ISSUE TITLE
5.1.1 demo/index.html fail - Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by hikikomori82** [atomiks/tippyjs#641]
## Bug description

I downloaded latest release 5.1.1. When I open demo/index.html in console there is error: "Uncaught SyntaxError: Cannot use import statement outside a module" and page is blank.

## Reproduction

- Download tippy 5.1.1 release from releases page
- Open demo/index.html in chromium browser

**Comment by atomiks** [comment]
The `demo` folder is used to develop with this library, not use code from, and works with `Parcel` module bundler only, so it won't work when you open it directly in the browser.

Although the GitHub releases page has download links, it's only the source code, not dist files. 

- [Read how to install the package here](https://atomiks.github.io/tippyjs/getting-started/)
- [How do I manually install/download the files?](https://github.com/atomiks/tippyjs/issues/633#issuecomment-549218281)
