### ISSUE TITLE
delegate uses Element.closest() not supported by IE11

### ISSUE THREAD

**Issue by alushin** [atomiks/tippyjs#642]
The delegate addon uses the following line to determine if an event triggered on an element matches the target
```
var targetNode = event.target.closest(target);
```
[Element.closest()](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) is not supported in IE11

**Comment by atomiks** [comment]
The docs mention you need to polyfill it

But tbh, there is already a `closestCallback` ponyfill which is already used internally, so we might as well just ponyfill it automatically I guess 🤷‍♂

**Comment by atomiks** [comment]
We'd also need a `matches` ponyfill which is kind of bothersome. Deciding to remain with requiring the user to polyfill it.

Since Popper is going to require users to polyfill methods in v2 the next version probably won't ponyfill anything to begin with.
