### ISSUE TITLE
Plugin docs are not accurate

### ISSUE THREAD

**Issue by some-sam** [atomiks/tippyjs#643]
## Bug description

Plugin docs do not accurate show how to use plugin.

The docs show:

```
// plugins passed a prop
tippy(targets, {
  followCursor: true,
  plugins: [followCursor],
});

// results in an error about "plugins" not being a known property.
```

While the actual usage appears to be

```
// plugins passed as a 3rd argument
tippy(targets, {
  followCursor: true
}, plugins: [followCursor],);

// works.
```

**Comment by atomiks** [comment]
You need to be using latest v5.1+

**Comment by some-sam** [comment]
Ah, I see now. I was running 5.0.2 -- great job on maintaining this thing so frequently!

I looked around a bit and cannot seem to find a changelog anywhere. While the commits are very descriptive, it would be nice to see a flat file with any interface changes, especially given that changes occur so rapidly.

Thanks for library!

**Comment by atomiks** [comment]
The changelog is on GitHub releases page https://github.com/atomiks/tippyjs/releases
