### ISSUE TITLE
wait option in v5

### ISSUE THREAD

**Issue by albert-gonzalez** [atomiks/tippyjs#645]
Hi!

I am using in v4 the **wait** option for showing the tooltip depending on some async calls. I am trying to migrate to v5, but this option is not available anymore, and I don't see in the migration guide any recommendation to migrate this option. I searched in the documentation and I didn't find any alternative.

Can you help me, please?

Thanks!

**Comment by atomiks** [comment]
Oof I forgot about that one. I believe it was added in a very early version by someone to integrate with frameworks but wasn't actually necessary.

You can achieve the same thing like this:

```js
tippy(ref, {
  onTrigger(instance) {
    instance.disable();
    // make your async call ...
    // once done:
    instance.enable();
    instance.show();
  }
});
```

**Comment by albert-gonzalez** [comment]
Nice, I'll try with this solution.

Thank you very much!

**Comment by atomiks** [comment]
You probably also need to use `onUntrigger` lifecycle to re-enable the instance depending on your cancelation/error logic, so that it can be triggered again.

You could also show a loading spinner as the content first and let it show normally instead of waiting but I'm not sure of the setup you have.

**Comment by albert-gonzalez** [comment]
Thanks again for your advice, I am going to make the change and I'll tell you if I find some problem. My tooltip is complex, it shows up immediately or after making an async call depending on multiple parameters. The "wait" option was very useful to do that.

**Comment by albert-gonzalez** [comment]
Hi again!

I have changed the code using onTrigger and onUntrigger props and It's working OK now :).

Thanks for your help and your amazing library!
