### ISSUE TITLE
Use require() (with Browserify) to import Tippy

### ISSUE THREAD

**Issue by Wolfr** [atomiks/tippyjs#646]
We have an old codebase where we use `require` instead of ES imports e.g.

```
window.tippy = require('tippy.js');
tippy('.js-trigger-tooltip');
```

If I upgrade from Tippy 4.3.4 to 5.1.2 tippy doesn't register as a function anymore.

What can I do to be able to call tippy?

**Comment by atomiks** [comment]
I think you need to append `.default` after the require call

**Comment by Wolfr** [comment]
Yes indeed!

`window.tippy = require('tippy.js').default;` works. Thanks you!
