### ISSUE TITLE
How can I manually "trigger" an instance?

### ISSUE THREAD

**Issue by some-sam** [atomiks/tippyjs#647]
I'd like to call `instance.trigger()`, which would essentially mimic triggering the instance -- eg, executing the `onTrigger` lifecycle hook, and taking into account the `delay` property.

`instance.show()` is available, but does not fire `onTrigger` or take into account `delay`.

Any workaround?

**Comment by atomiks** [comment]
> Any workaround?

```js
// or other event
instance.reference.dispatchEvent(new MouseEvent('mouseenter'));
```
