### ISSUE TITLE
hideOnClick property does not seem to have any effect

### ISSUE THREAD

**Issue by nicolethoen** [atomiks/tippyjs#648]
I guess I'm not positive if my understanding of this property is correct.

example of property not working: https://codepen.io/nicolethoen/pen/eYmYrvr

I am expecting that the tooltip should not hide if the document behind the tooltip is clicked?
Or that clicking the tooltip would not hide the tooltip?

Either way, neither of these things is happening.

The documentation reads:

> Determines if the tippy should hide if a mousedown event was fired outside of it (i.e. clicking on the reference element or the body of the page).
> 
> For click-triggered tippies, using false will prevent the tippy from ever hiding once it is showing.
> 
> To prevent clicks outside of the tippy from hiding it but still allow it to be toggled, use the string "toggle".

**Comment by KubaJastrz** [comment]
Hello @nicolethoen, it appears that you are using an outdated version of tippy (v0.13).

Here you can find the same example with latest version (v5.1.2): https://codepen.io/hawking/pen/NWPWzWy
Make sure to check out the imported files (css - base and scale animation & js - tippy and popper) in the pen settings.
