### ISSUE TITLE
tippyjs's tabindex breaks tabbed navigation

### ISSUE THREAD

**Issue by dcolens** [atomiks/tippyjs#65]
in https://github.com/atomiks/tippyjs/blob/master/src/js/core/createPopperElement.js#L86 a tabindex attribute is added to the tooltip. This tabindex breaks tabular navigation on a simple html page in the latest Chrome. Disabling Tippy fixes it.

My use case is the following:

the page contains multiple spans that have the same tippy's tip, each span has tabindex=0 so a user can navigate from one span to the next one and everytime the tooltip shows as expected. This works great on the first span but stops there, there is no way to navigate to the next element, but only to the tooltip.

Is there a really good reason for having that tabindex=0 ? 
   - YES: can we make it optional ?
   - NO can we remove it please ?

**Comment by FezVrasta** [comment]
I think it should be `-1`, this way it's still focusable but it will not change the tab navigation behavior

**Comment by dcolens** [comment]
`tabindex=-1` is good for me

**Comment by FezVrasta** [comment]
You may prepare a pull request to fix this

**Comment by atomiks** [comment]
It should probably only be added if the tooltip is interactive. If that's the case, you should have a close button on the tooltip which can be tabbed, which on click (or keyboard enter press) will close the tooltip, restoring focus to the reference element which has the tooltip.

Also, `tabindex="-1"` seems to have the same behavior to me? Since the popper receives focus and it's appended to the end of the body, it still seems to restart at the beginning of the page for me

**Comment by atomiks** [comment]
v1.0.1 - only applies to interactive tooltips and uses -1 instead

**Comment by liamtarpey** [comment]
@atomiks this still seems to be an issue for me on `v3.0.1`, I have set all of the tooltips to be `interactive:false` but I'm still getting `tabindex="0"` on every element.

**Comment by atomiks** [comment]
@liamtarpey it's because of `a11y: true`. Set `a11y: false`, but it's there for a reason. If the reference element can't receive focus then it's not accessible. What's wrong with the current behavior?

**Comment by liamtarpey** [comment]
Thanks @atomiks, I have some elements such as a little info icon that displays a tooltip which I'd rather wasn't accessible in certain cases. I'll give that a try :) thanks!

**Comment by liamtarpey** [comment]
But I could just remove the CSS outline for those particular elements I guess 😁

**Comment by liamtarpey** [comment]
@atomiks didn't know about that, thanks! :)

**Comment by kenticomartinh** [comment]
Hi, I just want to leave a comment that this being by default enabled sucks, if you place Tippy around a button, it catches the tab twice which is unwanted, and we found out that it does this extra thing much later than it was comfortable for us.

Please don't make such "hidden" features enabled by default the next time ... it is not a good practice overall

**Comment by atomiks** [comment]
@kenticomartinh if it's catching tab twice, you've put wrapped an inaccessible element around the button which the tippy is applied to...

**Comment by markjoeljimenez** [comment]
I currently have an anchor in my tooltip's content. Since the tooltip itself has a tabindex="-1", a user cannot tab onto that anchor. Is there an option where I can enable tabbing onto anchors in content?

**Comment by atomiks** [comment]
@markjoeljimenez that isn't related to the tabindex, it's because the tippy is appended to the end of the body. You need to use `appendTo` to append it to the reference's parent node instead so that it can be tabbed to after it

**Comment by jfstephe** [comment]
FWIW, I agree this was massively intuitive in v4. Just spent the best part of a day debugging my custom cell renderer in [ag-grid](https://www.ag-grid.com/example.php) which assumed event.relatedTarget was being set (tippy adding tabindex=0 knackered this).

Looks like this is no-longer added automatically in v5 :-)

**Comment by kenticomartinh** [comment]
@atomiks We use tippy around whole blocks of code, not just focusable components ... and it totally screwed up our keyboard accessibility in the whole app until we debugged that this this the case

**Comment by atomiks** [comment]
I'm kind of confused what the problem is? v5 doesn't add `tabindex` to the reference aymore. 

> massively intuitive in v4"

so auto-adding it made sense?  People were complaining about it.

**Comment by jfstephe** [comment]
@atomiks - Hi, sorry please don't get me wrong. I was trying to help and save people having the same issue time to investigate if this was still an issue in v5 (which it isn't).
