### ISSUE TITLE
Wordpress issue positioning tooltip

### ISSUE THREAD

**Issue by Aineia** [atomiks/tippyjs#651]
Hello, I decided to use tippy in WordPress. Tippy works fine on a normal HTML page, but not in WordPress. Chech the mov video I recorded below.
Is popper.js not functioning properly or need a to make some adjustments?

https://file.io/yM0hm5

Many thanks for your help

**Comment by atomiks** [comment]
The file doesn't work :-(

file.io
404
Page not found

**Comment by Aineia** [comment]
Hey sorry for that.
Here a link that works
https://drive.google.com/open?id=1nDayGT6bSHIajVcUdqDYfGq1kGpmHVLP

Let me know what you think.
Thanks for the help.

**Comment by atomiks** [comment]
It's probably a Popper bug.

Try `boundary: 'window'`

**Comment by Aineia** [comment]
Good morning!
Sadly still the same...

Anything wrong with my code?
<script src="https://unpkg.com/popper.js@1"></script>
<script src="https://unpkg.com/tippy.js@5"></script>
<script> 
tippy('.info_tooltip', {
boundary: 'window'
});
</script>

My alternative solution is to use distance: 40px which looks great on desktop, but on smaller screens, it creates a 40px gap. Is there a way to disable distance for mobile like media queries?

Many thanks!

**Comment by atomiks** [comment]
I don't know why that is happening without a repro unfortunately

**Comment by Aineia** [comment]
I  have been playing with this and found out that my theme was messing with the location. Now is fine.
But I noticed another problem.
By default works fine and does the fade_in as normal but when I try to add more arguments like these:
```
tippy('#myButton', {
    content: "I'm a Tippy tooltip!",
    placement:"bottom",
    animation: 'scale',
    arrow:'false',
    size: "large",
    theme: "mytheme"
});

```
It doesn't do anything. Can you please check the link below I created a sandbox so you can play with it as much as you want.
http://affectionate-kestrel.w5.poopy.life/


Many thanks for your help

**Comment by atomiks** [comment]
You have a syntax error. `<p>` tags inside the script. Then another script below it that's not called with those arguments so it works fine

**Comment by Aineia** [comment]
Hello Atomiks,

Could you please check this codepen and let me know why the animation, theme etc are not working? I cant see what im doing wrong here.

https://codepen.io/aineias/pen/KKwNwwQ

Thank you for your help

**Comment by atomiks** [comment]
You need to import the animations stylesheets separately. 

Info:

- [Included animations](https://atomiks.github.io/tippyjs/animations/#included-animations)
- [Linking stylesheets](https://atomiks.github.io/tippyjs/faq/#how-do-i-use-the-animations-or-themes-stylesheets-with-the-cdn)

**Comment by Aineia** [comment]
Thanks a lot, atomiks for the fast reply, your tippy.js saved a lot of time in my projects.

Cheers!
