### ISSUE TITLE
How can I use tippy.js as a notification?

### ISSUE THREAD

**Issue by QJan84** [atomiks/tippyjs#654]
Lieke PNotify: https://sciactive.com/pnotify/#demos-simple

I do not want to include another library that basically uses the same functions.

- How can I position the tippy.js dialog fixed? Aligned top-end to the parent element.
- A second dialog should be positioned under the first ... and so on
- Is it possible that tippy.js does not copy the HTML, but takes my reference directly?

**Is it worth adapting tippy.js or should I use PNotify directly?**

**Comment by atomiks** [comment]
> Is it worth adapting tippy.js or should I use PNotify directly?

I don't really think so. Tippy.js is about positioning an absolute element relative to another element and all the features of tooltips/popovers/dropdowns, which are a different UI element to alerts/notifications.

> I do not want to include another library that basically uses the same functions.

Which functions are the same?

**Comment by nicmare** [comment]
to be honest i was thinking the same. utilizing tippy as notification tool. so i found this thread via google.
