### ISSUE TITLE
How to detect the popper is out of boundaries?

### ISSUE THREAD

**Issue by lwxbr** [atomiks/tippyjs#656]
Hello, how I detect when popper is out of boundaries so I can flip it to render above(placement:right) and not out of window in the last menu item? (Using the modifiers of popper)

<a href="https://pastebin.com/8XfM2dei" target="_blank">https://pastebin.com/8XfM2dei</a>

**Comment by KubaJastrz** [comment]
`flipBehavior` prop will do it for you automatically:

```js
placement: "right",
flipBehavior: ["top"]
```

**Comment by lwxbr** [comment]
@KubaJastrz, I used the popper modifiers to change the offset and the properties of the arrow. So applying just the flip behavior wouldn't do anything until I program it manually.

For example, in the arrow modifier, I would to do something like:
```
fn(data, options){

  if(data.popperOutOfBounds){
      data.arrowStyles.bottom = 10;
  }
  else{
    data.arrowStyles.top = 10;
 }

  return data;
}
```

I didn't found that variable in tippy and in popper, so I had to create a function out of box to detect that the popper is out of bounds of viewport. I understand this issue is more a Popper issue than Tippy issue. Because is Popper that control the position of the elements, so in their modifiers they should have a flag indicating that the element is out of viewport.

**Comment by atomiks** [comment]
>  had to create a function out of box to detect that the popper is out of bounds of viewport

Can't you use `boundary: "viewport"`?

**Comment by lwxbr** [comment]
@atomiks, applied it here but didn't make any difference, did you read the code I pasted? There you can see I used modifiers to offset my Popper element, so I think this affect the way Popper identifies the element is out of boundaries.

**Comment by atomiks** [comment]
I did, I think the problem is you're bypassing all of Popper's modifier work. If you delete all your custom popperOptions and use that boundary it should just work.

Btw, Popper v2 will have a `detectOverflow` modifier which would allow detection but it's not out yet.

**Comment by lwxbr** [comment]
@atomiks, that would work if i remove the custom code, but did you saw that I want a custom behavior of Popper? 

I want that the popper appear in origin 0% 0% (x y) instead of 0% 50%. And I want the arrow in the start of popper and not in the middle of the popper. 

But this is not a Tippy issue. I think I will talk to the Popper developers to create that flag, this can be useful to many kind of situations.

I read the code of Tippy and Popper, I didn't found any variable or function that tells the element is out of bounds when I use the modifiers.

**Comment by atomiks** [comment]
> I want that the popper appear in origin 0% 0% (x y) instead of 0% 50%. And I want the arrow in the start of popper and not in the middle of the popper.

`placement: "right-start"`?

**Comment by lwxbr** [comment]
@atomiks, I think you got the point! I removed the custom modifiers and applied that, it works good! Thanks!
