### ISSUE TITLE
FlipBehaviour not working

### ISSUE THREAD

**Issue by Neill83** [atomiks/tippyjs#660]
## Bug description
My actual settings:

```
flipBehaviour: ['bottom-end', 'left-start'],
placement: 'top-end',
flipOnUpdate: true
```

This doesn't work. The tooltip placement doesn't change when scrolling.
Removing the `flipBehaviour`, the tooltip switches from top-end to bottom-end.
I want it to flip to the left-start (or right-start) when the content is too large.
What can I do?
I am using the latest version (5.1.2) of tippy.js

Thank you in advance.

**Comment by atomiks** [comment]
It's a Popper bug: https://github.com/popperjs/popper.js/issues/835 (includes workaround)

**Comment by Neill83** [comment]
oh thanks a lot.

It works using:

```
flipBehaviour: ['top', 'left-start'],
placement: 'top-end',
flipOnUpdate: true
```

this is hard to understand... I thought the first parameter of the array should be bottom (where it actually flips) and then left (where i want it to flip).

Thanks again 👍

**Comment by atomiks** [comment]
Yeah it's a bug that's fixed in Popper v2 but can't do anything for now :-(
