### ISSUE TITLE
How do I make Tippy.js track the cytoscape.js element as it is dragged

### ISSUE THREAD

**Issue by RickBogard** [atomiks/tippyjs#662]
I am using Cytoscape.js and Tippy.js.  I have an example creating two elements and I want a tool tip displayed for the elements and it should show while the element is being dragged.  I have tried the function tippy.setDefaultProps( {followCursor:'true'}), but I get an error that it is not a valid function.

This example is with TIppy v4, because the tooltip is not working in Tippy v5.x, but I would like a solution for both v4.x and v5.x

The codePen is here with my example: [Tippy v4](https://codepen.io/rbogard/details/jOEyWrL)

**Comment by atomiks** [comment]
You can just pass `followCursor: true` inside the options object. 

If not using that, there should be an event fired on each drag by Cytoscape which would allow you to call `instance.popperInstance.update()` to update the position while it's being dragged.

**Comment by atomiks** [comment]
There's a `drag` event to update the popper position. Although it doesn't work for the line node, only the circles.. but, not related to tippy
