### ISSUE TITLE
How to create permanent tooltips?

### ISSUE THREAD

**Issue by fdietze** [atomiks/tippyjs#664]
Thanks for this great library!

I'd like to create a tooltip that is shown instantly and never disappears.

Currently I'm using 
```javascript
{
  showOnCreate: true,
  hideOnClick: false,
  delay: [null, 99999999999.0],
}
```
This feels inelegant and it seems like there should be a better solution, but I wasn't able to find it.

Any ideas?

**Comment by atomiks** [comment]
You can remove the delay and use:
```js
trigger: 'manual'
```

**Comment by fdietze** [comment]
This works well, thank you!
