### ISSUE TITLE
SVG fiddles not working

### ISSUE THREAD

**Issue by wwhyte** [atomiks/tippyjs#666]
I'm trying to attach tippys to SVG elements and having no success -- the tippys are showing up in the DOM but with no height or width. In trying to debug this I came across the following jsfiddles:
http://jsfiddle.net/nholden/b7yk6mbb/1/
http://jsfiddle.net/819nouob/

I'm trying to view these in Chrome 79.0.3945.88 (Official Build) (64-bit).

It seems to me that neither of these are working as intended? In the rectangle one, "Hello, World!" appears, but that seems to be because of the title, not because of Tippy. In the circle one, nothing appears.

I also note that the rectangle one uses "new Tippy" while the circle one uses "tippy" -- this doesn't seem to be what's making the difference but I thought I should mention it. 

Would it be possible to fix those jsfiddles? That way I can see if I can resolve my problem myself (basically, "it's not working on SVG elements") or if I have a follow-up question.

**Comment by atomiks** [comment]
The problem with them is they aren't linking to major versions in the CDN so they broke when new majors got published. Here it is with latest: http://jsfiddle.net/h7cq5uf8/
