### ISSUE TITLE
Dynamic dom with tooltip in Vue project

### ISSUE THREAD

**Issue by zhangya5847** [atomiks/tippyjs#67]
I use this library in a Vue project.I want to do a feture like Echarts's word-cloud.
Here is my temeplate:
![image](https://user-images.githubusercontent.com/15855773/27528438-f28f1aac-5a82-11e7-87eb-903073f971d7.png)
Firstly,it implement the initTippy function in the mounted hook:
![image](https://user-images.githubusercontent.com/15855773/27528940-40cc8d60-5a85-11e7-9420-75a09fca6002.png)

Then, when the wordData's length changed, it  implement the updateTippy function:
![image](https://user-images.githubusercontent.com/15855773/27528918-25401b70-5a85-11e7-8a9b-6619a6f47f3b.png)

when the wordata's length reduce, it is prefect,but affter ruducing the length, i add some words,it has errors:
![image](https://user-images.githubusercontent.com/15855773/27528796-a39f6e5e-5a84-11e7-821f-993b967cf614.png)

Looking forward to your reply!

**Comment by atomiks** [comment]
That means the element you are passing into `getPopperElement` doesn't exist in the `this.tippy` instance. It might be that one of the `'.word'` elements doesn't have a title attribute and didn't receive a tooltip

**Comment by zhangya5847** [comment]
Yes, indeed it is.I try to solve the problem with another solution. I use the function this.tippy. destroyAll() to destroy all the tooltips, and then rebuild the Tippy instance.But it also has an error:
![image](https://user-images.githubusercontent.com/15855773/27533772-66a882e8-5a97-11e7-831c-462b168576f7.png)

**Comment by atomiks** [comment]
You misspelt `destroy`

**Comment by zhangya5847** [comment]
Sorry, my mistake!

**Comment by zhangya5847** [comment]
![image](https://user-images.githubusercontent.com/15855773/27536439-be961f1a-5aa1-11e7-8e3a-0bdb2a2ff39d.png)

**Comment by atomiks** [comment]
`destroyAll` is only in v1.0.0

**Comment by zhangya5847** [comment]
Thank you!I will check.

**Comment by atomiks** [comment]
@zhangya5847  did you get it working?

**Comment by zhangya5847** [comment]
Yes, it works! Thank you for your help.
