### ISSUE TITLE
Tippy on image map

### ISSUE THREAD

**Issue by abhion** [atomiks/tippyjs#671]
Hi,

I tried to add tippy on `area` on image maps. But it did not work. I see the tooltip below the image. Is there any way I can do this?

`<img sarc="assets/images/cp.PNG" usemap="#image-map" >

        <map name="image-map" style="position: relative">
            <area target="" alt="UPS" id="are" title="UPS" href="https://www.image-map.net/" coords="61,552,353,183"
                shape="rect">
            <area target="" alt="pac" title="pac" href="https://html.com/images/how-to-make-an-image-map/"
                coords="411,181,1387,364" shape="rect">
        </map>`

Javascript:

`tippy(document.querySelector('#are'), {
    content: 'TheTooltip',
showOnCreate: true,
  hideOnClick: false
 })`

**Comment by mattkaye** [comment]
I'm trying to do the same thing. I'll continue playing around with a few options but does anyone know if this has been done before?

**Comment by abhion** [comment]
@mattkaye I ended up using tooltipster.

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/issues/949

In Popper 2 (aka Tippy 6) you'll be able to extend `popperOffsets` to make this work for you, but it's not supported natively.

**Comment by maximilianh** [comment]
I cannot find popperOffsets in the documentation of tippy. There is https://atomiks.github.io/tippyjs/v6/all-props/#popperoptions but not popperOffsets. Is there a tippy example where popperOffsets is used? I guess I need to find the event target, find it's pixel position on the image and return that from the popperOffsets function?

**Comment by atomiks** [comment]
Can't really remember but I think it's like this:

```js
tippy(x, {
  popperOptions: {
    modifiers: [
      {
        name: 'imageMap',
        enabled: true,
        phase: 'read',
        requires: ['popperOffsets'],
        fn({state}) {
          state.modifiersData.popperOffsets = {
            // Hardcode the coordinate on the image map?
            x: someNumber,
            y: someNumber,
          };
        }
      } 
    ]
  }
});
```

**Comment by maximilianh** [comment]
Thanks!! Wow super quick reply. Looking more into this, I think this use
case is something where you don't want tippy. For tooltips on an image map,
they float where the mouse cursor is and so tippy/popper are actually not
needed. I think I'll implement something myself, without even popper...

**Comment by fundo-moretti** [comment]
One way to solve this is to use property [followCursor](https://atomiks.github.io/tippyjs/v6/all-props/#followcursor):

```
tippy(elArea, {
    content: "My tooltip",
    followCursor: true,
    plugins: [followCursor],
});
```
Note that the plugin must be imported when used with modules:

`import tippy, {followCursor} from 'tippy.js';`
