### ISSUE TITLE
Webpack output is larger than expected

### ISSUE THREAD

**Issue by alexmiddeleer** [atomiks/tippyjs#672]
The production build size of our app increased by about ~50kb after adding tippy, much more than expected (the motivation section of the docs page says that tippy + popper is roughly 13kb).  Do you have any ideas what might be causing this? I'm importing in one file:
```
import tippy, { inlinePositioning } from 'tippy.js';
```

**Comment by atomiks** [comment]
The 12.8 kB figure is the minzipped size. 50 kB unminified seems too large though still.

Here's what I get with `create-react-app`'s webpack config importing those two and building:

> GZip Size Online
> original size: 38850 / gzipped size: 12827

Maybe tree-shaking isn't working or you're checking the sizes of the DEV (not PROD) version

**Comment by alexmiddeleer** [comment]
Thanks for the input. I was checking the prod version, but I'll have to do some more analysis to determine whether tree shaking is working.

**Comment by alexmiddeleer** [comment]
I compared the results after gzipping the output and the size difference is much closer 14kb. Looks like this was pretty much a non-issue! Thanks for helping to clarify.
