### ISSUE TITLE
Tippy seems to prefer flipped position more often than it should?

### ISSUE THREAD

**Issue by alexmiddeleer** [atomiks/tippyjs#673]
Does tippy always prefer the "top" placement if it has multiple placement options (given its boundary rules)? I would expect that to be so by default, however I often observe it choosing an upside-down tippy (`placement: 'bottom'`) when a rightside-up tippy (`placement: 'top'`) would easily fit. I am placing tippies on inline elements and using the inlinePositioning plugin, if that is relevant. My full props set:
```
    theme: 'my-theme',
    delay: 500,
    offset: '0, -5',
    boundary: 'viewport',
    inlinePositioning: true,
    plugins: [ replaceTitleTippyPlugin, inlinePositioning ]
```

**Comment by atomiks** [comment]
Probably a bug, it should only flip when necessary

**Comment by alexmiddeleer** [comment]
Ok, thanks. I will create an issue for this if I have some time to produce a high quality bug report.

**Comment by alexmiddeleer** [comment]
Just an update - `flipBehavior: [ 'bottom', 'top' ]` seems to be a workaround, though not heavily tested yet.
