### ISSUE TITLE
Tippy flips tooltip when offset with negative y axis value is used

### ISSUE THREAD

**Issue by alexmiddeleer** [atomiks/tippyjs#676]
## Bug description

Tooltip flips when offset prop is used with negative y axis value, e.g. "0, -5". For more background, see #673. 

## Reproduction

https://codepen.io/AlgeoMA/pen/rNadrxM

**Comment by alexmiddeleer** [comment]
What I was trying to accomplish with `offset: '0, -5'` was moving the tippy closer to the content it's attached to.

**Comment by alexmiddeleer** [comment]
Perhaps as a workaround I can just add `top: 5px;` to the tippy-popper class instead of using offset?

**Comment by atomiks** [comment]
You can use `distance` instead, it doesn't have the bug

**Comment by alexmiddeleer** [comment]
If you want me to, I'd be happy to submit a PR to update the docs for offset so people like me don't misuse it 😄 .

**Comment by alexmiddeleer** [comment]
Nevermind, I see you beat me to the punch. Thank you!

**Comment by atomiks** [comment]
This will probably be fixed in the Popper 2 upgrade
