### ISSUE TITLE
enableDynamicInputDetection is not a function

### ISSUE THREAD

**Issue by VitorLuizC** [atomiks/tippyjs#68]
Tippy was not working for mobile devices and looking at Tippy's docs i found `tippy.enableDynamicInputDetection` function that enable dynamic input detection. But it doesn't work and I can't find it in the file.

![image](https://user-images.githubusercontent.com/9027363/27561165-71a4a3b0-5a9d-11e7-8039-6b62e64c3086.png)

**Comment by atomiks** [comment]
It's enabled by default in v1.0.0 and only available in v1.0.0. The docs are only a reflection of the latest version so make sure you're up to date.

Though it still should have been working on mobile before. What's going wrong?

**Comment by VitorLuizC** [comment]
Yeap, installing v1.0.0 fixed this issue. Thanks a lot!
