### ISSUE TITLE
Add a focusin trigger

### ISSUE THREAD

**Issue by iansan5653** [atomiks/tippyjs#682]
Currently, the only triggers are `mouseenter`, `focus`, `click`, and `manual`. This means you have to directly wrap the target element (or reference it, which can be difficult for React apps). It would be nice to have a way to show the tooltip when focus enters the target element and hide it when focus leaves.

**Comment by atomiks** [comment]
I'm not sure how this would work, can you give an example?

**Comment by iansan5653** [comment]
For the React wrapper, I wanted to make a generic component that I can use to wrap any of my components without having to forward all my refs (per the section on [component children](https://github.com/atomiks/tippy.js-react#component-children)). So I just wrap the children of my component in an `inline-block` `<div>`.

This works fine for mouse interaction as the tooltip appears when the mouse enters the `div` and disappears when it leaves. But it doesn't work for keyboard interaction because the `div` is not focusable. If I add `tabIndex="0"` then I can focus on the container, but that's a really strange behavior when I'm tabbing through a document - I don't want to focus on the container and then on the button within.

If Tippy used the [`focusin`](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event) event instead of `focus`, the tooltip would appear any time focus is _inside_ the `div`, rather than directly _on_ the `div`.

**Comment by iansan5653** [comment]
I'd be glad to work on a PR. Thanks for the info
