### ISSUE TITLE
`mouseRest` example prevents `interactive` behavior

### ISSUE THREAD

**Issue by justinanastos** [atomiks/tippyjs#684]
## Bug description

When using the mouse rest plugin, tooltips will still be hidden when set up to be interactive.

## Reproduction

https://codepen.io/justinanastos/pen/xxbyRdz

Hover over the button and then try to select the content because it's interactive; the `mouseleave` event will remove the tooltip when I'd expect it to remain.

**Comment by atomiks** [comment]
I'm not sure if it's possible. I think interactivity is missing a piece to enable plugins to "hook" into it... 🤔

**Comment by atomiks** [comment]
I removed this example for now. I might add it back in later if there aren't any problems with it in the future.
