### ISSUE TITLE
[Doc update] Tooltip arrow color

### ISSUE THREAD

**Issue by louisameline** [atomiks/tippyjs#686]
Hi there,
Great work on this lib, congrats :)

A typo in the doc here: https://atomiks.github.io/tippyjs/themes/#css-arrow
it says 
`.tippy-tooltip.tomato-theme[data-placement^='top'] .tippy-arrow`
while it should be
`.tippy-tooltip.tomato-theme[x-placement^='top'] .tippy-arrow`

Thank you!

**Comment by atomiks** [comment]
Hi, the doc is correct in v5 😄 

`data-placement` is the attribute on `.tippy-tooltip`, while Popper applies its own attribute, `x-placement`, to the outermost popper node, which isn't used for styling in Tippy

**Comment by louisameline** [comment]
Ok right, sorry, it's `vue-tippy` which uses an old version. I saw you reached to the author to make it more official and maintain it, any news on that?

**Comment by atomiks** [comment]
If you're still on v4, [its docs are available here](https://github.com/atomiks/tippyjs/tree/623e8416fbb314741db603c997081512105c0d96/website/src/pages) (this is linked on the README too) – maybe `vue-tippy` should link to this instead. Ideally, we'd have a versioning system on the docs in place so you didn't need to browse the `.mdx` files, but, I haven't had the time to make that :\

Yeah, I wanted to make one for Vue, but I realized that I don't have the time to maintain yet another framework's wrapper. I only work with React where the wrapper's codebase is really small and doesn't seem to have many issues, so it's easy to maintain. I'm not sure what Vue's would be like. I should probably just close that issue, I forgot about it

**Comment by louisameline** [comment]
Fair enough, thank you.
