### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by powah** [atomiks/tippyjs#687]
I'm working on replacing Qtip2 library with TippyJS and encountered big performance degradation. I can't provide Codesandbox example but I will try to give as much information as I can. TippyJS is used in an SVG context (d3 chart) which has many elements (thousands actually) but Tippy is added only on few of them (~ 5 reference elements). If tippies are triggered by mouseentering those elements everything works fine and quickly. But if tippies are manipulated via _tippy.show() and _tippy.hide() style recalculations takes more than 0.5 seconds (we have a datatable below the chart which triggers tooltips to show when row is hovered). As I mentioned Qtip handles that smoothly no performance issues at all. I tried to set as many performance related props as I found, something like this: 

`        tippy(arrayOfReferenceElements, {
            duration: [1, 20],
            placement: 'top-end',
            trigger: 'mouseenter',
            ignoreAttributes: true,
            flip: false,
            onShow(instance) {
                instance.setContent(instance.reference.getAttribute('label'));
            }
        });
`

but no effect. Did a bit of performance profiling in Chrome Devtools and saw the following:
Recalculate Style:
- Total Time: 678 ms
- Elements affected 27823
- First Invalidated @ createTippy.ts:1104

Any guidance is more than welcome. And thanks for the great work and library!

**Comment by atomiks** [comment]
I'm not sure why that would be happening without a repro unfortunately. After all, the event listeners also call the `show()` method themselves

**Comment by atomiks** [comment]
Can't help without repro sorry.
