### ISSUE TITLE
Issue with tooltip position

### ISSUE THREAD

**Issue by Awilum** [atomiks/tippyjs#688]
I have this strange issue with tooltip position
when it is opened on click, its position is wrong (from time to time), but when I try to scroll, position okey.

```
<script>
    tippy('.js-dropdown-btn', {
        placement: 'left',
        allowHTML: true,
        interactive: true,
        popperOptions: {
            positionFixed: false
        },
        trigger: 'click',
        maxWidth: 500,
        zIndex: 10,
        content: $('.js-dropdown-btn').siblings().html()
    });
</script>
```
![Screen Recording 2020-01-27 at 14 02 36](https://user-images.githubusercontent.com/477114/73169882-27b8ee00-410e-11ea-8e10-f5d73b3d3b15.gif)

Tested in Safari and Chrome

**Comment by atomiks** [comment]
Probably a Popper bug, probably fixed in Popper 2 😅

For now you can add this lifecycle prop, it should fix it:

```js
onMount(instance) {
  instance.popperInstance.update();
}
```

**Comment by Awilum** [comment]
@Awilum when Tippy will be updated with new Popper 2 ?

**Comment by atomiks** [comment]
Sometime in February

**Comment by Awilum** [comment]
```
    tippy('.js-dropdown-btn', {
        placement: 'left',
        allowHTML: true,
        interactive: true,
        popperOptions: {
            positionFixed: false
        },
        onMount(instance) {
            instance.popperInstance.update();
        },
        trigger: 'click',
        maxWidth: 500,
        zIndex: 10,
        content: $('.js-dropdown-btn').siblings().html()
    });
```

unfortunately, I still see this issue

**Comment by atomiks** [comment]
What if you wrap it in a `requestAnimationFrame` or two? Or if you remove `positionFixed` and use `appendTo: document.body` instead?

**Comment by Awilum** [comment]
@atomiks is it possible to do the same dropdown tooltip with Popper 2, and without Tippy ? example on the Popper 2 shows only how to create a one single tooltip, when I was trying to create several tooltips with Popper 2 (with help of ClassNames) it is not working. Is it possible ? and is there some real working example with Popper 2 for same task ?

**Comment by atomiks** [comment]
Yes anything is possible with it, Popper is the foundation to build tooltips/popovers etc by positioning them correctly (which is really complex). Abstractions on top require your own code. 

Couldn't really be bothered making an example rn, but you'd use `document.querySelectorAll('.js-dropdown-btn')` and loop over the elements and generate poppers for them, and add all the tooltip functionality they need to work

**Comment by Awilum** [comment]
@atomiks I think I have found the issue... 

Issue in the html code from here `content: $('.js-dropdown-btn').siblings().html()` there is some kind of css styles conflict with FontAwesome icons.

issue with tooltip position
```
    <div class="js-dropdown dropdown">
                                    <a class="dropdown__item" href="{{ path_for('admin.entries.edit') }}?id={{ entry.slug }}&type=editor">
                                        <i class="fas fa-edit dropdown__icon"></i>
                                        {{ tr('admin_edit') }}</a>
                                    <a class="dropdown__item" href="javascript:;" onclick="$('.js-add-entry input[name=id]').attr('value', '{{ entry.slug }}');" data-toggle="modal" data-target="#selectEntryTypeModal">
                                        <i class="fas fa-plus-circle dropdown__icon"></i>
                                        {{ tr('admin_add') }}</a>
                                </div>
```

and works fine without icons 

```
                                <div class="js-dropdown dropdown">
                                    <a class="dropdown__item" href="{{ path_for('admin.entries.edit') }}?id={{ entry.slug }}&type=editor">
                                        {{ tr('admin_edit') }}</a>
                                    <a class="dropdown__item" href="javascript:;" onclick="$('.js-add-entry input[name=id]').attr('value', '{{ entry.slug }}');" data-toggle="modal" data-target="#selectEntryTypeModal">
                                        {{ tr('admin_add') }}</a>
                                </div>
```

I will try to investigate why it is so, anyway, thanks @atomiks for your reply.

**Comment by atomiks** [comment]
My guess is the icons load in a split second later after popper positioned the tooltip already, causing the size to change. Wrapping the update call inside a requestAnimationFrame (or whenever they load) should fix it, or use the `sticky` prop.
