### ISSUE TITLE
Arrow position 

### ISSUE THREAD

**Issue by Alex360hd** [atomiks/tippyjs#69]
Hello,

First, nice plugin. Looking for a better alternative of tether and this one seems great !

However, I played a little with it and notified 2 problems related with arrows.

* You can't control arrow position when you use suffix for positionning your tooltip. For example, I want to display a tooltip in a "bottom-start" position. The arrow is on the top right corner of the tooltip whereas I want it on the top left corner.
* The display is buggy with rounded corners

The problem is that the arrow positionning is hard coded in a style="" html attribute.

It could be fixed with CSS and some !important rules but : 

* it's a practice to avoid, or use with caution, and overriding a buggy hard coded style attribute is not a case where !important is a good alternative....
* it's annoying to define some styles to correct arrow positionning on each projects you use tippyjs library

So I think it should be fixed directly in the library, by providing a flexible way to position the arrow the way you want.

See [an image](https://ibb.co/hOJUV5) to illustrate my words.

Thanks

**Comment by atomiks** [comment]
https://github.com/FezVrasta/popper.js/issues/179

I'd need Popper.js to implement a modifier for this functionality

Right now you can hack it by adding a custom `transform: translate` setting and shift the arrow.

**Comment by FezVrasta** [comment]
The situation in the picture shouldn't appear because Popper.js reads the width of the arrow and makes sure there's a bit of padding between the end of the popper and the arrow.

Are the Tippy.js arrow a zero width elements maybe?

**Comment by atomiks** [comment]
@FezVrasta they're [CSS triangles](https://stackoverflow.com/questions/7073484/how-do-css-triangles-work), so yes zero width and height with borders to produce the arrow appearance

They were originally a rotated rectangle but Chrome didn't render a perfectly sharp point & the transparent theme makes it overlap

**Comment by FezVrasta** [comment]
You could put the css triangle in a `::before` element and give the proper size to the parent element

**Comment by atomiks** [comment]
v1.1.0 - can't do customization until Popper implements it

**Comment by NastiaBlinov1** [comment]
Hi. Is there a solution for this issue yet?
