### ISSUE TITLE
Best way to add a wrapper to div.tippy-popper?

### ISSUE THREAD

**Issue by madjennsy** [atomiks/tippyjs#691]
For e.g.: when Tippy is trigger by a menu, I append it to header and I want to add a wrapper to div.tippy-popper, should it be done onMount? onShow? or after instancing tippy?

In my case, wrapper is required since width by percentage is added to .tippy-popper and I need this width% based on wrapper size, not on header size. I tried width:100% to .tippy-popper and width:75% to .tippy-tooltip but this was making conflicts with Style transform on .tippy-popper

**Comment by atomiks** [comment]
You should use `appendTo` to append it to the wrapper I guess.
