### ISSUE TITLE
Tippy with "focusout" trigger doesn't disappear when focus leaves the container from a child element

### ISSUE THREAD

**Issue by iansan5653** [atomiks/tippyjs#693]
When I closed #682, I used the same `onBlur` handler that was already use, and just called it on `focusout` in addition to `blur`. That handler checks whether `event.target` is the target element for the Tippy instance and if it is, hides the tooltip. This ensures that the tooltip isn't hidden if focus leaves the target element and enters the tooltip.

This appears to work at first glance, because when `focusout` is dispatched by the container element, the `event.target` is the container. However, when focus leaves the container element from a child, `event.target` is that child. 

For example, when the user tabs through the following document, `focusout` will be dispatched by `#container` when focus goes from `#b` to `#c` as expected. However, the `target` of that event will be `#b` _not_ `#container` as I expected:
```html
<a href="#" id="a">a</a>
<span id="container">
  <a href="#" id="b">b</a>
</span>
<a href="#" id="c">c</a>
<a href="#" id="d">d</a>
```

Thus, Tippy thinks that focus has gone to the tooltip and so the tooltip should stay visible, where in fact it has gone to the next element and the tooltip should hide.

**Comment by tenshi04** [comment]
It seems that this issue still persists the most recent version.

I have a few tooltips within some paragraph text and each tooltip has a link on it. First I tab to the first tooltip, and then tab to the link within the tooltip. Then I tab to the next tooltip, but the first tooltip still remains visible and does not hide.

**Comment by ajaykarwal** [comment]
2024 and this issue still persists... They close when tabbing in reverse with Shift+Tab.
