### ISSUE TITLE
tippy popover going out of the window

### ISSUE THREAD

**Issue by ajiteshsingh** [atomiks/tippyjs#695]
![Screenshot 2020-02-06 at 12 00 38 PM](https://user-images.githubusercontent.com/22662498/73911668-8c2b3880-48d8-11ea-9687-98e9e59a1563.png)

As you can see in the image the popper gets cut out of the window, is there any way I can confine the popper within the window viewport?

tippy options:

this.tippy = tippy(result, {
        delay: [500, 0],
        content: this.getPreviewElement(),
        allowHTML: true,
        theme: 'light block-folder-popover',
        animation: 'scale',
        appendTo: document.body,
        placement: 'right',
        boundary: 'viewport',
        flipOnUpdate: true,
        interactive: true,
        onShown: () => {
          this.triggerAutoplay();
        },
        onHide: () => {
          this.detachAutoplay();
        }
      });

**Comment by atomiks** [comment]
Do you mean at the bottom? `boundary: 'viewport'` should work 🤷‍♂ 

It's probs fixed in Popper 2
