### ISSUE TITLE
Tippy seems not to build the tip in some circumstances.

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#697]
Hi. Not sureit's a bug, but I try to ask. It's quite impossible to replicate the thing in codepen because in my case there's a too complex html/css/js structure.

What's happening is tippy creating the instance, but not showing anything on hover. By checking source page on console, I can see that nothing happens when I hover my element (usually you can clearly see the new dom elements created and destroyed by tippy on hover/out, at the bottom of the html source, but in this case nothing happens).

To prove that tippy instance gets created and the dom element recognized, I logged out the instance. See attachment.

<img width="1036" alt="Schermata 2020-02-06 alle 08 48 07" src="https://user-images.githubusercontent.com/437598/73916877-97716a80-48be-11ea-9178-33f04f07f496.png">

The html element is simply `<div id="info-tippy" title="test">info tippy</div>`

Also, I can confirm tippy is working properly with the above elements. 

<img width="204" alt="Schermata 2020-02-06 alle 09 02 09" src="https://user-images.githubusercontent.com/437598/73917378-91c85480-48bf-11ea-937e-ac87f43a9e73.png">

So I really can't say why it's not working for the element info-tippy element.

I must say though, that document area is a css slider (it's a multistep form, sliced into multiple sliding pages/panels). Don't know if maybe there's something there preventing tippy to build the tooltip. Anyway, it's very strange. Again, the tooltip is not built/created. It's not that's not visible because, say, out of view. No, it doesn't get created on hover.

**Comment by atomiks** [comment]
Do you have `opacity: 0` or some other CSS preventing it from showing? I think someone else had this problem a month or two back 🤔

If you use `trigger: "click"` and hover over the `popper` property (element) in the logged out instance, it should highlight the element in the DOM. If it does, but it's not visible, it's likely some CSS issue hiding it.

**Comment by stratboy** [comment]
By triggering click it doesn't do anything. I can say 3 new things:

- It's not a v5 issue > in fact, I updated to v5 because I hoped it would have solved the issue. THe issue was already there with v260.

- Instance is created, but no event is attached

- In console, if I hover the reference propery (the main element), it's not highlighted on page

That tells me that probably, the element we are seeing in page is not the one used by the tippy instance. And here comes in maybe Vue (from the shots you can see I'm using Vue). Maybe it a shadow dom - related thing. Still, I really don't know how to solve..

**Comment by atomiks** [comment]
So you're passing the wrong element in as the reference then I guess. Doesn't seem to be a problem with this lib, rather where you init the tippy

**Comment by stratboy** [comment]
I confirm the problem was when I instantiated tippy. Problem solved, thank you.
