### ISSUE TITLE
Tooltips go astray if the parent block has position absolute

### ISSUE THREAD

**Issue by Egorvoz** [atomiks/tippyjs#70]
Hello.
I have a problem - when you set `position: absolute` to parent block the tooltips go astray.

![weirdtooltips](https://user-images.githubusercontent.com/6547453/27679134-62cf2ade-5cc0-11e7-8670-6e18edbe0281.png)

So as you can see - div with class `container-fluid` has `position: absolute` and 
when i toggle Chrome DevTools - the tooltips go up.

I debug this - and i find the solution to use `followCursor` prop and set `position except top and bottom`,
but I wanna know how can i fix this.

P.S. Your lib is f*cking awesome. I am really like it.

**Comment by atomiks** [comment]
@FezVrasta

I guess this is a problem with Popper.js. You need to be scrolled down a bit too before they start being incorrectly positioned

Can you try and recreate it using Popper.js alone?

http://codepen.io/FezVrasta/pen/wGqJEz

**Comment by Egorvoz** [comment]
@atomiks I can recreate this bug, but lately. Because i am busy right now. 
Sounds good ?

**Comment by atomiks** [comment]
Yup, that's okay

**Comment by Egorvoz** [comment]
@atomiks So the simple way to reproduce it - use your main website (documentation).
*Steps:*
1. Go to your 
2. Open devtools.
3. Find in `Elements` tab div with `container-fluid` class.
4. Set in Styles  `position: absolute`.
5. Check the tooltips on your homepage main (documentation).
6. Most of them disappears (for example see `Creating a tooltip` section).
7. So this is main bug - when the parent element has an absolute position.

P.S. If you want i can record a screen to show the problem.

**Comment by atomiks** [comment]
I know that it's a problem because I did the same steps myself haha, what I meant is that Popper.js (not Tippy.js) is what controls the positioning of the tooltips, so if you see a problem relating to the positioning then the bug is most likely in Popper not Tippy. So you need to try and recreate it with Popper.js, not with my library.

**Comment by Egorvoz** [comment]
@atomiks gotcha

**Comment by Egorvoz** [comment]
@atomiks So i'll post the bug also in the popper js repo because I can reproduce it in Popper Main Website.

**Comment by Egorvoz** [comment]
@atomiks See https://github.com/FezVrasta/popper.js/issues/331
Popper.js has the same problem.
:-1:

**Comment by atomiks** [comment]
1.4.2 uses latest Popper which fixes this issue.
