### ISSUE TITLE
Proper tippy destroying

### ISSUE THREAD

**Issue by powah** [atomiks/tippyjs#702]
Let's say we have HTML

```html
<div id="parent">
  <div id="child"></div>
</div>
```

and Tippy bound to inner div **#child**. Later I want to remove **#parent** an everything inside of it (no memory leaks, etc.). Do I have to destroy Tippy instances myself before removing parent node? If I won't will I leave tippy instances hanging in the memory? 

Thanks in advance!

**Comment by atomiks** [comment]
> Do I have to destroy Tippy instances myself before removing parent node? If I won't will I leave tippy instances hanging in the memory?

Yes — removing the DOM nodes won't clean up the instances in JavaScript memory. You need to call `instance.destroy()`. The Tippy React wrapper handles all of this for you 😏

**Comment by powah** [comment]
Thanks!
