### ISSUE TITLE
Don't hide tooltip when use autocomplete in the input field

### ISSUE THREAD

**Issue by kukabuu** [atomiks/tippyjs#703]
I use tippy js for show tooltip with a login form. when I click in the input field, I want to choose text from autocomplete. if I do this, tooltip hides. 
has it any solution?

**Comment by atomiks** [comment]
`hideOnClick: false`?

**Comment by kukabuu** [comment]
Thanks for the quick response! 
I use the "mouseenter" trigger as an event that causes a tippy to show. 
`hideOnClick: false` doesn't work in this case :(

**Comment by atomiks** [comment]
`interactive: true`?

**Comment by kukabuu** [comment]
yes, I applied this property, but the tooltip disappears anyway

**Comment by atomiks** [comment]
I'm not sure otherwise without a CodePen repro unfortunately

**Comment by kukabuu** [comment]
https://codepen.io/kuka1234/pen/OJVMVWz

**Comment by atomiks** [comment]
Are you referring to the browser's autocomplete dropdown for the password? (It only shows on Firefox for me).

I'm guessing that it fires one of the events that the interactive tippy uses to determine when to hide. Since it's "native" it might be hard to workaround.

**Comment by kukabuu** [comment]
Thanks!
