### ISSUE TITLE
Tippy not showing at coordinate in canvas

### ISSUE THREAD

**Issue by chitgoks** [atomiks/tippyjs#705]
Hi again.

This is my code when creating a tippy in canvas

```
var tooltip = tippy(this.canvas, {
      allowHTML: true,
      duration: [500, 0],
      zIndex: 99999
});
tooltip.offset = '300,100';
tooltip.setContent('test');
tooltip.show();
```
What happens is that instead of showing the tooltip within the canvas area, it is always at the bottom of the browser 
![tippy](https://user-images.githubusercontent.com/3955470/74724790-cf41c000-5277-11ea-8907-6804242dea1f.png)

The mouse cursor is somewhere in the highlighted text in yellow.

Thoughts?

The '300,100' is just a sample. the original code is the x,y variable of the mouse coordinate.

If i use the boundary property, like setting value to 'viewport', the tooltip will always show above the canvas at center.

**Comment by atomiks** [comment]
I'll need a CodePen reproduction to help I think

**Comment by chitgoks** [comment]
hi @atomiks  thank you for responding. I think the solution for my use case is if the tooltip div is created within a dom element instead of outside in the root body. is that possible?

like i wish for example want the tippy tooltips to be created within div#parent2

<body>
    <div id="parent1">
        <div id="parent2">
        </div>
    </div>
</body>

**Comment by chitgoks** [comment]
@atomiks  seems i did not have luck finding a way to place the tippy generated dom inside another dom element instead of within the body tag. is this perhaps possible?

**Comment by chitgoks** [comment]
@atomiks  seems the appendTo property is the solution. i have a quick question though. i tried to manually set the offset but it does not follow the value i set.

e..g

tippyObject.offset = '300, 100';
x = 300
y = 100

thoughts?

**Comment by chitgoks** [comment]
i decided to use followCursor: true instead.
