### ISSUE TITLE
Rate exceeded.

### ISSUE THREAD

**Issue by bhavik-kher** [atomiks/tippyjs#706]
## Bug description

-- https://unpkg.com/popper.js@1

-- https://unpkg.com/tippy.js@5

**Comment by KubaJastrz** [comment]
We can't do anything as this is a cdn issue. https://github.com/mjackson/unpkg/issues/237

**Comment by KubaJastrz** [comment]
Looks like it started working again.

**Comment by bhavik-kher** [comment]
Is there any way to download files?I can host to my server
