### ISSUE TITLE
Ability for prop flipBehavior to accept values with suffixes such as `-start` or `-end`.

### ISSUE THREAD

**Issue by SkylerStearns** [atomiks/tippyjs#710]
## Problem

Prop `flipBehavior` currently does not accept values with suffixes such as `-start` or `-end`.

When using the placement prop `{ placement: 'right-start' }`, users are unable to successfully create alternative placements using the `flipBehavior` prop `{ flipBehavior: ['right-start', 'bottom-end']`. The result is a tooltip that ignores the `flipBehavior` prop entirely, with the initial placement either going out of view, or overlapping with the parent element.

## Solution

Functionality should be added to the `flipBehavior` prop to accept placement values with suffixes.
Example: When a user creates a tooltip using the prop `{ placement: 'right-start' }`, they should also be able to use the prop `flipBehavior` using values with suffixes to determine an alternative placement of the tooltip in the event that a placement cannot be used, such as `{ flipBehavior: ['right-start', 'bottom-end']`.

**Comment by atomiks** [comment]
This is fixed with the Popper v2 update (Tippy v6). I'll be releasing it very soon, like within the next few days, likely this weekend.

**Comment by SkylerStearns** [comment]
Perfect timing! Thanks for the update!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
