### ISSUE TITLE
ie11 support?

### ISSUE THREAD

**Issue by chitgoks** [atomiks/tippyjs#712]
I tried to open the tippy js website using ie11 and the tooltips do not work. is this for html5 browsers only?

i tried to also use the tippy js code in ie11 and included the polyfill for promises but it cannot understand such properties like onShow ... etc

this is when i use the onShow() property inside tippy 

```
onShow(instance) {
                            console.log(instance);
                            instance.popperInstance.reference = {
                                clientWidth: 0,
                                clientHeight: 0,
                                getBoundingClientRect() {
                                    return {
                                        width: 0,
                                        height: 0,
                                        top: y,
                                        right: x,
                                        bottom: y,
                                        left: x,
                                    };
                                }
                            };
                        }
```

**Comment by atomiks** [comment]
You should learn about transpilation to write new ES2015+ syntax that works on old browsers ➡️https://babeljs.io/ this has been part of everyone's development toolchain for a while 😄 If you don't know how to set it up, you can use the [online REPL](https://babeljs.io/en/repl) that you can copy/paste the code into to make it work on IE11.

The polyfills aren't necessary for Tippy v5.

**Comment by chitgoks** [comment]
first time using it now :D thank you @atomiks 

now, works in ie11.
