### ISSUE TITLE
Interactivity issue

### ISSUE THREAD

**Issue by spassat** [atomiks/tippyjs#713]
I have been referred by the author of the cytoscape-popper extension relating to a problem of creating a Tippy tooltip with the 'interactive: true' property. Another user of the same extension had the same problem.

See here: https://github.com/cytoscape/cytoscape.js-popper/issues/37 for a full description.

When the interactive setting is absent, I have no problem.

Any help or  advice on this issue would be grategully received.

**Comment by atomiks** [comment]
Hi, I can't help without a bug reproduction or at least some code/info, there's not enough for me to go off here
