### ISSUE TITLE
Console warning 

### ISSUE THREAD

**Issue by Wyzix33** [atomiks/tippyjs#715]
I'm getting a Console warning on Chrome browser
```
DevTools failed to parse SourceMap: webpack:///node_modules/tippy.js/dist/tippy.esm.js.map
```

I'm using webpack 4 and building for development, i have "tippy.js": "^6.0.0"  included like this:

```
import tippy, { sticky } from 'tippy.js';
```

tippy.esm.js.map is there but maybe it's malformed? 

Thanks

**Comment by atomiks** [comment]
Rollup automatically generates them, so not sure :\

**Comment by atomiks** [comment]
Have you tried https://github.com/atomiks/tippyjs/issues/327#issuecomment-583406064

**Comment by Wyzix33** [comment]
That was it 👍 

Thanks
