### ISSUE TITLE
Reactive content with v6

### ISSUE THREAD

**Issue by Glideh** [atomiks/tippyjs#716]
Imagine this situation:

```html
<button ref="myButtonRef" :data-title="buttonTitle">Hover Me</button>
```

```javascript
Tippy(myButtonRef, {
  content: (ref) => ref.dataset.title
})
```

Seems like `content` is only evaluated once.  
Since the `data-title` attribute will be updated later, the tooltip appears empty even after the update.

Is there a way to get the `content` on demand (when the user hover's the button) ?

**Comment by atomiks** [comment]
> Is there a way to get the content on demand (when the user hover's the button) ?

You can use the `onShow()` lifecycle + `.setContent()` method

```js
onShow(instance) {
  instance.setContent(instance.reference.dataset.title);
}
```

**Comment by Glideh** [comment]
That perfect, thanks.
I didn't think about using the events.
