### ISSUE TITLE
arrow position incorrect if tippy is inside text-align: center container

### ISSUE THREAD

**Issue by woothu** [atomiks/tippyjs#722]
## Bug description

::before element mispositioned in 'light-border' theme, when interactive: true and tooltip placed inside 'text-align: center' element. 

The problem doesn't appear on ~right or ~left placements.

## Reproduction

http://jsfiddle.net/be0o5jw8/7/

## Fix 
left: 0px seems to fix ::before element

**Comment by atomiks** [comment]
https://github.com/atomiks/tippyjs/commit/4392d35a1c3df58a79cab58163bd0ea2755a9504
