### ISSUE TITLE
Cannot destroy Tippy instance in onHidden since 6.0.0

### ISSUE THREAD

**Issue by lllopo** [atomiks/tippyjs#724]
I want to call destroy() on the tippy instance when it is completely hidden (so in the "onHidden"). 
This was working pretty fine before 6.0.0, but now it creates a circular reference, since destroy() calls unmount() (which is already called when the instance was hiding) which triggers "onHidden" again, which calls my destroy() again etc. 
I guess a simple check if the instance is already unmounted and not unmounting it again in the destroy method would solve it, but I don't know the code well, so I'm not sure if I got the situation right.

**Comment by victorsilent** [comment]
Why was closed? That's a real issue

**Comment by lllopo** [comment]
@atomiks Oookay, thanks for the fix in 6.0.1, but there is an additional issue (that's why I'm not creating a new one). Here it is : if you make the instance destroyed on onHidden, BUT you call this through `hideAll({diration: something})`, what you'll get is :
`setProps() was called on a destroyed instance. This is a no-op but indicates a potential memory leak.`
This is because, hideAll sets the duration to the one you passed, then hides the instance, then tries to restore the original duration property on that instance, which ... well ... was destroyed when hidden. 
So, here you should add an additional check to not restore properties on a destroyed instance, I believe (I don't know ... maybe also on an unmounted one, you know better).

**Comment by atomiks** [comment]
😵 yeah makes sense, the warning shouldn't be a problem though since it should get GC'd immediately after `hideAll()` finishes

**Comment by lllopo** [comment]
@atomiks No, not really a problem. More like quite annoying with filling up the console and also gives the feeling that the code does something wrong, while it isn't.

**Comment by atomiks** [comment]
Oh I agree it should be fixed, I just try to keep releases to a minimum for non-critical bugs like this. If it's too annoying you can temporarily use `patch-package` to remove the warning before I fix it in a future release 🙂

**Comment by lllopo** [comment]
Ah, no worries. Just put it the next release, whenever it comes. It is not critical indeed.

**Comment by Haraldson** [comment]
I guess this didn’t make it into any next releases?

I’m ‘stuck’ on Tippy because of Tiptap (as in, I don’t want to bloat my project with both Tippy _and_ Floating UI), and a service update would be much appreciated. Totally understand if that ain’t gonna happen, though.
