### ISSUE TITLE
Can a tooltip takes the width of its trigger element?

### ISSUE THREAD

**Issue by Arkellys** [atomiks/tippyjs#731]
Is there an easy/built-in way to make a tooltip takes the width of its trigger element?

I tried out the CSS way but I couldn't come up with something clean since the trigger element is not the true parent of the tooltip, even with the `appendTo: 'parent'` property.

**Comment by atomiks** [comment]
Yes, you can use a custom Popper modifier: https://codepen.io/FezVrasta/pen/gOpaoeL

**Comment by Arkellys** [comment]
Thank you for the quick reply @atomiks!

I am not sure to understand how I should include this modifier? Is it like a custom plugin? I'm using tippy.js-react so I don't think I can use the code as on the example. Maybe I should have ask the question on the other repository. ^^'

**Comment by atomiks** [comment]
Install `@tippyjs/react` instead (no dot) and uninstall `@tippy.js/react`. It's using the latest Tippy & Popper, so you'll be able to use that modifier inside `popperOptions`:

```js
popperOptions: {
  modifiers: [
    // same as the CodePen
  ]
}
```

**Comment by Arkellys** [comment]
Thank you, it works!

**Comment by FlorianWendelborn** [comment]
For others that try to go down this path, in order to have the tippy properly centered in a `SingleSelect` component, in this particular PR (https://github.com/3YOURMIND/kotti/pull/450), @carsoli and I ended up using this modifier instead:

```typescript
import { Props } from 'tippy.js'

type PopperModifier = Exclude<
	Props['popperOptions']['modifiers'],
	undefined
>[number]

/**
 * @see {@link https://github.com/atomiks/tippyjs/issues/731#issuecomment-596460597}
 */
export const sameWidth: PopperModifier = {
	enabled: true,
	fn: ({ instance, state }) => {
		const triggerReferenceWidth = `${state.rects.reference.width}px`

		if (state.styles.popper.width !== triggerReferenceWidth) {
			state.styles.popper.width = triggerReferenceWidth
			// force update the popper instance, so it can reposition the dropdown properly
			instance.update()
		}
	},
	name: 'sameWidth',
	phase: 'beforeWrite',
	requires: ['computeStyles'],
}
```

Hope that helps someone in the future. This issue was a good starting point for our investigation
