### ISSUE TITLE
Tippy v6 full of issues

### ISSUE THREAD

**Issue by stratboy** [atomiks/tippyjs#732]
Hi, I wrote for various issues last days, and you were quite fast and to the point answering my questions. Thank you. Anyway, I got several other issues with v6, too much to report all. I only want to point out that, essentially, it has too many, and I had to revert back to v5.2.1. I can only suggest a couple of things:

- should thoroughly test v6 again
- (or) maybe should add far more explanations and examples on v5 > v6 migration
- (or) maybe both point 1 and 2

What I'm sure is that v6 is not reliable at all.

Regards

**Comment by atomiks** [comment]
I don't understand why you'd even make this issue? If you have nothing to concrete to report it's not helpful at all. It has many automated tests already, and if you're not reporting the individual issues you're having (like the last one where you made no bug reproduction) there's nothing I can do.
