### ISSUE TITLE
Nested example for v.6

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#734]
Hi.
I found example with old version
https://codepen.io/armanio/pen/morPPy?editors=1010

I try to refactor with my case with v6, but I have issue: each time when I click the top-level trigger, it not close dropdown, but create a new one.
DEMO: https://codepen.io/7iomka/pen/NWqYrRg?editors=1010

Any ideas how to fix that?
Thanks for any ideas. I used that approach in production, and I need urgently hotfix.

**Comment by atomiks** [comment]
It was [`multiple`](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-multiple-or-relying-on-its-behavior), it's now gone so it will always create a new tippy when you use `tippy()` constructor. You'll need to refactor the logic to handle that change

**Comment by 7iomka** [comment]
> It was [`multiple`](https://github.com/atomiks/tippyjs/blob/master/MIGRATION_GUIDE.md#if-you-were-using-multiple-or-relying-on-its-behavior), it's now gone so it will always create a new tippy when you use `tippy()` constructor. You'll need to refactor the logic to handle that change

Ok.
But what workaround for this?

**Comment by hadrien-toma** [comment]
@7iomka did you reach to a workable example? :persevere:
