### ISSUE TITLE
Built in support for nested instance in v6

### ISSUE THREAD

**Issue by ArielGueta** [atomiks/tippyjs#735]
## Problem

When there is a nested instance, for example, a popover that contains popover, when you click on the inner element, it closes the first one. 

## Solution
Support for nested (stack) instances.

**Comment by atomiks** [comment]
This is supported by default provided the nested tippies are a child of the parent tippies (not for example appended to `document.body`), which is the default with `interactive: true`.

**Comment by ArielGueta** [comment]
Thanks for the quick response. Can you provide a code example, please? I see the example code in React. How I set an instance as a child of a parent? Thanks.

**Comment by ArielGueta** [comment]
Do I need to set the `appendTo` to parent element?

**Comment by atomiks** [comment]
`interactive: true` appends it to the parent of the reference by default. So with a nested tippy, the reference element is inside another tippy. It should just work without any effort.

**Comment by atomiks** [comment]
```js
const reference = document.createElement('button');
reference.textContent = 'reference';

const nestedReference = document.createElement('button');
nestedReference.textContent = 'nested reference';

const content = document.createElement('div');
content.append(innerReference);

tippy(nestedReference, {
  content: 'I am nested',
});

tippy(reference, {
  content,
  interactive: true
});
```

**Comment by ArielGueta** [comment]
So in these cases, we'll have the common issues of overflow hidden, right?

**Comment by atomiks** [comment]
Yes, but `overflow` is likely not going to be used on tippies in most cases. And if it is, you can use `strategy: 'fixed'` in `popperOptions` to work around it.

**Comment by ArielGueta** [comment]
Thanks a lot for your quick responses. Appreciated.
