### ISSUE TITLE
onDestroy hook is not invoked when singleton instance is destroyed

### ISSUE THREAD

**Issue by sqal** [atomiks/tippyjs#737]
## Bug description

Destroying singleton instance don't trigger `onDestroy` prop added to child instances.

## Steps to reproduce

- Go to - https://jsfiddle.net/mojtvy7L/
- Click on destroy button
- Console log should log "onDestroy tippy" three times

**Comment by atomiks** [comment]
This is expected behavior, the instances are separate from the singleton and can be re-used in a different singleton after the old one got destroyed

**Comment by sqal** [comment]
@atomiks ok, thanks for the explanation. I wasn't sure if it was a bug or should I destroy child instances manually. Maybe there should be some mention of this in the documentation?

**Comment by guanzo** [comment]
Hmmmm... this is just bit me. I expected `singleton.destroy()` to also destroy its instances. I think this should be documented somewhere.
