### ISSUE TITLE
tippy should be able to handle dynamic title attributes

### ISSUE THREAD

**Issue by sherzinger** [atomiks/tippyjs#74]
It would be very nice to have tippy js reflect title changes automatically.

The current manual behaviour potentially leads to a lot of extra code in many cases, because one must track tippy instances and programatically inform these about changes in the DOM.

Could we please have an option "dynamicTitle=true" which simply fetches the elements title attribute every time onShow is triggered? (just an implementation idea)

**Comment by atomiks** [comment]
Sure, I can add that

**Comment by sherzinger** [comment]
Awesome, thank you!

**Comment by atomiks** [comment]
@sherzinger Apologies for taking a while, I've added the option into the current master branch, can you verify that's what you want? Each time `show()` is called it just grabs the element's title attribute, updates the tooltip's content, then removes the title attr from the element

**Comment by sherzinger** [comment]
@atomiks thank you so much for your efforts!
I tested it and can confirm that it works well for me. The current title attribute is overwrites data-original-title and the popper as soon as the tooltip becomes visible, which has the desired effect.

A general remark, not necessary related to this topic: I tested this with Vue and it works well. It just sets the removed title attribute again when the title model changes. You might want to test tippy with other frameworks, though. I don't know how they behave when you remove bound attributes without their knowledge.

**Comment by atomiks** [comment]
`1.2.0`

**Comment by orioljd** [comment]
Hi, I try it and works fine with title attribute, but when I try it with data-html option don't work. it's posible to apply this on it also?

**Comment by atomiks** [comment]
@orioljd can you give an example use case of using it with `data-html`? Just like to conceptualize how things work before implementing them. thanks

**Comment by orioljd** [comment]
Yes of course, the code:

**HTML**
````html
<div style="display:none" id="moreinfo">
    That's the <i>example</i> of more info
</div>
<a href="/moreinfo-link" data-html="moreinfo" id="moreinfo-tippy">more info</a>
````
**JAVASCRIPT**
````javascript
tippy("#moreinfo-tippy",{dynamicTitle: true});
````

**Comment by atomiks** [comment]
Well you can use an HTML element directly.

```html
<div id="template">text</div>
<a href="/moreinfo-link" id="moreinfo-tippy">more info</a>
```

```javascript
tippy('#moreinfo-tippy', { 
  html: document.querySelector('#template') 
})
```

Whenever you modify the template, it will be "live" (since the element is appended to the tooltip itself).

**Comment by orioljd** [comment]
Ok I tried this, but when I use html option on tippy intance the behavior is different because the template disapear from DOM, and then I can't change it.

**Comment by atomiks** [comment]
It disappears from the visible page because it's appended to the tooltip

As long as you save it to a variable reference somewhere you can continue to modify it.

```javascript
const template = document.querySelector('#template') 
tippy('el', { html: template })
```

**Comment by orioljd** [comment]
OK perfect. Thank you
