### ISSUE TITLE
Where i can find CDN list for animation like: "tippy.js/animations/shift-away.css"

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [atomiks/tippyjs#740]
I want to use `shift-away` or `scale` animation:
https://atomiks.github.io/tippyjs/v5/animations/

This path works fine (I use the base path from the docs):
`https://unpkg.com/tippy.js@6.1.0/animations/scale.css`

But this idea missing from the docs :(

Any `jsdelivr` -or- on: https://cdnjs.com/libraries/tippy.js (Or someway to load all animations). 

```
tippy('button', {
  animation: 'scale'
});
```

**Comment by atomiks** [comment]
https://atomiks.github.io/tippyjs/v6/getting-started/#optional-extra-imports
