### ISSUE TITLE
Better documentation for HTML Content / Event Listeners? 

### ISSUE THREAD

**Issue by keeev** [atomiks/tippyjs#741]
Hey, I'm referring to this [issue](https://github.com/atomiks/tippyjs/issues/677) which imo mentions a piece of important information.

> 1. You need to select the btn element before tippy moves it out of the document, otherwise, you can't add the event listener since it won't be found when you query select it.

Depending on how important it is for other people. Would it be helpful for you if I'd (try 😀) to add this to the documentation? I know, at the moment it's like

> You can pass the element itself, which is useful for keeping event listeners attached (or when a framework is controlling elements inside): ...

I'm currently using the latest tippy for several use-cases in my app. It took me a while to figure out how it really works until I found out your comment here. Just asking if it would make sense to add it to the documentation and then create a PR or if it just would be for me in the end. 

Apart from that, thanks for maintaining tippy + popper. Great work on both. 🙌🏼

**Comment by atomiks** [comment]
> Would it be helpful for you if I'd (try 😀) to add this to the documentation?

Yes please! Feel free to add/fix anything with the documentation 😆

**Comment by keeev** [comment]
> Yes please! Feel free to add/fix anything with the documentation 😆

Nice, I'll try my best to explain. 😄 
Glad if I can help since Tippy will be saving my ass throughout my app.

**Comment by atomiks** [comment]
Closing but feel free to make a PR, although personally I don't see where the confusion lies 🤔
