### ISSUE TITLE
Tippy is not not auto hidden on mouse out?

### ISSUE THREAD

**Issue by yellow1912** [atomiks/tippyjs#742]
## Bug description

I'm not sure if this is a bug. I need to use Tippy in headless mode some places on my website, (but not all places). I wonder if I can do that. At the moment I'm trying to use headless mode (https://atomiks.github.io/tippyjs/v6/headless-tippy/) with the normal tippy:

`<script src="https://unpkg.com/tippy.js@6"></script>`

## Reproduction

I copied the sample code and modified it a bit like this:

`options.render = function (instance) {
            // The recommended structure is to use the popper as an outer wrapper
            // element, with an inner `box` element
            const popper = document.createElement('div');
            const arrow = document.createElement('div');
            const box = document.createElement('div');

            popper.className = 'tooltip';
            popper.appendChild(arrow);
            popper.appendChild(box);

            arrow.className = 'tooltip-arrow';
            box.className = 'tooltip-inner';
            box.textContent = instance.props.content;

            function onUpdate(prevProps, nextProps) {
                // DOM diffing
                if (prevProps.content !== nextProps.content) {
                    box.textContent = nextProps.content;
                }
            }

            // Return an object with two properties:
            // - `popper` (the root popper element)
            // - `onUpdate` callback whenever .setProps() or .setContent() is called
            return {
                popper,
                onUpdate // optional
            };
        };
`
When I hover over the tooltip, it does appear. However, when I move the mouse out the tip stays there and does not disappear at all?

**Comment by atomiks** [comment]
You need to set `animation: false` for it to unmount (or implement animation logic). The Headless module does that by default, but not the default one.

**Comment by yellow1912** [comment]
Thank you. So lets say that I can implement my own animation logic, I should do it right inside the onHide callback then calling instance.unmount()?

Continue with the above code, now I add:
```
options.onHide = function (instance) {
                // perform your hide animation...
                // once it completes:
                // for now do nothing just to see
                instance.unmount();
            };

```

And I'm getting the error below:

![image](https://user-images.githubusercontent.com/374134/77220842-c85be500-6b76-11ea-9e58-0d37d534ce2f.png)

**Comment by atomiks** [comment]
It should be at least wrapped in `requestAnimationFrame` I think (simulate a real async animation that will unmount it at the end) 🤔

**Comment by yellow1912** [comment]
You are right, wrapping it inside the requestAnimationFrame  does fix the issue.

**Comment by atomiks** [comment]
I fixed the example on the docs, it should be clearer now.
