### ISSUE TITLE
Delegate on wrapped disabled elements

### ISSUE THREAD

**Issue by rrushton** [atomiks/tippyjs#747]
## Bug description

If I wrap a disabled button in a span tag and use the delegate method to trigger tippy the results are inconsistent. It seems to only trigger if a small part of the span is not over the button. Once this happens then it works as normal.

## Reproduction
Using the latest popperjs/core and tippy 
https://jsfiddle.net/uxj9ct4f/

In this example if you enter the disabled button from either side or the bottom it does not work but if you enter from the top then it works. Once that happens you can then enter from the sides or bottom and have it work correctly as well.

**Comment by atomiks** [comment]
It seems to be a browser bug or something with the `mouseover` event: https://jsfiddle.net/mdrgo2ev/

**Comment by KubaJastrz** [comment]
`mouseover` doesn't work, but `mouseenter` should. As per https://stackoverflow.com/a/53008186

**Comment by atomiks** [comment]
> It appears that if the disabled element takes up 100% of the div, even this won't work

Not a problem with tippy, you'll need to find a workaround that ensures the events can fire

**Comment by rrushton** [comment]
Thanks for looking into this. 

For anyone else that runs into this issue, my work around was to use these styles on my wrapper element. Seems just having that 1px is enough to help. Not ideal but it works.

`display: inline-block;
padding: 1px;
margin: -1px;`
