### ISSUE TITLE
using setProps method for `allowHTML` property does not update

### ISSUE THREAD

**Issue by JeuelyFish** [atomiks/tippyjs#748]
## Bug description

When setting an tippy instance with the property `allowHTML` and then trying to update that property to via the setProps on the instance; the property does not update

## Reproduction

https://jsfiddle.net/JFish/7mwqnpha/5/

**Comment by atomiks** [comment]
I think it's because we check if the previous content is equal to the current content and only set it in that case; thankfully, it's not a vulnerability because `content` doesn't get set again.

https://jsfiddle.net/L81eyn74/

But yeah it's a bug — we should handle this case

**Comment by JeuelyFish** [comment]
Ah, gotcha. Thanks for the quick response @atomiks !
That bit of insight provides me with enough info to have a temporary workaround of storing the old content via `instance.props.content` updating both `allowHTML` and `content`  and then resetting it again with the stored old content.

See temporary work around here
https://jsfiddle.net/JFish/je59bopw/4/
