### ISSUE TITLE
destroy() triggers onHide event

### ISSUE THREAD

**Issue by dakur** [atomiks/tippyjs#749]
## Bug description
`instance.destroy()` causes `onHide` event to trigger.

## Reproduction

CodePen link: https://codepen.io/dakur/pen/VwvZEKL

I'm not pretty sure whether it is a bug or feature, but I just spent half an hour of saying `what?` for I ended in an infinite fetch request loop. My use-case is:
1. I have composite form field with some listeners in a tippy tooltip  
  ![image](https://user-images.githubusercontent.com/9862581/78803760-ac05d800-79bf-11ea-87b1-64d830accf81.png)
1. when I select something and leave this field editing by clicking out of tooltip (`onHide`), it sends a request to server with updated value
1. server sends back updated source code which is replaces the old one in DOM
1. when DOM is changed, I need to reinitialize all listeners and tippy as well -> so I call `instance.destroy()` and initialize it all again

But on the `destroy()` call, `onHide` is triggered again -> new request -> new DOM update -> reinitialize -> `destroy()` -> `onHide` -> new request…

I can overcome it with `instance = null` of course, but not sure if it is clean enough.

**Comment by atomiks** [comment]
It only calls `onHide` if it's still visible while being destroyed. It hides before being destroyed in that case.

**Comment by dakur** [comment]
Which is exactly my case.

Now I see I can overcome it by sending the request `onHidden` instead of `onHide` as well. That's not as soon as possible, but it is a compromise.

My question was rather if the hiding being triggered during destroy is a bug or not. Because when tippy is destroyed, it hides (in terms of visual perception, not events in tippy) anyway, doesn't it?

**Comment by atomiks** [comment]
Destroying the tippy removes event listeners, clears pending timeouts, and unmounts (hides + removes from DOM if necessary) the tippy. Hiding is part of the destroy process so this is expected behavior. For example there may be cases where you have logic in `onHide` that needs to be called if the tippy is destroyed before the user actually hides it themselves

**Comment by dakur** [comment]
Ok. And do you think that exposing `isBeingDestroyed` into `instance` variable (which is passed to `onHide` callback) is a good idea? I could differentiate then between normal hiding and "destroy hiding".

**Comment by atomiks** [comment]
I don't think that variable exists anymore 🤔  but can't you add that variable yourself to wherever you call `.destroy()`?

**Comment by dakur** [comment]
Aha, I have v5, I did not notice it is gone now.

Yeah, that probably might work. Thanks for replies.

**Comment by sn3p** [comment]
I'm also trying to prevent `onHide` from being fired on destroy.
Solved it by creating a custom property on the `state` object which I can check to prevent execution:

```js
instance.state.isDestroying = true;

console.log(instance.state);
{
  isDestroyed: false,
  isDestroying: true, // <- custom property
  isEnabled: true,
  isMounted: true,
  isShown: true,
  isVisible: true
}
```

Easy to implement but I think this would be a nice to have :)
