### ISSUE TITLE
tippy.update() removes title attribute

### ISSUE THREAD

**Issue by sherzinger** [atomiks/tippyjs#75]
Not sure if this is a bug or intended behaviour.

```
            const tip = tippy('.fjs-lin-reg-line:not([data-tooltipped])', {
              performance: true,
              theme: 'light',
              arrow: true,
              followCursor: true,
              onShow: function () {
                const el = document.querySelector('.fjs-lin-reg-line[data-tooltipped]')
                const popper = tip.getPopperElement(el)
                tip.update(popper)
              }
            })
```

I expect that this code would update the tooltip on every `onShow` to reflect potential title attribute changes.

This is what happens with the element when I hover over it 3 times:

1.
```
<line data-v-0dcc38ca="" x1="44.260416666666664" x2="486.86458333333337" y1="294.49797638080236" y2="67.13580619551755" class="fjs-lin-reg-line" data-tooltipped="" aria-describedby="tippy-tooltip-1" data-original-title="
<div>
  <p>Slope: 0</p>
  <p>Intercept: 0</p>
</div>
" title="
<div>
  <p>Slope: 0.35897759917176014</p>
  <p>Intercept: 143.2120522213481</p>
</div>
"></line>
```

2.
```
<line data-v-0dcc38ca="" x1="44.260416666666664" x2="486.86458333333337" y1="294.49797638080236" y2="67.13580619551755" class="fjs-lin-reg-line" data-tooltipped="" aria-describedby="tippy-tooltip-1" data-original-title="
<div>
  <p>Slope: 0.35897759917176014</p>
  <p>Intercept: 143.2120522213481</p>
</div>
"></line>
```

3.
```
<line data-v-0dcc38ca="" x1="44.260416666666664" x2="486.86458333333337" y1="294.49797638080236" y2="67.13580619551755" class="fjs-lin-reg-line" data-tooltipped="" aria-describedby="tippy-tooltip-1" data-original-title="html"></line>
```

**Comment by atomiks** [comment]
Yes it removes the title otherwise there'd be the browser's default tooltip + tippy tooltip on the element otherwise. 

Also, are you using complex HTML inside the title attribute? You should use the `html` setting and use a template instead, so you can update the element itself without needing to call `update()` (if it's not cloned).

**Comment by sherzinger** [comment]
I'm afraid I don't understand the first part of your reply.  When you call tippy('#id') the title attribute also remains, so why would it suddenly become an issue when calling .update() ?

And thank you for your advice, but I'm not entirely sure whether that would be the best approach for me. I've got a scatterplot with possibly many thousand circles. Right now each of that circle has it's data stored in a JS object [{cx: ..., cy: ..., tooltip: ...}, ...] so dynamically linking title to tooltip is very simple. In combination with https://github.com/atomiks/tippyjs/issues/74 I can call tippy once the circle is rendered and then forget about it entirely, which is great.

If I had to use html templates I would either have to...
1) ... create many thousand templates that have to be linked manually via the html option. This might also negatively impact the DOM performance.
2) ... create a single template that is shared and updated via event listeners on the circles

Both options sound rather unpleasant.
Any advice you might have is highly appreciated.

**Comment by atomiks** [comment]
>When you call tippy('#id') the title attribute also remains, so why would it suddenly become an issue when calling .update() ?

Not sure how you're experiencing that, the `title` attribute does get removed, it just gets stored in `data-original-title`.

**Comment by sherzinger** [comment]
Hmm, maybe this happens because title is bound to the data model in my case and set again by the framework after being removed by tippy.
