### ISSUE TITLE
Accessible Tooltips

### ISSUE THREAD

**Issue by sdzaveri** [atomiks/tippyjs#750]
## Problem

Tooltips are not accessible as they do not meet the following standard:
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

Specifically, it is not dismissible or hoverable

## Solution

* Support for the user to move their cursor to the tooltip and for it to persist.
* Support for the user to click `Escape` key and to have the tooltip dismiss.

**Comment by atomiks** [comment]
> Support for the user to move their cursor to the tooltip and for it to persist.

I don't see this implemented in many libraries (it's not the case in native tooltips for example) and it can cause problems in some cases. But you can enable it with the following:

```js
tippy(targets, {
  interactive: true,
  aria: {
    content: 'describedby',
  }
})
```

> Support for the user to click Escape key and to have the tooltip dismiss.

Native tooltips have this so I think it should be added by default. For now, it can be added as a plugin:

```js
const hideOnEsc = {
  fn({hide}) {
    function onKeyDown() {
      if (e.keyCode === 27) {
        hide();
      }
    }

    return {
      onCreate() {
        document.addEventListener('keydown', onKeyDown);
      },
      onDestroy() {
        document.removeEventListener('keydown', onKeyDown);
      }
    }
  }
};

tippy(targets, {
  plugins: [hideOnEsc]
});
```

Do you want to make a PR for this?

**Comment by atomiks** [comment]
I've added the `hideOnEsc` plugin to the docs which should fulfill the dismissibility point. And the first one is achievable without any plugin too.

To be honest, I'm not sure about adding it by default, especially if it can't be turned off 🤔 and I like to avoid adding new props especially if the user can add it themselves. It may only apply to tooltips, not some other poppers, and Tippy tries to stay fairly generic. I'll close for now but we'll see if any future users have issues.
