### ISSUE TITLE
Why is pointer-events: none set on all tippy elements?

### ISSUE THREAD

**Issue by osdiab** [atomiks/tippyjs#751]
I found it confusing that that was set by default without an obvious way to prevent that from being applied - I'm using this not just for tooltips but also for popovers with rich content inside them, and the examples also show buttons placed in popovers which don't work when `pointer-events` is set to `none`.

It's an easy fix to make the contents of the tippy box have `pointer-events: auto`, but I was wondering if there's something unsafe about doing that that may have motivated this default.

**Comment by atomiks** [comment]
`interactive: false` (default) sets `pointer-events: none`. If you set `interactive: true` it's not set. 

For certain behaviors this prevents issues, e.g. `followCursor`, hover flickering loops, and to prevent the cursor from changing when hovering it since it's not interactive.
