### ISSUE TITLE
Nested poppers with focus trigger and hideOnClick: false support

### ISSUE THREAD

**Issue by ArielGueta** [atomiks/tippyjs#754]
## Problem

When using nested poppers with `focus` trigger and `hideOnClick: false` (so that it'll not close it on following clicks on the input), the close functionality doesn't work anymore when we lose focus by clicking on the body of the nested popper.

## Solution

Should support nested poppers with the `focus` trigger and `hideOnClick: false`.

I have prepared  a live example of the issue:

https://stackblitz.com/edit/typescript-frecws

**Comment by atomiks** [comment]
I think you can use the new `onClickOutside` hook for this

**Comment by atomiks** [comment]
https://stackblitz.com/edit/typescript-frecws

**Comment by ArielGueta** [comment]
Thanks, it's kinda "hacky" way, but I can't see a different way to get around this.
