### ISSUE TITLE
Should I use ‘flipOnUpdate’ prop

### ISSUE THREAD

**Issue by lif3ng** [atomiks/tippyjs#755]
In https://github.com/atomiks/tippyjs/blob/master/website/src/pages/v6/ajax.mdx
```
tippy('#ajax-tippy', {
  content: 'Loading...',
  // This prop is recommended if your tooltip changes size while showing
  flipOnUpdate: true,
});
```

But console warning
```
`flipOnUpdate` is not a valid prop. You may have spelled it incorrectly, or if it's a plugin, forgot to pass it in an array as props.plugins. 
```

Should the document be updated?

**Comment by atomiks** [comment]
> Should the document be updated?

Yes this is a leftover from v5. If you want to make a PR I'll let you, if not I'll update it 🤗
