### ISSUE TITLE
How to keep Tippy from overflowing container in both directions?

### ISSUE THREAD

**Issue by NoMercy235** [atomiks/tippyjs#758]
Hello! I am trying to display a tooltip in a container using and the content inside the tooltip could make it overflow in both directions, but I don't want that behavior.

I am using this modifier:
```
       popperOptions={{
          modifiers: [{
            name: 'preventOverflow',
            options: {
              mainAxis: true, // even though I know it's true by default
              boundary: document.querySelector('.my-container')
            }
          }]
        }}
```
And the result is always something like this:
![image](https://user-images.githubusercontent.com/24717857/79236752-0bf3f700-7e76-11ea-8d72-89e481ed5496.png)
As you can see, the tooltip starts at the right place, but instead of ending just when the container ends, too, it always overflows it and goes to the window boundary.

Is there something I'm missing in the config? I can't seem to get my behavior to work but I'm sure it must be doable since it's not such an edge case. `appendTo` also doesn't help. It places the tippy element correctly in the DOM, but it overflows in the same way.

**Comment by atomiks** [comment]
Isn't this a `maxWidth` problem?

If you aren't importing the CSS add:

```css
[data-tippy-root] {
  max-width: calc(100vw - 10px);
}
```

**Comment by atomiks** [comment]
I believe in this case you'll actually need this modifier I made https://www.npmjs.com/package/popper-max-size-modifier

It lets you specify the `maxWidth` of the popper 100% dynamically so this won't happen. In your case you're constraining it to a boundary that's not the viewport so the hardcoded value above doesn't work.
