### ISSUE TITLE
Allow an optional outside wrapper element 

### ISSUE THREAD

**Issue by GresiRoost** [atomiks/tippyjs#760]
## Problem
I'm using Tippy to show an interactive popup menu on click. The page also has a mouse-hover plain CSS navigation menu just below.
The problem is that as you move the mouse down to the other popup, the gap between the tippy popup makes my popup menu appear.

![Tippy](https://user-images.githubusercontent.com/8970223/79374585-b5f78000-7f57-11ea-9947-f73685bcbc48.gif)

## Solution

Tippy needs an optional container around the entire thing (including the tippy-arrow) so that the mouse events doesn't end up below. Turns out I can't really see a way to do this - hence my feature request :) 

I know that I could adjust the z-index to that tippy is always on top over the pure CSS menu but it will still be visible underneath and I'm trying to prevent that. It being on top in the GIF is just for demonstration.

**Comment by atomiks** [comment]
This should be solvable without adding a new feature like that. 

Using the `onShow` lifecycle, add `style.pointerEvents = 'none'` to the CSS trigger element, then set `style.pointerEvents = ''` `onHide`.

**Comment by GresiRoost** [comment]
That wouldn't work in my case. I still want the menus to appear when you hover them on the side of the tippy popup. It is only in the slim area where the tippy-arrow is that I don't want pointer events to go through.

**Comment by atomiks** [comment]
So then you can add an invisible element just under the avatar that prevents pointer events from going through when you open the tippy
