### ISSUE TITLE
tabindex on reference element breaks 'click focus' trigger

### ISSUE THREAD

**Issue by GresiRoost** [atomiks/tippyjs#761]
## Bug description
If the reference-element has `tabindex="0"` on it to make it tab'able and you are using the `trigger: 'click focus'` combination then clicking on the element will briefly show the tooltip and then immediately hide it again. I believe it is caused by the focus- and click event canceling each other out

## Reproduction
Click the grey span element while it doesn't have focus:
CodePen link: https://codepen.io/RiggsDK/pen/wvKMjJm

**Comment by atomiks** [comment]
`hideOnClick: false` solves it, but I don't see why you need `click` + `focus` as focus acts like a click.

**Comment by Andos** [comment]
False. Try clicking the reference element multiple times. It will only get focus once - and will only ever open once. It needs both.

**Comment by GresiRoost** [comment]
False. Try clicking the reference element multiple times. It will only get focus once - and will only ever open once. It needs both.

**Comment by atomiks** [comment]
Fair enough, can you try and implement a PR to fix it?

**Comment by antenando** [comment]
> Fair enough, can you try and implement a PR to fix it?
> 
> btw, it would be so helpful to use state machines in this library but like... I can't import `xstate` and force the bundle cost onto the consumers lol. It would solve many of these types of state issues.

https://github.com/cassiozen/useStateMachine  [is only 1.5kb](https://bundlephobia.com/package/@cassiozen/usestatemachine@0.4.1)
