### ISSUE TITLE
Tippyjs and Vue

### ISSUE THREAD

**Issue by bangstarburst** [atomiks/tippyjs#762]
I use Tippyjs in a project using Vuejs but the events assigned on the element do not respond on the tooltip. I looked at the entire documentation but couldn't find a fix. My question is: Does Tippyjs capture the event assigned to the element by Vue? Thanks
Sorry for my bad english

**Comment by atomiks** [comment]
I'm not sure exactly what you mean by `capture the event`, but maybe take a look at the way `vue-tippy` is implemented. You likely use `mounted()` callback to invoke `tippy()` then clean it up in `destroyed()` or such.
