### ISSUE TITLE
Better support for multiline spans

### ISSUE THREAD

**Issue by philippkuehn** [atomiks/tippyjs#763]
When using tippy on an element that is split between two lines, the default behavior is something like that:

![fail1](https://user-images.githubusercontent.com/2500670/80205307-ac8ea780-862a-11ea-9b92-51f76df0fbb9.gif)

There was already [this issue](https://github.com/atomiks/tippyjs/issues/398) with a suggestion to use `followCursor`.

So when using `followCursor: 'initial'` with `placement: 'bottom'` the placement is weird (target is hidden) sometimes:

![fail2](https://user-images.githubusercontent.com/2500670/80205534-0f803e80-862b-11ea-90cd-c2859c5c36b2.gif)

So when using `followCursor: 'horizontal'` the offset is wrong:

![fail3](https://user-images.githubusercontent.com/2500670/80205566-20c94b00-862b-11ea-8a1f-f0c1572ec419.gif)

Is there anything I missed to improve the position of the tooltip?

**Comment by atomiks** [comment]
https://atomiks.github.io/tippyjs/v6/all-props/#inlinepositioning?

**Comment by philippkuehn** [comment]
Yeah, now it’s… different 😅

![fail4](https://user-images.githubusercontent.com/2500670/80207452-76532700-862e-11ea-8c2c-e04cc3728cee.gif)

**Comment by atomiks** [comment]
[Yeah...](https://github.com/atomiks/tippyjs/blob/master/src/plugins/inlinePositioning.ts#L5) I wanted to work on that for a while but for some reason it never worked fully reliably if the cursor entered the edges. If you can think of a solution please send a PR 😓

**Comment by atomiks** [comment]
For anyone interested in helping develop this feature, as I think it's pretty complex:

![demo of multiple rects](https://i.imgur.com/mTi93CX.png)

You need to be able to choose which rect to use based on two things:

1. Where the cursor entered from
2. The placement of the tippy

For example:

- The cursor entered from the bottom of the left part (the orange rect):
— `top` placement: virtual rect is the green rect above it
— `bottom` placement: virtual rect is the orange rect itself

- The cursor entered from the bottom of the very right part (the pink rect):
— `top` placement: virtual rect is the blue one above it
— `bottom` placement: virtual rect is the pink rect itself

- The cursor entered from the bottom of the purple rect to the right:
— `top` placement: virtual rect is the green rect, but only if the cursor is to the left of the blue rect
— `bottom` placement: virtual rect is the purple rect itself

**Comment by atomiks** [comment]
An alternative:

Detect if the two rects are "disjoined" and use a simpler version of the above, and if they're connected, use the current behavior? 🤔

**Comment by atomiks** [comment]
Install `v6.2.1` and it should work well now

**Comment by philippkuehn** [comment]
Hey, great! It’s much better! However there is a bug when the cursor comes from the left side. But it’s not always. The first example works as expected. The second doesn’t. 👀

![Apr-27-2020 09-10-50](https://user-images.githubusercontent.com/2500670/80344004-23b07f80-8867-11ea-94cf-79d1ea963ea4.gif)

**Comment by atomiks** [comment]
Noo 😢 that's the issue I mentioned haha, but I didn't encounter it this time.  [I used 1px buffer too](https://github.com/atomiks/tippyjs/blob/32ee406ac669913ba65d1e11bbdc7282f91ec4e9/src/plugins/inlinePositioning.ts#L62-L66), do you have any ideas?

**Comment by atomiks** [comment]
![demo](https://i.imgur.com/xbiED1Q.gif)

I can't reproduce it myself for example, but I know I encountered this last year when trying to add the feature 👀 Maybe a 2px buffer 😅? Can you try editing `node_modules/tippy.js/dist/tippy.esm.js` with `2` instead of the `1` in the link above?

**Comment by philippkuehn** [comment]
Haha, yeah 2px works for me! 😅

**Comment by atomiks** [comment]
I also use `2px` default for `interactiveBorder`, and haven't had any issues with that since 2017, so hopefully it's a "safe" value. I have no idea why `.clientX/Y` from the `MouseEvent` wouldn't be within the 1px-buffered bounds of `.getClientRects()` (accounting for rounding errors), but anyway...

**Comment by atomiks** [comment]
I published `6.2.2` @philippkuehn, let's hope `2` is enough or we might need a different solution D:

**Comment by philippkuehn** [comment]
Thank you for all your work! Works now as expected! ✌️
