### ISSUE TITLE
SVG Arrow position is incorrect when `.tippy-box` has `text-align: center;`

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs#764]
## Bug description

If you use SVG arrows and have a custom theme and you set `.tippy-box` to have `text-align: center;`, the arrow is incorrectly positioned.

## Reproduction

1. Go to https://atomiks.github.io/tippyjs/
2. Add `.tippy-box {text-align: center;}` to the inspector's stylesheet
3. Scroll down to the Arrows section and open some tooltips with SVG arrows

![image](https://user-images.githubusercontent.com/6430313/80206828-b669d800-8635-11ea-8084-5b04295d8b73.png)

---

If we look at the `.tippy-svg.arrow` element, this is what happens:

![image](https://user-images.githubusercontent.com/6430313/80206870-ced9f280-8635-11ea-9be0-68432a182ae3.png)

The svg has `position: absolute;` without a `left` property, so it's positioned as if it was text.
There are two easy fixes for this issue.

1. Make the SVG arrow initially positioned as it should
```css
.tippy-svg-arrow {
    display: flex;
}
```
2. Force the SVG arrow to stick to the left as default
```css
.tippy-svg-arrow > svg {
    left: 0;
}
```

**Comment by atomiks** [comment]
You could also add that property to `.tippy-content` instead to avoid that issue

**Comment by itayganor** [comment]
> You could also add that property to `.tippy-content` instead to avoid that issue

Absolutely. This is something a user might realize after having the bug. I think it's better to prevent it altogether to make sure users won't get confused.

**Comment by dovstone** [comment]
I tried the solutions above but didn't fix the issue. So I had to do the following
```
.tippy-box[data-placement^="top"] .tippy-arrow:before { 
    margin-left: -7px;
}
```
