### ISSUE TITLE
Incorrect positioning on desktop and doesn't work on mobile

### ISSUE THREAD

**Issue by trosel** [atomiks/tippyjs#766]
Hello, I'm looking for help in understanding what could be going wrong here. The tooltip transform is ~200 pixels too high on desktop web and it doesn't want to work at all in iOS browsers.

Look for the word "jurnale" with blue underline to see for yourself. https://occidental-lang.com/salute-jonathan/?c=1

You can see an image in this issue too https://github.com/occidental-lang/salute-jonathan/issues/1

---

I am pulling in the content after initial page load. Do I need to call something like `tippy().destroy()` on every new re-render of page content? 

This is where the tippy code is right now. It's inside of the `fetch` so that it gets initialized after I load the content with the data attributes in. https://github.com/occidental-lang/salute-jonathan/blob/master/index.html#L160

**Comment by atomiks** [comment]
https://popper.js.org/docs/v2/faq/#why-is-my-popper-in-the-wrong-location-or-not-visible-at-all

**Comment by trosel** [comment]
You are a lifesaver! So sorry I missed that. @atomiks

**Comment by decadence** [comment]
@atomiks Thanks!
