### ISSUE TITLE
Using tippy in react application without creating an instance

### ISSUE THREAD

**Issue by cksachdev** [atomiks/tippyjs#768]
I am trying to include tippy.js in a react application. There are several placed where I have aria-title, and title properties which need to be shown on mouse over as a tooltip. I have included tippyjs component in react app and updated *title* property to *data-tippy-content*, but I couldn't see the tippy component. Is it possible to include it in the way I am trying to do it? Please refer to the codesandbox link below:
https://codesandbox.io/s/react-tippyjs-example-r9oxz

**Comment by atomiks** [comment]
I don't really understand the CodeSandbox link. You've imported the component but haven't actually used it anywhere in your JSX tree?

**Comment by cksachdev** [comment]
@atomiks Here I have created another example using static html. 
https://codesandbox.io/s/tippyjs-plain-example-in3m0?file=/index.html

In this I am able to get tooltips by just invoking tippy(".tippy"). I am trying to achieve something similar in React, such that I can have tooltips in large code base and don't have to create a wrapper around my existing components.

**Comment by cksachdev** [comment]
@atomiks Exploring this further, when I trigger 
```
tippy(".tippy")
```
in the Chrome console, I am able to see the tooltips. I don't think I want to keep on calling tippy method on componentMount or componentDidUpdate. Any better way to get it to work across all the pages?

**Comment by atomiks** [comment]
The problem with that is how do you clean up or update the instances? The `<Tippy />` component handles everything for you for usage with React. I'm not sure why you'd want to use something else. Your app components should be structured in a way that wraps the Tippy component into an abstraction or something

**Comment by cksachdev** [comment]
@atomiks Thanks for the suggestion. So, should I be wrapping my ReactDOM.render method inside Tippy to get access to tippy across entire application? Could you please help with an example.

**Comment by atomiks** [comment]
[The docs show how to use the component](https://github.com/atomiks/tippyjs-react#-usage)
