### ISSUE TITLE
Wrong tooltip positions when X axis has overflow

### ISSUE THREAD

**Issue by itayganor** [atomiks/tippyjs#769]
## Bug description

When on mobile, there are some problems with positioning. It looks like tooltips can only be placed within a limited area in the page, if it has overflow at its X axis.

## Reproduction

1. open https://atomiks.github.io/tippyjs/ with DevTools mobile (as Galaxy S5 or something not too large).
2. add `width: 1000px` to `body` (or to any other parent container of the page content).
3. Scroll down until you reach any wide section, I think [**Placement**](https://atomiks.github.io/tippyjs/#placement) is a good one to test this on.
4. Click some buttons and see that the positioning is relative to the screen width "stuck" into the left.  ![wrongtippys](https://user-images.githubusercontent.com/6430313/80504940-5d26df00-897c-11ea-8ed0-a4d8ac6b272b.gif)
5. Double-click the page to zoom-out (as if you're really on mobile).
6. Click those buttons again, we can infer that tippys can't be placed outside the *initial zoom* boundary.

![image](https://user-images.githubusercontent.com/6430313/80504931-5ac48500-897c-11ea-8bff-2437efb7fce2.png)

**Comment by atomiks** [comment]
I guess this would be a Popper bug

**Comment by atomiks** [comment]
Actually I think it's a DevTools bug with the way they measure the viewport tbh. But can you make an issue on the Popper repo instead?

**Comment by itayganor** [comment]
> Actually I think it's a DevTools bug with the way they measure the viewport tbh. But can you make an issue on the Popper repo instead?

The DevTools reproduction is actually a demonstration of what I have experienced of tooltips in my website from mobile. I didn't expect DevTools to reproduce it, but it did :)

**Comment by atomiks** [comment]
If you can try one thing, can you edit `node_modules/@popperjs/core/lib/dom-utils/getViewportRect.js` and [remove the `visualViewport`](https://github.com/popperjs/popper-core/blob/aeb454d844b1b089022a0dfc0ab2ffb9bbd4102e/src/dom-utils/getViewportRect.js#L14) branch and see if that fixes it?

**Comment by itayganor** [comment]
> If you can try one thing, can you edit `node_modules/@popperjs/core/lib/dom-utils/getViewportRect.js` and [remove the `visualViewport`](https://github.com/popperjs/popper-core/blob/aeb454d844b1b089022a0dfc0ab2ffb9bbd4102e/src/dom-utils/getViewportRect.js#L14) branch and see if that fixes it?

Will do it now.
Meanwhile, I tried to reproduce it with Popper.js but it seems to work as expected:
https://codepen.io/iTayGNR/pen/jObwoqP

**Comment by atomiks** [comment]
Maybe because it's in an `<iframe>` (it has different semantics). Can you try in a plain `.html` document?

**Comment by atomiks** [comment]
This repros it for me.

```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        display: flex;
      }

      .push {
        width: 2000px;
        height: 200px;
        background: gray;
        flex-shrink: 0;
      }

      #popcorn {
        width: 200px;
        height: 200px;
        background: green;
        display: inline-block;
        flex-shrink: 0;
      }

      #tooltip {
        background-color: #333;
        color: white;
        padding: 5px 10px;
        border-radius: 4px;
        font-size: 13px;
      }
    </style>
  </head>

  <body>
    <div class="push"></div>
    <div id="popcorn"></div>
    <div id="tooltip">
      tooltip
    </div>

    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script>
      const popcorn = document.querySelector('#popcorn');
      const tooltip = document.querySelector('#tooltip');
      Popper.createPopper(popcorn, tooltip, {
        placement: 'top',
        modifiers: [
          {
            name: 'preventOverflow',
            options: {
              tether: false,
            },
          },
        ],
      });
    </script>
  </body>
</html>
```

**Comment by itayganor** [comment]
Damn, I was just creating https://pastebin.com/rXQjhT5N to send it to you. Exactly the same 😂
Anyway, I tried to drop the if statement regarding `visualViewport` and it doesn't seem to solve the issue.

**Comment by FezVrasta** [comment]
Everything seems to work here, what am I doing wrong?

![image](https://user-images.githubusercontent.com/5382443/80575231-850d5580-8a03-11ea-8a5e-54668b0428d3.png)

**Comment by FezVrasta** [comment]
Repro URL:

https://gistcdn.githack.com/FezVrasta/11b807834b33667c5d6d5422f0f6258c/raw/34fdc52bf041388bb3f57e4c94690ddfcf684a14/bug.html

**Comment by atomiks** [comment]
Open mobile DevTools @FezVrasta

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/80575944-a0c52b80-8a04-11ea-9514-98ae5b8ca24a.png)

Still working 🤷‍♂️

**Comment by itayganor** [comment]
@FezVrasta Have you managed to make it work?

**Comment by atomiks** [comment]
@itayganor you can track the fix here, it's kind of more complicatyed than we thought. It works in Popper 1 but we have no idea how that thing works 😂

https://github.com/popperjs/popper-core/pull/1098
