### ISSUE TITLE
Show error using interactive + delay

### ISSUE THREAD

**Issue by ocarreterom** [atomiks/tippyjs#770]
## Bug description
When using the properties `interactive: true` and `delay: x` the tooltip is shown after the delay, even if the cursor is not hover.

## Reproduction

Test: https://codepen.io/atomiks/pen/yvwQyZ

![screencast](https://user-images.githubusercontent.com/11599942/80511940-15548780-897d-11ea-8959-165597db796d.gif)

**Comment by atomiks** [comment]
That's not good 😳 looks like a regression in `6.2.0` after I refactored the logic into a new method and added an unncessary `if` branch.

Fixed and released 😇
