### ISSUE TITLE
Singleton problem

### ISSUE THREAD

**Issue by usb248** [atomiks/tippyjs#773]
I use singleton:
```
tippy.createSingleton(tippyInstances, {
                    animateFill: true,
                    ignoreAttributes: true,
                    hideOnClick: false,
                    offset: [0, 7],
                    moveTransition: 'transform 0.2s ease-out',
                    overrides: ['placement', 'content']
 })
```
later...
I need to override placement/content individually with:
`el._tippy.setProps({placement: 'left'})` and `el._tippy.setContent('new content here')`.
If i call these methods when the tooltip (which i want to update) is displayed, i need to hide&show the tooltip to see changes (if i don't use singleton, any problem, the content/position change directly). Why ?

(UMD + last version (V6) on FF)
Thanks

**Comment by atomiks** [comment]
I think it might be a bug; we may need to observe updates on the passed instances

**Comment by usb248** [comment]
Hi,
Thanks :). When it will be fixed you think ?

**Comment by atomiks** [comment]
I'm not sure but you should be able to workaround it by setting those props on the singleton instance as well if it's currently visible.

```js
const singleton = tippy.createSingleton(...);

singleton.setProps({placement: 'left'});
el._tippy.setProps({placement: 'left'});
```

**Comment by usb248** [comment]
I want to update not all tippy instances :/

**Comment by usb248** [comment]
Any updates ?

**Comment by atomiks** [comment]
I'm sorry I haven't had time to look at it.

You can find the [source here](https://github.com/atomiks/tippyjs/blob/bf975605aa694e1cb1ad82e964b926830243ac80/src/addons/createSingleton.ts), perhaps you can find a solution and submit a PR.

**Comment by usb248** [comment]
sorry i'm not comfortable with typescript 😬

**Comment by usb248** [comment]
@atomiks , after debug, i found that instance.popperInstance is null only in singleton mode. Therefore, the script doesn't run this : https://github.com/atomiks/tippyjs/blob/bf975605aa694e1cb1ad82e964b926830243ac80/src/createTippy.ts#L884
and cause the bug. Have you an idea ?
