### ISSUE TITLE
Delegate Instances not updating

### ISSUE THREAD

**Issue by dpDesignz** [atomiks/tippyjs#774]
## Bug description

When using the event delegation in `v6.2.3`, it doesn't attach itself until I hover over the tippy instance element. This is an issue if I want to update the content of the tippy, even if the user hasn't viewed it to start with.

## Reproduction

CodePen link: https://codepen.io/dpDesignz/pen/yLYzJqp

Open up the console log and try to change the tippy content. You will see an error saying it's not attached. Now hover over one of the eyes and then press the button for that eye and it will work.

This was working in the last version when I originally requested info on this in issue #767 which I believe I had running `v6.2.2` at that time

**Comment by atomiks** [comment]
That's how event delegation works; the instances don't exist until they are triggered. 

If you need to update it before the instance is created, you need to change the `data-tippy-content` attribute instead. It's not possible that it worked in `v6.2.2` either, and it doesn't if you change to the version in the CodePen, since the code I changed between the versions isn't related

**Comment by dpDesignz** [comment]
> 
> 
> That's how event delegation works; the instances don't exist until they are triggered.
> 
> If you need to update it before the instance is created, you need to change the `data-tippy-content` attribute instead. It's not possible that it worked in `v6.2.2` either, and it doesn't if you change to the version in the CodePen, since the code I changed between the versions isn't related

Ah, apologies, I'm re-learning Javascript after 10 years as it seems I'm way behind the ball! That makes total sense. Thanks for explaining how that works. It turns out it worked before because there was leftover code updating elsewhere.

If anyone else doesn't understand this, my code to make this work is now as follows

```javascript
if (viewBtnIcon._tippy) {
  viewBtnIcon._tippy.setContent(`View ${data.name}`);
} else {
  viewBtnIcon.dataset.tippyContent = `View ${data.name}`;
}
```
