### ISSUE TITLE
broken or my mistake?

### ISSUE THREAD

**Issue by alewolf** [atomiks/tippyjs#777]
In Laravel 7 I installed tippy with `npm i tippy.js `
Then I added `import tippy from 'tippy.js';` to my `app.js` and ran `npm run watch`. It compiled fine and I do see references to tippy in the compiled `app.js` output. 

But when I type `console.log(tippy)` I get the following error `Uncaught ReferenceError: tippy is not defined`

I've tried several changes on how to import tippy, but I start to get the feeling the issue is somewhere else. But I have no clue on how to pinpoint the problem. Is it a bug in tippy, or the compiled app.js, or in the browser?

Do you have an idea how to find the problem?

**Comment by alewolf** [comment]
After having deleted all node modules, including removing the popper dependency in my `package.json` and reinstalling all node modules, it started to work. 

I guess there was a conflict with my previous popper.js install.

**Comment by humblecoder** [comment]
@alewolf what framework are you using?  You'll need to "import" it in the context of the current component or if you're using something like VueJS, you'll have to add it to the root instance either via plugin creation or via something like: 

```
import tippy from 'tippy.js'
Object.defineProperty(Vue.prototype, '$mycustomtippy', {value: tippy})
```
