### ISSUE TITLE
Possibility to use Tippy.js with submodules

### ISSUE THREAD

**Issue by ewilan-riviere** [atomiks/tippyjs#779]
## Problem

I have light project and I need to use tooltip but I need lightest library, Tippy.js is small but I would to use just basics modules to have very light js file. Do you think that would be possible?

## Solution

Optional division when import module ?

Thanks for this plugin !

**Comment by atomiks** [comment]
Hi, it already has a "core" and extensible with separate pieces (tree-shakable plugins if you use a module bundler). The core is about 4.5 kB excluding Popper. The CDN version has everything bundled together though which is larger, so you'd need to use a module bundler.
