### ISSUE TITLE
Remove references to .config in package.json

### ISSUE THREAD

**Issue by crystalfp** [atomiks/tippyjs#780]
## Bug description
I'm using eslint in VS Code and every time I receive the following error:
```
[Error - 6:24:32 AM] ESLint stack trace:
[Error - 6:24:32 AM] Error: Failed to load config "./.config/eslint.config" to extend from.
Referenced from: D:\Projects\IdeaIgniterEnvironment\node_modules\tippy.js\package.json
```
In the package the subdirectory `.config` does not exist.

I will open an issue also to the VS Code eslint plugin. It is not clear to me where the problem is.

## Reproduction
Have VS Code with eslint plugin.
Load a project that references tippy.js
See the error.

**Comment by atomiks** [comment]
I don't think any plugins/packages should read the config from any `node_modules`' `package.json`s, it would be a bug. The configs are specified in package.json to reduce the number of config files in the root directory, /cc @FezVrasta

**Comment by crystalfp** [comment]
Thanks James! I think so and opened an issue for eslint vs code extension. On the other side, tippy is the only package I use that refers another local file.See you! MarioInviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: James N <notifications@github.com> Data: 17/05/20  07:50  (GMT+01:00) A: atomiks/tippyjs <tippyjs@noreply.github.com> Cc: Mario Valle <mvalle@cscs.ch>, Author <author@noreply.github.com> Oggetto: Re: [atomiks/tippyjs] Remove references to .config in package.json (#780) 
I don't think any plugins/packages should read the config from any node_modules' package.jsons, it would be a bug. The configs are specified in package.json to reduce the number of config files in the root directory, /cc @FezVrasta

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/atomiks/tippyjs/issues/780#issuecomment-629747378",
"url": "https://github.com/atomiks/tippyjs/issues/780#issuecomment-629747378",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
