### ISSUE TITLE
`followCursor` prop: position is not updated after touch on hybrid devices

### ISSUE THREAD

**Issue by usb248** [atomiks/tippyjs#781]
## Bug description

Position not updated while it should.
I have a hybrid screen (mouse cursor + touch screen) : Asus Zenbook

## Reproduction

Not possible without screen.
My options:
```javascript
{
   content: '0 km',
   trigger: 'manual', // or mouseenter or anything else, the same bug is here
   touch: true,
   followCursor: true,
   triggerTarget: $('.mapboxgl-canvas').get(0),
   placement: 'right'
}
```
All works fine with cursor, but from the moment that i touch my screen, the tooltip becomes static forever even if i relocate my native cursor (even passing the mouse over `triggerTarget`) with my mouse (which works before touch...).

Have you a workaround to manually/programmatically update/set the position of tooltip when i trigger touch event on canvas element + prevent loosing updates position after touch event .. ?
I tried:
```javascript
instance.setProps({
         getBoundingClientRect: function() {
                                return {
                                    width: 0,
                                    height: 0,
                                    top: e.point.y,
                                    bottom: e.point.y,
                                    left: e.point.x,
                                    right: e.point.x,
                                }
        }
})

instance.popperInstance.update()
```
It does anything

Thanks :)

**Comment by usb248** [comment]
Same bug on demo page (https://atomiks.github.io/tippyjs/#follow-cursor) :
![screencast-atomiks github io-2020 05 19-14_34_50](https://user-images.githubusercontent.com/7659927/82327369-9633fb80-99de-11ea-9b23-a52afe05551f.gif)

At the begin, as you can see, it works, and i touch my screen (cursor disapear), we don't see on the gif, but i touch everywhere else on the same button, the tooltip is static... I have to do focusout and focusin (hide/show) to update the position...

**Comment by usb248** [comment]
Another little video to show you that tooltip's position isn't updated anymore after touch:
![bug](https://user-images.githubusercontent.com/7659927/82333039-7bfe1b80-99e6-11ea-9b38-ca8dda5aaf6a.gif)

**Comment by usb248** [comment]
Another lib which handle this correctly, if you want to see the code: http://qtip2.com/demos#section-positioning

**Comment by atomiks** [comment]
@usb248 does this commit fix the behavior? https://github.com/atomiks/tippyjs/commit/7b9354ea9edd30943475bbee1c5d2f88d8b19d76

**Comment by usb248** [comment]
Possible to get a tmp umd version ? I haven’t the setup to transpile source file on my current computer.

**Comment by atomiks** [comment]
[Well the change is actually only 1 line](https://github.com/atomiks/tippyjs/commit/7b9354ea9edd30943475bbee1c5d2f88d8b19d76#diff-0634cda447d7b519769668d8cd9a96c0L33) so you should be able to edit the source and test it (`node_modules`, or copy the UMD version to a file and use that instead)

**Comment by usb248** [comment]
Ok i will try it. I keep you posted

**Comment by usb248** [comment]
@atomiks the problem seems to be solved. For the moment all my tests are conclusive.
thanks !

**Comment by atomiks** [comment]
Okay great. I'll try to make a patch release soon.
