### ISSUE TITLE
trigger: 'manual' isn't respected

### ISSUE THREAD

**Issue by guanzo** [atomiks/tippyjs#785]
## Bug description

Oh boy this one is a doozy, but i managed to reproduce it. Unsure if its a tippy or popper bug, or a bug at all.

## Reproduction

https://codesandbox.io/s/fervent-mccarthy-zk2tn?file=/iframe.html

1. Click "test" button.
2. Position your mouse cursor over the "show modal" button so that after clicking, your cursor is inside the grey modal that appears after the click.
3. Keep your cursor inside the grey modal, and click "close". This sets trigger: 'manual', and the grey modal disappears.
4. Move your mouse, the tippy disappears even tho it's supposed to be manually triggered.

To "fix" the bug. On step 3, move your cursor outside the grey modal, then click "close" and move your mouse. The tippy stays open, respecting the manual trigger.

The code is pretty ugly, but i wanted to exactly, and quickly, reproduce my apps environment, and the exact elements involved.

The tippy is inside the iframe, and the grey modal is in the top level window. When the grey modal appears under the cursor, it somehow tricks tippy into thinking the cursor is still inside the tippy? In any case, the manual trigger should be respected here.

**Comment by atomiks** [comment]
I don't think interactivity works across different frames/document contexts

**Comment by guanzo** [comment]
Is that the root problem for `manual: 'trigger'` not being respected?

**Comment by atomiks** [comment]
I think it's because there's a `mouseleave` listener bound to the body, so when the cursor leaves we hide the element. IIRC that was only necessary for Safari, back in 2017, it could be unnecessary now... but also not sure if that's the actual issue (point 4.).

**Comment by atomiks** [comment]
Can you see if https://github.com/atomiks/tippyjs/commit/7fec59a9e545fe1b80838df1e7af35ce015d6208#diff-3a0bbb8141b000b9df8c4b17b0278f2fR284-R1068 fixes it? (commit name got grouped accidentally).

**Comment by guanzo** [comment]
Didn't fix it. https://codesandbox.io/s/shy-rgb-bwreg?file=/tippy.js

`tippy.js` was generated by cloning this repo and running `npm run build`.

Tried with 7fec59a and 7b9354e

**Comment by atomiks** [comment]
For me it's fixed in the CodeSandbox... 👁️

**Comment by guanzo** [comment]
For the following reasons, I wouldn't mind if this issue is closed (until somebody else runs into the same problem)

* I'm no longer using tippy for this part of my UI
* It's a super niche bug. 
* I can tell you're passionate about this project due to the number of commits and fixed issues, and having this hard-to-solve issue stay open probably bothers you.

Regardless, thanks for this excellent library.

**Comment by atomiks** [comment]
I guess 🤷‍♂️
