### ISSUE TITLE
Put the Demo from the FAQs on the Home Page

### ISSUE THREAD

**Issue by LondonWebFactory** [atomiks/tippyjs#786]
## Problem

Fantastic project but it took me ages to figure out how to implement it. The documentation is beautifully designed but not very clear. Then I found the "Nothing is working" FAQ. 

## Solution

Follow the example of Bootstrap. Move the "Nothing is working" FAQ to the home page. Add some simple cut and paste examples with CDN links so that people can paste it into a document and start playing straight away. 

Kind Regards,
Adrian

**Comment by atomiks** [comment]
Can you explain which parts are confusing in detail? Or create a PR with some changes that's easier to understand? (I can't make the changes if I have implicit bias of understanding)

**Comment by LondonWebFactory** [comment]
The solution is really simple. Just add a starter template to the "Creation" section.  

Checkout the screenshot I took from Bootstrap. 

![2020-06-11_08-53-05](https://user-images.githubusercontent.com/26409558/84359871-2a9a1400-abc1-11ea-8b28-e549c85d6568.png)

![2020-06-11_08-57-25](https://user-images.githubusercontent.com/26409558/84360886-ba8c8d80-abc2-11ea-8d9e-e4e54f282bee.png)

**Comment by Lemmie88** [comment]
Just wanna say thanks for your work. It was simple to implement for my needs and literally got it done in 2 seconds. Cheers :)

**Comment by atomiks** [comment]
I think the best option is to merge both "Getting Started" and "Creation" into one page. Going to fix it in a sec.

**Comment by LondonWebFactory** [comment]
That's great! :)
