### ISSUE TITLE
Carriage return is not working in 6.2.3

### ISSUE THREAD

**Issue by molyviatis** [atomiks/tippyjs#787]
Carriage returns within the tooltip are not working in version 6.2.3.  This worked in previous versions.

**Comment by atomiks** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Make sure to follow the bug report issue template when you submit a new issue, this way I will already have all the information needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to amend your issue with the necessary details.
