### ISSUE TITLE
How do I insert a line break into the text in a tooltip in tippy.js version 6.2.3?

### ISSUE THREAD

**Issue by molyviatis** [atomiks/tippyjs#788]
Hi, 

I am using tippy.js in my Angular 9.1 application and love it.  I have tooltip text that comes from a webapi service.  In this service I insert \n in the text when I want a line break in the tooltip.  This worked great in tippy.js version 5.2.0 but since upgrading to 6.2.3, it doesn't work anymore.  If I downgrade back to 5.2.0, it works again.  Is there a new way of doing this in the latest version?  How do I insert a line break into the text in a tooltip in tippy.js version 6.2.3?
Please help

**Comment by atomiks** [comment]
`allowHTML: true`?

**Comment by molyviatis** [comment]
Thanks for the suggestion but unfortunately it didn't work.

**Comment by atomiks** [comment]
I tried in v5 and v4 and `\n` didn't work either; it doesn't unless you wrap the content in `<pre>` first. You need to use `<br>` for line breaks with HTML.

**Comment by molyviatis** [comment]
I achieved it in 5.2.0 with "white-space: pre;" in the css but this stopped working in later versions.

**Comment by seahindeniz** [comment]
Hi @atomiks 

Quoting from https://atomiks.github.io/tippyjs/v6/all-props/#content
> Note
>
>To render strings as HTML, set allowHTML: true. This can open you up to XSS attacks, so be careful.

What do you think simply replacing all `\n` characters with `<br>` in the content before rendering it? 
If there is going to be a case that needs to print literally `\n`, users can use something like `\\n` like in the native title attribute.
