### ISSUE TITLE
Is it better to skip rendering the Tippy component on the server?

### ISSUE THREAD

**Issue by hk86** [atomiks/tippyjs#789]
Hi there,

i've a short question regarding the Tippy component. I render my app on the server side, is it better to skip rendering the Tippy component on the server or will Tippy do it by itself?

Option A:
```
const content = <div>CONTENT HERE</div>
const element = <div>SOME ELEMENT</div>
<Tippy content={content}>
    {element}
</Tippy>
```

Option B:
```
const content = <div>CONTENT HERE</div>
const element = <div>SOME ELEMENT</div>
if (NOT SERVER) {
    <Tippy content={content}>
        {element}
    </Tippy>
}
return element
```

Does it make sense from a performance perspective to go with option B?

**Comment by atomiks** [comment]
There's no need for any conditionals, the vast majority of the logic is only run in the client-side effects which are noops on the server

**Comment by hk86** [comment]
thanks!
