### ISSUE TITLE
When i Import styles and animation files it throws errors

### ISSUE THREAD

**Issue by sagarCS** [atomiks/tippyjs#790]
When i import the style and animation file like :
`
import 'tippy.js/animations/scale.css'; 
import 'tippy.js/dist/tippy.css';
`
and the when i run my app it throws this error:
```
ERROR in ./node_modules/tippy.js/dist/tippy.css (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--8-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/postcss-loader/src??ref--14-0!./node_modules/tippy.js/dist/tippy.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
BrowserslistError: Unknown browser query `dead`
    at /home/sagar/Desktop/Latest/UI-React/node_modules/postcss-cssnext/node_modules/browserslist/index.js:164:11
```
can anyone help me what might be the issue?

**Comment by atomiks** [comment]
I think your PostCSS config needs to ignore `node_modules` because there's a property in this package's `package.json` that specifies browserslist config.
