### ISSUE TITLE
Documentation doesn't cover various arrow sizes

### ISSUE THREAD

**Issue by monstermac77** [atomiks/tippyjs#791]
I'm using `<script defer src="https://unpkg.com/tippy.js@6.2.3/dist/tippy-bundle.umd.min.js"></script>` in my HEAD. Tippy works great. I can't tell you how much time we've wasted with Bootstrap tooltips at this point, we're switching all future tooltips to Tippy. 

One thing I can't figure out is how to get the arrow size to be small, as in shown in the demo page. 

Here's what I've tried: 
`arrow: small`
`arrow: 'small'`
`arrow: 'Small'`
`arrow: 'smallArrow'`
`arrowType: 'small'`
`arrowType: 'sharp'`
`arrowType: 'Small'`

**Comment by atomiks** [comment]
[See this section on the docs](https://atomiks.github.io/tippyjs/v6/themes/#changing-the-arrow-size). You can inspect the CSS yourself and find out what needs to be changed manually too.

**Comment by monstermac77** [comment]
Got it, thanks! I clearly was just heavily assuming that it was something passed to the constructor (i.e. Javascript, not CSS).
