### ISSUE TITLE
Add prop to pass a className

### ISSUE THREAD

**Issue by katarc** [atomiks/tippyjs#792]
## Problem

I want to be able to pass a class name to the inner tooltip box.
Currently I am using the `onShown()` method to add the class, but seems a bit too convoluted for something so standard?

## Solution
Add additional properties to add class names to tooltip content box and arrow

**Comment by atomiks** [comment]
You can create your own `className` plugin prop which does this — [see this example](https://github.com/atomiks/tippyjs-react/blob/master/src/className-plugin.js).

**Comment by zhaoyao91** [comment]
create className plugin is a workaround, but this feature is such a common use case, I vote for `class` prop

**Comment by MightyPork** [comment]
The plugin works fine (even without react after removing the react-specific parts), but I have a problem with TypeScript - className can't be added to the properties object in tippy(). I wrapped the call to `tippy()` in a plain JS file that tricks TypeScript into not checking the type, but it feels super ugly. There must be a better way
