### ISSUE TITLE
Changing arrow size with scale doesn't change transform property on parent div

### ISSUE THREAD

**Issue by katarc** [atomiks/tippyjs#794]
## Bug description

Awesome library and having so much fun so far! I noticed that (following **https://atomiks.github.io/tippyjs/v5/themes/#changing-the-arrow-size**) when I give transform: scale(0.75) to the arrow:before element, it still places the `data-tippy-root` element based on original size of the tip.

This results in the tip hovering way above the element and looks odd. 

I am also not sure how to correct the behavior - since the style is added inline dynamically.

## Reproduction

https://stackblitz.com/edit/angular-gunadi

this shows two buttons, and both have tooltips at the same position

**Comment by atomiks** [comment]
The offset of the tippy isn't based on the arrow size, you need to manually specify it. 

https://atomiks.github.io/tippyjs/v6/all-props/#offset

e.g. `offset: [0, 5]` (default is always `10` px distance)
