### ISSUE TITLE
tipply.js v6.2.3 is not compiling

### ISSUE THREAD

**Issue by Krishna-Agrawal** [atomiks/tippyjs#795]
After installing tippy v6.2.3, getting this error
```
ERROR in node_modules/tippy.js/index.d.ts(95,19): error TS2304: Cannot find name 'unknown'.
node_modules/tippy.js/index.d.ts(112,39): error TS2304: Cannot find name 'Omit'.

```

**Comment by atomiks** [comment]
You need to upgrade your TypeScript package version to latest.

**Comment by Krishna-Agrawal** [comment]
@atomiks I am trying to use tippy library, but not able to use it because of this issue, can you please tell me why it is invalid.
And if it is invalid, please tell me how can I use this lib.

**Comment by Krishna-Agrawal** [comment]
I can not do that as I am using Angular6, can you please tell me which version of tippy.js supports Typescript 2.9.2.

Thanks
