### ISSUE TITLE
Interactive tooltips inside <svg>

### ISSUE THREAD

**Issue by gorgitko** [atomiks/tippyjs#796]
## Problem

When an interactive tooltip is invoked, tippy places its `<div>` to DOM after the triggering element. But it is not possible to place regular HTML elements inside `<svg>` (except `<foreignObject>`, but that is not important), so the interactive tooltip is not displayed.

## Solution

A solution would be to append the tooltip `<div>` outside of a `<svg>` element. [Here](https://jsfiddle.net/gorgitko/vdcmeb52/20/) is my dirty solution. It is using a `MutationObserver` on the `<svg>`. When the tooltip's `<div>` with attribute `data-tippy-root` is appended to the `<svg>`, it is moved to the `<body>`.

**Comment by atomiks** [comment]
You can use `appendTo` to specify where to put it instead. The default can be overridden in this case

**Comment by gorgitko** [comment]
Thank you for the prompt reply. My bad, I haven't seen this option. `appendTo: () => document.body` works same as my solution :+1: :slightly_smiling_face:

Anyway, I was googling for `tippy.js interactive svg` and haven't found anything related, so at least this issue could help others if it bubble up to top search results.
