### ISSUE TITLE
Multiple tippys instance getting created on mouseEnter event

### ISSUE THREAD

**Issue by kunalahirrao** [atomiks/tippyjs#798]
I want tippy on mouse enter and removing it on mouse leave. But the **border** of tippy remains and it gets **darker** with a successive mouse enter events.

**Sandbox** for the same: https://codesandbox.io/s/fullcalendar-v4-vue-bt8uu

**Comment by atomiks** [comment]
You're calling `tippy()` each time you hover over the element, which always creates new instances. You need to create a single instance only upon the component mounting, then clean it up when it gets destroyed.

**Comment by kunalahirrao** [comment]
Issue solved ---  
onUntrigger(instance) {
instance.destroy()
},
