### ISSUE TITLE
Hide On Click doesn't hide when button is middle clicked.

### ISSUE THREAD

**Issue by madprops** [atomiks/tippyjs#80]
Using this on  buttons:

```
			tippy(this, 
			{
				delay: [1200, 100],
				animation: 'scale',
				hideOnClick: true,
				duration: 100,
				arrow: true,
				performance: true,
				size: 'regular',
				arrowSize: 'small'
			});
```

Actually I used to have hideOnClick: false, and it still hid the tippy when clicked or right clicked. Just changed it to true and noticed it hides a bit faster on click. But it doesn't hide at all when middle clicked.

**Comment by atomiks** [comment]
The click handler on the `document` is what hides tooltips upon click, not sure why it wouldn't work for middle click. I only have a laptop to test on. Can you make a CodePen please?

**Comment by madprops** [comment]
CodePen: https://codepen.io/madprops/pen/EXzzPR

I think the problem might be that click no longer activates for middle click, I think, you have to use "auxclick"  https://developer.mozilla.org/en-US/docs/Web/Events/auxclick

**Comment by atomiks** [comment]
Does it work on the docs page? https://atomiks.github.io/tippyjs/

I noticed right-clicking on the CodePen doesn't hide it either, but it does on my docs page (which has Bootstrap v4.alpha6 CSS)

**Comment by madprops** [comment]
Nope, none of the examples I tried in the doc page hid the tooltip with right or middle click. Using Chrome 59 on Windows

**Comment by atomiks** [comment]
I guess you're right, right-clicking brings up the context menu but doesn't run the handler function for `click`. I guess the it's the same for middle click now too.

```javascript
document.onclick = e => alert(e.which)
```
Binding even more custom events doesn't seem that nice, couldn't you bind custom events to the tooltipped element yourself and hide it when appropriate?

**Comment by madprops** [comment]
Binding even more custom events doesn't seem nice :) It's not a big problem though, most cases don't require right or middle clicking anyway. Just thought you might like to know about it.

**Comment by atomiks** [comment]
Gonna close this since I don't really think it's important and can be solved by the dev themselves if need be.
