### ISSUE TITLE
second tooltip not comes at first hover on same element

### ISSUE THREAD

**Issue by CyberT33N** [atomiks/tippyjs#800]
## Bug description

Hello there :) Maybe not a bug but not sure how to solve it. 
I use the custom method as you see below to start a tooltip when the page is loaded. This works fine.. 

I destroy the tooltip once I hover over the same element where I set the tooltip on.  This is not working at the **first hover**!

Doesnt matter if I **destroy/hide/disable** the element or when I **do not destroy** the tooltip, the second tooltip will not come on the first hover on any scenario. Only at the second hover it comes.

How can I destroy and open a new tooltip while iam still inside the first hover? If this is not possible I would be also happy with any js workaround to fix this.

Greets

## Reproduction
```javascript

          let el = document.querySelector('.ui__downloadList__item.purple');
          layertwo_preLoadTooltip = tippy(el, {
            trigger: 'manual',
            animation: 'scale',
            inertia: true,
            // default [skidding, distance]
           offset: [0, 20],
            placement: 'bottom',
            maxWidth: 'none',
          
          
            content: `<div>
            <p class="layertwo-preload-tooltip-text">Hover those 3 Boxes for more details!</p>
            <i id="layertwo-preload-tooltip-text-pointer" class="fa fa-mouse-pointer" aria-hidden="true"></i>
            </div>`,
            allowHTML: true
          });
          layertwo_preLoadTooltip.show();
          



          
          
          $(document).on("mouseenter mouseleave", ".ui__downloadList__item.purple", function (e) {
            if (e.type == "mouseenter") {

          layertwo_preLoadTooltip.destroy();
          
          setTimeout(() => {
            tippy('.ui__downloadList__item.purple', {
              animation: 'scale',
              content: content,
              allowHTML: true,
              placement: 'bottom'
            });
          }, 1500);
          
          
          } // if(  layertwoFirstVisit == true  ){
          });
          
```

**Comment by CyberT33N** [comment]
As it seems setTimeout was causing the problem. When i remove it it works on first hover. Very strange

**Comment by CyberT33N** [comment]
As it seems delay is causing a new bug. When you set **first time** a delay that has **different value on the second hover** then the tooltip popup 2 times instead of 1 time. Doesnt matter what value the delay has on second hover.

When the delay is **fixed and is not changing on the first hover** then its working. So this works:
```
delay: [1500, 0]
```

However I want that the first hover delay is longer than all other after the first one. Thats why I created the code like below.

**Please notice again** as related to the first code posted at this topic that this element was already used and then destroyed before next tooltip come with code below, thats maybe the reason why those bugs happen.

For some reasons the whole problems are related to SetTimeout/Tippy.js delay

```javascript
              
                      $(document).on("mouseenter mouseleave", ".ui__downloadList__item.purple", function (e) {
                        if (e.type == "mouseenter") {
  
                            let delay = 0;
                            if(  layertwoFirstVisit == true  ){
                            layertwoFirstVisit = false;
                            delay = 1000;
                            }
                            
                            layertwo_preLoadTooltip.destroy();

                              tippy('.ui__downloadList__item.purple', {
                                animation: 'scale',
                                content: content,
                                allowHTML: true,
                                placement: 'bottom',
                                // default [skidding, distance]
                               offset: [0, 20],
                               delay: [delay, 0],
                                placement: 'bottom',
                              });
                            
                             }
                          });
```

**Comment by atomiks** [comment]
The problem is you're using event delegation to create the tippy which is problematic. You should use `delegate()` instead (see Addons section) or create the tippy instances on init, not in response to events.

**Comment by CyberT33N** [comment]
Delegation seems to work but not with followCursor: true

The first hover its disabled and on seconds its only working.

"create the tippy instances on init, not in response to events."
- Can you give a example please what you mean here

**Comment by atomiks** [comment]
https://codepen.io/atomiks/pen/yvwQyZ

Pasting the following works?:
```js
tippy.delegate('body', {
  content: 'tooltip',
  target: 'button',
  followCursor: true
});
```

> Can you give a example please what you mean here

As in you call `tippy()` once the elements are on the DOM (loaded), not upon a `mouseenter` event, etc. Tippy adds the event listeners for you

**Comment by CyberT33N** [comment]
Since I don´t know how to start a delegate manually I used the delegate on my second tooltip at the mouseenter function as sended above. Thats where all worked except the followCurser which only worked on the second hover.

Is there a way to trigger a delegate tippy manually? Then I can try to replace the first tooltip aswell with it.

Also I figured out that I doesnt matter which css selector I use on the first tippy I create with event. So its not related to the same element.

**Comment by atomiks** [comment]
You need to move the `tippy()` call **outside** of your event listener. You've put it inside the handler function

**Comment by CyberT33N** [comment]
I´am not sure how to realise this which dynamic changing the delay value. When I use trigger: 'mouseenter' instead of my jquery mouseenter function then the tippy is already created and all values are fixed and delay can not changed anymore.

Is there a way to change the tippy values once the tippy was created?

**Comment by CyberT33N** [comment]
Also random stuff like css animations are also not working until both tippys are destroyed. This complete event method is totally bugged and cause multiple stuff not to working internal at tippy or external at my css animations. This here I mean:
```javascript
const layertwo_preLoadTooltip = tippy(document.querySelector('.ui__downloadList__item.purple'), {});
```

I mean I want to use your methods (https://atomiks.github.io/tippyjs/v6/methods/) thats why I use this code that I can run:
```javascript
layertwo_preLoadTooltip.show();
layertwo_preLoadTooltip.destroy();
```

However it´s not working in any scenario. Since you said I should use delegate (https://atomiks.github.io/tippyjs/v6/addons/) I do not understand how to use this with the methods like .show() or .destroy()

Can you give please any working scenario for how to create tippys with manually trigger that its works without any problem?

**Comment by atomiks** [comment]
You can update any prop with the `.setProps()` method. So the following will use `1000ms` delay initially and then `0ms` delay after the first visit.

```js
let visited = false;

tippy('button', {
  delay: [1000, 0],
  onShow() {
    if (!visited) {
      instance.setProps({delay: 0});
      visited = true;
    }
  }
});
```

**Comment by CyberT33N** [comment]
First of all I found out why the tippy overlapped 2 times. It was because I created the tippy each time again when the user hover the element cause I create the tippy creation inside the jquery mouseenter function. Also as it seems when you do this then tippy create always a new tooltip in DOM even when the css selector is the same. 

Seconldy thank your for your example I really appreciate that and understand what you want to archive. However in my case the delay isn´t working anymore in anyway.

I outsourced now all tippys like:

```javascript
 
const layertwo_threeBoxes_backend = tippy(document.querySelector('.ui__downloadList__item.purple'), {
  theme:'layertwo-Tooltip-threeBoxes',
  animation: 'scale',
  content: content,
  hideOnClick: false,
  followCursor: true,
  allowHTML: true,
  width:"50%",
  trigger: 'manual',
   inertia: true,
  placement: 'bottom',
 offset: [0, 20],
  placement: 'bottom',
  maxWidth: 'none'
});

```
And I show and hide it within my jquery mouseenter function
```javascript
 layertwo_threeBoxes_backend.show();
layertwo_threeBoxes_backend.hide();
```

I tried your **onShow** code and **aswell delay only** but both not working anymore. The tippy just comes straight. Not sure why.

I tried again to **setTimeout** the  layertwo_threeBoxes_backend.show(); bymself and it worked actually fine except that **followCursor: true,** is bugging with setTimeout! The first tippy is anywhere in the top left corner and then when I move the mouse the tippy come back to the mouse spot. Without setTimeout this problems not occures.

You can reproduce this via the codepen link you send above with:

```javascript
const test = tippy(document.querySelector('button'), {
  content: 'tooltip',
trigger: 'manual',
followCursor: true,
});


setTimeout(() => { test.show(); }, 5000);
```

**Comment by atomiks** [comment]
1. Calling `.show()` doesn't respect the `delay` prop. It will show the tippy immediately. Why are you using the `.show()` method? 

2. `followCursor` doesn't attach a mouse listener until the tippy has been triggered for perf reasons, so when you call `.show()` it doesn't know where the cursor is until you move the mouse once it shows — and even if it did listen before trigger, the cursor might not have been on the page at all yet when you call `.show()` after 5000 ms, so it would still be a bug in that case

**Comment by CyberT33N** [comment]
1. What else should I use when not show? No other methods seems to be valid for this. also it says "**Programmatically show the tippy at any time**" and doesnt matter if first show or second show the delay never works. Can you give example please how to start tippy manually without show then

2. Why should it now know where the mouse is.  I make 5 seconds timeout and then go with my mouse over the element where the tippy is and then once the .show() fires it still in the top left corner. I doesn´t realise the first the first mouse position in any scenario. Only via the default hover tippy it works.
