### ISSUE TITLE
Migrated from v5.2.0 to v6.2.3, theme has a different look

### ISSUE THREAD

**Issue by xerosanyam** [atomiks/tippyjs#801]
## Bug description
The light theme in v6.2.3 has
- more glow than it had before
- has a border around the box

is this intended? Am I doing something wrong?
Looked at migration guide, no clue

## Screenshots
![Light theme 5.2.0](https://user-images.githubusercontent.com/3167278/85583196-abdeb580-b65b-11ea-9406-908db506021b.png)
Light theme - 5.2.0

![image](https://user-images.githubusercontent.com/3167278/85583423-df214480-b65b-11ea-98ee-68e9d8b66004.png)
Light theme - 6.2.3

**Comment by atomiks** [comment]
Something in your CSS is causing the issue. Try to delete all styling related to tippy and work back incrementally. Someone else experienced a problem with themes after upgrading too.

**Comment by xerosanyam** [comment]
thanks for replying. I am quite sure that I don't have any css related to tippy that would create this issue

**Comment by xerosanyam** [comment]
is it possible that it could happen because multiple tippy instances are getting created ?

**Comment by atomiks** [comment]
Maybe? Can't you inspect the CSS and DOM yourself to find out?
