### ISSUE TITLE
animationFill is buggy on Safari (Version 13.1.1 (15609.2.9.1.2))

### ISSUE THREAD

**Issue by usb248** [atomiks/tippyjs#802]
## Bug description

just see gif
![bug](https://user-images.githubusercontent.com/7659927/85685608-84293500-b6cf-11ea-8daf-50cb9a4d5d86.gif)

## Reproduction

```javascript
                var tippyInstances = tippy('.tippy',{
                    content: function(reference) {
                        var title = reference.getAttribute('title')
                        reference.removeAttribute('title')
                        return title
                    }
                })

                tippySingleton = tippy.createSingleton(tippyInstances, {
                    animateFill: true,
                    ignoreAttributes: true,
                    offset: [0, 7],
                    moveTransition: 'transform 0.2s ease-out',
                    overrides: ['placement', 'content']
                })
```

**Comment by usb248** [comment]
it seems the `animationFill:true` the problem

**Comment by atomiks** [comment]
Safari did have issues with that a while ago but I thought they were fixed 🤔 

This seems to work in Safari: https://atomiks.github.io/tippyjs/#material-filling-effect

Is it just a problem with singletons or standalone instances?

**Comment by usb248** [comment]
Hi,

This si specific to Singleton

**Comment by atomiks** [comment]
Can't reproduce (Safari `13.0.5` though)
https://imgur.com/a/gs2bH6J

**Comment by usb248** [comment]
However all works fine in all browser or without animateFill in safari... it’s very strange.

**Comment by usb248** [comment]
@atomiks can u share codepen's link ? in order to test in my safari ?

**Comment by atomiks** [comment]
I wasn't signed in so couldn't save it, you can just write the same code (pasted from your code too) from the bug report template

**Comment by usb248** [comment]
@atomiks , after many tests, my conclusion is that is a problem related to `<a>`.
See this codepen, it should doesn't work in your safari too : https://codepen.io/usb248/pen/WNrZpMN

**Comment by atomiks** [comment]
This fixes it:

```css
.tippy-box {
  will-change: transform;
}
```

I can't add it by default since it can disables subpixel antialiasing on low DPI displays. I'd enable that only for Safari if possible.

**Comment by usb248** [comment]
no explanation for this being specific to links :confused: ?
