### ISSUE TITLE
The undefined props are not set to defaults

### ISSUE THREAD

**Issue by makarov906** [atomiks/tippyjs#803]
## Bug description
If pass the undefined option, then tippy will use this value instead of setting the default value

## Reproduction

```js
tippy('button', {
  content: 'tooltip',
  trigger: undefined
});

`Uncaught TypeError: Cannot read property 'split' of undefined`
```

CodePen link: https://codepen.io/makarov906/pen/oNbwErz

**Comment by atomiks** [comment]
That's how object spreading works, `{ ...defaults, ...specified}`, the `undefined` value takes over the default. How should it work?

**Comment by makarov906** [comment]
I expect defaults options to be applied

**Comment by atomiks** [comment]
Hmm yeah I guess.

**Comment by p12y** [comment]
Why has this been closed? I think this is a valid bug. I was just creating a wrapper component for this and had to manually remove all undefined props before passing them to tippy. I agree with @makarov906 that default values should be applied.
