### ISSUE TITLE
Tippy instance not removed when class is changed

### ISSUE THREAD

**Issue by dlh-0492** [atomiks/tippyjs#804]
## Bug description

I am trying to create a spoiler effect like that on Reddit. As you can see I have used Tippy to create a tooltip showing "Reveal spoiler". When a `span` with the `md-spoiler-text` class is clicked, the class gets changed to `md-spoiler-text-revealed`. However, the tooltip continues to show (it still pops up on mouseover) even though the element in question no longer has the class `md-spoiler-text` declared in the Tippy instance. Could this be changed so that the tippy instances for individual elements can be added or removed when they have classes added to or removed from them?

## Reproduction

    <!DOCTYPE html>

    <html>
        <head>
            <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="ROBOTS" content="index, nofollow" />
            <meta name="GOOGLEBOT" content="noindex, nofollow" />`

            <style>
            .tooltip
            {
                box-sizing: border-box;
                border-collapse: separate;
                cursor: pointer;
                letter-spacing: normal;
                line-break: auto;
                position: relative;
                -webkit-text-size-adjust: none;
                -moz-text-size-adjust: none;
                -ms-text-size-adjust: none;
                -o-text-size-adjust: none;
                text-size-adjust: none;
                word-break: normal;
                word-spacing: normal;
                word-wrap: normal;
            }
            
            .md-spoiler-text
            {
                background: #4f4f4f;
                border-radius: 2px;
                cursor: pointer;
                color: transparent;
            }
            
            .md-spoiler-text > *
            {
                opacity: 0;
            }
            
            .md-spoiler-text-revealed
            {
                background: rgba(79, 79, 79, 0.1);
                border-radius: 2px;
                color: #000000;
                cursor: auto;
                opacity: 1;
                transition: background linear 2s, color ease-in 2s;
            }
            
            .md-spoiler-text-revealed > *
            {
                transition: opacity linear 2s;
                opacity: 0;
            }
            
            .tippy-box[data-theme~="spoiler-text-tooltip"]
            {
                 font-size: 11px;
                 line-height: 16px;
                 pointer-events: none;
            }
            </style>

            <script src="http://code.jquery.com/jquery-latest.min.js"></script>
            <script src="https://unpkg.com/@popperjs/core@2"></script>
            <script src="https://unpkg.com/tippy.js@6"></script>
            <script>
            $(document).ready(function() {
                $(".md-spoiler-text").on("click", function() {
                    $(this).removeClass("md-spoiler-text").addClass("md-spoiler-text-revealed").unbind();
                });
                
                tippy.setDefaultProps({
                    allowHTML: true,
                    arrow: true,
                    duration: [200, 200],
                    offset: [0, 10]
                });
                
                tippy(".md-spoiler-text", {
                    content: "Reveal spoiler",
                    theme: "spoiler-text-tooltip"
                });
            });
            </script>
        </head>
        <body>
            <span class="tooltip md-spoiler-text">Spoiler Alert</span>
        </body>
    </html>

**Comment by atomiks** [comment]
You just need to destroy the tippy instance once the spoiler has been revealed. Check the Methods page on the docs.

**Comment by dlh-0492** [comment]
Thanks! This was my fix:

    var spoilers = tippy(document.querySelectorAll(".md-spoiler-text"));
    spoilers.forEach((elem, i) => {
        elem.setProps({
            content: "Reveal spoiler",
            theme: "spoiler-text-tooltip"
        });
    });
    
    $(".md-spoiler-text").on("click", function() {
        $(this).addClass("revealed");
        spoilers[this._tippy.id - 1].destroy();
    });
