### ISSUE TITLE
If using tab, the label does not go away

### ISSUE THREAD

**Issue by crystalfp** [atomiks/tippyjs#805]
If I tab to a "tippy enabled" button or hover and remain over it, the tippy label remains visible.
Is there any setting to say: "after this interval make the label go away"?
Why? If I put the cursor on the button, to make the label disappear, I simply need to move the pointer. But if I use the tab key to navigate the interface, I cycle through the buttons, so the last label never goes away, covering part of the interface. This way I'm forced to use the mouse to make the labels disappear.
My tippy labels are created this way:
```
		tippy(selector, {
				delay: 400,
				duration: 100,
				maxWidth: 150,
				theme: "material",
				animation: "scale"
		});
```
Thanks for clarifying!
mario

**Comment by atomiks** [comment]
Without a CodePen it's not possible to help — if you check the docs website, you'll see that tabbing through will close the previous tippies.
