### ISSUE TITLE
working after timeout

### ISSUE THREAD

**Issue by xerosanyam** [atomiks/tippyjs#807]
## Bug description
Tippy v6, was not working for me on mobile. Keeping it inside setTimeout, made it work.
Using along with vue, any ideas what I might be doing wrong?
It was working perfectly in v5.

## Reproduction
Will Update soon

**Comment by atomiks** [comment]
Unfortunately i'm not sure sorry :-( I don't recall any async behavior being introduced that would cause that. 

Feel free to update this with a reproduction so I can determine the issue.
