### ISSUE TITLE
Always showing tippy

### ISSUE THREAD

**Issue by nickjacobs** [atomiks/tippyjs#808]
I need to show all the tippys on load for a specific case - 
I see an old question about this - answered using ShowOnInit:true   -  I don't see this in the docs anywhere and it didn't work for me.

Is ShowOnInit still around, or is there another way to achieve having all the tips open , always?

**Comment by atomiks** [comment]
3 props are needed:

- `trigger: 'manual'`
- `showOnCreate: true`
- `hideOnClick: false`

**Comment by nickjacobs** [comment]
Thats great, thanks for the answer - but it is causing an issue - whichever tippy is last in the document shows in the correct place, but a copy also display at the very top of the document - that is, I don't see a copy when inspecting the dom, but it does show at the top of the page...any ideas on that ? :)
