### ISSUE TITLE
for nesting, must inner element be tippied before the outer element?

### ISSUE THREAD

**Issue by zhaoyao91** [atomiks/tippyjs#810]
I've create some simple prototypo to check the nesting feature, but the inner tippy only took effect if it was initialized before the outer tippy.
Is this by design or a bug? I didn't find any document address this.

**Comment by atomiks** [comment]
Nope it works no matter when initialized. See https://codepen.io/atomiks/pen/BajJPPR

**Comment by zhaoyao91** [comment]
> What might be happening is you're using a CSS selector to tippy the element, but the content is moved outside of the document and into the tippy, so it doesn't get found.

Yes, it's just the cause, I've reproduced it, thanks! https://codepen.io/zhaoyao91/pen/GRoxvyW
