### ISSUE TITLE
Accessibility (a11y): Keyboard navigation with `appendTo: document.body`

### ISSUE THREAD

**Issue by ar-rm** [atomiks/tippyjs#812]
I'm using `createSingleton()` for a Tippy instance on multiple `<button>`s on the same page.

```
[...]
appendTo: () => document.body,
allowHTML: true,
interactive: true,
a11y: true
[...]
```

The Tippy instance has two `<button>`s which copy some text.

✅ I can `focus` the button via the `tab` key, which shows Tippy.

❌ The problem is, I can't `tab` key *into* the Tippy instance to focus the two *inner* buttons. Instead `tab` just moves on to the *next* accessible item on the page.

This breaks accessibility.

---

I've found that if I set `trigger: 'click'` to debug, I **can** focus those two buttons, but only **after** I've focused the *rest* of the accessible elements on the page.

This makes sense since the markup for this Tippy instance is just before `</body>`. Which is probably one of the reasons `appendTo:` defaults to the `trigger` element and not `<body>`.

But having the Tippy's markup at the end of the page's markup is useful. ex: Getting around CSS issues related to it being a sibling element.

**The question is:**
Is there a way around this?

Could Tippy's markup be at the end of the page's markup **and** its interactive/html content still remain in the "flow/sequence" of `tabbing` for accessibility?
 

I'd assume no :-)

It would probably require not only sequentially adding `tabindex` to the triggering `<button>` and then the inner buttons, but also *knowing* what `tabindex` to start on, since there are likely others on the rest of the page. And even that's not great, because what about the focusable elements *after* the Tippy `trigger` element?

I guess this would be possible, but seems out of the scope of what Tippy should be doing. Also, I might have **no idea** what I'm talking about :-)

Here's some related issues (mostly for cross referencing):
https://github.com/atomiks/tippyjs/issues/65#issuecomment-514796473
https://github.com/atomiks/tippyjs/issues/746#issuecomment-605849731
https://github.com/atomiks/tippyjs/issues/546#issuecomment-519762627
https://atomiks.github.io/tippyjs/v6/accessibility/

---

During development I thought I'd need to use `appendTo: () => document.body`, but I tried again and it looks like I'll be able to go back to the default (Tippy instance as a sibling element), which allows for the sequential keyboard navigation I'm looking for.

---

Thanks for all of your work on Tippy!

**Comment by atomiks** [comment]
The docs mention you will need to use a focus management solution (e.g. focus the tippy as soon as it's open, then restore focus to the trigger element upon close) in the case it's appended to the body. 

Alternatively, while the tippy is open, maybe add a document key listener that detects the tab key was pressed and programmatically move focus to the first tabbable tippy content element, then once focus exits the tippy, close it and resume focus to the element directly after the original trigger element.

How exactly it will work depends on the UI element I think.

**Comment by ar-rm** [comment]
Thanks for the quick reply.

> The docs mention you will need to use a focus management solution (e.g. focus the tippy as soon as it's open, then restore focus to the trigger element upon close) in the case it's appended to the body.

Yes I saw that. But I noticed it was in the `v5` documentation but **not** `v6`, so I thought maybe something had changed:

https://atomiks.github.io/tippyjs/v5/faq/#my-tooltip-appears-cut-off-or-is-not-showing-at-all
https://atomiks.github.io/tippyjs/v6/faq/#my-tooltip-appears-cut-off-or-is-not-showing-at-all


I tried versions of this, but it doesn't `focus()` because it's `undefined`:

```
    onShown(instance) {
        instance.popper.focus()
    },
```

I know I'm doing something wrong, but I'm not sure what.


---

I found this, which seems to detail this approach. Do you agree?

https://medium.com/@matuzo/writing-javascript-with-accessibility-in-mind-a1f6a5f467b9
https://codepen.io/matuzo/pen/pRNVJN?editors=1010

---

#### re: Using the default `appendTo` (as a sibling):

It basically works fine, with a slight issue related to `moveTransition`.

I'm using this:
`moveTransition: 'transform 0.2s cubic-bezier(0.22, 1, 0.36, 1)'`

(Which is almost straight out of your Docs.)

It looks great. It's really impressive that Tippy, via createSingleton()`, knows to **not** apply that transition in cases where focus changes within the `delay` time.

But sometimes it seems the animations overlap, and you can see the other Tippy instance transition in from the top/left, or where it last was.

Here's a video that will hopefully better illustrate. I've slowed down the `transition-duration` property so you can see it better:

![Tippy js--Issue-812--moveTransition-video](https://user-images.githubusercontent.com/199155/86966532-557f7580-c137-11ea-9242-22ef5606c664.gif)

✅ Vertical movement
❌ Horizontal movement

I've tried various `delay` and `moveTransition` values. Nothing but `0` works. Which kinda defeats the point ;-)

This is one of the reasons I switch *to* `createSingleton`. To avoid this.

Maybe you have some insight into how to avoid this?

---

Other Reference:
https://github.com/atomiks/tippyjs-react/issues/216
