### ISSUE TITLE
Bug position

### ISSUE THREAD

**Issue by usb248** [atomiks/tippyjs#814]
## Bug description

Tooltip isn't positing correctly. Seems to be since latest release. When i downgrade i haven't the bug.

## Reproduction

https://codepen.io/usb248/pen/WNrZpMN

Just see (tested on last version FF on windows 10) :
![image](https://user-images.githubusercontent.com/7659927/86928439-d426e380-c134-11ea-9c2d-100a287d4e5f.png)

**Comment by atomiks** [comment]
Thank you for the bug report. There was a missing `if` in the `followCursor` plugin refactor which caused this bug with singletons' positioning. 

Fixed in `v6.2.5`

**Comment by usb248** [comment]
thanks for your quick fix @atomiks
