### ISSUE TITLE
Tag v6.2.5

### ISSUE THREAD

**Issue by sgerrand** [atomiks/tippyjs#815]
💁 Version 6.2.5 was recently [published to npm](https://www.npmjs.com/package/tippy.js/v/6.2.5) without being tagged in version control. Would you please tag the relevant commit when you have a chance.

https://github.com/atomiks/tippyjs/compare/v6.2.4...master

**Comment by atomiks** [comment]
Uhm yeah I released that right before going to sleep and forgot sorry 😓 

Added
