### ISSUE TITLE
createSingleton() + `moveTransition` prop = Unexpected Transitions

### ISSUE THREAD

**Issue by ar-rm** [atomiks/tippyjs#817]
I noticed an issue with `createSingleton()` and the `moveTransition` prop.

I see that that Tippy defaults to creating the DOM elements as siblings to the trigger items. It's really impressive that it knows to *not* apply that transition in cases where focus changes within the `delay` time. (Or at least, it seems like that's what Tippy is doing.)

But sometimes the transition that's applied (when quickly moving from one trigger to the next) **overlap** (not the perfect description) and you can see the newly triggered Tippy instance transition in from the top/left (or where it was last?).

I'm normally using this:
`moveTransition: 'transform 0.2s cubic-bezier(0.22, 1, 0.36, 1)'`

(Which is almost straight out of the [docs](https://atomiks.github.io/tippyjs/v6/addons/#smooth-transitions).)

### Example:

Here's a video that will hopefully illustrate. I've slowed down the `transition-duration` property so you can see it better:

![Tippy js--Issue-812--moveTransition-video](https://user-images.githubusercontent.com/199155/86966532-557f7580-c137-11ea-9242-22ef5606c664.gif)

✅ Vertical movement = Expected
❌ Horizontal movement = Unexpected

I've tried various `delay` and `moveTransition` values. Nothing but `0` works. Which kinda defeats the point of using `createSingleton()` ;-)

### Possible Causes:

- It seems to have something to do with the `translate()` values that are applied to each Tippy instance.

- It might also have something to do with when Tippy is creating or removing the markup associated with each trigger.

### Reproduction:

I haven't been able to nail down the *exact* steps that cause this, but I've been testing it a lot. It's definitely reproducible and I can *feel* it about to happen when I quickly switch between certain trigger elements.

I know that doesn't help much, but I wanted to give as much information about it as I could.

---

I originally mentioned this here:
https://github.com/atomiks/tippyjs/issues/812#issuecomment-655737258

Sorry for the *sorta* double post. That original issue was `closed` and I wasn't sure if you still receive notifications of comments on closed issues. Also, this is a separate issue. So I thought that would be better for tracking purposes.

**Comment by madjennsy** [comment]
@ar-rm I was having the same issue and I fixed it by forcing Singleton instance appendTo: document.body

**Comment by ar-rm** [comment]
> @madjennsy  I was having the same issue and I fixed it by forcing Singleton instance appendTo: document.body

Thanks for the reply.

Yes, that was one of the first things I tried and it definitely fixes it.

But as a consequence it causes other Accessibility issues, which I mentioned here: https://github.com/atomiks/tippyjs/issues/812

**Comment by atomiks** [comment]
Do you have a CodePen repro of this that I can play around with?

**Comment by ar-rm** [comment]
> Do you have a CodePen repro of this that I can play around with?

Sure.

I just created a reduced test case:
https://codepen.io/ar/full/ZEQRzqz

### Notes:
- There are some props that I left in, that shouldn't be related, but I wanted to leave them in so you could see.
- There are a few notes in the CSS and JS, prefixed with "// Issue #817:".

### While creating this I noticed a couple things:
- Adding `position: relative` to the trigger's parent element helps, but the issue remains. Removing it exaggerates it.
- Lowering the `delay` prop down to `0` exaggerates the issue.

---

It looks like your **"Singleton tippy with a transition"** demo here https://atomiks.github.io/tippyjs/#singleton uses `appendTo: () => document.body`. Which is probably partially why this isn't seen there.

It makes total sense that the *singleton* would work better with `appendTo: () => document.body`. And I'd be glad to switch to that, if it weren't for the unintended consequences related to accessibility.

**Comment by atomiks** [comment]
Okay I see. The issue is the tippy is being appended to a **different** parentNode (`<td>`) when a new reference element gets triggered. This prevents it from being able to transition. The tippy needs to be in a stable parentNode context to transition. This means you can't use the default a11y appendTo, so you'll have to implement a custom keyboard/focus solution.

**Comment by ar-rm** [comment]
> Okay I see. The issue is the tippy is being appended to a **different** parentNode (`<td>`) when a new reference element gets triggered. This prevents it from being able to transition. The tippy needs to be in a stable parentNode context to transition.

Ahh. That makes sense.

I tried `appendTo: () => document.querySelector("table")` and that definitely smoothed things out. `document.body` is even more stable. As you already know :-)

> This means you can't use the default a11y appendTo

Yeah. I really want to use singleton because it's sooo smooth and pleasing when quickly triggering via different elements. But implementing custom handling of the "accessibility tab order/flow" seems like a bad idea. Like I'm asking for a lot of trouble :-)

I think I can roughly figure out how to:
- Save the previous `document.activeElement`
- Restore it `onHide()`

But I don't know how to get the tab key to cycle:
- From the trigger **into** the Tippy instance
- Through the buttons inside (that's simple/default)
- And then next to the next available `tab` focusable item

I hate the idea of faking all of these native behaviors. Which is why keeping the Tippy markup in-the-flow of the markup via the *default* `appendTo` value (as a sibling element) is so appealing.

Trade-offs, I suppose.

> so you'll have to implement a custom keyboard/focus solution.

Do you have any ideas or could you point me in any good directions?

These all seem like clever but not-as-good-as-native ideas:
https://hiddedevries.nl/en/blog/2017-01-29-using-javascript-to-trap-focus-in-an-element
https://allyjs.io/tutorials/accessible-dialog.html#trapping-focus-inside-the-dialog
https://stackoverflow.com/questions/7208161/focus-next-element-in-tab-index
https://medium.com/@matuzo/writing-javascript-with-accessibility-in-mind-a1f6a5f467b9

Or, at least, something that an accomplished JS library author would be much better at implementing than me ;-)

Thanks!!

**Comment by atomiks** [comment]
What I wrote [here](https://github.com/atomiks/tippyjs/issues/812#issuecomment-655266626) are my only suggestions, it's something you'll have to investigate. If you come up with a good solution remember to post it back in this issue for others if they encounter the same problem

**Comment by ar-rm** [comment]
> @atomiks
> What I wrote here are my only suggestions, it's something you'll have to investigate. 

I understand.


I realize `appendTo() => document.body` is not the default Tippy behavior. And this default results in out-of-the-box accessibility *benefits* (for interactive Tippy content).

But as you mentioned, to get the most visual benefits of `createSingleton()` it needs a "stable parentNode context to transition". Which, by default, *breaks* accessibility.

IOW:
- Default = Accessible
- Singleton (best implementation) = Not accessible


It's just my humble suggestion that Tippy users would benefit from a built-in solution to this conflict; by maintaining accessibility feature parity between `Normal` and `Singleton` instances of Tippy.


----


### Example Solutions:

> If you come up with a good solution remember to post it back in this issue for others if they encounter the same problem


The author of [Micromodal.js](https://micromodal.now.sh/) seems to have done a very nice job of:
- Creating an accessible modal
- Whose markup is in a "stable parentNode" just before the `</body>`
- Handles "trapping focus" and returning it on close

(I realize Tippy isn't a library to create modals, but given some of props available, it gets pretty close.)


----


### Tippy Docs:

Functional code aside, I think it would be helpful to add a note about this to the Singleton documentation:
https://atomiks.github.io/tippyjs/v6/addons/#smooth-transitions
https://github.com/atomiks/tippyjs/blob/master/website/src/pages/v6/addons.mdx

ex:
> Smooth transitions require a stable parentNode context to transition. This can be achieved via `appendTo() => document.body`. Note: This may break [Accessibility](https://atomiks.github.io/tippyjs/v6/accessibility/#interactivity) if you have [interactive](https://atomiks.github.io/tippyjs/v6/all-props/#interactive) items enabled"

(I can submit a pull request if that's what you'd prefer.)

If I had seen a note like this when evaluating Tippy, I would have known much sooner what to expect and wouldn't have gone down all of the rabbit holes I did :-) I still would have used Tippy though!


----



Again, thanks for Tippy and the time you've taken on this issue!



----

Reference:
- WAI-ARIA Authoring Practices 1.1
- W3C Working Group Note 14 August 2019
- Keyboard Interaction

> 2. When a dialog closes, focus returns to the element that invoked the dialog unless either:
The invoking element no longer exists. Then, focus is set on another element that provides logical work flow.

Source:
https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-7
https://www.w3.org/TR/2019/NOTE-wai-aria-practices-1.1-20190814/#keyboard-interaction-7

(You already know this, but I'm just including it for quick reference.)

**Comment by atomiks** [comment]
The default singleton has no transition, so accessibility still works fine. 

The quickest "fix" would be to disable transitions if the user is using a keyboard and keep everything the same. This has aesthetic downside but most keyboard usage for non-form elements is done by those who likely wouldn't appreciate the animation much anyway (e.g. vision difficulties/screen reader usage).

**Comment by ar-rm** [comment]
> The default singleton has no transition, so accessibility still works fine.

Agreed.

> The quickest "fix" would be to disable transitions if the user is using a keyboard and keep everything the same. This has aesthetic downside but most keyboard usage for non-form elements is done by those who likely wouldn't appreciate the animation much anyway (e.g. vision difficulties/screen reader usage).

I had this thought, but wasn't sure how to implement it.

- I tried different version of `trigger`. ex: `[mouseenter click]` to try to use `click` as what screen readers would use. But couldn't get the behaviors right across all of the input methods.

- I wanted to try to add a conditional in the `trigger` prop, but wasn't sure that was even possible.

- Do I need to attach custom event listeners to each button and essentially trigger Tippy manually?

Can you point me in the best direction?

Thanks.
