### ISSUE TITLE
tippy and CSP

### ISSUE THREAD

**Issue by dalescher** [atomiks/tippyjs#818]
Hello Atomiks,

I am facing issues trying to avoid unsafe-inline for my CSP. I followed what is said on your manual for CDN (at least what I understood) and use: 

**Scripts:**

```
<script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.min.js"></script>
<script src="https://unpkg.com/tippy.js@6/dist/tippy.umd.min.js"></script>
```

**Styles:**

`<link rel="stylesheet" href="https://unpkg.com/browse/tippy.js@6.2.5/dist/tippy.css">`

This works from a CSP point of view since I do not have anymore warning in the console. However, tippy seems to not work properly anymore.

Could you please detail the best approach? And also tell if it will work in production?

Thanks for your work by the way, I really like tippy!

**PS:** forgot to mention that I add to download tippy.css instead of using the cdn since I had two warnings:

1. Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://unpkg.com/browse/tippy.js@6.2.5/dist/tippy.css".
localhost/:53 

2. Cross-Origin Read Blocking (CORB) blocked cross-origin response https://unpkg.com/browse/tippy.js@6.2.5/dist/tippy.css with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by atomiks** [comment]
You just have the wrong link.

>https://unpkg.com/**browse**/tippy.js@6.2.5/dist/tippy.css

Correct link: https://unpkg.com/tippy.js@6.2.5/dist/tippy.css
