### ISSUE TITLE
Wrong position with followCursor: true & mousemove handler

### ISSUE THREAD

**Issue by usb248** [atomiks/tippyjs#825]
## Bug description

Tooltip wrong position on first page load, just see
![bug](https://user-images.githubusercontent.com/7659927/88655408-ffb34300-d0ce-11ea-9c53-ac485c4596b9.jpg)

## Reproduction

Put the mouse cursor on blue area (without moving) during intialisation page
CodePen link: https://codepen.io/usb248/pen/WNrZpMN

The tooltip should be placed near of the cursor and not at top left of triggerTarget

EDIT: Same effect if i leave the browser tab and if i come back in

**Comment by atomiks** [comment]
Seems to happen on Firefox only? Chrome works correctly.

**Comment by usb248** [comment]
Not tested in Chrome 🤷🏻‍♂️.  Thanks for your reactivity.

**Comment by usb248** [comment]
@atomiks , why followCursor doesnt' listen touchmove listener ? 🤔

**Comment by atomiks** [comment]
follow**Cursor** not follow**Finger** 🤷‍♂️
