### ISSUE TITLE
Content function for dynamic content

### ISSUE THREAD

**Issue by Mycl95** [atomiks/tippyjs#826]
## Problem

When using a function for the content that function gets called only once so I have to use the setContent method for dynamic content. 

## Solution

It would be very handy if that content function would get called everytime before the tooltip shows up to generate dynamic content without having to set it manually each time.

**Comment by atomiks** [comment]
This can be replicated with a plugin.

```js
const enhancedContentFunction = {
  fn: (instance) => ({
    onShow() {
      if (typeof instance.props.content === 'function') {
        instance.setContent(instance.props.content(instance.reference));
      }
    }
  })
};

// ...


tippy(targets, {
  plugins: [enhancedContentFunction]
});
```

**Comment by drziskind** [comment]
> This can be replicated with a plugin.
> 
> ```js
> const enhancedContentFunction = {
>   fn: (instance) => ({
>     onShow() {
>       if (typeof instance.props.content === 'function') {
>         instance.setContent(instance.props.content(instance.reference));
>       }
>     }
>   })
> };
> 
> // ...
> 
> 
> tippy(targets, {
>   plugins: [enhancedContentFunction]
> });
> ```

For future visitors...
If you want the function to fire on every hover you'll have to reference the function in another property and set the content like this:

```js
const enhancedContentFunction = {
  fn: (instance) => ({
    onShow() {
      if (typeof instance.props.dynContent === 'function') {
        instance.setContent(instance.props.dynContent(instance.reference));
      }
    }
  })
};

tippy(targets, {
  dynContent: () => Math.random().toString(36).substring(7),
  plugins:[enhancedContentFunction]    
});

```
otherwise your function reference gets clobbered with the text result and only gets called on the first hover
