### ISSUE TITLE
Lost event 

### ISSUE THREAD

**Issue by rafaelgfirmino** [atomiks/tippyjs#827]
Hi !

I am trying to use tippy.js with vue.js but when I try to hide an element the event is lost and I cannot add it further. I tried using updated to update the tippy.js instance but to no avail.

You can see in this example:
https://tzizq.csb.app/

**Comment by atomiks** [comment]
The problem here is mainly with the way it's being wrapped with Vue I think, I would recommend using a Vue wrapper for Tippy, because there's some things missing like cleanup of the instances, etc.
