### ISSUE TITLE
Placement + followCursor

### ISSUE THREAD

**Issue by mhaidamashko** [atomiks/tippyjs#828]
When I set these two props as 
```
{
  placement: 'right',
  followCursor: true,
}
```
Expect: Tooltip will be rendered at the right side of the cursor.
Result: Tooltip always rendered above the cursor ignoring `placement`.

How I can get what I expect?
Any ideas?

Thank you for your great work.

**Comment by usb248** [comment]
I have same options and it works. Show your codepen for help

**Comment by mhaidamashko** [comment]
I think problem with esm module (when you are using followCursor as plugin)
https://atomiks.github.io/tippyjs/v6/plugins/#modules-esm 
```
import tippy, {followCursor} from 'tippy.js';

tippy(targets, {
  followCursor: true,
  plugins: [followCursor],
});
```
And you are right when I've reproduced it with CDN(when it's one bundle) in Codepen it have been worked fine.
I'm not sure is it possible to use esm in Codepen or similar services?

**Comment by mhaidamashko** [comment]
Okay, I've checked it again and it works fine. Thank you.
