### ISSUE TITLE
Material. Tippy not working on mat-label in mat-form-field

### ISSUE THREAD

**Issue by davayd** [atomiks/tippyjs#829]
## Bug description

Hi. 
Tooltip not working when mouse hover on question-icon in mat-label.
![image](https://user-images.githubusercontent.com/17270614/89342364-59a5a100-d6ab-11ea-8cf7-3777854c3f87.png)

## Reproduction

Stackblitz link: https://stackblitz.com/edit/angular-rs55xg

**Comment by atomiks** [comment]
It's probably because the element doesn't have pointer events or is blocked somehow.
