### ISSUE TITLE
Singleton with AJAX Loading

### ISSUE THREAD

**Issue by sparanoid** [atomiks/tippyjs#830]
## Bug description

It seems Singleton with AJAX loading doesn't work well together. 

## Reproduction

CodePen link: https://codepen.io/sparanoid/pen/BaKaLYM

**Comment by atomiks** [comment]
This is because the `onShow` call needs to be in the singleton, not the individual tippy instances

**Comment by Dreanad** [comment]
Hey there, how can i access the current instance ? i need to access dataset property for an ajax call on each when mousenter (onShow)

**Comment by leeovery** [comment]
Was this issue ever solved?

I have content being fetched inside the onshow event handler. But ofc when those tippy instances are passed into a singleton, the onshow events on the children don't get called. 

Wondering if there's a neat way around it?
