### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by xreider** [atomiks/tippyjs#833]
Hello! I want to import themes, but your link is to download animations 
Screenshot https://ibb.co/58JwY8n
https://atomiks.github.io/tippyjs/v6/themes/

I need CDN link for themes. Thank you

**Comment by atomiks** [comment]
It's just an example... you put `/themes` instead of `/animations` with the right file name.

**Comment by xreider** [comment]
https://unpkg.com/tippy.js@6.2.6/themes/light.css
