### ISSUE TITLE
Tooltips get triggered by accident on mobile

### ISSUE THREAD

**Issue by Trunksome** [atomiks/tippyjs#834]
Hey there,

I use "touch={["hold", 500]}" to make sure showing the tippy requires a long press on touch devices. This is the behaviour I want, there is one problem though: while scrolling, the tooltip often gets triggered just because the user scrolls above a certain button. This is quite confusing and does not look good.

What I would like to do is "cancel" the 500ms hold behaviour if the user scrolls (at all, or maybe with a minimal threshold).
Is there any way for me to achieve that?

Thanks in advance! Loving the library by the way. 👍

**Comment by atomiks** [comment]
Probably a bug, a video screencast would help!
