### ISSUE TITLE
The Tooltip does not change its position after its contents change

### ISSUE THREAD

**Issue by hstaniszewski** [atomiks/tippyjs#835]
Hi, tippy.js is a great plugin!

I have the following problem. I am using the Vue framework. The content of my tooltips is dynamic and its dimensions change. The Tooltip, unfortunately, does not recalculate its position after its content changes.

To visualize my problem, I created the following fiddle:
[https://jsfiddle.net/bmptz4sy/15/](https://jsfiddle.net/bmptz4sy/15/)

Hover over the text to show the tooltip and then click on the button to add more lines. Tooltip stays at the same position but it shouldn't. Only after the tooltip is displayed again, its position changes.

**Comment by dzabrzenski** [comment]
You can do that this way: 

https://jsfiddle.net/vkje34tf/

**Comment by hstaniszewski** [comment]
Thank you Darius! Looks like the solution to my problem.
