### ISSUE TITLE
support runtime class prefix

### ISSUE THREAD

**Issue by zhaoyao91** [atomiks/tippyjs#836]
## Problem

We've built a component based on tippy and customized styles by selecting tippy classes under a namespace. But he end application has already been using tippy and loaded the default theme, but as it's global, it poluted  our component. We can't force our user to refactory their app, so we have to proctect our component.

## Solution

I found this lib currently support built time prefix. I hope it could be runtime so we can set prefix of tippy in our component lib.

**Comment by atomiks** [comment]
You can use headless tippy instead.
