### ISSUE TITLE
tippy doesn't work on any element / selector unless the selector is *

### ISSUE THREAD

**Issue by BHNowaru** [atomiks/tippyjs#837]
I'm working on creating an electron app (which doesn't use webpack because webpack SUCKS), and I imported tippy and it refuses to work on any specified element / selector unless it uses the wildcard selector, which then it appears graciously on any object. It doesn't even work on a blank page with a `div` in the middle. 

Any ideas? :Q

**Comment by atomiks** [comment]
Unfortunately I'm not sure sorry
