### ISSUE TITLE
Is there any way to load Tippy in the head? (interaction with Turbolinks)

### ISSUE THREAD

**Issue by robertdrakedennis** [atomiks/tippyjs#838]
Hi there! I use tippyjs with Laravel and a front-end Js package called Turbolinks, when using Turbolinks I'm recommended to keep all my js in the head, I'm not using Vue or React for Tippy, and was mainly wondering if there is a way to initialize Tippy when its called in a script tag in the head. The reason I'm asking this is I use the CDN for it and call ``tippy(...)`` in the footer, however this doesn't actually work when it's called / initialized in the head. Am I missing some sort of interaction or is this mainly just not the way I'm supposed to be adding this? Thanks for any suggestions.

**Comment by atomiks** [comment]
You'd need a `DOMContentLoaded` event listener to wait for the elements to load I think
