### ISSUE TITLE
Use style field in package.json

### ISSUE THREAD

**Issue by seahindeniz** [atomiks/tippyjs#839]
## Problem

This is the way to import the CSS file, which is kind of ugly because of the relative path
```scss
@import 'tippy.js/dist/tippy.css';
```

## Solution

Using the `style` field in package.json file like this
```jsx
{
  "style": "dist/tippy.css",
  ...
  "version": "6.2.6"
}
```

will allow importing style file in this way
```scss
@import "~tippy.js";
```

**Comment by atomiks** [comment]
There's a bunch of other CSS files that can be, or need to be, imported as well though, so imo for consistency it should be left as it is.
