### ISSUE TITLE
Can I remove the white space on the right of the tooltip?

### ISSUE THREAD

**Issue by Idkw13** [atomiks/tippyjs#840]
Just hover on the button
https://codepen.io/smio/pen/RwaoNby

**Comment by atomiks** [comment]
Yes, see Popper's [preventOverflow#padding](https://popper.js.org/docs/v2/modifiers/prevent-overflow/#padding).

You'd put this in a `popperOptions` prop:

```js
popperOptions: {
  modifiers: [
    {
      name: 'preventOverflow',
      options: {
        padding: 0, // no padding
      },
    },
  ],
}
```
