### ISSUE TITLE
Mount but not show

### ISSUE THREAD

**Issue by avele** [atomiks/tippyjs#845]
Hello

Is there a way I can mount tippy on create without showing it?

My case is - I need to access mounted DOM right after tippy creation, but I dont need tippy to be in active/visible state.

**Comment by atomiks** [comment]
I guess you can use some CSS to keep it hidden while it's showing.

**Comment by avele** [comment]
> I guess you can use some CSS to keep it hidden while it's showing.

Yeah, I know, but I also want to prevent all the code associated with showing to run (like adding event listeners on document to detect outside tippy click).
