### ISSUE TITLE
forced reflow while executing JavaScript took xx ms

### ISSUE THREAD

**Issue by gloomydumber** [atomiks/tippyjs#848]
real-time data by API (2 seconds renewal) is marked on my web's table cell
when i applied tippyjs on table cells,
refreshed page is no problem with tippyjs pop-up at first,
but as time goes by, there is lag with loading tippyjs pop-up
and chrome console message me 'forced reflow while executing JavaScript took xx ms'

is there any solution?

**Comment by atomiks** [comment]
Hi, a repro is needed to help debug
