### ISSUE TITLE
Library does not remove <title> tag for <svg>

### ISSUE THREAD

**Issue by artyomtrityak** [atomiks/tippyjs#85]
[Spec](https://www.w3.org/TR/SVG/struct.html#__svg__SVGDocument__title)

Titles are embedded in SVG as a tag i.e.

```html
 <svg><title>Here is the title</title>...</svg>
```

So library needs to remove / add it on hover same way it does it for non-svg titles.

P.S. I made some local changes for my project, are you interested in PR about this?

**Comment by atomiks** [comment]
>P.S. I made some local changes for my project, are you interested in PR about this?

That would be nice, thanks!

**Comment by artyomtrityak** [comment]
i'm still on this, will submit fix within a week

**Comment by atomiks** [comment]
v3 doesn't use title anymore, so this will no longer be a problem.
