### ISSUE TITLE
Overlapping when multi tippies are appeared on the screen

### ISSUE THREAD

**Issue by caliskanmu** [atomiks/tippyjs#850]
Hello, I need to show multi tippy elements on the page at the same time. But the problem is taht there is an overlapping when two of them are close to each other. Is there a way to solve this?

I want to show multi tippy elements but I wanna see all contents at the same time as well. Thank you.

![tippy_overlap](https://user-images.githubusercontent.com/9104418/91644455-cb6fd100-ea44-11ea-9712-8eba6c875e43.PNG)

**Comment by atomiks** [comment]
It's probably possible if you wrote your own popper modifier that detected collisions with other tippies.

**Comment by caliskanmu** [comment]
> It's probably possible if you wrote your own popper modifier that detected collisions with other tippies.

Unfortunately I have limited time to prepare my project. It looks a bit complicated which will take long time to detect and reposition tippies for limited time. But if this is not possible I may need to think other ways to show.

Also if it is possible to solve by modifying popper js, I may need to open an issue in popper js. Thanks for the idea.

**Comment by atomiks** [comment]
Yeah I think it's a really complex problem though, no one has written one for Popper yet.
