### ISSUE TITLE
Prevent tooltip to overflow on other elements

### ISSUE THREAD

**Issue by AncaBucalaete** [atomiks/tippyjs#851]
Hi,
I have a button with a tippy tooltip. The tippy content might be very small or pretty big, can be sometimes larger then my screen so I'll need to scroll down my page to see the end of it. I problem I have is that I have a menu bar on the upper side and it needs to be visible all the time, so the tooltip should never overflow that element.   
Do you have any suggestions for me?

Thanks

**Comment by atomiks** [comment]
You can use Popper's `preventOverflow` modifier with a `padding` object that specifies a `top` property with a value matching the height of the menu bar.

https://popper.js.org/docs/v2/modifiers/prevent-overflow/
