### ISSUE TITLE
interactiveDebounce. The tooltip doesn't hide if you keep moving the mouse

### ISSUE THREAD

**Issue by Denhai** [atomiks/tippyjs#856]
## Bug description

`mousemove` events prevent the tooltip from closing. Even when they're outside the button. See the video:
![demo gif](https://user-images.githubusercontent.com/10227167/92998087-0995e600-f557-11ea-8a5d-669941d751b0.gif)

## Reproduction

CodePen link: https://codepen.io/denhai/pen/LYNmJdW

**Comment by atomiks** [comment]
That's the purpose of it.

**Comment by Denhai** [comment]
Oh ok. Hmm, I don't know when I'd use that.

When the user moves their mouse from the button to the tooltip, if they're inprecise and the mouse briefly slips outside the interactive area, I want the tooltip to stay open.

That's what I thought this feature was for. Is there another a way?

**Comment by Denhai** [comment]
I don't see why moving the mouse around in some random corner of the page should keep it open lol.

Does that make sense? I can do a PR.

**Comment by atomiks** [comment]
Yeah I guess

**Comment by atomiks** [comment]
> When the user moves their mouse from the button to the tooltip, if they're inprecise and the mouse briefly slips outside the interactive area, I want the tooltip to stay open.

This is what the `interactiveBorder` prop is for though, which is spacial not temporal related.

Sorry but I didn't really read properly as I've been busy 😬
