### ISSUE TITLE
Show one tooltip on hover + and another different tooltip on click (interactive)

### ISSUE THREAD

**Issue by guivr** [atomiks/tippyjs#857]
Hi! How can I show a normal tooltip on hover (explaining what clicking would do) then show a different tooltip (dropdown, HTML content, etc) when triggered by a click? Is it possible?

**Comment by atomiks** [comment]
You can add separate tippy instances to the same element yes

**Comment by guivr** [comment]
Hi, atomiks! Thank you so much for your attention.

I've tried that... If I use:

```
<div data-copy-tippy><i class="cssscan-fas cssscan-fa-copy cssscan-copy-pinned"></i></div>
```

then

```
tippy.delegate('body', {
  target: '[data-tippy-content]',
  followCursor: true,
  plugins: tippy.followCursor,
  arrow: false
});
```

and

```
tippy.delegate('body', {
  target: '[data-copy-tippy]',
  interactive: true,
  content: copyDropdown.outerHTML,
  allowHTML: true,
  appendTo: document.body,
  theme: 'cssscan-tippy-with-dropdown',
  trigger: 'click',
  offset: [0, 15],
});
```

only the first tooltip is enabled.

How can I fix this? Am I doing it wrong?

**Comment by atomiks** [comment]
I believe delegates only work for 1 instance

**Comment by guivr** [comment]
:( Ok. Thanks for the information!
