### ISSUE TITLE
Multiple instances with different 'trigger' option for one element

### ISSUE THREAD

**Issue by v3il** [atomiks/tippyjs#86]
Hi. Is it possible to create 2+ instances for one element? For example, I want to use default functionality of tooltips (show on hover) and at the same time I want to create another popover and show it on click.
I think, it's possible with `trigger: 'manual'`, any cases with default functionality?

**Comment by atomiks** [comment]
Demo: https://codepen.io/anon/pen/rzpzJe?editors=1010

You'll need to set the title attribute manually since tippy removes it after an instance is created
