### ISSUE TITLE
Tippy with dynamic content that stays present in the DOM

### ISSUE THREAD

**Issue by sn3p** [atomiks/tippyjs#868]
I'm trying to create a Tippy instance with dynamically populated content generated by a [Phoenix](https://www.phoenixframework.org/) [LiveView](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html).
The LiveView is basically a container which is dynamically updated by the backend (via WebSockets). 

This means:

1. The content needs to be present in the DOM at all times, both when Tippy is shown or hidden.
2. The content has bindings and listeners so cloning or injecting HTML will not work afaik.

Is there a way to achieve this using Tippy?

Sample of my code:

#### Template

```eex
<button class="target">notifications</button>

<div class="dropdown" style="display: none;">
  <%= live_render(@conn, NotificationsLive, session: %{"user_id" => user_id}) %>
</div>
```

#### JavaScript

```js
const target = document.querySelector(".target");
const dropdown = document.querySelector(".dropdown");

dropdown.style.display = "block";

tippy(target, {
  content: dropdown,
  interactive: true
});
```

**Comment by sn3p** [comment]
The only workaround I can think of is forcing the tooltip to always remain "open":

```js
tippy(target, {
  // ...
  trigger: "manual",
  showOnCreate: true,
  hideOnClick: false
});
```

And doing the toggling/transitions manually.
But this would also mean I lose the build in features like close on click outside.

**Comment by Sandburg** [comment]
Hey @sn3p, did you find a way to keep the tooltip in the DOM?

**Comment by sn3p** [comment]
@Sandburg nope unfortunately not, still looking for it.
If you find it please let me know :)

**Comment by sn3p** [comment]
@atomiks do you have any ideas on how this can be achieved?

**Comment by KubaJastrz** [comment]
I believe this line from the default template is responsible for removing `content` from the DOM: https://github.com/atomiks/tippyjs/blob/38caf47592f37cfec6fbb8c2f6220df8ccc1025c/src/template.ts#L40

Maybe if you could use a custom `render` prop then it would work? Here are docs for [headless tippy](https://atomiks.github.io/tippyjs/v6/headless-tippy/).

**Comment by atomiks** [comment]
I think the simplest option here is to move the content to `document.body` (or some other container) in `onHidden`, then move it back into the tippy `onShow`.

```js
const target = document.querySelector(".target");
const dropdown = document.querySelector(".dropdown");

dropdown.style.display = "block";

tippy(target, {
  content: dropdown,
  interactive: true,
  onHidden() {
    document.body.append(dropdown);
  },
  onShow({popper}) {
    popper.firstElementChild.append(dropdown);
  }
});
```

`onHidden` gets called after the tippy has been removed from the DOM but this should happen sync, it might cause an issue though.

**Comment by dwarfmondo** [comment]
@sn3p I'm dealing with a similar issue. Would you mind sharing how you solved this? Thanks!

**Comment by sn3p** [comment]
Hey @dwarfmondo, this is what I did ([working demo](https://codepen.io/snap/pen/LYzBGPx)). Hope it helps!

```js
const target = document.querySelector(".target");
const dropdown = document.querySelector(".dropdown");
const content = document.querySelector(".content");

tippy(target, {
  content: dropdown,
  onShow: () => {
    // Move content to the dropdown on show.
    dropdown.append(content);
  },
  onHidden: () => {
    // Move content outside the dropdown on hide.
    // This way it remains present in the DOM so it can receive updates.
    document.body.append(content);
  },
});
```

```html
<button class="target">Hover me</button>
<div class="dropdown"></div>
<div class="content">Dynamic content</div>
```

```css
.content {
  display: none;
}

.dropdown .content {
  display: block;
}
```

**Comment by dwarfmondo** [comment]
@sn3p Perfect. Thank you!!!

**Comment by msykes** [comment]
@sn3p Thanks for following up with the solution, great workaround, works perfectly for my scenario.
