### ISSUE TITLE
Tooltip not showing unless scroll to top of window

### ISSUE THREAD

**Issue by gregg-cbs** [atomiks/tippyjs#874]
## Bug description
I import tippy js and css as recommended in the doc.

I add appropriate triggers and instantiation of tippy.

When I hover on the toolip icon to show the tooltip, nothing shows. 
But when I scroll so the tooltip icon is at the top of the window, and hover on it, the tooltip shows.

Tooltip gets appended to the DOM but it is not visible, the transform is "-1080px" whenever the tooltip icon is not near the top of the browser window.

## Reproduction
Browser: Mozilla Firefox Developer 84.0b2 (64-bit)

**SCRIPTS**
```
script(src="https://unpkg.com/@popperjs/core@2")
script(src="https://unpkg.com/tippy.js@6")
```

**JS**
```
tippy('[data-tippy-content]', {
  theme: 'light-border',
  content: 'We use this to validate that your company is participating in this programme.',
  allowHTML: true
});
```

Screen recording of the issue:
[Screen Recording 2020-11-19 at 12.31.04 pm.mov.zip](https://github.com/atomiks/tippyjs/files/5566282/Screen.Recording.2020-11-19.at.12.31.04.pm.mov.zip)

**Comment by gregg-cbs** [comment]
I removed bootstrap and any other script / styling till I only had Tippy.
And then this was the effect.
[tippy_issue_2.mov.zip](https://github.com/atomiks/tippyjs/files/5566403/tippy_issue_2.mov.zip)

^ I am unable to replicate this in a sandbox. But this behaviour is strange.

**Comment by atomiks** [comment]
Positioning won't work if `<html>` has `position` styling other than static

**Comment by gregg-cbs** [comment]
It seems to be working today and I have changed nothing.
Very confusing.

But thanks for the response.
