### ISSUE TITLE
How do i stop tippy from overflowing past the window!?

### ISSUE THREAD

**Issue by gregg-cbs** [atomiks/tippyjs#875]
For the love of God, how can this not be default functionality!
Can you please tell me how to stop the tooltip from flowing outside of the window boundary?

<img width="536" alt="Screenshot 2020-11-20 at 11 44 46 am" src="https://user-images.githubusercontent.com/57114335/99786514-44079a80-2b27-11eb-8865-eb5dfb0d85d9.png">
**Using this script**
```
https://unpkg.com/tippy.js@6
```

1. **When using cdn, this does not work.**
```
tippy.setDefaults({
  popperOptions: {
    modifiers: {
      preventOverflow: {
        boundariesElement: 'window'
      }
    }
  }
})

// tippy.setDefaults is not a function
```

2. **None of these work popper settings work:**
```
tippy('[data-tippy-content]', {
  appendTo: () => $('main')[0],
  theme: 'light-border',
  allowHTML: true,
  placement: "right-start",
  offset: [0, 10],
  popperOptions: {
    modifiers: [
      {
        name: 'preventOverflow',
        options: {
          // mainAxis: false, // true by default
          // rootBoundary: 'document',
          // altBoundary: true,
          // tether: true,
          // escapeWithReference: false,
          // boundary: customBoundary,
        },
      },
    ],
  }
});
```

I expect this tooltip to fit to the right and if it cannot, then fit underneath.
But it seems tippy / popper do not care about the window and make the tooltip as wide as it wants to be.

**Comment by atomiks** [comment]
You need to use the `flip` modifier with the `fallbackPlacements` option
