### ISSUE TITLE
open on click, close on mouseleave

### ISSUE THREAD

**Issue by artivilla** [atomiks/tippyjs#879]
Not sure why the tipper shows again right after hiding itself. Is this markup valid?
```
    tippy('[data-tippy-content]',
        {
            allowHTML: true,
            trigger: 'click mouseleave',
            onTrigger(instance, e) {
                if (e.type === 'mouseleave') {
                    instance.hide();
                }
            },
        });
```

**Comment by atomiks** [comment]
Well the problem here is you've put a "leave" event as the trigger (`mouseleave`), while triggers should only reference "enter" events.

**Comment by nbaleli-w** [comment]
I'd like to also know how to achieve the 'open on click, close on mouseleave ' ?

**Comment by julioolvr** [comment]
Same here. If I'm reading this code correctly then it seems that closing on `mouseleave` only happens when `mouseenter` is used as a `trigger`?

https://github.com/atomiks/tippyjs/blob/cac8a1260cab174d8442efa1bc1d973e298d3373/src/createTippy.ts#L157-L164

**Comment by atomiks** [comment]
You can dynamically change the trigger with lifecycle hooks:

```js
tippy(targets, {
  content: 'tooltip',
  trigger: 'click',
  onShow({setProps}) {
    setProps({trigger: 'mouseenter'});
  },
  onHide({setProps}) {
    setProps({trigger: 'click'});
  }
});
```

@julioolvr that code is for cursor leaving the popper during a `delay` and is unrelated
