### ISSUE TITLE
Add ES-browser build

### ISSUE THREAD

**Issue by mario-aleo** [atomiks/tippyjs#880]
## Problem

Every build option that we have has the `process` validation, so if you try to import tippy.js to a project that is built for modern browsers and so it doesn't have a building step, it's going to fail because `process is not defined at validation.ts:46`.

## Solution

It would be nice to have a `.mjs` output that does not transpile ES2015+ code and removes all references to process by assuming it is in a production environment.
This approach has been done at Redux [reduxjs/redux#3143](https://github.com/reduxjs/redux/pull/3143) and, as stated there by Tim, is similar to the one of Vue [vuejs/vue#7110](https://github.com/vuejs/vue/pull/7110).

**Comment by atomiks** [comment]
Are you able to create a PR?

Also, can't you polyfill `process` in the browser? This would allow you to retain the warning messages which are helpful when using the lib, although the file size remains large with the warnings I suppose. You could also use the UMD version instead.

**Comment by IanVS** [comment]
This would be great.  The ES build could also use `import.meta.env` instead of `process.env` to be compatible with modern build tools like astro, snowpack, and vite, and I believe webpack 5 too.
