### ISSUE TITLE
Question: how to prevent flip after shown?

### ISSUE THREAD

**Issue by zhaoyao91** [atomiks/tippyjs#884]
After searching I found a `flipOnUpdate` prop in v5 but not in v6. How to implemenet this feature: allow flip on show up but do not flip anymore on scrolling when it's shown.

**Comment by atomiks** [comment]
You could stop the scrolling event listeners from firing. This does have the drawback of not updating while scrolling but usually this doesn't matter. v5 handled it in a kind of advanced way to account for this which you could likely code yourself

```js
tippy(ref, {
  popperOptions: { 
    modifiers: [
      {name: 'eventListeners', options: {scroll: false}}
    ]
  }
});
```

**Comment by zhaoyao91** [comment]
this code snippet doesn't work as expect. the popper should move while scrolling, only without flipping

**Comment by atomiks** [comment]
That's what I mentioned, but the way v5 handled it was to actually change the placement and then disable flipping.

```js
tippy(ref, {
  placement: 'right',
  onMount({popperInstance}) {
    popperInstance.setOptions({
      // this is the flipped placement (if it is flipped)
      placement: popperInstance.state.placement,
      modifiers: [
        {name: 'eventListeners', options: {scroll: false}}
      ]
    });
  },
  onHidden({popperInstance}) {
    popperInstance.setOptions({
      // back to the original one
      placement: 'right',
      modifiers: [
        {name: 'eventListeners', options: {scroll: true}}
      ]
    });
  }
});
```

**Comment by zhaoyao91** [comment]
Thanks for this idea. setting popper directly has some problem, I replaced it with `tippyInstance.setProps`. a simple version of solution works yet not perfect since remember the placement and other modifiers need more codes.

**Comment by atomiks** [comment]
For those wanting an easy cut-paste plugin:

```js
export const disableFlipAfterScroll = {
  name: "disableFlipAfterScroll",
  defaultValue: true,
  fn({ props }) {
    const originalPlacement = props.placement;
    const originalPopperOptions = props.popperOptions;

    return {
      onMount({ setProps, popperInstance }) {
        setProps({
          placement: popperInstance.state.placement,
          popperOptions: {
            ...props.popperOptions,
            modifiers: [
              ...(props.popperOptions.modifiers || []),
              {
                name: "flip",
                enabled: false,
              },
            ],
          },
        });
      },
      onHidden({ setProps }) {
        setProps({
          placement: originalPlacement,
          popperOptions: originalPopperOptions,
        });
      },
    };
  },
};
```

**Comment by mpereira** [comment]
@atomiks thanks for Tippy.js, and for this expedient plugin! It works perfectly.
