### ISSUE TITLE
How can I get one button to trigger multiple targets?

### ISSUE THREAD

**Issue by lukejames1111** [atomiks/tippyjs#886]
I am trying to make it so that there is one button, which when clicked will show multiple tooltips at the same time. Is this possible?

**Comment by atomiks** [comment]
You use `triggerTarget: button` for each of the `tippy()` calls/instances.

**Comment by lukejames1111** [comment]
I've tried that approach, but for some reason it won't fire;

`
<span class="btn btn-success show-tooltip">test</span>

<span class="test-one" data-tippy-content="This is tooltip">Text</span>
<span class="test-two" data-tippy-content="This is another tooltip">Text</span>

<script>
tippy('.test-one', {
    triggerTarget: '.show-tooltip'
});

tippy('.test-two', {
    triggerTarget: '.show-tooltip'
});
</script>
`
