### ISSUE TITLE
Docs should include default values of props

### ISSUE THREAD

**Issue by silverwind** [atomiks/tippyjs#887]
## Problem

The default values for props are nowhere visible on the v6 docs, they were present on v5 in the table.

https://atomiks.github.io/tippyjs/v6/all-props/
https://atomiks.github.io/tippyjs/v5/all-props/

I just had to dig into the source to find out that `hideOnClick` defaults to `true`.

## Solution

Add the default value on the [header](https://atomiks.github.io/tippyjs/v6/all-props/#hideonclick), e.g. `hideOnClick (default: true)`.

**Comment by atomiks** [comment]
Every example has the default as the first line.

<img width="286" alt="Screen Shot 2020-12-18 at 7 25 14 pm" src="https://user-images.githubusercontent.com/22450188/102591833-c30fe300-4166-11eb-81fe-09460e224aa4.png">

**Comment by silverwind** [comment]
Indeed, it's there. I didn't consider looking at example code because because when I'm looking for usage, I generally visually skip over example code.
