### ISSUE TITLE
Prevent placement change?

### ISSUE THREAD

**Issue by dornstein** [atomiks/tippyjs#889]
I'm using tippy for flyouts on items in a left nav.  Normally the placement is on the right of the left nav items, but when the browser window is narrow enough the placement jumps to the left side of the reference element.  I'd like to prevent this (knowing that the tip/popper will be clipped).  I've been reading through the docs for both tippy and popper, but can't figure out how to get this behavior.  Any guidance?

**Comment by atomiks** [comment]
```js
popperOptions: {
  modifiers: [{ name: 'flip', enabled: 'false' }]
}
```
