### ISSUE TITLE
Can't get multiple tooltips to work

### ISSUE THREAD

**Issue by Hapistorique** [atomiks/tippyjs#89]
Hi,

I'm trying to use this library to add tooltips via an API on elements with a specific class.

The issue is that all examples on the documentation are using IDs, so I have no idea how to get it to work with multiple elements.

Here is an example of what I've tried based on the example found in the doc : https://codepen.io/Hapistorique/pen/zdLpZa

Should I do a forEach? What happens if you only use one 'tip' variable?
This isn't explained at all, unless I've missed it

It only works with the very last element and it's really buggy

**Comment by atomiks** [comment]
The documentation explains that you can just use a CSS selector. So for multiple elements with a class name of "example", you just do:

```javascript
tippy('.example')
```

The AJAX/fetch example there is more complex because it's using a HTML template which gets trickier when you need to clone it rather than use the element directly, etc

**Comment by Hapistorique** [comment]
Yeah sorry, I meant the API/template examples are using IDs and very few are showing how to use classes

I'll try to use your snippet and get it to work with my API

Thanks a lot

**Comment by prattyy** [comment]
i went through the example at  codepen [](https://codepen.io/anon/pen/GEmOQy?editors=0010)
but cant seem to find how to use ajax example with multiple elements
simply duplicating the button element in that example doesnot work
Could you please provide an example

**Comment by atomiks** [comment]
@prattyy I updated the pen to use 2 again.

**Comment by prattyy** [comment]
Thanks for you quick reply

**Comment by prattyy** [comment]
When creating multiple tooltips  this way how do we access the element while initiating the tooltip
for example 
```
<span class="order-tooltip" data-orderid="123456">Order ID 123456</span>
<span class="order-tooltip" data-orderid="454515">Order ID 454515</span>

const tip = tippy('.order-tooltip', {  
  arrow: true,
  html: '#tooltipTemplate',
  onShow() {
    // `this` inside callbacks refers to the popper element
    const content = this.querySelector('.tippy-content')

    if (tip.loading || content.innerHTML !== initialText) return

    tip.loading = true
    console.log($('.order-tooltip').data('orderid')) // This is not working 
    var orderid = $(this).data('orderid');
    var url = "/fetch_position_tooltip?" + $.param({orderid: orderid})

    fetch(url).then(resp => resp.json()).then (responseJSON =>{

      content.innerHTML = responseJSON
      tip.loading = false
    }).catch(e => {
        console.log(e)
      content.innerHTML = 'Loading failed'
      tip.loading = false
    })
  })
```
how to access the "data" attribute for each of the span element when instantiating the toolitip ?

**Comment by atomiks** [comment]
`this._reference` refers to the span element. 
`this` is the tooltip popper element.
