### ISSUE TITLE
HTML Content: Dropdown: Example-Code?

### ISSUE THREAD

**Issue by nicmare** [atomiks/tippyjs#890]
Hey,
Where do i find the corresponding example code please?
https://atomiks.github.io/tippyjs/#html-content
i want to integrate the dropdown in my project

**Comment by keeev** [comment]
You probably found it already but there's even a [section in the Documentation](https://atomiks.github.io/tippyjs/v6/html-content/) for that.

**Comment by nicmare** [comment]
> You probably found it already but there's even a [section in the Documentation](https://atomiks.github.io/tippyjs/v6/html-content/) for that.

yes i know this but i want to know how to insert the github like emoji interaction

**Comment by KubaJastrz** [comment]
it's here https://github.com/atomiks/tippyjs/blob/38caf47592f37cfec6fbb8c2f6220df8ccc1025c/website/src/components/examples/Dropdown.js
