### ISSUE TITLE
Nesting issue with data-template

### ISSUE THREAD

**Issue by xreider** [atomiks/tippyjs#894]
## Bug description

Nothing happens when I activate nesting in template button with [data-template]
I use that code to activate tippies

```
document.addEventListener('DOMContentLoaded', activateTipites)

function activateTipites() {
  tippy.setDefaultProps({
  theme: 'light',
  arrow: tippy.roundArrow,
  duration: 0,
});

const instance = tippy('[data-template]', {
  content(reference) {
    const id = reference.getAttribute('data-template');
    const template = document.getElementById(id);
    return template.innerHTML;
  },
  trigger: 'click',
  interactive: true,
  allowHTML: true,
  placement: 'bottom-end',
  offset: [13,13],
  appendTo: document.body,

});

window.addEventListener("resize", () => {
  tippy.hideAll()
});
}

```

templates (pug)

```
    div(style='display: none;')
      #menuWrapper
        #menuPC.linksAreBlack
          include ../partials/menu.pug
      #languageSwitcherTemplate
        #languageSwitcher
          a(href=`/zh_en${__URL__}`) zh_en
          a(href=`/zh_ru${__URL__}`) zh_ru
          a(href=`/ru${__URL__}`) ru
          a(href=`/en${__URL__}`) en
```

## Reproduction

I click on **a(data-template="menuWrapper" aria-expanded='true')** and a menu opens. No problem
This menu has **a(data-template="languageSwitcherTemplate" aria-expanded='true')**. I click it and nothing happens.
**a(data-template="languageSwitcherTemplate" aria-expanded='true')** is nested. If I assign **data-template="languageSwitcherTemplate"** for any another visible element, **#languageSwitcherTemplate** will appear.
But I need to activate nested button.

**Comment by atomiks** [comment]
Closing old issues
