### ISSUE TITLE
how do I set target of the 'interactive' prop?

### ISSUE THREAD

**Issue by KutnerUri** [atomiks/tippyjs#895]
The `interactive` prop official responsibility is to allow user interaction with the tooltip. (i.e. hovers and clicks)

The main difference seems to be the location of the popped element:
- `interactive={true}` inserts the tooltip next to the target element.  
![image](https://user-images.githubusercontent.com/5400361/106740840-9be07880-6623-11eb-8775-183578604e34.png)
- `interactive={false}` inserts the tooltip at the end of the body.  
![image](https://user-images.githubusercontent.com/5400361/106740798-8ec38980-6623-11eb-8a2c-48f96c11d6d2.png)

As you can see, this has a side effect of receiving different css rules from the application root. (I opted to apply styles to a `div` rather than the `body`).

Is there a way to specify the insertion point?
Ideally, I could make a something like `<div id="tippy-insertion-root" style={{display: 'none'}} />` without having to change the configuration of Tippy.

**Comment by atomiks** [comment]
`appendTo` does that

**Comment by KutnerUri** [comment]
indeed! thanks!
