### ISSUE TITLE
Stretching the popover to the full width and height of the screen

### ISSUE THREAD

**Issue by msimkunas** [atomiks/tippyjs#897]
Is it possible to detach the popover from its reference element and stretch it to the full width and eight of the screen?

In my use case I'd like to display the popover as a regular popover on wider screens but stretch it to the corners of the display on mobile devices, effectively turning it into a modal window that covers the entire screen. Is this possible?

**Comment by atomiks** [comment]
I'd say you can use media queries and units like `vw/vh` to stretch it on mobile, and it should work without issues
