### ISSUE TITLE
Switch to Rollup for bundle generation

### ISSUE THREAD

**Issue by FezVrasta** [atomiks/tippyjs#9]
Webpack is awesome to bundle apps, but for libraries Rollup is the recommended bundler because it creates smaller bundles.

I think you should switch to it to reduce the weight of the library, also, you should set `Popper.js` as external dependency in the Rollup configuration, doing so people will have to manually include Popper.js and Tippy.js, with the ability to decide which version to use.

**Comment by FezVrasta** [comment]
You can basically copy what I do in Popper.js, the same config should be fine.

If you need help let me know and I'll try to dedicate some time on it when I can.

**Comment by atomiks** [comment]
Have switched for v0.4.0
