### ISSUE TITLE
Rollup dependency and Travis tests

### ISSUE THREAD

**Issue by artyomtrityak** [atomiks/tippyjs#90]
1. There is no rollup dependency in project, should it be added? Btw for latest rollup version build does not work, i had to install `0.47.6` so version might be needed.
2. I'm going to automate some tests for this project, are you interested in some kind of automated TravisCI tests runs?
3. To make code consistent i propose to add Eslint as JavaScript linter

**Comment by atomiks** [comment]
Merged, what else needs to be done?

Still need to write way more tests too..

**Comment by artyomtrityak** [comment]
@atomiks right now there are only tests which you can run manually and next step is to set up TravisCI to run tests on master / other branches / pull requests automatically.

Also i think we should set up eslint rules and check code style

Yes, i agree, it would be nice to have more tests. Once everything will be set up it will be easy to add more

**Comment by atomiks** [comment]
Looks like it's "passing" now. Not sure how any of this works since this is my first time, but I really appreciate your help setting it all up. Thanks!

**Comment by artyomtrityak** [comment]
My pleasure!
I really like this project and want to make it even better
