### ISSUE TITLE
Overflow / not-working "top-end" for icon within Webix library

### ISSUE THREAD

**Issue by fendrikat** [atomiks/tippyjs#900]
Hello,
when having a icon about 25px wide on the right end of the screen in a toolbar from Webix, I did not find a way to avoid the tippy with about 200px width overflowing almost completely off the right screen side.

I tried "top-end", which would be perfect solution, but had no success. Also other suggestions, with "strategy" and more did not work. "left" did work, but would than cover the toolbar, which is unwanted.

I solved it for now by setting a padding of about 200px and arrow padding -200 px, but would be great if "top-end" could work also for such cases.

Thank you,

Frank

**Comment by atomiks** [comment]
The positioning engine Popper should handle that automatically without issues. There were recently some bug fixes published, so if you upgrade tippy fresh again, it should reinstall popper as well and maybe help. Otherwise I'm not sure without anything to reproduce or work off of sorry
