### ISSUE TITLE
Clicking link inside target

### ISSUE THREAD

**Issue by NotWhatYouThinkIAm** [atomiks/tippyjs#901]
Hello,

I have a link inside one of my targets that I create a tippy around. It is triggered from a click. Is there a way to not show the tippy instance if the link inside the target is clicked?

```
<div id="test" data-template="test-popup" tabindex="0">
     <a href="https://google.com>link</a>
</div>

tippy("#test")
```

Thanks!

**Comment by atomiks** [comment]
I'm not sure what's being asked exactly. Do you have a CodePen to demonstrate?

**Comment by aabdolla** [comment]
> I'm not sure what's being asked exactly. Do you have a CodePen to demonstrate?

So is there a way to make the tippy not appear if you click a link inside of the trigger element? Here is the CodePen: https://codepen.io/robgarciaert/pen/BaQYBEY

Thanks!

**Comment by atomiks** [comment]
@aabdolla you add a listener to the `<a>` element that calls `event.stopPropagation()` so the event won't trigger the tippy.

```js
document.querySelector('a').addEventListener('click', e => e.stopPropagation())
```
