### ISSUE TITLE
Tippyjs with LitHtml

### ISSUE THREAD

**Issue by Blakeinstein** [atomiks/tippyjs#903]
I have an SPA, with a router loading in html content on a div.
The html content is a cached Template Result using [lit-html](https://lit-html.polymer-project.org/) that is rendered over the page.
Would it be possible to cache tippy as well? Without calling tippy's constructor every time the route changes?

Example:
```html
<div id="#content"></div>
```

```js
import {html, render} from 'lit-html';
import {cache} from 'lit-html/directives/cache.js';
import tippy from 'tippy.js';

...

const html = () => {
	return html`<div data-tippy-content="tooltip data"></div>`;
};

render(cache(html()), content);

tippy(content.querySelectorAll('[data-tippy-content]');
```

maybe render it to a virtual Dom and then just appendChild?

**Comment by atomiks** [comment]
I'm not sure how this lib works. You might be better off asking at their repo

**Comment by Blakeinstein** [comment]
Solved this with delegates!
