### ISSUE TITLE
Incorrect positioning for wrapped span

### ISSUE THREAD

**Issue by xpe** [atomiks/tippyjs#905]
## Bug description

With the cursor over a wrapped span (also called a multiline span), the default tooltip shows up in an incorrect place.

## Reproduction

Moving the cursor over "and get to what's real" looks like this:

<img width="861" alt="jump-misplaced-tooltip" src="https://user-images.githubusercontent.com/4576329/107965207-3cb22a80-6f78-11eb-8ca5-39004b25f80c.png">

CodePen link: https://codepen.io/xpe/pen/yLVMbwp

**Comment by xpe** [comment]
Related ticket #398 (but not fixed)

**Comment by atomiks** [comment]
Use `inlinePositioning` plugin which is available by default in the UMD version (as in the CodePen)

```js
tippy('span', {
  inlinePositioning: true
});
```
