### ISSUE TITLE
Show and hide after clicking

### ISSUE THREAD

**Issue by x4r7** [atomiks/tippyjs#906]
hello im using tippy for show tips for a second on click
the code looks like this
```
      tippy('.copybtn', {
        content: 'Скопировано!',
        trigger: 'click',
        duration: 200,
        delay: 50,
      });
```
is that possible to make it show after click for a few seconds and hide it?

**Comment by x4r7** [comment]
and is it possible to change tip content after click?

**Comment by atomiks** [comment]
Yes it's possible. You can use the `onShow` hook and add a `setTimeout` inside that calls `instance.hide()`

> and is it possible to change tip content after click?

All available in the docs
