### ISSUE TITLE
'followCursor: initial' position does not update if triggered again while shown

### ISSUE THREAD

**Issue by aeroheim** [atomiks/tippyjs#909]
## Bug description

The position of tooltips using `followCursor: initial` do not update if you trigger them again while they are already shown. I ran into this while trying to implement context menus using the `contextmenu` event as my trigger as shown in the examples below. I'm not sure if this is an actual bug though as `contextmenu` isn't listed as a trigger in the docs, but if it is supported then I think the expected behavior would be for the position to update immediately on re-trigger (i.e tooltip should appear at mouse when right-clicking at different spots).

## Reproduction

sandbox: https://codesandbox.io/s/tippy-contextmenu-followcursor-bunhg?file=/src/App.js
codepen: https://codepen.io/aeroheim/pen/ExNwJpM

**Comment by atomiks** [comment]
You're right that `contextmenu` isn't explicitly supported as a trigger. Here's an example of contextmenu on the docs https://atomiks.github.io/tippyjs/v6/misc/#context-menu

**Comment by aeroheim** [comment]
Ah, it looks like I missed that part of the docs. Thanks for the clarification!
