### ISSUE TITLE
Material filling effect example from the documentation not working

### ISSUE THREAD

**Issue by arisolt** [atomiks/tippyjs#910]
Hi, 

As per https://atomiks.github.io/tippyjs/v6/animations/#material-filling-effect, I am copy pasting the code into my script file, but the browser throws this error: 

```SyntaxError: Unexpected identifier 'tippy'. import call expects exactly one argument.```

Any idea what's going wrong?

**Comment by atomiks** [comment]
The syntax shown is for module bundlers not browsers. In the case of a browser you need to link the CSS stylesheets separately (the plugin is already added in the CDN `umd` version).
