### ISSUE TITLE
Set different props in event delegation

### ISSUE THREAD

**Issue by pd4d10** [atomiks/tippyjs#912]
It's good to have [event delegation addon](https://atomiks.github.io/tippyjs/v6/addons/#event-delegation), but there seems no way to set different props in different instances.

How about adding a function prop to do this?

```js
delegate('#parent', {
  target: '.child',
  setInstanceProps(target) {
    // Set different props by the target
  }
});
```

**Comment by atomiks** [comment]
You can use set props as data attributes

**Comment by pd4d10** [comment]
Thanks for the quick reply.

Do you mean data attributes like `data-tippy-content`? It does work, but only for primitive values. For example:

```js
tippy(targets, {
  // string
  content: 'Hello',
  // Element
  content: document.createElement('div'),
  // (reference) => string | Element
  content: (reference) => reference.getAttribute('title'),
});
```

The second and third are not primitive values and do not work in this case.

**Comment by atomiks** [comment]
This can be added as a feature I suppose, so it would allow you to set the props based on the target that was passed in:

```js
delegate('#parent', {
  target: '.child',
  getTargetProps(target) {
    // random content for <div class="random" />
    return target.className === 'random'
      ? {content: () => Math.random()}
      : {};
  }
});
```

**Comment by pd4d10** [comment]
Any updates? I've implemented your proposal [here](https://github.com/bytedance/bytemd/blob/99d232cb30446559059c7fe47482d08eec7b2e74/packages/bytemd/src/delegate.ts), which works fine currently. Perhaps I can send a pull request if needed.

**Comment by atomiks** [comment]
Sorry, I just realized you can use `onCreate()` to achieve the same thing.

```js
delegate('#parent', {
  target: '.child',
  onCreate({reference, setProps}) {
    // random content for <div class="random" />
    setProps({
      content: reference.className === 'random'
        ? Math.random()
        : 'default'
    });
  }
});
```
