### ISSUE TITLE
Wrong positioning for ellipsis inline element

### ISSUE THREAD

**Issue by zhaoyao91** [atomiks/tippyjs#916]
## Bug description

If the reference is an inline element and is truncked by text ellipsis, the position is wrong

![image](https://user-images.githubusercontent.com/3808838/109791253-31841d80-7c4d-11eb-9dd0-246d11bbce63.png)

## Reproduction

https://codepen.io/zhaoyao91/pen/MWbXJVP

**Comment by atomiks** [comment]
I'm not sure why the <span> in the example is stretching to the whole width as if it weren't clipped at 100px, but if you apply it to the outer div it works. It's not possible to fix this because the element is actually that wide and there's no way to detect otherwise.

**Comment by zhaoyao91** [comment]
oh thanks, it works
