### ISSUE TITLE
tippy is breaking angular build which didnt break before

### ISSUE THREAD

**Issue by AsafEini** [atomiks/tippyjs#917]
seems like the tipy.js library is breaking my app which havent been before.
i have attached a screen shot of the error.
![image (1)](https://user-images.githubusercontent.com/19238395/109806474-6da78600-7c2d-11eb-9804-a764f90bfcd9.png)

err in text:

2 import type { Placement, Boundary, RootBoundary, Context } from “../enums”;
              ~
node_modules/@popperjs/core/lib/utils/detectOverflow.d.ts:2:65 - error TS1005: ‘;’ expected.
2 import type { Placement, Boundary, RootBoundary, Context } from “../enums”;
                                                                  ~~~~~~~~~~
node_modules/@popperjs/core/lib/createPopper.d.ts:1:13 - error TS1005: ‘=’ expected.
1 import type { OptionsGeneric, Modifier, Instance, VirtualElement } from “./types”;
              ~
node_modules/@popperjs/core/lib/createPopper.d.ts:1:73 - error TS1005: ‘;’ expected.
1 import type { OptionsGeneric, Modifier, Instance, VirtualElement } from “./types”;


what might be the issue?

**Comment by atomiks** [comment]
Popper updated its TypeScript converter build, you need to update all of your TypeScript related dependencies. This includes type testing, eslint, etc.
