### ISSUE TITLE
Integrating tippy with an AJAX call

### ISSUE THREAD

**Issue by teebling** [atomiks/tippyjs#918]
**Update: see second comment**

Hello :) Looking for some help getting AJAX-loaded HTML content to show in a tooltip when hovering over an `a` element. I've read the tippy [documentation on AJAX tooltips](https://atomiks.github.io/tippyjs/v6/ajax/) but this implementation doesn't seem to play friendly with what I have already.

I have a link on my page like so:

`<a href="/ajax.php?var=apples" class="ajax_link">Apples</a>`

When the user hovers over this link, a (jQuery syntax) ajax call is made:

```
// When mouse enters the link...
$(".ajax_link").mouseenter(function(e) {

    // Declare variable to get the href attribute of this link.
    var link = $(this).attr('href');

    // Make the ajax request to the href in the link, then when PHP script is done, add it to the tooltip div `#tooltip`.
    $.ajax({
      url: link,
      cache: false
    }).done(function( html ) {
    $('#tooltip').html(html);
    });

    return false;
});
```

The PHP script itself connects to and queries a MySQL database with the variable '`apples`' (taken from the link's URL parameter) and the result of the SQL is printed as HTML like this:

```
<div>Fruit size: Small</div>
<div>Fruit color: Red</div>
<div>Fruit shape: Circular</div>
```

As I explained already, this HTML is then added to the div `#tooltip` via jQuery's `.html()`. Right now `#tooltip` is just a static, normal div element on my page that I made for testing the ajax call, which works! Yay! The returned html is printed to the div on my page. _Nota bene_ - tippy hasn't even been installed or anything yet up to this point.

Now comes the part that I'm having trouble with...

I want this `#tooltip` div to be an actual Tippy.js tooltip, with the [followCursor prop](https://atomiks.github.io/tippyjs/v6/all-props/#followcursor) enabled. By combining Tippy's functionality with what I already have, I'd be able to do the following:

> 1. User hovers over the link
> 2. A Tippy tooltip with `followCursor` appears showing some placeholder 'Loading...' HTML (an image to be specific)
> 3. In the background the AJAX call is made
> 4. When the call is done, the HTML returned by the PHP script is added into the tooltip itself using `.html()`.

But doing this doesn't seem so simple at all... here's what I've tried so far:

- [Followed the tippy.js docs for an example ajax tooltip](https://atomiks.github.io/tippyjs/v6/ajax/), and just put my jQuery ajax stuff in the `onShow(instance)` bit. This seemed to destroy the ajax part completely and I don't know why (maybe because it is in jQuery syntax whereas tippy.js is in vanilla JS? Yes - I made sure to load jquery and Tippy before this bit).
- Failing that, I printed the HTML to a hidden `div` like normal, and then tried to get Tippy to grab the HTML from that hidden `div` using Tippy's [Element.innerHTML](https://atomiks.github.io/tippyjs/v6/html-content/#element-innerhtml). It did grab the static HTML from the `div` that was already loaded in the DOM, but not the HTML that had just been added dynamically by ajax for some reason. Maybe Tippy is too quick and grabs the innerHTML of the `div` before the ajax HTML is even there?

So I've had a really good crack at it but I just can't seem to get this implemented. Does anyone have any ideas on where I could go with this?

Many thanks for reading.

**Comment by teebling** [comment]
### Update

So I managed to sort of get it working by doing the following:

```
  $(".ajax_link").mouseenter(function(e) {

    tippy(this, { trigger: 'mouseenter', content: 'loading', followCursor: true, delay: 0, duration: [100, 1000] });

    var link = $(this).attr('href'); //Gets link url

    $.ajax({ //Make the ajax request
      url: link,
      type: "GET",
      cache: true
    }).done(function( html ) {
    $('#tippy-1').html(html);
    });

    return false;
});
```

Which looks good-ish at first. I can see that the tooltip that was generated (`#tippy-1`) has now been populated with the HTML from the ajax request. Here's what it looks like:

![buggy](https://user-images.githubusercontent.com/49092979/109852991-5082af80-7c4d-11eb-9573-985331172690.gif)

But it seems rather slow and buggy. In fact, every time I mouse over the link, it seems that several instances of the tooltip are generated, which probably explains the slowdown:

![several](https://user-images.githubusercontent.com/49092979/109853149-82941180-7c4d-11eb-9dc1-710af59f8da1.gif)

On inspection (having set the delay higher so I could see them in the web inspector), I could see many instances of the tooltip appearing in the DOM: `#tippy-2`, `#tippy-3`, `#tippy-4` and so on. Shouldn't it just generate `#tippy-1` and then leave it be?

I'm also concerned about making the PHP/MYSQL/AJAX request every single time the user mouses over (potentially another reason why it's slow?) - is there any way I could get it to run the ajax call only once, and then on any subsequent `mouseenter`s on the same element cache or store somehow the ajax returned html?

**Comment by teebling** [comment]
### Update 2: solved!

Found out what the issue was eventually. I was calling tippy inside the mouseenter event, so every time the mouse entered the link a new tippy instance was created, leading to the 'multiple tippys being generated' issue I was having.

By putting the tippy stuff outside this event, standalone, it worked correctly. For anyone else who also got into this hole here is how it worked in my final implementation:

HTML:

```
<span class="ajax_catch">
  <a href="/ajax.php?var=apples" class="ajax_link">Apples</a>
</span>

<div  id="template" style="display: none;">
      <div class="d2-tt">
      </div>
</div>

```

jQuery:

```
<script>
  $('body').on('mouseenter', '.ajax_catch', function(e) {

      var link = $(this).find('.ajax_link').attr('href');

      $.ajax({
        url: link
      })
      .done(function( html ) {
        $('.d2-tt').html(html);
      });

      return false;
  });

  $(function() {

    const template = document.getElementById('template');

    tippy('.ajax_catch', {
      content: template.innerHTML,
      allowHTML: true,
      followCursor: true,
      theme: 'tomato',
      arrow: false,
      duration: 200,
      offset: [0, 10],
      placement: 'auto',
      placement: 'auto-start',
      placement: 'auto-end',
      touch: 'hold'
    });

  });
</script>
```

**Comment by beautifulmim** [comment]
It would be awesome if the library provide a simple option to set the URL and abstract the user from handling the events and state management. I consider the way documented (https://tippyjs.bootcss.com/ajax/) is nice to keep, but for further customizations.

I've found an alternative way to get the content via AJAX, by integrating HTMX, which could be quite straightforward. It has a seamless transition when showing the tooltip after the ajax has returned.

```
<span
    data-tippy-content="
        <div hx-on::after-request="
            const popper = this.closest('[data-tippy-root]')
            const instance = popper._tippy
            instance.popperInstance.update()
            popper.classList.remove('visually-hidden')
        ">
            <span
                hx-on::before-request="this.closest('[data-tippy-root]').classList.add('visually-hidden')"
                hx-get='PARTIAL_URL'
                hx-swap="outerHTML transition:false"
            >
                Loading... (This wont be visible at any point)
            <span>
        </div>
    "
    data-tippy-allowhtml='true'
>
    Hover me to show a tooltip
</span>
```

Replace `PARTIAL_URL` for the ajax URL. Adding the `htmx.process` on the `onShow` event when initializing the tooltip is required for HTMX to work. Make sure `visually-hidden` class at least has `visibility: hidden` property.

```
const tippy_options = {
    //...
    onShow(instance) {
        htmx.process(instance.popper)
    }
}
```
