### ISSUE TITLE
Data attribute props

### ISSUE THREAD

**Issue by aaronstezycki** [atomiks/tippyjs#920]
Hi, I'm sorry if this question has been answered elsewhere, can't find any answers atm to it.

Is there a way to pass data attributes as props to tippy without having to initiate multiple instances? I'm wanting to pass data attributes to set an explicit placement, but can't see whether it's possible or not. I know there are certain props that can be passed this way.

I tried this, which is the example given in the docs for the content prop, but doesn't seem to work.

```
tippy('[data-tooltip]', {
    // Content
    content(reference) {
        const title = reference.getAttribute('data-tooltip');
        return title;
    },
    // Placement
    placement(position) {
        const position = this.getAttribute('data-tooltip-position');
        return position;
    },
});
```

Also this would super handy for things like maxWidth too, allowing this to be used on the fly in an arbitrary setting.

Right now it seems like to be able to set these you have to initiate tippy like so:

```
tippy('[data-tooltip-placement="top-start"]', {
    placement: 'top-start'
}
tippy('[data-tooltip-placement="top-end"]', {
    placement: 'top-end'
}

```

Thanks for any advice in advance :)

**Comment by atomiks** [comment]
What's wrong with this?

```html
<div data-tooltip data-tippy-placement="top-start"><div>
<div data-tooltip data-tippy-placement="top-end"><div>
```

```js
tippy('[data-tooltip]');
```

Each one will use its own placement as specified by the attribute.
