### ISSUE TITLE
followCursor: horizontal breaks when using a singleton

### ISSUE THREAD

**Issue by adam-lynch** [atomiks/tippyjs#921]
## Bug description

The tooltip is placed incorrectly when using `followCursor: 'horizontal'` on a singleton. From my testing (Firefox & Chrome for Mac), it doesn't always appear when expected and when it does, it's at the top of the screen. The X position seems to be correct but the Y position isn't. 

`followCursor: true` works as expected.

## Reproduction

CodePen link: https://codepen.io/adam-lynch/pen/MWbPEjd

It's not clear to me if `followCursor` should be on the instance, singleton, or both. It doesn't seem to make any difference to this bug though.

**Comment by atomiks** [comment]
I don't think followCursor was tested or designed to work with singletons, what's the use case here?

**Comment by adam-lynch** [comment]
Thanks for the quick reply. I'm working on a highlight extension. I.e. select text, highlight. I inject an element wrapping the text, which has a tooltip with actions. 

The highlight could be split across elements (e.g. paragraphs) and contain elements (e.g. `<i>`) so multiple highlight elements (and tooltips) could be created. Example:

```html
<p>Hello <mark>world</mark></p>
<p><mark>This is </mark><i><mark>my</mark></i> highlighter</p>
```

![image](https://user-images.githubusercontent.com/1427241/110466088-2a399580-80cd-11eb-87e7-a8080831fcec.png)

This is *one* highlight. All highlight elements have the same tooltip content (including a shared note field). I'm iterating on the tooltip UX / behaviour but I wanted to see how `followCursor: 'horizontal'` would feel. Rather than three tooltip positions (two within the second paragraph), the X position would follow the cursor.

Maybe I don't need a singleton though? 

If it helps, since creating this issue, we're thinking we'd like just one tooltip to show above all highlight elements (whenever any are hovered over). `followCursor: 'horizontal'` still sounds good but I need to test it out to be sure.

**Comment by adam-lynch** [comment]
After iterating on the design a bit more, we don't need this.
