### ISSUE TITLE
hideAll() disables instances

### ISSUE THREAD

**Issue by roryaherne** [atomiks/tippyjs#923]
## Bug description

Calling the static method hideAll() disables the instances

## Reproduction

- Open codepen link. 
- Switch to mobile view using dev tools. 
- Click on tooltip to activate
- Scroll to trigger hideAll();
- Click on tooltip again (it no longer works)

CodePen link: https://codepen.io/roryaherne/full/oNYJpRr

**Comment by atomiks** [comment]
This seems to be working correctly now.
