### ISSUE TITLE
Mobile positioning breaks on scroll

### ISSUE THREAD

**Issue by wrabit** [atomiks/tippyjs#925]
When using on mobile, the tooltip displays correctly initially, but once you scroll it is positioned fixed to the top left of the screen.

Initial:

![image](https://user-images.githubusercontent.com/5918271/110911252-bc7eab00-8312-11eb-9e7c-c6a8912c65c6.png)

After and during any scrolling:

![image](https://user-images.githubusercontent.com/5918271/110911312-d3250200-8312-11eb-8f79-063b5107564b.png)

It's been initiated by alpine.js:

```
<div x-ref="tippy" x-init="init()" x-data="{
    init() {
        tippy($el, {
            content: $el.querySelector('[data-tippy-content]').innerHTML,
            allowHTML: true,
            delay: 200
        })
    },
}">
    <x-icons.check-circle />

    <div data-tippy-content style="display: none;">
        This is the tooltop body
    </div>
</div>
```

Is there any common pitfalls that anyone knows of to look at?

TIA

**Comment by atomiks** [comment]
That might mean the reference element it was attached to no longer exists on the DOM (or got replaced by a cloned element or such), you can log out the instance and see if `instance.reference` is on the page

**Comment by wrabit** [comment]
It's probably because the parent is re-rendered on update, I have tried setting appendTo: () => document.body is not fixing it.

In my use case, where the tooltip is also a link to perform an action, it would be preferential to disable the tooltip for taps / all mobile. Is there an API-way to carry this out? Thanks again in advance

**Comment by atomiks** [comment]
`touch: false` will disable for taps

> It's probably because the parent is re-rendered on update, I have tried setting appendTo: () => document.body is not fixing it.

The rendering engine being used shouldn't be throwing away the old element, it should be diffing the attributes etc. You probably need to recreate the instance on each render

**Comment by atomiks** [comment]
Repro needed for further investigation.

**Comment by EtiennePASSOT** [comment]
> That might mean the reference element it was attached to no longer exists on the DOM (or got replaced by a cloned element or such), you can log out the instance and see if `instance.reference` is on the page

You're the best

**Comment by EtiennePASSOT** [comment]
@atomiks You're the best
