### ISSUE TITLE
Unreachable interactive content

### ISSUE THREAD

**Issue by interlark** [atomiks/tippyjs#927]
I got a situation where 2 elements placed vertically close to each other with interactive tooltips, so for the bottom one it's pretty hard to reach it's interactive tooltip. Is there any solutions?

Here's a demo: https://codepen.io/interlark/pen/bGBZBoq

Here's screen cast:
![Interactive_content-2](https://user-images.githubusercontent.com/20641837/111073120-5440ec80-84ff-11eb-9ba3-1a82581bf313.gif)

**Comment by atomiks** [comment]
`offset: [0, 5]` works well. (default is 10px)
