### ISSUE TITLE
Allow calling `injectCSS` manually

### ISSUE THREAD

**Issue by Michael-ZecOps** [atomiks/tippyjs#931]
## Problem

I'm using Tippy in a web extension, running at [`"run_at": "document_start"`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#run_at). At this time, `document.head` is unavailable, and so Tippy throws an exception here:

https://github.com/atomiks/tippyjs/blob/6609fbc3cee8611fb95ab9f381bb926aca20d2f6/src/css.ts#L11

## Solution

Please, allow to call `injectCSS` manually at a later time. I think doing the following is a good, backwards compatible solution:

1. Don't call `injectCSS` if `document.head` is not available.
2. Provide a new API, `initInjectCSS`, which will inject the CSS if `document.head` is available and if it wasn't injected before (so calling `initInjectCSS` again, or if `document.head` was available on init, does no harm).

**Comment by atomiks** [comment]
You want to use `tippy.js`, not `tippy-bundle.js`: https://unpkg.com/tippy.js@6.3.1/dist/tippy.umd.min.js
