### ISSUE TITLE
transform on parent element

### ISSUE THREAD

**Issue by Kapsonfire-DE** [atomiks/tippyjs#933]
## Bug description

I have a <main> tag, performing transform: scale(x) to scale the whole container to fit page. If i use tippy inside of a element it inherits its transform, but the calculated positions doesnt fit.

## Solution
Maybe traverse to the parents and take there scale into calculation.

**Comment by essejmclean** [comment]
Can confirm this issue is causing problems for me as well. I have a parent that is scaled and need to feed my scale value into the transforms for Tippyjs positioning.

e.g. 3x scale down on parent, pass 3x to Tippyjs which is multiplied against the translate values.

**Comment by atomiks** [comment]
This was/is an open Popper bug, not related to this library.

**Comment by Torres7707** [comment]
I just figure out this problem by use popperOptions
```
<Tippy
        ....
        popperOptions={{
          modifiers: [
            {
              name: 'preventOverflow',
              options: {
                boundary: document.getElementById('progress-status'),
              },
            },
            {
              name: 'flip',
              options: {
                boundary: document.getElementById('progress-status'),
              },
            },
            {
              name: 'applyScale',
              enabled: true,
              phase: 'beforeWrite',
              fn({ state }) {
                state.styles.popper.transform = `${state.styles.popper.transform} scale(${scale})`;
                state.styles.popper.transformOrigin = `${state.placement === 'top' ? 'bottom' : 'top'}`;
              },
            },
          ],
        }}
     ....
/>
