### ISSUE TITLE
Changing text content of the reference 

### ISSUE THREAD

**Issue by gniewus** [atomiks/tippyjs#934]
Hey,
I have attached tippy to multiple <p> elements. These P elements can change dynamically. Unfortunately when using:                             `$(instance.reference).text(NEW_CONTENT_OF_P_ELEMENT)` 
to adjust the text content, tippy does not work anymore on the changed instance. Is there a way to keep it working no even though the reference object has slightly changed?

**Comment by atomiks** [comment]
`instance.reference.textContent = NEW_CONTENT_OF_P_ELEMENT`. Not sure why jQuery would clone/change the original reference element.
