### ISSUE TITLE
Show tooltip only if text-overflow: ellipsis applied to reference

### ISSUE THREAD

**Issue by nikkii94** [atomiks/tippyjs#936]
Hello!

Is there a way to show the tooltip only if the reference element has text-overflow: ellipsis?

My code:

`
const tippyInstances = tippy('th[data-tippy-content]');
createSingleton(tippyInstances, {
    theme: 'info',
    moveTransition: 'transform 0.2s ease-out',
    delay: 500,
});
`

**Comment by atomiks** [comment]
Checking `scrollWidth` vs `offsetWidth` of an element's size will allow you to implement this
