### ISSUE TITLE
Use prevent overflow without sticky

### ISSUE THREAD

**Issue by NotWhatYouThinkIAm** [atomiks/tippyjs#937]
Hello,

So I have a scenario where the tippy I am trying to show can be right up against the bottom of the page. I currently have only flip for a modifier which does what I want when there is space. Without prevent overflow, it will go offscreen to the right. But when I add prevent overflow, it doesn't go offscreen which is good but the tippy stays sticky and follows down when the user scrolls. Is there a way to take advantage of the prevent overflow but not have it stay on the screen as the user scrolls down?

Without prevent overflow: https://codepen.io/robgarciaert/pen/BaQYBEY
With prevent overflow: https://codepen.io/robgarciaert/pen/rNjYwaJ

**Comment by atomiks** [comment]
I've enabled Discussions for all questions to go inside instead of Issues.
