### ISSUE TITLE
Tooltip persists even after the element is hidden

### ISSUE THREAD

**Issue by amanagr** [atomiks/tippyjs#938]
## Bug description

When tooltip is displayed and the element on which the tooltip was shown is hidden, tooltip persists.

## Reproduction

CodePen link: https://codepen.io/amanagr/pen/xxgPJye

(Just hover over the button, the button will hide itself after 5s)

**Comment by amanagr** [comment]
Someone else also requested this in #419.

**Comment by atomiks** [comment]
This sort of thing is your responsibility to handle rather than the library's.

**Comment by amanagr** [comment]
Can you add an option in `hideAll` which someone can call periodically like a cron job which destroys tooltips whose `reference` elements are no longer present in DOM or displayed?

**Comment by amanagr** [comment]
or any way I can access all the `mountedInstances` directly.

**Comment by amanagr** [comment]
Oh! https://github.com/atomiks/tippyjs/issues/745#issuecomment-607531942 answers that for me. Thanks for your help.

**Comment by amanagr** [comment]
I do think this discussion should be documented on the plugin page.
