### ISSUE TITLE
Any way to get the reference to the initial target element?

### ISSUE THREAD

**Issue by kuanyen** [atomiks/tippyjs#940]
```js
const targetEl = document.querySelector('#button')
const instance = tippy(targetEl, { content: hello })
console.log(instance.props.triggerTarget)  //  ===> null
```
https://atomiks.github.io/tippyjs/v6/all-props/#triggertarget

For some reason, I want to dynamically add & remove target element from a `tippy` instance, however, I cannot find any API to get the initial target element. I cannot understand why it is `null`, though the documentation said this:
```js
tippy(targets, {
  // default (reference is used)
  triggerTarget: null,
});
```

**Comment by atomiks** [comment]
`instance.reference` is the target by default

**Comment by kuanyen** [comment]
> `instance.reference` is the target by default

1. I found this API seems not to be documented? Only simply mentioned in [FAQ/plugin](https://atomiks.github.io/tippyjs/v6/faq/#plugin).
2. It seems I cannot change this value? (if change element, the tooltip cannot show up anymore...)

**Comment by atomiks** [comment]
The "documentation" is just this https://atomiks.github.io/tippyjs/v6/tippy-instance/#shape-and-properties and asks you to inspect the properties of the instance which could be a lot better 😅 

> It seems I cannot change this value? (if change element, the tooltip cannot show up anymore...)

Yeah you can't. You need to destroy the old instance and make a new one
