### ISSUE TITLE
Cannot read property 'setContent' of undefined

### ISSUE THREAD

**Issue by 1144075799** [atomiks/tippyjs#943]
The error message is as follows:
![1619745195106](https://user-images.githubusercontent.com/38463468/116636637-50283b80-a994-11eb-86f4-3671eea6a9ed.jpg)
I introduced tippy in the react project:
import tippy from'tippy.js'
import'tippy.js/dist/tippy.css';
The above error code is as follows: 
![1619745339229](https://user-images.githubusercontent.com/38463468/116636759-a72e1080-a994-11eb-8338-4fa60334749a.jpg)
Hope you can help to solve it！

**Comment by atomiks** [comment]
Well the variable `tippyInstance` is undefined for some reason. Maybe initialize isn't being called before the `update()` callback is firing.
