### ISSUE TITLE
Prevent Tippy closing on scroll?

### ISSUE THREAD

**Issue by fuzzybad** [atomiks/tippyjs#944]
Our site is using Tippy tooltips with interactive: true, triggered on click event.  The tooltips should stay open until explicitly closed by the user, but we're finding that scrolling browser window causes them to close.  This is a problem for mobile users, who need to scroll in order to read our larger tooltips.  

Has anyone experienced anything like this, or can suggest a solution?

**Comment by fuzzybad** [comment]
Found other JS had event bound to scroll event

**Comment by edwinbbu** [comment]
Facing the same issue. 
@fuzzybad Could you elaborate on the approach taken?

**Comment by fuzzybad** [comment]
This was over a year ago, I don't recall the details.  I would suggest using the "Event Listeners" tab in browser Developer Tools to see if there are any unexpected event bindings on your Tippy elements.
