### ISSUE TITLE
When the mouse is scrolled, the prompt does not disappear

### ISSUE THREAD

**Issue by 1144075799** [atomiks/tippyjs#946]
When the mouse is scrolled, the prompt does not disappear, as shown in the following figure:
![8CEBBB9B-FD02-450B-A052-8F68A7C5C8AD](https://user-images.githubusercontent.com/38463468/118458644-8f44e380-b72d-11eb-9dc3-659069ea8884.png)

**Comment by 1144075799** [comment]
My code is as follows:
// Get element and initialize tippy instance
    function initialize(el) {
      // element = el;
      // @ts-ignore
      // if (!tippyInstance) tippyInstance = tippy(element);
      // if(!tippyInstance) tippyInstance = createSingleton()
      tippy(el, {
        content: `<div>
          <div>${props.item.description}</div>
          <div>时间</div>
        </div>`,
        allowHTML: true,
      })
    }

    return (content) =>
      html`<div
        directive=${getElement(initialize)}
        class="my-item"
        style="width:100%;display:flex;line-height:${props.item.height}px; margin-left:2px; justify-content: center;"
        @click=${() =>
          onItemClick(
            props.item
          )}
      >
        ${props.item.description}
      </div>`;

**Comment by 1144075799** [comment]
My code is as follows:


   // Get element and initialize tippy instance
    function initialize(el) {
      // element = el;
      // @ts-ignore
      // if (!tippyInstance) tippyInstance = tippy(element);
      // if(!tippyInstance) tippyInstance = createSingleton()
      tippy(el, {
        content: `<div>
          <div>${props.item.description}</div>
          <div>时间</div>
        </div>`,
        allowHTML: true,
      })
    }

    return (content) =>
      html`<div
        directive=${getElement(initialize)}
        class="my-item"
        style="width:100%;display:flex;line-height:${props.item.height}px; margin-left:2px; justify-content: center;"
        @click=${() =>
          onItemClick(
            props.item
          )}
      >
        ${props.item.description}
      </div>`;

**Comment by atomiks** [comment]
The browser sometimes won't fire a mouseleave event when scrolling off the reference element, which is the native behavior
