### ISSUE TITLE
Not removed after reference remove from DOM

### ISSUE THREAD

**Issue by VictorPulzz** [atomiks/tippyjs#947]
## Bug description
Hello!
When the item is removed from the DOM, let's say I delete the item of the purchase, the item itself is removed and tippy jumps to the upper right corner, because reference element disappeared...

**Comment by Crisfole** [comment]
I have seen this behavior as well.

**Comment by atomiks** [comment]
In this case it's your responsibility to destroy the tippy along with the removal of the element.
