### ISSUE TITLE
404 from production CDN

### ISSUE THREAD

**Issue by dschu012** [atomiks/tippyjs#948]
## Bug description

In the [example](https://atomiks.github.io/tippyjs/v6/getting-started/) you use https://unpkg.com/tippy.js@6 for the production CDN. Starting today I have seen a lot of 404 from this CDN, did the library somehow get removed?

## Reproduction

CodePen link: https://codepen.io/atomiks/pen/yvwQyZ

**Comment by a-know** [comment]
This is happening to me too. What's wrong?

**Comment by a-know** [comment]
I don't want it to stay that way, so I'm dealing with the following work-arounds.
I'm not sure if this is a good way to go...

`<script src="https://cdn.jsdelivr.net/npm/tippy.js@6"></script>`

**Comment by atomiks** [comment]
CDN issues are outside the scope of the project, unpkg is the most popular one which is why it's used but they can have downtimes
