### ISSUE TITLE
Insert an input field inside tooltip

### ISSUE THREAD

**Issue by mattia-malnis** [atomiks/tippyjs#949]
Hi!
I need to insert an `<input>` inside a tooltip but I've noticed that when the tooltip hides the content is removed from the DOM so, when the form is submitted, the tooltip input value is not passed to the server.
The code looks like this:

```
<form action="/" method="post">
  <label>Name</label>
  <input type="text" name="first-name" />

  <div id="element">Additional field</div>
  <div id="content">
    <label>Additional field</label>
    <input type="text" name="additional-field" />
  </div>
  <input type="submit" />
</form>

<script>
  tippy("#element", {
    content: document.getElementById("content").innerHTML,
    trigger: "click",
    allowHTML: true,
    interactive: true,
  });
</script>
```

Anyone have any suggestions to make sure that the input value is passed to the server?
Thanks!

**Comment by atomiks** [comment]
I've enabled Discussions for all questions to go inside instead of Issues.

**Comment by hasintha** [comment]
Yes this is a headache, please someone help to avoid unmounting the tippy from DOM :(

**Comment by hasintha** [comment]
> I've enabled Discussions for all questions to go inside instead of Issues.

Sir is there a solution to this particular issue?
