### ISSUE TITLE
Show tooltips a specific number of times

### ISSUE THREAD

**Issue by miguelapg** [atomiks/tippyjs#953]
## Problem

Sometimes, and in some areas where the mouse could be pass more due to a concentration of features, to show tooltips every time is damaging the user experience.

In other circumstances, once the tooltip is shown, replicating the same behavior and show it once and again is too redundant and doesn't make sense as the user already know or read the message before

## Solution

I think that if you could enable some kind of feature where the tooltips are shown a configurable number of times, 2, 3, 5 times, etcetera, that could be a great advance in the set of features of this also great tool.

Hope you like this idea.

**Comment by atomiks** [comment]
Can be implemented by the user themselves with a plugin. Adding more features like this to core has a bundle size cost and increases the complexity of the lib when most people don't use it
