### ISSUE TITLE
awesome work, but does it support the tool tip to pop always flushed to bottom? 

### ISSUE THREAD

**Issue by halukkaramete** [atomiks/tippyjs#954]
Sometimes, ( depending on the scroll position of mobile device ), I see that te tool tip pops in an area that is halfway visible. but if I scroll a tiny bit, it starts appearing where I told it to appear ( placement:bottom-start ). 

So, I thought, what if I designate an area on my web page and dedicate that area to show the tool tips? 
In my implementation, a translation will pop for every word on the display. So it is OK for the translations to pop always at the bottom of the current view.  It's ki d of lime the status bar of the browsers...  You know when you move the mouse over links, you can see where you are heading from the status bar. From UX point of view, that kind of tool-tipping cn perfectly work too.  

But , Is it possible?

**Comment by atomiks** [comment]
It does with a custom `getReferenceClientRect` function, you can position the tippy virtually anywhere you want.
