### ISSUE TITLE
Even with aria set to null, the aria-describedby attribute is still added to the element

### ISSUE THREAD

**Issue by DaTrader** [atomiks/tippyjs#955]
## Bug description

In contrast to the documentation, setting aria property to null makes no difference, and Tippy still adds the aria-describedby attribute to the element. I would really appreciate if it didn't change the element when aria is set to null.

## Reproduction

CodePen link: https://codepen.io/damir_p/pen/xxdwzBJ

**Comment by atomiks** [comment]
The `aria` prop expects an object not `null`. 

`aria: {content: null}`

**Comment by DaTrader** [comment]
The above snippet provides an object to aria, the object of { content: null}, as per the example in aria property 6.x docs:

```
// disable completely, left up to you to control
  aria: {
    content: null,
    expanded: false,
  },
```
https://atomiks.github.io/tippyjs/v6/all-props/#aria
