### ISSUE TITLE
Calling update() without setting title attribute will set text to "html"

### ISSUE THREAD

**Issue by ericcirone** [atomiks/tippyjs#96]
In removeTitle.js, you will set the data-original-title to "html" if there is no title attribute on the tag. If I call tippy().update(popper) without setting the title tag then the tooltip will read html due to how update() works. 

I am using Vue and am blinding calling update when the component changes. I have a workaround by setting the title to data-original-title, but I feel that even if I call an update() and didn't set a title, it shouldn't get overridden.

**Comment by atomiks** [comment]
How about this?

```javascript
export default function removeTitle(el) {
  const title = el.getAttribute('title')

  // Only set `data-original-title` attr if there is a title
  if (title) {
    el.setAttribute('data-original-title', title)
  }

  el.removeAttribute('title')
}
```

**Comment by ericcirone** [comment]
That will probably work, as long as you don't depend on data-original-title to be "html" for when options.html is set.

**Comment by atomiks** [comment]
1.2.1
