### ISSUE TITLE
Tooltip not displayed on dialog

### ISSUE THREAD

**Issue by sdalu** [atomiks/tippyjs#960]
## Bug description

The tooltip is not displayed (visible over) on dialog element (either natively on chrome, or polyfilled on firefox)

## Reproduction

Example below is for Chrome (no polyfill code injected)
CodePen link: https://codepen.io/sdalu/pen/vYmjmKo

**Comment by atomiks** [comment]
Tooltips get appended to the `<body>` by default which is beneath the dialog. Specifying `appendTo: 'parent'` will fix it (or the dialog itself)
