### ISSUE TITLE
[Bug] Popper flip modifier doesn't work

### ISSUE THREAD

**Issue by sanyaches** [atomiks/tippyjs#962]
```"tippy.js": "6.3.1"```

I configure my tippy instance as follow:
```
tippy(triggerEl, {
  appendTo: document.body,
  content: menuEl,
  theme: 'dropdown',
  placement: 'bottom-start',
  popperOptions: {
    modifiers: [
      {
        name: 'flip',
        options: {
          fallbackPlacements: ['top-start'],
        },
      },
    ],
  },
  trigger: 'manual',
  interactive: true,
  arrow: false,
  offset: [0, 4],
  hideOnClick: false,
  showOnCreate: true,
})
```
It doesn't work as I expect it (check `document.body` overflow and change placement from `'bottom-start'` to `'top-start'`), it overflows `document.body`. I think it can be some problem with `popperOptions` property.

**Comment by atomiks** [comment]
Need a CodePen repro. Most likely a Popper bug regardless though
