### ISSUE TITLE
Why does "instance.reference" seem to break when using "tippy.createSingleton()"?

### ISSUE THREAD

**Issue by nmg196** [atomiks/tippyjs#964]
I'm trying to avoid duplicate Tippyies appearing when moving quickly between table cells:

![image](https://user-images.githubusercontent.com/8134047/129562251-22db252b-4fd0-4d26-8ffe-5a4c40f2a89b.png)

The obvious answer was to use the createSingleton() function, but this seemed to break my code as the "instance.reference" passed to onShow() seems to be an orphan div and not the acutual HTML element the user is hovering over.  My code needs instance.reference as the tooltip data is stored in `$(instance.reference).data("dataItems");`

Is there a  way to get the correct instance.reference when using createSingleton?   OR  is there another way to prevent mulitple Tippies appearing at the same time?

    const tippyInstances = tippy('td.hasEntries');
	const singleton = tippy.createSingleton(tippyInstances, {
		interactive: true,
		placement: 'right',
		delay: [500, 100],
		appendTo: () => document.body,
		allowHTML: true,
		onShow(instance) {
			var items = $(instance.reference).data("dataItems");

			if (items === undefined || items.length == 0) {
				console.warn("Error: No data items found!"); // this fires :(
				return;
			}

			var output = outerTemplate(items[0]);
			instance.setContent(output);
		}
	});`

**Comment by mstrelan** [comment]
Similar issue with this config:

```
const tippyInstances = tippy('.gridjs-th', {
  content: () => document.querySelector('.foo').innerHTML,
  allowHTML: true,
}
const singleton = createSingleton(tippyInstances, {
  moveTransition: 'transform 0.2s ease-out',
});
```

Without the singleton the HTML is rendered correctly, otherwise it is escaped and the raw HTML is displayed.

**Comment by atomiks** [comment]
In the second example, the singleton instance itself needs `allowHTML: true` for it to work. 

`onTrigger(instance, event)` => `event.currentTarget` will point to the "current" reference
