### ISSUE TITLE
[Feature Request] Add option to prevent opening tooltip on `mouseenter` if mouse button is pressed

### ISSUE THREAD

**Issue by benface** [atomiks/tippyjs#965]
## Problem

I have a range slider with a Tippy on the handle, and on the same page I also have some buttons with Tippys on them. The problem is when the user is dragging the handle and the cursor happens to hover the other buttons, their tooltips open, which is confusing/annoying because the user is not able to click on these buttons while they are dragging the handle.

## Solution

I feel like it would be much better UX for the `mouseenter` trigger to open a tooltip only when the user is not dragging something or selecting text, in other words when the mouse button is not pressed. But because this would be a breaking change (and because customization is good), I would imagine a new config option to get that behavior, which could be called something like `noTriggerOnDrag`.

**Comment by atomiks** [comment]
I think this behavior can be added on your own as a plugin? https://atomiks.github.io/tippyjs/v6/plugins/

**Comment by benface** [comment]
@atomiks Ah yes, I suppose returning `false` if the mouse button is pressed in `onShow` would do it. I'll try that, thanks!
