### ISSUE TITLE
Submit form not working inside tippy

### ISSUE THREAD

**Issue by rebelcolony** [atomiks/tippyjs#967]
So I have a form that works fine while outside but inside my tippy nothing happens on submit. This is expected?

```
tippy('#add-company-form-button', {
    content: addCompanyForm.innerHTML,
    allowHTML: true,
    interactive: true
})
```

**Comment by emsifa** [comment]
Is `addCompanyForm` a `<form>` element? if yes, maybe that is why your form doesn't work since you put only its `innerHTML` to tippy's content.

**Comment by rebelcolony** [comment]
@emsifa is correct adding a `div` container around the form fixed it so the content I'm passing to tippy is the entire form.
