### ISSUE TITLE
Tooltips not working inside of Alpine.js' `<template x-if="">` and `<template x-for="">` attributes

### ISSUE THREAD

**Issue by dfallman** [atomiks/tippyjs#968]
Maybe I'm missing something very basic but can't seem to get Tippy to work within Alpine's x-if and x-for attributes. I don't get any error messages or anything, it's just being ignored.

Tippy (v6.x, using CDN dev) works great otherwise but anything inside either a x-for loop or a conditional x-if statement is ignored. I've tried both the `<button data-tippy-content="Normal cupcake">Text</button>` + `tippy('[data-tippy-content]');` approach as well as the `...class="tippyNormal"` and `tippy('.tippyNormal', { content: 'Normal cupcake', });`

So for me, the following works great:

```
<span x-show="isView.title">
   <a :href="book.uri" class="font-bold ml-0.5 tippyTitle" x-text="book.title"></a>
</span>
```

but not:

```
<template x-if="isView.title">
   <a :href="book.uri" class="font-bold ml-0.5 tippyTitle" x-text="book.title"></a>
</template>
```

Appreciate any help -- maybe I'm missing something very obvious and/or this is an Alpine issue. Thanks!

**Comment by atomiks** [comment]
The framework should(?) have lifecycle events that correspond to when the elements in its render/template get created. These hooks allow you to initialize Tippy correctly.
