### ISSUE TITLE
Tippy position is just wrong and I dont know what to do...

### ISSUE THREAD

**Issue by RickKukiela** [atomiks/tippyjs#970]
![image](https://user-images.githubusercontent.com/3813238/130883096-f808cfa0-c1a7-4ce5-a76c-d92e0f715a9c.png)

Nothing I change in the settings or the css of the elements on the page around it have any effect. It just doesn't work right :(

I'm literally only passing the content option on this screen shot. The layout is flex, everything is border-box. Using the CDN version from the getting started guide.

**Comment by atomiks** [comment]
A Popper update might have broken something. If you downgrade to an old version, `@2.9.2` is there an issue?

**Comment by RickKukiela** [comment]
Honestly I threw my hands up with this and implemented a different library that didn't give me any problems and have moved on. Good luck.

**Comment by baraa-elwan** [comment]
@atomiks this problem appears only if the target position is `absolute`

**Note**: changing popper version didn't help

**Comment by tadaskarpavicius** [comment]
Can confirm this. Tooltips were all over the place for me too.
Loading Popper@2.9.2 through the CDN fixed the issue. 
This should be fixed ASAP... 
How do I lower Popper version if I load the plugin through the npm?

**Comment by atomiks** [comment]
https://github.com/popperjs/popper-core/releases

Can you also test each version from 2.9.3 until the most recent one and tell me which version causes the issue and a CodePen demonstrating it? Then I can try and debug it and submit a PR for a fix for Popper.

**Comment by atomiks** [comment]
After investigating myself I found an issue with a recent PR in Popper that looks like it broke positioning for all elements that aren't a full pixel/integer `width` or `height` (which is like, most elements that have computed width/height from text....) I've submitted a PR so hopefully it should be fixed ASAP.

**Comment by atomiks** [comment]
This should now be fixed in the latest Popper version
