### ISSUE TITLE
Blurred/frosted background

### ISSUE THREAD

**Issue by spyderdsn** [atomiks/tippyjs#971]
I tried to create a theme with a blurred (frosted) tippy background however it looks like this is not possible. Any idea how to achieve this? The output is transparent, not frosted. Thanks

```
.tippy-popper .tippy-tooltip  {
      -webkit-backdrop-filter: blur(20px) saturate(200%);
      backdrop-filter: blur(20px) saturate(200%);
      -webkit-box-shadow: 0 0 20px rgb(0 0 0 / 10%);
      box-shadow: 0 0 20px rgb(0 0 0 / 10%);
      background: hsla(0,0%,100%,.8);
}
```

**Comment by atomiks** [comment]
The selector in the latest version (v6) is `.tippy-box` not the above.

**Comment by spyderdsn** [comment]
I’m using VUE wrapper for it: https://kabbouchi.github.io/vue-tippy/4.0/demo.html

so the version 4.0
