### ISSUE TITLE
How to force Tippy to update its positioning? 

### ISSUE THREAD

**Issue by GitHubish** [atomiks/tippyjs#972]
I use TippyJS with Angular Framework and the Wysiwyg Tiptap editor (based on Prosemirror). I use Tiptap as part of the mention functionality (@ like Github). Only, my component that displays in the popper displays a mention list that depends on an HTTP call. Out when this list is displayed at the bottom of the page sometimes, the popper is cut. If I retype one more letter, TippyJS detects that the content is "bigger" than the available space and so positions it on top so that it is fully visible. I've searched in every corner, tested a lot of things but I can't find a solution. How can I do it? Could there be a public method to "force" the positioning update? 

Thanks

**Comment by atomiks** [comment]
Calling `instance.popperInstance.update()` will manually update its position.
