### ISSUE TITLE
Wrong calculations for position when page styles used 'rem' instead of px

### ISSUE THREAD

**Issue by 7iomka** [atomiks/tippyjs#974]
1) When page uses `px` all works fine
![image](https://user-images.githubusercontent.com/18473137/132315331-bbb85d62-9df0-4571-b427-6ec301c5ec6e.png)

2) When page uses `rem`
![image](https://user-images.githubusercontent.com/18473137/132315472-63f1e3ca-1152-4a14-b21f-e075c8cf508f.png)

**Comment by 7iomka** [comment]
For confirmation, I prepared Demo:
https://codepen.io/7iomka/pen/KKqWaXV?editors=0100

Open first (tooltip) and resize area to 1000px+ to have the same buggy behavior.
![image](https://user-images.githubusercontent.com/18473137/132702788-ecab9d52-00bd-400e-8eb5-50de307c7afa.png)

**Comment by 7iomka** [comment]
I notices that happens only when tippy appendTo is default (as sibling for trigger)
And if trigger not have parent with relative position that happens.
But, this is not expected behavior, anyway

**Comment by atomiks** [comment]
It happens with `px` also. Looks like the flex container is the issue. If you append the tooltip outside of the flex header container (i.e. `appendTo: () => document.body`) it works, might be an issue with the latest Popper version (or was always a bug)
