### ISSUE TITLE
Prohibit overflow of other elements

### ISSUE THREAD

**Issue by HenrijsS** [atomiks/tippyjs#978]
I'm using Tippy to create tooltips for options that configure a belt, but the tooltip overlaps the belt preview (See below).

It currently looks like this, when it overflows the main belt preview: http://snpy.in/Btw2ZP

But I'd like to adjust the maximum height for it to look like it goes out of bounds: http://snpy.in/j43oIl

This functionality is already built in when the Tooltip is higher than the screen, it then pops down. I want to make it do it sooner. Is there a way to configure this?

**Comment by atomiks** [comment]
You might want to specify a custom wrapping div for the `flip` modifier that wraps the content _below_ the belt.

```js
popperOptions: {
    modifiers: [
    {
      name: 'flip',
      options: {
        boundary: document.querySelector('#myCustomWrapper'),
      },
    },
  ],
}
```

```html
<div id="belt"></div>
<div id="myCustomWrapper">
  content...
  <button id="withTooltip"><button>
</div>
```

**Comment by atomiks** [comment]
I've enabled Discussions for all questions to go inside instead of Issues.
