### ISSUE TITLE
Tooltip corners flatten as contents increase

### ISSUE THREAD

**Issue by PorkchopDonut** [atomiks/tippyjs#98]
I'm using Tippy to illustrate stats on items for a game I'm developing and the stats list is pretty lengthy (at least 8 lines on average) and I'm noticing that the more lines of text you add to the tooltip, the more the corners stop looking round and start looking flat, making the tooltip look like a skewed octagon.  I've included the image below to demonstrate this occurrence;

![bugillustration](https://user-images.githubusercontent.com/10764837/30293397-f4d00700-96fe-11e7-906f-537b1e2ecabc.png)

Perhaps I'm misusing the code, but as far as implementation goes Tippy is pretty straightforward so I have to wonder if there's a setting I missed or if this is just how it functions.

**Comment by PorkchopDonut** [comment]
It's worth noting that I also have tooltips with much less content that maintain their proper corners.  These smaller-content tooltips abide by the animation rules I stipulate for all of my tooltips while the larger-content tooltips do not.  Regardless of what I set the animation style to, they will only animate with the "expanding circle" method.

**Comment by PorkchopDonut** [comment]
Further experimentation led me to discover that neglecting to include any settings at all for the tooltips (leaving them at their default settings for everything) resulted in the following;

![bugillustration](https://user-images.githubusercontent.com/10764837/30296793-0d11fca4-970b-11e7-9fb7-c965f4b932e2.png)

This leads me to believe that the "expanding circle" animation is the primary issue here.  The circle appears to be animating from a point offset from the center and not expanding out far enough to fully render the corners.

**Comment by atomiks** [comment]
Yep I did so much adjusting on the expanding circle animation and found those settings to look best. The downside is that it doesn't expand enough when there's a lot of content. It's meant to be used for small toolotips. I believe I make note of that in the docs (or maybe I removed it accidentally). 

To disable it, just set `animateFill: false`.

**Comment by PorkchopDonut** [comment]
Don't know why I didn't see that in the documentation beforehand; my apologies.  Setting 'animateFill: false' rectified my issue and it works magnificently now.  Thank you so much; I love this library.
