### ISSUE TITLE
is there a way to make the tooltip sticky after click?

### ISSUE THREAD

**Issue by francofgp** [atomiks/tippyjs#984]
Somebody knows a way to do something like the following:

When hover over the event, show the tooltip. When event is clicked, keep tooltip on the screen (sticky)
When event is clicked again, hide the tooltip. Hide tooltip when different event is clicked.

I would like to have such behavior, but I don't know how to achieve it.

**Comment by atomiks** [comment]
`trigger: "mouseenter click"`
