### ISSUE TITLE
Span tooltips clickable on mobiles?

### ISSUE THREAD

**Issue by panomitrius** [atomiks/tippyjs#996]
I'm trying out Tippy and have created a few tooltips by adding tooltips like this one the JS section:
```
tippy('#defintion-inre-feno', {
  content: "<b>Title:</b><br>Explanation..."
});
```

It works great on desktops and appears when mouse hovers over, but on mobiles it doesn't show and is not clickable. How do I get it to work?

**Comment by atomiks** [comment]
You likely need to make the element focusable via `tabindex="0"`

**Comment by panomitrius** [comment]
Somehow started to work now!
